### ISSUE TITLE
TYPE Error in ICED NORMLIZATION.

### ISSUE THREAD

**Issue by Acton-Lee** [nservant/HiC-Pro#101]
Hello there,

  HiC-pro  (version 2.9.0) can be run under python 3.6.3 after some format changing, but getting the following error when applying for demo samples:

  File "/home/acton/Applications/HiC-Pro-2.7.8/HiC-Pro_2.9.0/scripts/ice", line 73, in <module>
    i, j, data = loadtxt(filename).T
  File "iced/io/fastio_.pyx", line 41, in iced.io.fastio_.loadtxt (iced/io/fastio_.c:1776)
TypeError: expected bytes, str found
make: *** [ice_norm] Error 1

Can you please help me?
Thanks.

~Acton

**Comment by nservant** [comment]
Hi Acton,
If the error is still there, could ask the question on the forum please ?
https://groups.google.com/forum/#!forum/hic-pro
Thanks

**Comment by DRosen1996** [comment]
> Hello there,
> 
> HiC-pro (version 2.9.0) can be run under python 3.6.3 after some format changing, but getting the following error when applying for demo samples:
> 
> File "/home/acton/Applications/HiC-Pro-2.7.8/HiC-Pro_2.9.0/scripts/ice", line 73, in
> i, j, data = loadtxt(filename).T
> File "iced/io/fastio_.pyx", line 41, in iced.io.fastio_.loadtxt (iced/io/fastio_.c:1776)
> TypeError: expected bytes, str found
> make: *** [ice_norm] Error 1
> 
> Can you please help me?
> Thanks.
> 
> ~Acton
Hi, were you able to solve this issue?
