### ISSUE TITLE
HiC-Pro for Capture HiC

### ISSUE THREAD

**Issue by mfilip8** [nservant/HiC-Pro#102]
Hi, 

my question is rather naive: I can see from the news in the latest releases that an option to run HiC-Pro for Capture-HiC was added, but it is not clear to me how does it practically work and also it would be great if you can point to some documentation.
We are already using the HiC-Pro pipeline for our HiC samples and we would like to use it also for our C-HiC data.
Thanks a lot in advance!
Best,
Marco

**Comment by nservant** [comment]
Hi Marco
Sorry for the lack of help for this part. I'm going to release a new version soon ... I will take time to do it.
Are you talking about capture-C (4C like profile) or capture Hi-C (Hi-C on a targeted region) ?
Best
N

**Comment by mfilip8** [comment]
Hi Nicolas,

it's promoter capture HiC (many vs all), where we use HindIII as restriction enzyme and with a subset of the fragments as our baits (promoters).
Thanks a lot again, I'll look forward to hearing from you on the subject.

Best,
Marco

**Comment by nservant** [comment]
ok. So basically, you can use HiC-pro until the detection of valid pairs.
using the command 
./HiC-Pro -i data -o output -c config -s mapping -s proc_hic -s quality_checks -s merge_persample

This will generate allValidPairs file with the list of valid interactions.
Then, I'm not very familiar with promoter capture-Hi-C, so I do not know which type of downstream analysis you would like to do.
I wrote a couple of months ago an utility utils/make_viewpoints.py, that can generate a viewpoint BED file for a set of targets ... as for 4C profile for instance.
So, I never analyzed promoter capture Hi-C so far myself. But if you think that I can add any additional function for promoter capture, do not hesitate to ask me.

Best

**Comment by bkinnersley** [comment]
Hi Nicolas,

Similarly to Marco I am also interested in using HiC-Pro to analyse promoter capture Hi-C data. Just to confirm, by including target regions as an annotation file through CAPTURE_TARGET = "" it is only currently possible to generated valid pairs and not continue to normalized contact maps? Ideally I would like to analyse the capture Hi-C data using an iterative correction procedure to correct for biases

Thanks

Best wishes

Ben

**Comment by nservant** [comment]
Hi Ben,
That's a good point. I do not think it will work for promoter capture ! 
The CAPTURE_TARGET was defined for capture Hi-C, ie. Hi-C one a small region (more like 5C). Therefore if you specify the CAPTURE_TARGET, it will only keep the interaction within the targeted regions ... which is not what you want in promoter capture experiment.
Regarding your other questions, yes you can use it in stepwise mode with the -s option.
If you want to stop at the list of valid interactions, just run "-s mapping -s proc_hic -s quality_checks"
See the help for all steps.
Hope it helps
Nicolas
