### ISSUE TITLE
Documentation-- how to properly choose a ligation site

### ISSUE THREAD

**Issue by jamesdalg** [nservant/HiC-Pro#106]
I notice that the ligation site parameters is clear in documentation. How does one choose a good site? I'm getting 13-20% of my reads as valid and wonder if it might be due to either an alignment or ligation site parameter.  The default is AAGCTAGCTT, but NEB seems to suggest that an extra A might be needed here.  Further, I find that the size of the resulting fragments file is much smaller than a similar MboI fragments file. Is this normal?  How does one most accurately choose the site? 
![image](https://user-images.githubusercontent.com/26911077/32350291-58005982-bff0-11e7-9842-b616aaca2821.png)

**Comment by nservant** [comment]
Hi,
Regarding the dangling end, those are unligated fragments. There is nothing to do to rescue them.
However, it's true that you have a lot of "Dumped pairs", ie. pairs which are flltered based on the parameters you put on the config file (min_frag_size, min_insert_size, etc.). Let these values empty to remove this filter.
Regarding the ligation site, it depends on your protocol, and resctriction. This is something you need to check with the wet lab part. However, I do not think that it will really impact the fraction of valid pairs ...
Change the filtering options in the config file, and you should reach the 50% of valid pairs.
N

**Comment by jamesdalg** [comment]
Many thanks. One more question-- where are the dangling end, religation, and self cycle pairs written to, respectively? I'm wondering if there is something that can be changed in the wet lab and would like to examine them to determine that.

**Comment by nservant** [comment]
By default, there are not written.
You can set up the option 
GET_ALL_INTERACTION_CLASSES = 1
GET_PROCESS_SAM = 1

If GET_ALL_INTERACTION_CLASSES = 1, then, dangling-end, self-circle, etc will be written in dedicated files.
If GET_PROCESS_SAM=1, you will also get a SAM file, with all paired reads with a flag based on their type (valid, dangling-end, etc.). This file is useful if you want to look at into IGV for instance. You can then color the reads based on the XX flag to look at the different classes of read pairs.
N
