### ISSUE TITLE
label misplacement in plotMapping.pdf

### ISSUE THREAD

**Issue by e-manduchi** [nservant/HiC-Pro#109]
Hello, 
I've just used HiPro v2.9.0 for the first time and noticed that the labels indicating % values in the histogram are misplaced. I'm attaching the output of my run.
For example, in the first histogram the value 9.7% should be placed in the bottom gray rectangle, whereas currently it is placed together with the 90.3% in the same blue rectangle. Similarly for the other plots.
Thanks for your attentions.
[plotMapping.pdf](https://github.com/nservant/HiC-Pro/files/1482796/plotMapping.pdf)

**Comment by e-manduchi** [comment]
P.S. Similar issues occur in the other bar plots generated. See attached
[plotHiCContactRanges.pdf](https://github.com/nservant/HiC-Pro/files/1482806/plotHiCContactRanges.pdf)
[plotHiCFragment.pdf](https://github.com/nservant/HiC-Pro/files/1482807/plotHiCFragment.pdf)
[plotMappingPairing.pdf](https://github.com/nservant/HiC-Pro/files/1482809/plotMappingPairing.pdf)

**Comment by nservant** [comment]
Hi,
yes absolutely. This is because recent versions of ggplot2 update the way they deal with the text label.
I fixed it in the devel branch of HiC-Pro. I'll try to release a new stable version that correct for this bug before the end of the year. Best

**Comment by nservant** [comment]
Btw, if you want to try the devel version (2.10.0), do not hesitate :) even if it is not yet stable.

**Comment by e-manduchi** [comment]
Thanks for your prompt response!
