### ISSUE TITLE
File system loop detected

### ISSUE THREAD

**Issue by Kaaaaaai** [nservant/HiC-Pro#110]
Hi nservant,

I installed HiC-Pro and ran test_data successfully. But now I use my own data and have been in troubled.

Here I paste my error message，thanks.

[gaojd@mendel dro_data]$ time /lustre/user/lulab/gaojd/wxk/software/HiC/HiC-Pro_2.9.0/bin/HiC-Pro -c running_room/config-hicpro.txt -i /lustre/user/lulab/gaojd/wxk/data/drosophila_data/dro_data/ -o hicpro_18_test
find: **File system loop detected**; '/lustre/user/lulab/gaojd/wxk/data/drosophila_data/dro_data/HiC-Pro_results/rawdata' is part of the same file system loop as '/lustre/user/lulab/gaojd/wxk/data/drosophila_data/dro_data/'.

real	0m0.115s
user	0m0.052s
sys	0m0.144s

What could I do to solve this ?

thanks,
kai

Then I ran test again and failed. I think there may be some connections between the two issues, so I copied the test error below.

[gaojd@mendel 11_18_tmp]$ less nohup.out 
/lustre/user/lulab/gaojd/wxk/data/11_18_tmp/hicpro_latest_test folder alreads exists. Do you want to delete it before running ?(y/n) [n] : 
/lustre/user/lulab/gaojd/wxk/software/HiC/HiC-Pro_2.9.0/bin/HiC-Pro: line 258: read: read error: 0: Bad file descriptor
0.03user 0.12system 0:00.09elapsed 158%CPU (0avgtext+0avgdata 1560maxresident)k
0inputs+88outputs (0major+17194minor)pagefaults 0swaps
nohup.out (END)

**Comment by Kaaaaaai** [comment]
Nservant, thank you for your reply.

I checked and found that there are two different HiC-Pro in my environment. When I deleted to have only one left, the software ran smoothly at once, with no error in the middle of the process.

Thank you so much,
Kai

**Comment by Kaaaaaai** [comment]
Hi nservant,

I encountered such a problem when I ran my own data with HiC-Pro:

Run HiC-Pro 2.9.0
--------------------------------------------
Sat Nov 18 20:40:49 EST 2017
Bowtie2 alignment step1 ...
/lustre/user/lulab/gaojd/wxk/software/HiC/HiC-Pro_2.9.0/scripts/bowtie_wrap.sh -c /lustre/user/lulab/gaojd/wxk/data/11_19_tmp/config-hicpro.txt -u >> hicpro.log
--------------------------------------------
Sun Nov 19 01:40:48 EST 2017
Bowtie2 alignment step2 ...
/lustre/user/lulab/gaojd/wxk/software/HiC/HiC-Pro_2.9.0/scripts/bowtie_wrap.sh -c /lustre/user/lulab/gaojd/wxk/data/11_19_tmp/config-hicpro.txt -l >> hicpro.log
--------------------------------------------
Sun Nov 19 04:50:48 EST 2017
Combine both alignment ...
/lustre/user/lulab/gaojd/wxk/software/HiC/HiC-Pro_2.9.0/scripts/bowtie_combine.sh -c /lustre/user/lulab/gaojd/wxk/data/11_19_tmp/config-hicpro.txt >> hicpro.log
~
~
~
~
~
~
It stopped running, but the test data is working well. Will this have some connection with the quality of my sequencing data or just a software error?

Thank you so much,
Kai

**Comment by nservant** [comment]
Hi

Could you have a look in the log folder. If the program stops, I guess 
you should find an error in the logs.

thanks


Le 19/11/2017 à 12:07, Kaaaaaai a écrit :

**Comment by Kaaaaaai** [comment]
Hi nservant,

I attached the log file below,

/lustre/user/lulab/tools/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/dixon_2M/SRR400264_00_R1_hg19.bwt2glob.unmap.fastq --rg-id BMG --rg SM:SRR400264_00_R1 --phred33-quals -p 2 -x /lustre/user/lulab/gaojd/wxk/data/hg19_tmp/hg19 -U rawdata/dixon_2M/SRR400264_00_R1.fastq.gz 2> logs/dixon_2M/bowtie_SRR400264_00_R1_global_hg19.log | /lustre/user/lulab/jiangy/software/bin/samtools view -F 4 -bS - > bowtie_results/bwt2_global/dixon_2M/SRR400264_00_R1_hg19.bwt2glob.bam
/lustre/user/lulab/tools/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/dixon_2M/SRR400264_00_R2_hg19.bwt2glob.unmap.fastq --rg-id BMG --rg SM:SRR400264_00_R2 --phred33-quals -p 2 -x /lustre/user/lulab/gaojd/wxk/data/hg19_tmp/hg19 -U rawdata/dixon_2M/SRR400264_00_R2.fastq.gz 2> logs/dixon_2M/bowtie_SRR400264_00_R2_global_hg19.log | /lustre/user/lulab/jiangy/software/bin/samtools view -F 4 -bS - > bowtie_results/bwt2_global/dixon_2M/SRR400264_00_R2_hg19.bwt2glob.bam


I deleted the files the software created before and tried again. Everything was going well.
Can you tell me what led to the previous error?

**Comment by nservant** [comment]
Hi Kai,
Difficult to say. Did you look into the log folder directly (instead of the main log). In the log folder you can find more details. But if you re-run HiC-pro in the same output, the old logs have been replaced.
Best
