### ISSUE TITLE
(ERR): bowtie2-align exited with value 1

### ISSUE THREAD

**Issue by Kaaaaaai** [nservant/HiC-Pro#115]
Hi nservant,

Sorry to bother you again. 
Yesterday I was running the software and it appeared a new problem. Here I posted the error message below.

Mon Nov 27 15:17:48 EST 2017
Bowtie2 alignment step2 ...
/lustre/user/lulab/gaojd/wxk/software/HiC/HiC-Pro_2.9.0/scripts/bowtie_wrap.sh -c /lustre/user/lulab/gaojd/wxk/data/dro_cell-12/config-hicpro.txt -l >> hicpro.log
Exit: Error in Bowtie alignment
make: *** [bowtie_local] Error 1

log file error:
[gaojd@mendel genome_fastq]$ less -S bowtie_SRR_R1_dm6.bwt2glob.unmap_local.log 
Warning: Could not open read file "bowtie_results/bwt2_global/genome_trimmed.fastq/SRR_R1_dm6.bwt2glob.
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1

[gaojd@mendel genome_fastq]$ less -S readsTrimming.log 
##Fastq file: bowtie_results/bwt2_global/genome_fastq/SRR_R2_dm6.bwt2glob.unmap.fastq
##Restriction sites:
GATCGATC
##Output File: bowtie_results/bwt2_global/genome_trimmed.fastq/SRR_R2_dm6.bwt2glob.unmap.fastq

##Trimmed reads: 36688

Will this error be related to the length of the reads? Because the length of reads I used this time is 36bp.

Best,
kai

**Comment by nservant** [comment]
Hi kai
I think that there is something wrong in the name of your input folder.
Do you have the "fastq" keyword in the directory name ?
N

**Comment by Kaaaaaai** [comment]
yes, the path I put my _R1/R2 fastq files is like that 
/lustre/user/lulab/gaojd/wxk/data/dro_cell-12/test_data/genome_fastq/

**Comment by nservant** [comment]
This is something that I have fixed in the current devel version but not in the 2.9.0.
Please remove the "fastq" in the directory names.
Thanks
