### ISSUE TITLE
Problem with paring of R1 and R2

### ISSUE THREAD

**Issue by BohanC** [nservant/HiC-Pro#117]
Hi,Servant
Thank you so much for the brilliant software Hic-pro. I have a problem in the process beginning from the fastq data. There are something wrong with the pairing of R1 and R2 tags process .

Pairing of R1 and R2 tags ...
/usr/local/hicpro/2.9.0/HiC-Pro_2.9.0/scripts/bowtie_pairing.sh -c /config/file/path/config_from_bam.txt >> hicpro.log

make: *** [bowtie_pairing] Error 1

I checked the READs name in fastq R1 and R2. I am not sure whether they should be absolutely same? 
For example, the first read’s name in R1 is xxxxxxxxxxxN:1:xxxxxxxxx . In R2 is 
xxxxxxxxxxxN:2:xxxxxxxxx . Is it the point of error? Because in test data you provide, the Reads name are absolutely same in R1 and R2.

**Comment by nservant** [comment]
Hi BohanC,
I think I already answer your question, but 'yes', R1 and R2 should have exactly the same names !
Best

**Comment by BohanC** [comment]
Hi nservant!

I have solved the problem with the different reads name in R1 and R2! Thank you so much. Here are some questions make me confused. After generated the matrix, how can I determine which solution is prosper? Then I was confused on what should I do after getting the Hic-Pro results. Could I have a pipeline or some software you suggest for subsequent analysis, such as comparing the samples.

Best,
BohanC 

发自我的 iPhone
