### ISSUE TITLE
File conversion

### ISSUE THREAD

**Issue by yuzhang0327** [nservant/HiC-Pro#118]
Hi,

As I want to convert the validpair to .hic files,however, most of our former data were generated with hicpro 2.7.1, we can not directly convert them to .hic files. I just wonder do we have an easy way to convert the old format files except for rerunning the fastq data?

Best,
Yu

**Comment by nservant** [comment]
Hi Yu,
Could you show me the 10 first lines of your .AllvalidPairs please ?
I'll think about that.
Cheers

**Comment by yuzhang0327** [comment]
Of course! Here is the files:

ST-E00126:415:HKVGNALXX:2:2104:11921:60360      chr1    33      -       chr1    166324  +       111
ST-E00126:415:HKVGNALXX:2:1116:18101:8868       chr1    33      -       chr9    53323980        -       236
ST-E00126:415:HKVGNALXX:2:1124:14894:37770      chr1    34      -       chr1    32183   +       179
ST-E00144:520:H553CCCXY:3:1109:17371:19803      chr1    34      -       chr5    31400   +       329
ST-E00144:520:H553CCCXY:3:2202:8613:36873       chr1    34      -       chr5    4096606 -       236
ST-E00318:325:HJMTFALXX:2:2112:14286:21842      chr1    35      -       chr1    698797  -       269
ST-E00144:520:H553CCCXY:3:1217:6614:73000       chr1    35      -       chr5    4413813 -       116
ST-E00545:100:HCNYYALXX:1:1101:31385:31037      chr1    36      -       chr5    16551479        -       156
ST-E00144:520:H553CCCXY:3:1203:27336:11857      chr1    36      -       chr7    28705333        +       171
ST-E00144:520:H553CCCXY:3:2104:15757:7937       chr1    36      -       chr14   35142747        -       147

Thanks very much for your kind help!

Best,
Yu

**Comment by nservant** [comment]
Hi,
I just update the code to support the old format
https://github.com/nservant/HiC-Pro/blob/devel/bin/utils/hicpro2juicebox.sh
Could you just try this version of hicpro2juicebox.sh ... it should work !
However, note that Juicebox will not filter based on the mapping quality, and I'm not sure you can zoom in until the restriction fragments resolution (I did not test actually)
Let me know if it works
Best

**Comment by yuzhang0327** [comment]
Hi,

Sorry for the delayed reply. I have tried several files using the script, it works very well. That's great as it will save a lot of time. Thanks very much!

Best,
Yu

**Comment by nservant** [comment]
great ! N
