### ISSUE TITLE
No error but did not generate the "hic_results" directory

### ISSUE THREAD

**Issue by yeswzc** [nservant/HiC-Pro#120]
Hi,
I succeeded run HiC-Pro under SGE with test data. 
But when revised the config file to my own data, and run step1,the directory "hic_results" didnot show up.No warn or error information occured.
What is wrong?

**Comment by nservant** [comment]
Hi,
Could you have a look within the logs folder. I'm sure one of the log file should contain an error message ...

**Comment by yeswzc** [comment]
They are all empty.

**Comment by yeswzc** [comment]
My HiCPro_step1_IMR90_split.sh fike:
#!/bin/bash
#$ -l h_rt=10:00:00
#$ -M yeswzc
#$ -m ae
#$ -j y
#$ -N HiCpro_s1_IMR90_split
##$ -q batch
#$ -V
#$ -t 1-1
#$ -pe smp 16
#$ -cwd

FASTQFILE=inputfiles_IMR90_split.txt; export FASTQFILE
make --file /software/HiC-Pro_2.9.0/scripts/Makefile CONFIG_FILE=/prj/04.HiCPro/01.config.txt CONFIG_SYS=/software/HiC-Pro_2.9.0/config-system.txt all_sub 2>&1

And inputfiles_IMR90_split.txt file:
one/buffalo_L1_R1_clean.fastq.gz

linux$ cat hicpro.log  
-----------
rawdata/one/HIC_L1_R1_clean.fastq
rawdata/one/HIC_L1_R2_clean.fastq
-------------
rawdata/one/HIC_L1_R1_clean.fastq
rawdata/one/HIC_L1_R2_clean.fastq
Running bowtie on full length reads ...
Running bowtie on full length reads ...
/software/bowtie2-2.3.4-alpha-linux-x86_64/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/one/HIC_L1_R1_clean_B45_2.fa.bwt2glob.unmap.fastq --rg-id BMG --rg SM:HIC_L1_R1_clean --phred33-quals -p 2 -x /prj/00.reference//B45_2.fa -U rawdata/one/HIC_L1_R1_clean.fastq.gz 2> logs/one/bowtie_HIC_L1_R1_clean_global_B45_2.fa.log | /software/align/samtools-1.3.1/samtools view -F 4 -bS - > bowtie_results/bwt2_global/one/HIC_L1_R1_clean_B45_2.fa.bwt2glob.bam
/software/bowtie2-2.3.4-alpha-linux-x86_64/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/one/HIC_L1_R2_clean_B45_2.fa.bwt2glob.unmap.fastq --rg-id BMG --rg SM:HIC_L1_R2_clean --phred33-quals -p 2 -x /prj/00.reference//B45_2.fa -U rawdata/one/HIC_L1_R2_clean.fastq.gz 2> logs/one/bowtie_HIC_L1_R2_clean_global_B45_2.fa.log | /software/align/samtools-1.3.1/samtools view -F 4 -bS - > bowtie_results/bwt2_global/one/HIC_L1_R2_clean_B45_2.fa.bwt2glob.bam


linux$ ll logs/one/ 
two log files are both empty.

Could you help ?

**Comment by nservant** [comment]
I would expect a log file in logs/one/bowtie ...
Otherwise it means that bowtie was not run ...
What about if you copy/paste the command line form the log file on your cluster ? does it work ?
And stupid question, but are you sure that it is not running ? the mapping can take a few hours ...

**Comment by yeswzc** [comment]
Thank you for replying.
The log file do exist in  logs/one/bowtie ..., but are all empty, with no content.
The logs are command for runnng bowtie, they are succeed running with bam files and fastq files in the bowtie_results/bwt2_global/one/ directory.
What could be wrong ?

**Comment by nservant** [comment]
So you have some results the bowtie folder ??
Did you succeed in running HiC-pro in standalone mode (no cluster) ?

**Comment by yeswzc** [comment]
Yes. In the bowtie folder:
ll bowtie_results/bwt2_global/one/
total 39213068
-rw-r--r-- 1 wuzhichao xujianlong_group  4135583744 Dec 21 23:02 HIC_L1_R1_clean_B45_2.fa.bwt2glob.bam
-rw-r--r-- 1 wuzhichao xujianlong_group 15409315840 Dec 21 23:03 HIC_L1_R1_clean_B45_2.fa.bwt2glob.unmap.fastq
-rw-r--r-- 1 wuzhichao xujianlong_group  4462739456 Dec 21 23:03 HIC_L1_R2_clean_B45_2.fa.bwt2glob.bam
-rw-r--r-- 1 wuzhichao xujianlong_group 16146345984 Dec 21 23:03 HIC_L1_R2_clean_B45_2.fa.bwt2glob.unmap.fastq

I successfully run the test data on both SGE mode and standalone mode. And I did not try standalone mode with  my data. They are too large. Is there a way to jump to the step next to bowtie? I can run bowtie under clusert model and then run flowing step of HiC-Pro.

**Comment by nservant** [comment]
ok. And do you have a bowtie_results/bwt2_local/one/ folder ??
Thanks very strange. Usually, you have no error message when the cluster decide to just kill the job.
If you dataset is too big, I would first suggest to split your input fastq files into reads chuncks using the split_reads utility ?
In the intput folder of your sample 'one', you can put as many fastq files as you want ... these files will be processed in parallele. With smaller files it would be good to see if it could run.

And I also saw that you did not specify any memory information in your job submission parameter
 #$ -l h_rt=10:00:00
I do not know how your cluster is configured, but for instance, on my cluster, if I do not specify how many RAM I need, it allows by default something like 1Gb. This could explain that your job was killed, because it requires too much RAM compare to what you ask for.
Best

**Comment by yeswzc** [comment]
It just worked now, very werid.  But I had three folder under fastq directory, it only read one.
I think it may because the file name must be ended with fastq.gz, not fq.gz
Thank you for help.
