### ISSUE TITLE
How to pool several datasets

### ISSUE THREAD

**Issue by Tocci89** [nservant/HiC-Pro#121]
Hi nservant,
is there a way in Hic-Pro to combine several datasets in order to obtain a pool of replicates?
Running Hic-Pro on different replicates together I obtain one matrix-set per replica, but I'd like to have the matrix resulting from the union of them (like HOMER does). 
Thanks in advance

**Comment by nservant** [comment]
Hi Tocci89,
HiC-Pro will consider as a sample all reads within one input folder ...
If you run it with one replicate per input folder, let's say ;
data
++ sample1
++++ fastq files of samples 1
++ sample2
+++++ fastq files of samples2
....

You can then rerun HiC-pro starting from the validPairs files you get during the first analysis.
For instance ;
++ data
++++ sample_merge
++++++++ validPairs replicate1
++++++++ validPairs replicate2
...
In this case, all files within the same folder will be considered as coming from the same sample, and will be merged. Just rerun Hic-Pro in stepwise mode starting with option -s merge_persample -s build_contact_maps -s ice_norm
Hope it helps

**Comment by Tocci89** [comment]
Thanks so much!

**Comment by jennymoon90** [comment]
Hi nservant,
How do you get plotHiCContactRanges.pdf?
I ran the mapping step first with -s mapping -s proc_hic -s quality_checks, and only got the other 3 pdf files in "pic" folder. Then I ran -s merge_persample -s build_contact_maps -s ice_norm, and got the "matrix" folder. However, the plotHiCContactRanges.pdf file is missing in the first step, and "pic" folder was not generated in the second step.
Thank you,
Jenny

**Comment by jennymoon90** [comment]
Hi nservant,
Thank you for your reply.

I saw that the input files for quality checks is bam files.
"INPUT DATA TYPE IN STEPWISE MODE
-s mapping	.fastq(.gz) files
-s proc_hic	.bam files
-s quality_checks	.bam files
-s merge_persample	.validPairs files
-s build_contact_maps	.validPairs files
-s ice_norm	.matrix files"

In my case, I had moved all .validpairs files to a single folder, and run:
HiC-Pro -i $VALIDPAIRS -o $OUTPUT -c $HOME/config-hicpro.txt -s merge_persample -s build_contact_maps -s ice_norm # Modify config-hicpro.txt
Now, do I just need to run HiC-Pro -I $INPUT -o $OUTPUT -c $HOME/config-hicpro.txt -s quality_checks? And what do I use as INPUT here?
Thank you,
Jenny

**Comment by jennymoon90** [comment]
Thank you, nservant.
This works.
Jenny

**Comment by benxiahu** [comment]
> Hi Tocci89,
> HiC-Pro will consider as a sample all reads within one input folder ...
> If you run it with one replicate per input folder, let's say ;
> data
> ++ sample1
> ++++ fastq files of samples 1
> ++ sample2
> +++++ fastq files of samples2
> ....
> 
> You can then rerun HiC-pro starting from the validPairs files you get during the first analysis.
> For instance ;
> ++ data
> ++++ sample_merge
> ++++++++ validPairs replicate1
> ++++++++ validPairs replicate2
> ...
> In this case, all files within the same folder will be considered as coming from the same sample, and will be merged. Just rerun Hic-Pro in stepwise mode starting with option -s merge_persample -s build_contact_maps -s ice_norm
> Hope it helps

I have 3 replicates for Hi-C. I obtained 3 folders which included .allValidPairs and matrices after finishing HiC-Pro. I want to merge those replicates.
I firstly put all replicated .allValidPairs into one folder: merge
inputfiles_HiCHIP.txt 
/proj/HiC_activity/Hi-C/home_output/hic_results/data/merge/validPairs_replicate1
/proj/HiC_activity/Hi-C/home_output/hic_results/data/merge/validPairs_replicate2
/proj/HiC_activity/Hi-C/home_output/hic_results/data/merge/validPairs_replicate3

I did not change the ./config-hicpro_home.txt which was used in "HiC-Pro -i ./home -o ./home_output -c ./config-hicpro_home.txt -p"

HiC-Pro -i ./merge -o ./merge_output  -p -s merge_persample -s build_contact_maps -s ice_norm -c ./config-hicpro_home.txt. When I ran this command, I got the following error:

Exit: Error: Directory Hierarchy of rawdata '/proj/HiC_activity/Hi-C/home_output/hic_results/data/merge' is not correct. No '.validPairs' files detected

Do I need to fix the config-hicpro_home.txt?
Thanks in advance.

**Comment by rikrdo89** [comment]
> Hi Tocci89,
> HiC-Pro will consider as a sample all reads within one input folder ...
> If you run it with one replicate per input folder, let's say ;
> data
> ++ sample1
> ++++ fastq files of samples 1
> ++ sample2
> +++++ fastq files of samples2
> ....
> 
> You can then rerun HiC-pro starting from the validPairs files you get during the first analysis.
> For instance ;
> ++ data
> ++++ sample_merge
> ++++++++ validPairs replicate1
> ++++++++ validPairs replicate2
> ...
> In this case, all files within the same folder will be considered as coming from the same sample, and will be merged. Just rerun Hic-Pro in stepwise mode starting with option -s merge_persample -s build_contact_maps -s ice_norm
> Hope it helps

Just to clarify, we should use the allvalidpairs instead of validpairs when pooling replicates, given that the allvalidpairs are aready deduplicated, right?

**Comment by nservant** [comment]
Currently the `-s merge_persample` step requires .validPairs, and will remove duplicates if RM_DUP=1 in the config file.
Otherwise, you can directly use `.allValidPairs` with `-s build_contact_maps`

**Comment by jennymoon90** [comment]
Hi nservant,
When I establish the directories, can I link the .validPairs files using "ln -s", or do I have to copy paste all .validPairs into the same directory?
Thanks,
Jenny

**Comment by nservant** [comment]
links should be ok
N

**Comment by raquelsofi** [comment]
> 

Hi Nicholas,

I tried to run in the way you describe above, with two .validPairs files inside the sample folder, but i obtain two raw matrices instead of one.


This was my command:

qsub -cwd -pe make 15 -l hostname=node10 \
-e loge_hicpro.txt -o logo_hicpro.txt \
-b yes singularity exec hicpro_latest_ubuntu.img HiC-Pro \
-i data/ \
-c config_test_latest.txt \
-s merge_persample \
-s build_contact_maps \
-s ice_norm \
-o MergedSamplesHuman25kb

and data folder contains 

~/HiCPRO_mergedreplicas/hg38/data $ ls *

Sample-Fresh:
S39779_B6-Fre_S1_L002_001_hg38.bwt2pairs.validPairs
S39780_B12-Fre_S2_L002_001_hg38.bwt2pairs.validPairs

Sample-Frozen:
S39781_C12-Fro_S3_L002_001_hg38.bwt2pairs.validPairs
S39782_D12-Fro_S4_L002_001_hg38.bwt2pairs.validPairs


This is the output of HiC matrix results:

~/HiCPRO_mergedreplicas/hg38 $ ls MergedSamplesHuman25kb/hic_results/matrix/Sample-Fresh/raw/25000/

Sample_S39779_B6-Fre_25000_abs.bed 
Sample_S39780_B12-Fre_25000_abs.bed
Sample_S39779_B6-Fre_25000.matrix  
Sample_S39780_B12-Fre_25000.matrix


Any thought why the samples are not being merged?

Thank you!

Raquel
