### ISSUE TITLE
LIGATION SITE : What does it mean?

### ISSUE THREAD

**Issue by bagavi** [nservant/HiC-Pro#125]
I am Vivek, a non-biologist, working with HiC data. I was am stuck defining the following parameter in the config file: **LIGATION SITE**

I understand that the above ligation junction is used to trim the reads during the second step of alignment.  However, how do I determine the _ligation site_ of the [dataset](https://www.ncbi.nlm.nih.gov/sra/?term=SRR2911057) I am working on? This dataset was published in [genome research](http://genome.cshlp.org/content/26/3/342.short)

**Comment by nservant** [comment]
Hi Vivek
I think I already directly answer your question, but anyway .... the ligation motif depends of your restriction enzyme. Did you check in the paper how the Hi-C data were generated ? is it with a 6-bp cutter ? a 4bp cutter ? which enzyme, etc.
Based on these information, and using the cutting motif, you should easily be able to infer the expected motif after ligation.
best

**Comment by tangyueting** [comment]
Hi, I am Ting,I used two enzymes and got four ligation sites, I would like to understand if the software supports specifying multiple values ​​for LIGATION_SITE in a single config file.Looking forward to your reply, thanks.
