### ISSUE TITLE
Exit: Error in Bowtie alignment make: *** [bowtie_global] Error 1

### ISSUE THREAD

**Issue by mkmwong** [nservant/HiC-Pro#126]
Hi, 

I tried to run hicpro on the test data provided, and I changed the path of bowtie2 index accordingly.
Here's the output of the run:
Run HiC-Pro 2.10.0
--------------------------------------------
Sun Jan 21 17:22:06 PST 2018
Bowtie2 alignment step1 ...
/home/mkmwong/HiCPro_bin/HiC-Pro_2.10.0/scripts/bowtie_wrap.sh -c /scratch/users/mkmwong/config_test_latest.txt -u >> hicpro.log
Exit: Error in Bowtie alignment
make: *** [bowtie_global] Error 1

real    0m2.350s
user    0m0.135s
sys     0m0.229s

and here's what in hicpro.log
  1 -----------
  2 rawdata/dixon_2M_2/SRR400264_01_R1.fastq.gz
  3 rawdata/dixon_2M_2/SRR400264_01_R2.fastq.gz
  4 -------------
  5 rawdata/dixon_2M_2/SRR400264_01_R1.fastq.gz
  6 rawdata/dixon_2M_2/SRR400264_01_R2.fastq.gz
  7 Running bowtie on full length reads ...
  8 Running bowtie on full length reads ...
  9 /home/mkmwong/bin/bowtie2-2.2.4/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un hicpro_latest_test/bowtie_results/bwt2_globa
    l/dixon_2M_2/SRR400264_01_R1_hg19.bwt2glob.unmap.fastq --rg-id BMG --rg SM:SRR400264_01_R1 --phred33-quals -p 2 -x /scratch/users/mkmwong/bowtie2_idx/hg19 -U r
    awdata/dixon_2M_2/SRR400264_01_R1.fastq.gz 2> logs/dixon_2M_2/bowtie_SRR400264_01_R1_global_hg19.log | /home/mkmwong/anaconda3/envs/py27/bin/samtools view -F 4
     -bS - > hicpro_latest_test/bowtie_results/bwt2_global/dixon_2M_2/SRR400264_01_R1_hg19.bwt2glob.bam
 10 /home/mkmwong/bin/bowtie2-2.2.4/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un hicpro_latest_test/bowtie_results/bwt2_globa
    l/dixon_2M_2/SRR400264_01_R2_hg19.bwt2glob.unmap.fastq --rg-id BMG --rg SM:SRR400264_01_R2 --phred33-quals -p 2 -x /scratch/users/mkmwong/bowtie2_idx/hg19 -U r
    awdata/dixon_2M_2/SRR400264_01_R2.fastq.gz 2> logs/dixon_2M_2/bowtie_SRR400264_01_R2_global_hg19.log | /home/mkmwong/anaconda3/envs/py27/bin/samtools view -F 4
     -bS - > hicpro_latest_test/bowtie_results/bwt2_global/dixon_2M_2/SRR400264_01_R2_hg19.bwt2glob.bam
~

**Comment by nservant** [comment]
Hi
Could you look within the log folder ? you should find a bowtie.log file ?
Thanks

**Comment by iceduangbing** [comment]
who know how to solve this trouble

**Comment by nservant** [comment]
Could you check the bowtie log in the log folder please ?

**Comment by ZihuaLiu666** [comment]
Hey! I ever encountered this problem. Please check your config.txt file.

In your configure file, there should be some info like this:

#######################################################################
## Annotation files
#######################################################################

REFERENCE_GENOME = PBH.v1.5

As you can see, my reference genome is PBH.v1.5.fasta but the file name I wrote here is PBH.v1.5 (without .fasta). And then my bowtie2 index files are:
####
PBH.v1.5.1.bt2
PBH.v1.5.2.bt2
PBH.v1.5.3.bt2
PBH.v1.5.4.bt2
PBH.v1.5.rev.1.bt2
PBH.v1.5.rev.2.bt2
####

And I highly recommend you to store your reference genome file, bowtie2 index files, BED file and sizes file in one folder, for example, you could name the folder as 'ref' or other names as you like. @iceduangbing

**Comment by mkmwong** [comment]
Dear all,

I actually fixed that issue after discussing with Nicolas on the HiC-Pro forum. Just for all of your reference on an approach to solve this issue, please go to the following thread: https://groups.google.com/forum/#!searchin/hic-pro/mandy%7Csort:date/hic-pro/RZu_JS2ouns/5F7FtIqyBQAJ Thanks!
