### ISSUE TITLE
hicpro2higlass.sh normalization failure

### ISSUE THREAD

**Issue by aakashsur** [nservant/HiC-Pro#127]
Hi, in the hicpro2higlass.sh script, I don't think the --norm flag is working as intended. It looks like including the flag triggers 
```cooler zoomify $out```
and excluding the flag triggers 
```cooler zoomify --no-balance $out```
According the the latest docs (http://cooler.readthedocs.io/en/latest/cli.html#cooler-zoomify) , the default is no balancing, therefore the flag should explicitly trigger balancing, i.e. 
`cooler zoomify --balance $out`

**Comment by nservant** [comment]
corrected in v.2.11.0
