### ISSUE TITLE
Single chromosome sparse matrix

### ISSUE THREAD

**Issue by Tocci89** [nservant/HiC-Pro#132]
Hi Nservant,
is there a way to generate the .matrix and the _ord/_abs.bed files for each chromosome, taking only intrachromosomal bins?
Thanks in advance!

**Comment by nservant** [comment]
Hi,
Not yet. But it is a good idea. I can add it in the todo list
In the meantime you can do it in R, using the HiTC package.
Load the HiC-Pro output using the importC function.
Then export using the exportC function.
Best

**Comment by Tocci89** [comment]
Thanks a lot!

**Comment by nservant** [comment]
split_sparse.py utils ready in devel version.
