### ISSUE TITLE
How does HiC-Pro work to generate a matrix?

### ISSUE THREAD

**Issue by werhoog** [nservant/HiC-Pro#133]
I already knew that HiC-Pro can generate valid pairs of reads.And then how this software work to generate a matix which can be plot to show HiC heatmap?That is to say,the matrix score used to plot a heatmap come from?

**Comment by werhoog** [comment]
the latter , thanks!

**Comment by nservant** [comment]
This is pretty straightforward. On one side you have your genomic bins at the desired resolution. On the other side you have your reads assigned to restriction fragments.
For a pair of genomic bins, we can therefore find how many pairs of interacting loci (reads) overlap.
The matrix is just build by summing up for all pairs of genomic bins, how many time we observe an interaction.
