### ISSUE TITLE
HOW bowtie2 work?

### ISSUE THREAD

**Issue by werhoog** [nservant/HiC-Pro#135]
It seems that bowtie2 maps reads pairs seperatly. However, bowtie2  can map paired reads in a command line.So ，how bowtie2 work in HiC-Pro to map paired reads?

**Comment by nservant** [comment]
In Hi-C, we usually align the R1 and R2 reads independently as we do not have any a priori on the distance between the two reads. As paired-end mappers usually expect to have the R1/R2 reads a few hundred base pairs apart, this could lead to wrong mapping ...
