### ISSUE TITLE
why use -f paremeter to transform the validpairs to juicer input?

### ISSUE THREAD

**Issue by werhoog** [nservant/HiC-Pro#137]
As the title shows , what the bed file function is . Because the HiC-Pro pipline already use such bed file to filter useless pairs or reads to  get better validpairs?
Thanks!

**Comment by nservant** [comment]
yes, but the format of the two files are not the same.
In the hicpro2juicebox script, I'm using the HiC-Pro BED file (-r option) to create the Juicebox restriction file.
