### ISSUE TITLE
Allele assignment swapped in validPairs compared to BAM

### ISSUE THREAD

**Issue by ilya-kolpakov** [nservant/HiC-Pro#140]
I have a following pair in the (paired) BAM file

<id>	83	chr?	16752771	42	77M	=9487408	0	<stripped>	XA:i:2
<id>	163	chr?	9487408	35	98M	=	16752771	0	<stripped>	XA:i:0

In the validPairs file, however, it appears as

<id>	chr?	9487456	+	chr?	16752808	-287	HIC_chr?_141	HIC_chr?_8480	35	42	2-0

I would expect that the allele tag should be '0-2' and not '2-0' as it is the mate at position 16752771 which is originally assigned.

This is the single instance I tracked down after noticing that the mate at 9487456 could not be assigned to an allele (since it spans no variants). I do not know at this moment how frequently this happens.

**Comment by nservant** [comment]
already answered in the forum.
This should not have any impact on the results, but I agree that this is not very logical.
Checked in the mapped_2hic_fragments.py file. Line 636, as tag is assigned.
But then, reads are reordered Line 690 before writing the output.
I can see to fix that in a next release.

**Comment by nservant** [comment]
Has been fixed on 2.11.0

**Comment by ilya-kolpakov** [comment]
Thank you, Nicholas.
