### ISSUE TITLE
Is bam file remove duplicates?

### ISSUE THREAD

**Issue by werhoog** [nservant/HiC-Pro#142]
Hi,thanks for your great program.I am confused about the bam file from  bowtie_results fold.I used the newest version of HiC-Pro . 1)Therefore, are those merge bam files(in bw2/  fold) from R1 and R2 bams been remove duplicates? And I also find a file in hic_results fold in data fold named *****_interaction.sam. 2)So ,Does  this sam file equal to such bam file in bw2 ?

Thank you!

**Comment by nservant** [comment]
Hi,
Duplicates are not remove at the BAM level, but after the detection of valid Pairs.
Basically, the _allValidPairs contains all de-duplicated valid pairs for a given samples .... so duplicates are removed when we merge the .validPairs file.
Regarding the _interaction.sam file, this is  useful if you want to look at the reads using IGV for instance. All mapped reads are in this file (including duplicates), and pairs are annotated according to their classification (valid, dangling-end, etc). This is just a quality control.
Hope it helps
