### ISSUE TITLE
find: “bowtie_results/bwt2”: No such file or dir

### ISSUE THREAD

**Issue by werhoog** [nservant/HiC-Pro#149]
Hi, It seems there are some wrong in "mapped_2hic_fragments" step.
1) I used merge_bam from __R1.bam and  __R2.bam ( not begin with raw fastqfiles)
2) step 1) is fine for I get  right fastq files and mergeSAM.log 

3)dir like below:
/test/merge_results/bowtie_results/bwt2/protein1/protein1_merge.bam.bwt2pairs.bam
/test/merge_results/bowtie_results/bwt2/protein2/protein2_merge.bam.bwt2pairs.bam
/test/merge_results/bowtie_results/bwt2/protein3/protein3_merge.bam.bwt2pairs.bam
/test/merge_results/config_csseq_mm10.txt
/test/merge_results/logs
/test/merge_results/rawdata
/test/merge_results/tmp

Actually I run -s mapping -s proc_hic -s quality_checks -s  build_contact_maps, but only merged bams appeared which confused me a lot.

And I run “HiC-Pro_2.10.0/bin/HiC-Pro -i  /test/merge_results/bowtie_results/bwt2/  -o 
/test/merge_results/hic_results  -c  /test/merge_results/config_csseq_mm10.txt   -s proc_hic -s quality_checks  -s  build_contact_maps -s ice_norm   "

Thanks !

**Comment by werhoog** [comment]
I run “HiC-Pro_2.10.0/bin/HiC-Pro -i /test/merge_results/bowtie_results/bwt2/ -o
/test/merge_results/hic_results -c /test/merge_results/config_csseq_mm10.txt -s proc_hic -s quality_checks -s build_contact_maps -s ice_norm " and got "bowtie_results/bwt2”: No such file or dir" in step   "mapped_2hic_fragments"

**Comment by nservant** [comment]
Hi,
This is because there is currently no way to start from "paired" BAM file. It requires the R1 and R2 bam files. This point is in my TODO list ...
In addition, I think that trying to write everything in the same folder might not work in some cases.
Could you try to specify another output folder like ;

```
HiC-Pro -i /test/merge_results/bowtie_results/bwt2/ -o
/test/merge_results_2 -c /test/merge_results/config_csseq_mm10.txt -s proc_hic -s quality_checks -s build_contact_maps -s ice_norm 
```

Thanks

**Comment by werhoog** [comment]
Actually, I failed it .But I just run .py program to get validfiles.
And I just want to ask if there is some way to get matrix file without "0" discard as well as inner-chromosome interaction?
Thank you!
