### ISSUE TITLE
Bug in install prefix ??

### ISSUE THREAD

**Issue by nservant** [nservant/HiC-Pro#150]
Hi Ray,
Sorry I miss your email but I think I already answer on the forum.
It means that HiC-Pro was not successfully installed.
The config-system.txt file is created at the end of the installation 
process.

But now that I'm looking more carefully at your command, I think there 
is something strange in the installation path.

/isg/shared/apps/HiC-Pro/2.10.0/bin/../scripts//Makefile

means that the HiC-Pro binary bin, should be in 
/isg/shared/apps/HiC-Pro/2.10.0/bin/
However, it looks for the config-system file in 
/isg/shared/apps/HiC-Pro/2.10.0/HiC-Pro_2.10.0/config-system.txt
while it shoud in theory be in /isg/shared/apps/HiC-Pro/2.10.0/

I'm wondering wether there is a conflict between the "HiC-Pro/2.10.0" 
and the HiC-Pro_2.10.0 ...
Could you try to re-install it setting the PREFIX to /isg/shared/apps/ 
or maybe /isg/shared/apps/HiC-Pro ?
Otherwise, please send me the config-system and the command you used. I 
can try to reproduce your error.
Thanks
Nicolas

Le 18/04/2018 à 23:58, RAY OQUENDO a écrit :
>
> Hi Nicolas,
>
>     I am working to test the HiC-Pro installation at University of 
> Connecticut.  I am trying to run the test data that in on the website. 
> We have run into a problem that we have not been able to find 
> documentation (see  below).   We dont get any messages in the error 
> report.  This is what we get in the output file. What would you recommend?
>
>
>
> Run HiC-Pro 2.10.0
> /isg/shared/apps/HiC-Pro/2.10.0/bin/../scripts//Makefile:48: 
> /isg/shared/apps/HiC-Pro/2.10.0/HiC-Pro_2.10.0/config-system.txt: No 
> such file or directory
> make: *** No rule to make target 
> `/isg/shared/apps/HiC-Pro/2.10.0/HiC-Pro_2.10.0/config-system.txt'. Stop.

**Comment by tarak77** [comment]
Hi Nicolas,

I am facing the same problem with HiC-Pro not installing properly. After going on HiC-Pro-master directory and using 'make configure' command, for some reason the config-system.txt file shows scripts and sources in **/HiC-Pro-master/HiC-Pro_2.11.0-beta** directory. And HiC-Pro gets installed in **/HiC-Pro-master/HiC-Pro_2.11.0-beta** as well

But HiC-Pro_2.11.0-beta is no where to be found in HiC-Pro-master directory!

I have attached those files below
[config-system.txt](https://github.com/nservant/HiC-Pro/files/2279417/config-system.txt)
[config-install.txt](https://github.com/nservant/HiC-Pro/files/2279418/config-install.txt)

Hope to hear from you soon, Thanks!
Tarak
