### ISSUE TITLE
names of R1/R2

### ISSUE THREAD

**Issue by nservant** [nservant/HiC-Pro#153]
it seems that sometimes the read names in R1/R2 files are not exactly the same.
if it happens, HiCPro currently launch an error and stops ...

**Comment by milkcookie** [comment]
it seq by company, to assemble the genome.

**Comment by nservant** [comment]
yes because the merge expect to have the R1 and R2 files in the same order.
So to do that, it checks if the read names are the same ... which is not the case here.

**Comment by milkcookie** [comment]
Hi
I found the problem, its becouse the reads num in two fq file is diff. any suggestion to solve it?

**Comment by milkcookie** [comment]
Hi:
I try some test today, but when the fastq file has diff num of reads there will meet this problem?
how to avoid this diff happen in bam file by bowtie2? if I can add some args to skip?

**Comment by nservant** [comment]
Hi,
I think I fixed it.
In order to test it, would you mind sending me two small SAM files with a few reads ?
Thanks

**Comment by milkcookie** [comment]
Hi 
I have some PE clean data with diff num of reads.
I don't know why it happen?
can you give me some suggestion?
the problem happle becouse of the diff num of reads, not the seq name?

**Comment by nservant** [comment]
Difficult to say. What do you mean by 'clean' ?  PE raw data should always be paired with same number of reads in the two files. Could you have access to the files before cleaning ?

**Comment by milkcookie** [comment]
yes
I have raw data
the clean data had been trimming adapter and dumping the low quality reads, I don't know what happened, the company do it.
so I want to know is there some tools to correct the reads, so it can be same numbers in R1 and R2.

**Comment by nservant** [comment]
should be fixed now in devel (v2.11.0)
