### ISSUE TITLE
Error in digesting a genome

### ISSUE THREAD

**Issue by am33567** [nservant/HiC-Pro#155]
Hello I am having trouble runing the digest genome utility:

**Command:**
/programs/HiC-Pro_2.7.9/bin/utils/digest_genome.py -r dpnii -o Jc_dpnii.bed ~/bin/atac_dnase_pipelines/data/bds_pipeline_genome_data/Jc/JcV1m.fasta 

**Error message**
  File "/programs/HiC-Pro_2.7.9/bin/utils/digest_genome.py", line 39
    print line.split()[0][1:], "..."
             ^
SyntaxError: invalid syntax

List of scaffold names and chomosomal size from the fasta genome file:
000000F 7212301
000001F 6152144
000002F 5953652
000003F 5796727
000004F 5486522
000005F 5244073
000006F 5097445
000007F 4069977
000008F 4700922
000009F 4554608
000010F 4399645
000011F 4387397
000012F 4301180
000013F 4114783
000014F 3864861
000015F 3868481
000016F 3783006
000017F 3566204
000018F 3448479
000019F 3425763
000020F 3387890
.

.
001118F 701
001114F 1756
001103F 2916
001113F 1845
001098F 3862
1123    20139
1125    22383
1126    14404
1127    18141
1128    73155
1129    12402
1130    10338
1131    32963
1132    13681
1133    7356
1134    11053
1136    7912
1138    11258

Any ideas?

Thanks

**Comment by nservant** [comment]
Hi
Could you check which python you are using ? HiCPro requires python 2.7
best

**Comment by am33567** [comment]
Yes, I am using python 2.7. To set environment first I do:
export PYTHONPATH=/programs/HiC-Pro_2.7.9/lib64/python2.7/site-packages:$PYTHONPATH
export PATH=/programs/HiC-Pro_2.7.9/bin:$PATH

**Comment by nservant** [comment]
Hi, 
Did you fix your issue ? otherwise, could you share with me your fasta file ?
thanks

**Comment by nservant** [comment]
This is an issue due to the fact that you are using python3 and not 2.7.X.
