### ISSUE TITLE
Seems to be stuck in "Combine both alignment" step

### ISSUE THREAD

**Issue by nsauerwald** [nservant/HiC-Pro#156]
I have run HiC-Pro successfully many times so I don't think there is anything wrong with my installation or dependencies. For some reason, on this run it seems to be stuck somewhere in the combining alignments step. It hasn't exited out so I have no error message, but I don't understand why it would just stop here for so long. The following screenshot shows the current output, which hasn't changed in at least 2 weeks:

![screen shot 2018-05-14 at 2 11 30 pm](https://user-images.githubusercontent.com/39094651/40015269-bfad7024-5780-11e8-8415-52efc8e95400.png)

Any idea what the issue could be, or if there is some way to fix this without having to start HiC-Pro over again? Thanks in advance for your help!

**Comment by nservant** [comment]
Still an issue with the samtools sort ...
How big are your data compared to your previous samples ?
What about your local disk space ? or the disk space in /tmp ?
Nicolas

**Comment by nservant** [comment]
yes but I think that by default samtools is using /tmp for the sort ...

**Comment by nservant** [comment]
no. The mapping is working as a block. You can start after the mapping, but you can't run independently the mapping steps. Sorry.

**Comment by nsauerwald** [comment]
Thanks!
