### ISSUE TITLE
Can someone please point to some open source hi-C dataset?

### ISSUE THREAD

**Issue by udion** [nservant/HiC-Pro#157]
Can someone please point to some open source hi-C dataset? I tried [http://promoter.bx.psu.edu/hi-c/download.html](http://promoter.bx.psu.edu/hi-c/download.html) but the links are not working. Please help.

**Comment by nservant** [comment]
What kind of data are you looking for ?
Here is an example of Hi-C ENCODE data sets.
https://www.encodeproject.org/search/?type=Experiment&assay_title=Hi-C

**Comment by udion** [comment]
Hey, thanks for the reply.
I was trying to do an experiment to improve the resolution of hi-C dataset, so I was looking for high resolution dataset (for training)

**Comment by nservant** [comment]
ok. So look at the Rao et al. dataset (Cell 2014). They have some data up to 1kb resolution
