### ISSUE TITLE
folder already exist

### ISSUE THREAD

**Issue by nservant** [nservant/HiC-Pro#161]
Hi Group,
     I am trying to get HiC-Pro up and running for our Univ project.   I was able to run the complete Test Dataset and receive the 
correct output as per the HiC-Pro website.

I then proceed to run HiC-Pro with our data.   I received the following message after several days of processing:

Run HiC-Pro 2.10.0
--------------------------------------------
Fri May 18 08:29:10 EDT 2018
Bowtie2 alignment step1 ...
/isg/shared/apps/HiC-Pro/2.10.0/scripts/bowtie_wrap.sh -c /home/CAM/aromd/HiCPro_Config_Prod.txt -u >> hicpro.log
--------------------------------------------
Thu May 24 00:59:08 EDT 2018
Bowtie2 alignment step2 ...
/isg/shared/apps/HiC-Pro/2.10.0/scripts/bowtie_wrap.sh -c /home/CAM/aromd/HiCPro_Config_Prod.txt -l >> hicpro.log
/home/CAM/aromd/HiCPro_Prod_008_Output folder alreads exists. Do you want to delete it before running ?(y/n) [n] : 

real	0m0.418s
user	0m0.050s
sys	0m0.090s

My batch file has the following execution statement:

time HiC-Pro -c HiCPro_Config_Prod.txt -i rawdata -o HiCPro_Prod_008_Output

I did notice some additional post with this error message but they did not provide any clarification for my problem.

Any feedback would be appreciated.

Thanks in advance.
Ray

**Comment by st1553** [comment]
I'm having this same issue now. Was this fixed? If so what was it, its possible its still not fixed. Thank you
