### ISSUE TITLE
../scripts//Makefile:169: recipe for target 'hic_qc' failed

### ISSUE THREAD

**Issue by iza88** [nservant/HiC-Pro#163]
Hi
I'm trying to run on the test data

> Thu Jun 14 12:25:33 STD 2018
> Run quality checks for all samples ...
> /usr/local/bin/HiC-Pro_2.10.0/scripts/make_plots.sh -c /home/ivan/hic-pro/HiC-Pro-master/config_test_latest.txt -p "all" >> hicpro.log
> /home/ivan/hic-pro/HiC-Pro-master/bin/../scripts//Makefile:169: recipe for target 'hic_qc' failed
> make: *** [hic_qc] Error 1

I took this file to build bowtie2 indexes:
[ftp://ftp.ensembl.org/pub/grch37/release-83/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna_sm.primary_assembly.fa.gz](url)

**Comment by nservant** [comment]
Could you please have a look into the log folder ?
The Rout file should have an error ...
Thanks

**Comment by iza88** [comment]
please take a look
[logs.zip](https://github.com/nservant/HiC-Pro/files/2129715/logs.zip)

**Comment by nservant** [comment]
ok, so something went wrong before.
Could you give me the list of results you have in the data folder ?
Thanks

**Comment by iza88** [comment]
![image](https://user-images.githubusercontent.com/14890699/41846952-18ec14c6-7881-11e8-9946-e8cc2fb122d1.png)
![image](https://user-images.githubusercontent.com/14890699/41846970-22fb777c-7881-11e8-8e81-088588895b17.png)

**Comment by nservant** [comment]
humm .. the validPairs are there, but R cannot load them.
Are they empty ?

**Comment by iza88** [comment]
yes, they are

**Comment by WenChangYu** [comment]
I came across the same error. Why is the Validpairs is empty?  Is there something wrong in using the software or my data?
Thanks in advance.

**Comment by iza88** [comment]
if it's the right file, it's not empty
![image](https://user-images.githubusercontent.com/14890699/43790726-1c859ee6-9a7c-11e8-96de-014475fc4d09.png)

**Comment by JWDu0122** [comment]
the same error .......
> ####################################
> ##
> ## plotMappingPortion.R
> ##
> ####################################
> ## Get Mapping stat files for all fastq files of a given sample
> allmapstat_r1 <- list.files(path=bwtDir, pattern=paste0("^[[:print:]]*",r1tag,"[[:print:]]*\\.mapstat$"), full.names=TRUE)
> allmapstat_r2 <- list.files(path=bwtDir, pattern=paste0("^[[:print:]]*",r2tag,"[[:print:]]*\\.mapstat$"), full.names=TRUE)
> stopifnot(length(allmapstat_r1)>0 && length(allmapstat_r2)>0)
Error: length(allmapstat_r1) > 0 && length(allmapstat_r2) > 0 is not TRUE
Execution halted

**Comment by JWDu0122** [comment]
![image](https://user-images.githubusercontent.com/49836989/87152228-eac16c00-c2e7-11ea-9a6a-e10051c49a51.png)

**Comment by JWDu0122** [comment]
![image](https://user-images.githubusercontent.com/49836989/87154873-8f45ad00-c2ec-11ea-806a-09a0e5012e2b.png)

**Comment by nservant** [comment]
Hi,
Your validPairs files are empty. And all reads are in DumpPairs.
Could you check your restriction fragment file ? especially the chromosome name between your bam and the restriction fragment files ?
N

**Comment by wjq1981** [comment]
> Hi, Your validPairs files are empty. And all reads are in DumpPairs. Could you check your restriction fragment file ? especially the chromosome name between your bam and the restriction fragment files ? N

Hi, I also have the above problem. My validPairs files are empty. And all reads are in DumpPairs.

bwt2pairs.bam:
A00920:284:H5FJJDSXY:3:1101:1009:3302   67      ctg000099       32506709        40      150M    =       32506709        0       GATCTNAACCGCTCTCCGGCGAAGGTTTTCGCCGGGGATAGGAAAGGATGTTCATGCCGGCTAGATGGAGGAGCGAGAAGAATAAGGTTAAGGCGGAATTTAAGTTGCAATTTCATGTTACTCAGGTAAGTTTTTAAATTTCAGTTGTCT  FFFFF#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF,FFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF  AS:i:-6 XN:i:0  XM:i:2  XO:i:0  XG:i:0  NM:i:2  MD:Z:5A140T3    YT:Z:UU RG:Z:BMG
A00920:284:H5FJJDSXY:3:1101:1009:3302   131     ctg000099       32506709        40      150M    =       32506709        0       GATCTNAACCGCTCTCCGGCGAAGGTTTTCGCCGGGGATAGGAAAGGATGTTCATGCCGGCTAGATGGAGGAGCGAGAAGAATAAGGTTAAGGCGGAATTTAAGTTGCAATTTCATGTTACTCAGGTAAGTTTTTAAATTTCAGTTGTCT  FFFFF#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF,FFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF  AS:i:-6 XN:i:0  XM:i:2  XO:i:0  XG:i:0  NM:i:2  MD:Z:5A140T3    YT:Z:UU RG:Z:BMG
A00920:284:H5FJJDSXY:3:1101:1009:10567

fragment file:
ctg000024	0	2166	HIC_ctg000024_1	0	+
ctg000024	2166	2997	HIC_ctg000024_2	0	+
ctg000024	2997	3255	HIC_ctg000024_3	0	+
ctg000024	3255	3890	HIC_ctg000024_4	0	+
ctg000024	3890	8773	HIC_ctg000024_5	0	+
ctg000024	8773	12146	HIC_ctg000024_6	0	+
ctg000024	12146	15260	HIC_ctg000024_7	0	+
ctg000024	15260	18164	HIC_ctg000024_8	0	+
ctg000024	18164	19740	HIC_ctg000024_9	0	+
ctg000024	19740	22306	HIC_ctg000024_10	0	+
ctg000024	22306	32381	HIC_ctg000024_11	0	+
ctg000024	32381	34822	HIC_ctg000024_12	0	+

**Comment by wjq1981** [comment]
> Hi, Your validPairs files are empty. And all reads are in DumpPairs. Could you check your restriction fragment file ? especially the chromosome name between your bam and the restriction fragment files ? N

I tried to troubleshoot the error and I found that the file generated by mapped_2hic_fragments.py is empty.

**Comment by BenxiaHu** [comment]
have you resolved your question?
@wjq1981  @iza88 @JWDu0122

**Comment by wjq1981** [comment]
> have you resolved your question? @wjq1981 @iza88 @JWDu0122

Not yet resolved.
