### ISSUE TITLE
hicpro2juicebox.sh - no output

### ISSUE THREAD

**Issue by lurebgi** [nservant/HiC-Pro#164]
Hi, 

I am running hicpro2juicebox.sh. The version of juicebox is Juicebox_1.8.8.jar. After the message

> Running Juicebox ...
> 
> Fetching user directory... Default User Directory: /home/user/luohao
> HiC Directory: /home/user/luohao/juicebox
> Window W: 480 H480
> Listening on port

Nothing really produced and the program seems to be stalled. Below shows some lines of pre file
`head tmp/16074_allValidPairs.pre_juicebox_sorted`

E00434:67:HCVHVCCXY:5:1101:22313:52063/1 0 ScmhRig_100;HRSCAF=436 15161 0 0 ScmhRig_100;HRSCAF=436 24505 1 0 4
E00434:67:HCVHVCCXY:5:1101:25063:65371/2 1 ScmhRig_100;HRSCAF=436 10283 0 1 ScmhRig_100;HRSCAF=436 11313 1 3 25
E00434:67:HCVHVCCXY:5:1102:22871:51166/1 1 ScmhRig_100;HRSCAF=436 32604 0 1 ScmhRig_100;HRSCAF=436 84341 1 7 7
E00434:67:HCVHVCCXY:5:1103:10673:47580/1 0 ScmhRig_100;HRSCAF=436 15493 0 1 ScmhRig_100;HRSCAF=436 15712 1 39 23
E00434:67:HCVHVCCXY:5:1103:15503:29121/1 0 ScmhRig_100;HRSCAF=436 27746 0 1 ScmhRig_100;HRSCAF=436 27803 1 42 42
E00434:67:HCVHVCCXY:5:1103:31538:3243/1 1 ScmhRig_100;HRSCAF=436 94127 0 0 ScmhRig_100;HRSCAF=436 116065 1 30 16
E00434:67:HCVHVCCXY:5:1103:8268:25376/2 0 ScmhRig_100;HRSCAF=436 11125 0 1 ScmhRig_100;HRSCAF=436 11251 1 8 7
E00434:67:HCVHVCCXY:5:1104:21531:30211/2 0 ScmhRig_100;HRSCAF=436 60715 0 1 ScmhRig_100;HRSCAF=436 60874 1 3 0
E00434:67:HCVHVCCXY:5:1104:26220:3665/1 0 ScmhRig_100;HRSCAF=436 43429 0 1 ScmhRig_100;HRSCAF=436 63680 1 40 3
E00434:67:HCVHVCCXY:5:1105:12936:2346/1 0 ScmhRig_100;HRSCAF=436 116994 0 1 ScmhRig_100;HRSCAF=436 117177 1 0 0

Thanks, 
Luohao

**Comment by nservant** [comment]
great. I close
