### ISSUE TITLE
singularity ov virtual machine ubuntu

### ISSUE THREAD

**Issue by zine-el-aabidine** [nservant/HiC-Pro#165]
HI 
I've tried to install directly  hic-pro but it didin't work so I tired singularity.  it seems to be installed correctly but when i tried i got no output. Here  you my command line :
$ singularity exec hicpro_latest_ubuntu.img HiC-Pro -c config_test_latest.txt -i test_data -o hicpro_latest_test
$ singularity exec hicpro_latest_ubuntu.img HiC-Pro -h
usage : HiC-Pro -i INPUT -o OUTPUT -c CONFIG [-s ANALYSIS_STEP] [-p] [-h] [-v]
Use option -h|--help for more information

HiC-Pro 2.10.0
---------------
OPTIONS

   -i|--input INPUT : input data folder; Must contains a folder per sample with input files
   -o|--output OUTPUT : output folder
   -c|--conf CONFIG : configuration file for Hi-C processing
   [-p|--parallel] : if specified run HiC-Pro on a cluster
   [-s|--step ANALYSIS_STEP] : run only a subset of the HiC-Pro workflow; if not specified the complete workflow is run
      mapping: perform reads alignment - require fast files
      proc_hic: perform Hi-C filtering - require BAM files
      quality_checks: run Hi-C quality control plots
      merge_persample: merge multiple inputs and remove duplicates if specified - require .validPairs files
      build_contact_maps: Build raw inter/intrachromosomal contact maps - require _allValidPairs files
      ice_norm : run ICE normalization on contact maps - require .matrix files
   [-h|--help]: help
   [-v|--version]: version

Please could you help me it's very urgent

Thank you

**Comment by nservant** [comment]
Hi,
Indeed, the singularity command is working.
What do you have with your first command ;
` singularity exec hicpro_latest_ubuntu.img HiC-Pro -c config_test_latest.txt -i test_data -o hicpro_latest_test`
Best

**Comment by zine-el-aabidine** [comment]
THank you
i have Nothing.

**Comment by zine-el-aabidine** [comment]
My working directory contains: 
config_test_latest.txt     hic-tutorial_ubuntu.img.part  test_data
hicpro_latest_ubuntu.img  HiC-Pro-master.zip  hic-tutorial_ubuntu.img  singularity-2.5.1.tar.gz


Thank you

Best

**Comment by nservant** [comment]
You have nothing !! That's weird !
I just made a test, it works on my laptop.
Do you have something in the test_data folder ?

**Comment by zine-el-aabidine** [comment]
YES
.
├── dixon_2M
│   ├── SRR400264_00_R1.fastq.gz
│   └── SRR400264_00_R2.fastq.gz
└── dixon_2M_2
    ├── SRR400264_01_R1.fastq.gz
    └── SRR400264_01_R2.fastq.gz

2 directories, 4 files

**Comment by zine-el-aabidine** [comment]
I tried last a week to install hic-pro but it didn't work. i missed a step or a detail i don't know

**Comment by zine-el-aabidine** [comment]
Sorry. But nothing is happening. no error and no result

**Comment by nservant** [comment]
Can you at least enter the singularity image ?
It's difficult to help you without additional information.

**Comment by zine-el-aabidine** [comment]
yes without any problem. I'm sorry for that

Singularity hicpro_latest_ubuntu.img:~/Téléchargements>
