### ISSUE TITLE
make: *** [build_raw_maps] error 255

### ISSUE THREAD

**Issue by xiaoaozqd** [nservant/HiC-Pro#169]
Dear nservant,
Sorry to distrub you again!
when the Hic-pro work step by step there was an error:
Generate binned matrix files ...
/home/zengqd/software/hicpro/bin/HiC-Pro_2.10.0/scripts/build_raw_maps.sh -c /home/genome/Caulobacter/config-hicpro.txt
bacteria.size not found. Exit
make: *** [build_raw_maps] error 255

while the file bacteria.size in the work dir
[zengqd@subnet94-129 Caulobacter]$ cat  /home/genome/Caulobacter/bacteria.size 
Chromosome	4042929
the chromosome name as the same as bacteria_dpnii.bed
"[zengqd@subnet94-129 Caulobacter]$ head bacteria_dpnii.bed
Chromosome	0	130	HIC_Chromosome_1	0	+
Chromosome	130	225	HIC_Chromosome_2	0	+
"

Was there some thing wrong?
the config-hicpro.txt
"
#######################################################################
#######################################################################

REFERENCE_GENOME = bacteria
GENOME_SIZE = bacteria.size
"
The genome file "
[zengqd@subnet94-129 Caulobacter]$ head Caulobacter_crescentus_na1000.ASM2200v1.dna.toplevel.fa 
>Chromosome dna:chromosome chromosome:ASM2200v1:Chromosome:1:4042929:1 REF
"
the work dir
[zengqd@subnet94-129 Caulobacter]$ ll -ht
总用量 11G
drwxrwxr-x 6 zengqd zengqd  138 7月  27 22:07 HiC_data_out
-rw-r--r-- 1 zengqd zengqd 2.8K 7月  27 21:36 config-hicpro.txt
drwxrwxr-x 3 zengqd zengqd   20 7月  27 21:35 HiC_data
-rw-rw-r-- 1 zengqd zengqd   19 7月  27 20:02 bacteria.size
-rw-rw-r-- 1 zengqd zengqd 1.9M 7月  27 18:19 bacteria_dpnii.bed
-rw-rw-r-- 1 zengqd zengqd 5.3M 7月  26 21:14 bacteria.rev.1.bt2
-rw-rw-r-- 1 zengqd zengqd 988K 7月  26 21:14 bacteria.rev.2.bt2
-rw-rw-r-- 1 zengqd zengqd 5.3M 7月  26 21:14 bacteria.1.bt2
-rw-rw-r-- 1 zengqd zengqd 988K 7月  26 21:14 bacteria.2.bt2
-rw-rw-r-- 1 zengqd zengqd   17 7月  26 21:14 bacteria.3.bt2
-rw-rw-r-- 1 zengqd zengqd 988K 7月  26 21:14 bacteria.4.bt2
-rw-rw-r-- 1 zengqd zengqd 4.0M 7月  26 09:38 Caulobacter_crescentus_na1000.ASM2200v1.dna.toplevel.fa

**Comment by nservant** [comment]
Please set the full path to your size file in the config.
