### ISSUE TITLE
Capture Hi-C options clarification

### ISSUE THREAD

**Issue by stayingsong** [nservant/HiC-Pro#173]
Hello,

Could you clarify exactly what the following options do for the following 3 cases:

[CAPTURE_TARGET] | BED file of target regions to focus on (mainly used for capture Hi-C data)
[REPORT_CAPTURE_REPORTER] | Report interactions between targeted and non-targeted loci (=1) and between targeted loci only (=0)

1) CAPTURE_TARGET specified but REPORT_CAPTURE_REPORTER not specified
2) CAPTURE_TARGET specified and REPORT_CAPTURE_REPORTER=1
3) CAPTURE_TARGET specified and REPORT_CAPTURE_REPORTER=0

Specifically, is there a default value set for REPORT_CAPTURE_REPORT?

What I am guessing is that in case 1, the normal contact matrix with all the interactions is written.  In case 2, only interactions where at least one end involves a captured fragment are written?  And in case 3, only interactions where both ends involve captured fragments are written?  Does that sound right?  Or if not, where are the capture-specific results written to in the results directory?

Thanks,

Michael

**Comment by nservant** [comment]
Hi,
Let's say that we have an interaction between two fragments A et B.
In practice, A and B can be ;
CAPTURE - CAPTURE, ie both A and B fragments match the targeted regions
CAPTURE - REPORTER,  ie. only A or B match the targeted regions
REPORTER - REPORTER, ie. none of them overlap the targeted regions ... those are the off targets.

By default, REPORT_CAPTURE_REPORTER is set to 1, meaning that both CAPTURE - CAPTURE and CAPTURE - REPORTER reads are used to build the map. If set to 0, only the CAPTURE-CAPTURE reads are used.

The allValidPairs file contains all interactions regardless their overlap with the targets. The ontarget.allValidPairs are the subset that overlap with the target and which are used to build the maps.
Does it sound good now ? I can update a bit the manual.
Best
