### ISSUE TITLE
 How to merge contact matrices of two replicates

### ISSUE THREAD

**Issue by QianzhaoJ** [nservant/HiC-Pro#175]
Hi,
I have got contact matrices of two replicates. Is there a way to merge two matrices directly? Or I have to merge fastq files first and run HiC-pro pipline again ?
Thank you !

Best,
Qianzhao

**Comment by nservant** [comment]
Hi,
Basically, you just have to sum the two matrices.
You can easily do that in any programming langage such as python or R.
Otherwise, just 'cat' the two allValidPairs files, and rerun HiC-pro from this new file with the option -s build_contact_maps -s ice_norm. Please look at the manual about the stepwise HiCpro mode.
Best

**Comment by QianzhaoJ** [comment]
Thanks for your help !


________________________________
发件人: Nicolas Servant <notifications@github.com>
发送时间: Tuesday, August 14, 2018 4:04:13 PM
收件人: nservant/HiC-Pro
抄送: QianzhaoJ; Author
主题: Re: [nservant/HiC-Pro] How to merge contact matrices of two replicates (#175)


Hi,
Basically, you just have to sum the two matrices.
You can easily do that in any programming langage such as python or R.
Otherwise, just 'cat' the two allValidPairs files, and rerun HiC-pro from this new file with the option -s build_contact_maps -s ice_norm. Please look at the manual about the stepwise HiCpro mode.
Best

―

**Comment by lizc07** [comment]
Hi, nservant.
Should I just sum the two iced matrices?
Or, sum the two raw matrices and do ice_norm?

Best

**Comment by lizc07** [comment]
> sum and then iced
> N
get!
Thanks much.

**Comment by MzwaneleN** [comment]
Hi Nicolas. 

Wet lab scientist here. Can you please show me an example of a syntax to use in python to sum two matrices? I am sorry for asking for something so basic. Thanks.

**Comment by Biswa2410** [comment]
> Hi, Basically, you just have to sum the two matrices. You can easily do that in any programming langage such as python or R. Otherwise, just 'cat' the two allValidPairs files, and rerun HiC-pro from this new file with the option -s build_contact_maps -s ice_norm. Please look at the manual about the stepwise HiCpro mode. Best

Hi, I have 4 replicates (say, k1_1, k1_2, k1_3, k1_4) for a single dataset and I have generated 4 .hic files using hicpro2jjuicebox.sh. Now I want to create a single .hic file for all the four .hic files. Is it possible?

Thank you.
