### ISSUE TITLE
running HiC-Pro on cluster

### ISSUE THREAD

**Issue by tarak77** [nservant/HiC-Pro#177]
Hi Nicolas,

I am trying to run HiC-Pro on cluster(TORQUE) on my Mac. After setting -p argument, I do get the message statement stating the two step procedure but when I run 
qsub HiCPro_step1.sh
from my output folder, I get an error stating that 
qsub : command not found

How to install qsub on my local Mac?

Thanks,
Tarak

**Comment by nservant** [comment]
Hi Tarak
Not sure to get your point. The schedulers like torque, sge, slurm are usually used to parallelize over multiple nodes ... so cannot really be used on a single Mac ? Did I misunderstand something ?

**Comment by tarak77** [comment]
Oh okay, my bad. Thanks!
