### ISSUE TITLE
Error in HiC-Pro make install.

### ISSUE THREAD

**Issue by SiyiWanggou** [nservant/HiC-Pro#178]
Hi,
I'm installing HiC-Pro on ubuntu 16.04.
When I 'make install', the system report the following error:

(hic) zokygwongpy27@ubuntu:~/biosoft/hicpro/HiC-Pro$ make install
(g++ -Wall -O2 -std=c++0x -o build_matrix /home/zokygwongpy27/biosoft/hicpro/HiC-Pro/scripts/src/build_matrix.cpp; mv build_matrix /home/zokygwongpy27/biosoft/hicpro/HiC-Pro/scripts)
(g++ -Wall -O2 -std=c++0x -o cutsite_trimming /home/zokygwongpy27/biosoft/hicpro/HiC-Pro/scripts/src/cutsite_trimming.cpp; mv cutsite_trimming /home/zokygwongpy27/biosoft/hicpro/HiC-Pro/scripts)
runner=zokygwongpy27
Installing the iced package in --user repository
(cp /home/zokygwongpy27/biosoft/hicpro/HiC-Pro/scripts/src/ice_mod/iced/scripts/ice /home/zokygwongpy27/biosoft/hicpro/HiC-Pro/scripts; cd /home/zokygwongpy27/biosoft/hicpro/HiC-Pro/scripts/src/ice_mod/; /home/zokygwongpy27/miniconda3/envs/hic/bin/python setup.py install --user;)
cp: cannot stat '/home/zokygwongpy27/biosoft/hicpro/HiC-Pro/scripts/src/ice_mod/iced/scripts/ice': Not a directory
/bin/sh: 1: cd: can't cd to /home/zokygwongpy27/biosoft/hicpro/HiC-Pro/scripts/src/ice_mod/
/home/zokygwongpy27/miniconda3/envs/hic/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory
Makefile:56: recipe for target 'iced' failed
make: *** [iced] Error 2

### My config-install.txt is as below:
PREFIX = /home/zokygwongpy27/biosoft/hicpro/bin
BOWTIE2_PATH = /home/zokygwongpy27/miniconda3/envs/hic/bin/bowtie2
SAMTOOLS_PATH = /home/zokygwongpy27/miniconda3/envs/hic/bin/samtools
R_PATH = /home/zokygwongpy27/miniconda3/envs/hic/bin/R
PYTHON_PATH = /home/zokygwongpy27/miniconda3/envs/hic/binin/python
CLUSTER_SYS = SGE

#######################################################################
#######################################################################
#######################################################################
#######################################################################
R_PATH = /home/zokygwongpy27/miniconda3/envs/hic/bin
BOWTIE2_PATH = /home/zokygwongpy27/miniconda3/envs/hic/bin
SAMTOOLS_PATH = /home/zokygwongpy27/miniconda3/envs/hic/bin
PYTHON_PATH = /home/zokygwongpy27/miniconda3/envs/hic/bin
INSTALL_PATH = /home/zokygwongpy27/biosoft/hicpro/bin/HiC-Pro_2.11.0-beta
SCRIPTS = /home/zokygwongpy27/biosoft/hicpro/bin/HiC-Pro_2.11.0-beta/scripts
SOURCES = /home/zokygwongpy27/biosoft/hicpro/bin/HiC-Pro_2.11.0-beta/scripts/src
ANNOT_DIR = /home/zokygwongpy27/biosoft/hicpro/bin/HiC-Pro_2.11.0-beta/annotation
CLUSTER_SCRIPT = /home/zokygwongpy27/biosoft/hicpro/bin/HiC-Pro_2.11.0-beta/scripts/make_sge_script.sh

How can I fix this problem above?
Thanks a lot!

**Comment by nservant** [comment]
Hi,
Could you check if you have a ice_mod symbolinc link in the src directory that points to the ice 0.4.2 folder ? I think that the link is missing ... Although it is on the github codes.
To fix it, just rename the iced 0.4.2 folder into ice_mod.
I'll change that when I will come back to the lab in a few weeks.
N
