### ISSUE TITLE
resolution for hicpro2juicebox

### ISSUE THREAD

**Issue by skyingg** [nservant/HiC-Pro#179]
How can I generate .hic at 1kb bin?

**Comment by nservant** [comment]
Using the hicpro2higlass.sh tool, specifying the -r option to 1000 
N

**Comment by skyingg** [comment]
hicpro2higlass.sh generates .cool file, right? I need .hic for loop calling by juicer.

**Comment by nservant** [comment]
Ah yes sorry. 
I'm not a juicebox/juicer expert, but as far as I know, the .hic file is not linked a given resolution.
That's why the input of hicpro2juicebox.py utility is a list of valid interaction product and not a matrix at a given resolution.
Does it make sense ?
