### ISSUE TITLE
how to get specific chromosome intra-chromosome contact matrix?

### ISSUE THREAD

**Issue by zyxplus** [nservant/HiC-Pro#181]
I am focus on chr3 now, and I just want to get its  intra-chromosome contact matrix, it would be a computaional waste if i run the whole pipeline and then delete other files. Any suggestion?

**Comment by nservant** [comment]
But so far, you only have fastq files right ?
So I think that you have to run HiC-pro on the full genome. Then use the split_sparse.py utility to extract the chr3 contact maps.
best
