### ISSUE TITLE
low alignment rate for hic-pro/2.10.0

### ISSUE THREAD

**Issue by huanglabtoronto** [nservant/HiC-Pro#183]
Hi,

I've used the test dataset to test installation and the process could be run without any noticeable complains that I am aware of, except that the alignment rate is really low:

sample dixon_2M
250000 reads; of these:
  250000 (100.00%) were unpaired; of these:
    238694 (95.48%) aligned 0 times
    4022 (1.61%) aligned exactly 1 time
    7284 (2.91%) aligned >1 times
4.52% overall alignment rate

which is stark contrast with the demo results
250000 reads; of these:
  250000 (100.00%) were unpaired; of these:
    31815 (12.73%) aligned 0 times
    184618 (73.85%) aligned exactly 1 time
    33567 (13.43%) aligned >1 times
87.27% overall alignment rate

I am attaching my config here. hic-pro/2.10.0 was used.

[config_test_latest.txt](https://github.com/nservant/HiC-Pro/files/2326524/config_test_latest.txt)

**Comment by huanglabtoronto** [comment]
# update #
The problem was with the bowtie2 index. Using the one provided from igenome the problem was solved.

Thanks.

**Comment by IzaakH-A1** [comment]
> # update
> The problem was with the bowtie2 index. Using the one provided from igenome the problem was solved.
> 
> Thanks.

Hi, please can you elaborate on how you solved this issue. I am also getting very low read alignment from the mm10 genome.
