### ISSUE TITLE
ERROR: hicpro_latest_ubuntu.img is not an image file

### ISSUE THREAD

**Issue by remember-past** [nservant/HiC-Pro#184]
Hi,I've installed the singularity but when I wanted to try 'sudo singularity build hicpro_latest_ubuntu.img ~/HiC-Pro/Singularity' in my PC, the terminal issued 'ERROR: hicpro_latest_ubuntu.img is not an image file'. So what's wrong with the hicpro_latest_ubuntu.img? Does it be destroyed during the download or as other problems?
![default](https://user-images.githubusercontent.com/15341760/44761568-2cbeea00-ab76-11e8-8025-87f6ecb993a8.png)

**Comment by nservant** [comment]
Which singularity version are you using ?
The 'build' command should create the hicpro_latest_ubuntu.img image from the recipe file 'Singularity'
Otherwise, you can directly download the image at https://zerkalo.curie.fr/partage/HiC-Pro/singularity_images/

**Comment by LinuxPersonEC** [comment]
> Which singularity version are you using ? The 'build' command should create the hicpro_latest_ubuntu.img image from the recipe file 'Singularity' Otherwise, you can directly download the image at https://zerkalo.curie.fr/partage/HiC-Pro/singularity_images/

This link is now broken.

**Comment by nservant** [comment]
Please use https://zenodo.org/records/8376626 instead
