### ISSUE TITLE
mapped_2hic_fragments.py -- NameError: name 'dist' is not defined

### ISSUE THREAD

**Issue by mthjwu** [nservant/HiC-Pro#185]
I got the following error message when running the HiC data with MseI cut. It seems the 'dist' variable is not assigned correctly for some interactions and this makes the program terminated.

`cat logs/HIC8832/mapped_2hic_fragments.log`

>/soft/anaconda2/bin/python /soft/HiC-Pro_2.11.0-beta/scripts/mapped_2hic_fragments.py -v -t 100 -m 100000 -s 100 -l 600 -a -f /task/run_pipeline/Hi-C/pipeline/config/hg19_msei.bed -r bowtie_results/bwt2/HIC8832/HIC8832_hg19.bwt2pairs.bam -o hic_results/data/HIC8832
>\#\# overlapMapped2HiCFragments.py
>\#\# mappedReadsFile= bowtie_results/bwt2/HIC8832/HIC8832_hg19.bwt2pairs.bam
>\#\# fragmentFile= /task/run_pipeline/Hi-C/pipeline/config/hg19_msei.bed
>\#\# minInsertSize= 100
>\#\## maxInsertSize= 600
>\#\# minFragSize= 100
>\#\# maxFragSize= 100000
>\#\# allOuput= True
>\#\# SAM ouput= False
>\#\# verbose= True 
>
>\#\# Loading Restriction File Intervals ' /task/run_pipeline/Hi-C/pipeline/config/hg19_msei.bed '...
>Warning :  10736128 fragment(s) outside of range. Discarded
>load_restriction_fragment function took 232397.918 ms
>\#\# Opening SAM/BAM file ' bowtie_results/bwt2/HIC8832/HIC8832_hg19.bwt2pairs.bam '...
>
>\#\# Classifying Interactions ...
>Traceback (most recent call last):
>  File "/soft/HiC-Pro_2.11.0-beta/scripts/mapped_2hic_fragments.py", line 746, in <module>
>    str(htag) + "\n")
>NameError: name 'dist' is not defined

**Comment by nservant** [comment]
I just made a fix in the devel branch
https://github.com/nservant/HiC-Pro/tree/devel
The script mapped_2hc_fragments.py has been updated.
Sorry for the bug !
N

**Comment by mthjwu** [comment]
Great! Thanks for the fast turnover.

**Comment by mzhibo** [comment]
I have the newest version. For some of the reason, among the parallel jobs, some of the jobs finished successfully but some of them reported error at the mapped_2hic_fragment step with the same error message listed above. Because of a bug in the mapped_2hic_fragment.sh script that overwrites log files instead of appending to it. I can't post a error log file here. The only message I can show here is 
Assign alignments to restriction fragments ...
Logs: logs/DpnII_HiC_nc14/mapped_2hic_fragments.log
make: *** [mapped_2hic_fragments] Error 1
The same bug of overwriting instead of appending log messages also exist to mergeSAM.log in the most current version.
Could you help look into it again? Thanks!

**Comment by mzhibo** [comment]
> I have the newest version. For some of the reason, among the parallel jobs, some of the jobs finished successfully but some of them reported error at the mapped_2hic_fragment step with the same error message listed above. Because of a bug in the mapped_2hic_fragment.sh script that overwrites log files instead of appending to it. I can't post a error log file here. The only message I can show here is
> Assign alignments to restriction fragments ...
> Logs: logs/DpnII_HiC_nc14/mapped_2hic_fragments.log
> make: *** [mapped_2hic_fragments] Error 1
> The same bug of overwriting instead of appending log messages also exist to mergeSAM.log in the most current version.
> Could you help look into it again? Thanks!

I didn't see update was only to the devel branch. I will try the 2.10.1 version and see if the problem still exists

**Comment by nservant** [comment]
Hi,
Latest version is 2.11.1 on the devel branch.
This version should fixed the issue with the 'dist' value. I will generate a stable release in the coming hours.
However, I think you are right for the logs ... I add an issue for the next release to double check that

**Comment by Bonnie19920126** [comment]
Dear nservant,
 I try the lasted master and development version of HiC-Pro, but I got the error, name 'or1_fragname' is not defined. I change the code in mapped_2hic_fragments.py, define the value of 'or1_fragname' a null character, but latter new error occurred,  Logs: logs/dixon_2M/make_Rplots.log make: *** [hic_qc] Error 1.

cat /bioNSW/lixin/causal-lncRNA/Hi-C/Hi-C_Pro/HiCPro_testdata/output/logs/dixon_2M/mapped_2hic_fragments.log
/pub2/lixin/software/conda/anaconda2/bin/python /pub2/lixin/software/HiC-Pro/HiC-Pro-install/HiC-Pro_2.11.2-beta/scripts/mapped_2hic_fragments.py -v -S -t 100 -m 100000 -s 100 -l 600 -a -f /pub2/lixin/software/HiC-Pro/HiC-Pro-install/HiC-Pro_2.11.2-beta/annotation/HindIII_resfrag_hg38_1.bed -r bowtie_results/bwt2/dixon_2M/test_dataset_Human_GRCh38.bwt2pairs.bam -o hic_results/data/dixon_2M
## overlapMapped2HiCFragments.py
## mappedReadsFile= bowtie_results/bwt2/dixon_2M/test_dataset_Human_GRCh38.bwt2pairs.bam
## fragmentFile= /pub2/lixin/software/HiC-Pro/HiC-Pro-install/HiC-Pro_2.11.2-beta/annotation/HindIII_resfrag_hg38_1.bed
## minInsertSize= 100
## maxInsertSize= 600
## minFragSize= 100
## maxFragSize= 100000
## allOuput= True
## SAM ouput= True
## verbose= True 

## Loading Restriction File Intervals ' /pub2/lixin/software/HiC-Pro/HiC-Pro-install/HiC-Pro_2.11.2-beta/annotation/HindIII_resfrag_hg38_1.bed '...
Warning :  28860 fragment(s) outside of range and discarded.  831531  remaining.
load_restriction_fragment function took 11290.090 ms
## Opening SAM/BAM file ' bowtie_results/bwt2/dixon_2M/test_dataset_Human_GRCh38.bwt2pairs.bam '...
## Classifying Interactions ...
Warning - no restriction fragments for  SRR071233.317  at  1 : 221445421
Warning - no restriction fragments for  SRR071233.317  at  18 : 74248256
Traceback (most recent call last):
  File "/pub2/lixin/software/HiC-Pro/HiC-Pro-install/HiC-Pro_2.11.2-beta/scripts/mapped_2hic_fragments.py", line 744, in <module>
    str(htag) + "\n")
NameError: name 'or1_fragname' is not defined

Could you help me to fix this problem? 
Thank you for your time and effort.

Best

**Comment by nservant** [comment]
Hi,
I'm surprised that this error is still there ...
Would you agree to share with me your bam file test_dataset_Human_GRCh38.bwt2pairs.bam' 'and your BED file 'HindIII_resfrag_hg38_1.bed' in private message !?
Thanks !

**Comment by Bonnie19920126** [comment]
Dear nservant,
  I'm sorry, I make a mistake for my annotation file, the chromosome name are different than the ones used in my bowtie indexes. I'm sorry to trouble you. Thank you! Hi-C pro is very useful and convenient!
Best

**Comment by Bonnie19920126** [comment]
Thank you very much.

Best wishes
