### ISSUE TITLE
Error in the merge_valid_interactions.sh script while running the test dataset

### ISSUE THREAD

**Issue by cshukla** [nservant/HiC-Pro#19]
Hi 

I am trying to use HiC-Pro and running into an error on the test dataset itself. The software compiles properly, aligns the test reads properly but gives an error at the stage of merging multiple files from same sample.

```
Merge multiple files from the same sample ...
/usr/local/bin/HiC-Pro_2.6.0/scripts/merge_valid_interactions.sh -c /Users/chinmayshukla/Downloads/config_v2.5.1_orlatter.txt >> hicpro_test.log
Exit: Error in input type.'.fastq|.bam|.validPairs|.matrix' files are expected.
make: *** [merge_valid_interactions] Error 1
```

Any help would be appreciated!

**Comment by nservant** [comment]
Sorry I did not see you issue before. Can you  please give me the exact command line you are using to run HiC-Pro ? Can you also give me the list of files you get in the hic_results/data folder.
Thank you very much
Nicolas
