### ISSUE TITLE
Error in extract_snps.py

### ISSUE THREAD

**Issue by tarak77** [nservant/HiC-Pro#190]
Hi Nicolas,

I am trying to generate allele specific maps by producing a VCF file, from an intercross of Mus musculus 129/SV-Jae and Mus musculus castaneus. For that I use the extract_snps.py script, but not gives me the following error:

```
(py2) wg-dhcp174d160d214:utils tarakshisode$ ./extract_snps.py -i /Users/tarakshisode/HiC-Pro-master/mgp.v5.merged.snps_all.dbSNP142.vcf.gz -r CAST_EiJ -a 129S4_SvJae > /Users/tarakshisode/HiC-Pro-master/snps_CASTEiJ_129S4.vcf
Error : ALT sample not found
```

Is there a way to fix the error? Any help will be great!

**Comment by nservant** [comment]
Hi,
The program stops because the genotype "129S4_SvJae" does not exist in the vcf file.
Please check your vcf file.
I looked at my sanger V5 file, and the only 129* genotypes I found are 129P2_OlaHsd and 129S1_SvImJ
best

**Comment by tarak77** [comment]
Ok, I see. thanks

**Comment by tarak77** [comment]
I changed it to -a 129S1_SvImJ but then get the following error

```
(py2) wg-dhcp174d160d214:utils tarakshisode$ ./extract_snps.py -i /Users/tarakshisode/HiC-Pro-master/mgp.v5.merged.snps_all.dbSNP142.vcf.gz -r CAST_EiJ -a 129S1_SvImJ > /Users/tarakshisode/HiC-Pro-master/snps_CASTEiJ_129S1.vcf
Traceback (most recent call last):
  File "./extract_snps.py", line 163, in <module>
    for line in vcf_handle:
  File "/Users/tarakshisode/anaconda3/envs/py2/lib/python2.7/gzip.py", line 464, in readline
    c = self.read(readsize)
  File "/Users/tarakshisode/anaconda3/envs/py2/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/Users/tarakshisode/anaconda3/envs/py2/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/Users/tarakshisode/anaconda3/envs/py2/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x1e55f218 != 0x4f3d1ddL
```

I did download the vcf.gz file again, but gives me the same error. Any reason why?

**Comment by nservant** [comment]
Could you try to gunzip the vcf first ?

**Comment by tarak77** [comment]
For some reason it is not able to:
```
Taraks-MacBook-Pro:hic-pro-master tarakshisode$ gunzip mgp.v5.merged.snps_all.dbSNP142.vcf.gz
gunzip: mgp.v5.merged.snps_all.dbSNP142.vcf.gz: unexpected end of file
gunzip: mgp.v5.merged.snps_all.dbSNP142.vcf.gz: uncompress failed
```

Is there any other source to get that file?

Thanks again!

**Comment by nservant** [comment]
Your file looks corrupted
ftp://ftp-mouse.sanger.ac.uk/current_snps

**Comment by tarak77** [comment]
I am using the same link but for some reason the file is corrupted, is there any other source for the same?

**Comment by tarak77** [comment]
got it. thanks!
