### ISSUE TITLE
Permission denied to run HiC

### ISSUE THREAD

**Issue by amit4mchiba** [nservant/HiC-Pro#191]
I have no idea how shall I explain my problem, but I will try my best now.

I first felt a lot of difficulties in installing HiC-Pro. The main problem initially was in iced setup. The program was not able to copy iced and install it for some reason. So, i just copied iced-0.4.2 and named it as iced-mod and performed installation. I was successful, and was even able to run HiC analysis first time with test-op and then with my own data. 

But just when I tried to run another analysis, it am not able to. When I try to use HiC-Pro, i am getting message -

amit8chiba@amit8chiba-Precision-Tower-7910:/mnt/md0/Opu_r1.2_final/HiC-Pro-master/bin$ ls -l
total 16
-rwxr-xr-x 1 amit8chiba amit8chiba 10480  8月  3 23:14 HiC-Pro
drwxr-xr-x 2 amit8chiba amit8chiba  4096  8月  3 23:14 utils
amit8chiba@amit8chiba-Precision-Tower-7910:/mnt/md0/Opu_r1.2_final/HiC-Pro-master/bin$ ./HiC-Pro
-bash: ./HiC-Pro: Permission denied

This is really surprising. Then I thought to reinstall HiC-Pro. But Now i am not able to install it at all. I have no clue what I have done wrong, rest all utilies and everything seems fine. I have not changed anysetup in my computer, I tried using chmod -R 755 to give permission or use sudo but not working at all.

Then I tried reinstalling HiC-Pro again, successful but then I still do not have permission to use it. 

I have no idea on what happened and how shall i proceed.

I am working on a Ubuntu 16 OS, and installed all dependensies using miniconda.

Please help and let me know if You need any more information to get more idea on my problem.

thank you in advance,

with best regards
Amit

**Comment by nservant** [comment]
Dear Amit,
Regarding your first point with the iced folder and symbolic link, it is solved in the HiC-Pro version 2.11 in the master branch, although i still do not understand why the ice_mod symbolic link disappears for some users.
For the other point, that's strange, but it is difficult to help you as this more related to your system.
In practice, HiC-pro should be easy to install with simply
make configure
make install 

In particular, as you already use it once, there is not reason why you should not use it again !!
If you have more question, I'll be happy to help you, but I would need more details
best
Nicolas
