### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jennymoon90** [nservant/HiC-Pro#192]
Hi,
I encountered an error during installation of HiC-Pro 2.10.0
What I did was downloaded HiC-Pro-2.10.0.tar.gz into my folder on a SGE server. And -zxvf it.
I modified the config-install.txt file as the following:
#########################################################################
#########################################################################

PREFIX = /u/project/geschwind/jennybea/Hi-C_tools
BOWTIE2_PATH = /u/local/apps/bowtie2/2.2.9/bowtie2
SAMTOOLS_PATH = /u/local/apps/samtools/0.1.19/gcc-4.4.7/samtools
R_PATH = /u/local/apps/R/3.4.0/gcc-4.9.3_MKL-2017.0/bin/R
PYTHON_PATH = /u/local/apps/python/2.7.3/bin/python
CLUSTER_SYS = SGE

Then I ran `make configure`, and got the following messages:
make -f ./scripts/install/Makefile CONFIG_SYS=./config-install.txt
make[1]: Entering directory `/u/project/geschwind/jennybea/Hi-C_tools/HiC-Pro-2.10.0'
./scripts/install/install_dependencies.sh -c ./config-install.txt -o  /u/project/geschwind/jennybea/Hi-C_tools/HiC-Pro_2.10.0 -q
Make sure internet connection works for your shell prompt under current user's privilege ...
Starting HiC-Pro installation ...
export /u/local/apps/bowtie2/2.2.9/bowtie2 in PATH
export /u/local/apps/samtools/0.1.19/gcc-4.4.7/samtools in PATH
export /u/local/apps/R/3.4.0/gcc-4.9.3_MKL-2017.0/bin/R in PATH
export /u/local/apps/python/2.7.3/bin/python in PATH
Directory /u/home/j/jennybea/bin does not exist!
Exit - Error - unable to install/check dependancies !
make[1]: *** [configure] Error 1
make[1]: Leaving directory `/u/project/geschwind/jennybea/Hi-C_tools/HiC-Pro-2.10.0'
make: *** [configure] Error 2

I do not understand why it has to find the directory /u/home/j/jennybea/bin. Would you suggest how I can go about this?
Thanks,
Jenny

**Comment by nservant** [comment]
Hi,
I think that there is something wrong in your config file ...
_PATH Directory /u/home/j/jennybea/bin does not exist! Exit_

**Comment by tarak77** [comment]
Hi, I am facing similar error while working on Linux:
```
(py27) [tshisode@darwin HiC-Pro-2.10.0]$ make configure
make -f ./scripts/install/Makefile CONFIG_SYS=./config-install.txt
make[1]: Entering directory `/home/tshisode/HiC-Pro-2.10.0'
./scripts/install/install_dependencies.sh -c ./config-install.txt -o  /home/tshisode/HiC-Pro-2.10.0/HiC-Pro_2.10.0 -q
Make sure internet connection works for your shell prompt under current user's privilege ...
Starting HiC-Pro installation ...
export /home/tshisode/miniconda3/envs/py27/bin/bowtie2 in PATH
export /home/tshisode/miniconda3/envs/py27/bin/samtools in PATH
export /usr/local/bin/R in PATH
export /home/tshisode/miniconda3/envs/py27/bin/python in PATH
Directory /home/tshisode/bin does not exist!
Exit - Error - unable to install/check dependancies !
make[1]: *** [configure] Error 1
make[1]: Leaving directory `/home/tshisode/HiC-Pro-2.10.0'
make: *** [configure] Error 2
```
for my `config-install.txt` file:
```
#########################################################################
## Paths and Settings  - Start editing here !
#########################################################################

PREFIX = /home/tshisode/HiC-Pro-2.10.0
BOWTIE2_PATH = /home/tshisode/miniconda3/envs/py27/bin/bowtie2
SAMTOOLS_PATH = /home/tshisode/miniconda3/envs/py27/bin/samtools
R_PATH = /usr/local/bin/R
PYTHON_PATH = /home/tshisode/miniconda3/envs/py27/bin/python
CLUSTER_SYS = TORQUE
```

Any help?

**Comment by tarak77** [comment]
Nvm, i installed it!

**Comment by nservant** [comment]
You can specify the number of CPUs to use for a given analysis, only in the config-hicpro.txt file.

**Comment by liyini0823** [comment]
When I use HiC-Pro -h , I got errors
usage : HiC-Pro -i INPUT -o OUTPUT -c CONFIG [-s ANALYSIS_STEP] [-p] [-h] [-v]
Use option -h|--help for more information
Error - Installation - config system not detected. Please (re) install HiC-Pro !

**Comment by nservant** [comment]
Did you follow the installation procedure ?
This error message means that you did not install HiC-Pro properly.
Best

**Comment by Antony-1996** [comment]
**I encounter the same problem ,the result is here**
make -f ./scripts/install/Makefile CONFIG_SYS=./config-install.txt
make[1]: Entering directory `/cluster/apps/HiC-Pro-master'
./scripts/install/install_dependencies.sh -c ./config-install.txt -o  /usr/local/bin/HiC-Pro_2.11.1 -q
Make sure internet connection works for your shell prompt under current user's privilege ...
Starting HiC-Pro installation ...
export /cluster/apps/bowtie/2.2.1 in PATH
export /cluster/apps/samtools/1.9/bin in PATH
export /cluster/apps/R/3.5.2/bin in PATH
export /cluster/apps/python/2.7.15/bin in PATH
Checking dependencies ...
Checking Python libraries ...
The required Python libraries appear to be already installed.
Checking R installation ...
The required R packages appear to be already installed.
Bowtie2 Aligner appears to be already installed.
samtools v1.0 or higher is needed [1.9-28-g0cfa699 detected].NORMAL
make[1]: *** [configure] Error 1
make[1]: Leaving directory `/cluster/apps/HiC-Pro-master'
make: *** [configure] Error 2

**my configure install txt file is here** 
PREFIX =
BOWTIE2_PATH = /cluster/apps/bowtie/2.2.1
SAMTOOLS_PATH = /cluster/apps/samtools/1.9/bin
R_PATH = /cluster/apps/R/3.5.2/bin
PYTHON_PATH = /cluster/apps/python/2.7.15/bin
CLUSTER_SYS =
~

**Comment by nservant** [comment]
There is something strange with samtools.
Could check the path again and the version ?

**Comment by Antony-1996** [comment]
yeah ,the version of samtools is so strange.I try another version,the software work perfectly.thanks
