### ISSUE TITLE
.hic file generated by hicpro2juicebox.sh cannot be read by Juicebox Desktop

### ISSUE THREAD

**Issue by gundalav** [nservant/HiC-Pro#194]
Dear Nicolas, 

HiC-Pro is a truly great tool!
I tried this script to make the `hic` file:

```
/home/ubuntu/.hicpro_tools/HiC-Pro_2.11.0-beta/bin/utils/hicpro2juicebox.sh \
 -i hicpro_latest_test/hic_results/data/dixon_2M/dixon_2M.allValidPairs \
 -g hg19 \
 -o ./  \
 -j /home/ubuntu/Tools/Juicebox/out/artifacts/juicer_tools_jar/juicer_tools.jar

```

I got this message:

```
HiC-Pro format > 2.7.5 detected ...
Generating Juicebox input files ...
Running Juicebox ...
Not including fragment map
Start preprocess
Writing header
Writing body
..............................................................................................................................................................
Writing footer

Finished preprocess
Error reading datasetnull
java.io.EOFException
	at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
	at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:182)
	at juicebox.tools.utils.original.NormalizationVectorUpdater.updateHicFile(NormalizationVectorUpdater.java:78)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:112)
	at juicebox.tools.HiCTools.main(HiCTools.java:96)
done !
```

Nevertheless, the file `dixon_2M.allValidPairs.hic` is created. However
when I tried to view it with Juicebox Desktop using `File > Open > Local` sequence
I got this error message:

<img width="380" alt="screen shot 2018-10-03 at 10 26 45" src="https://user-images.githubusercontent.com/8143832/46385438-28e33200-c6f7-11e8-9392-97092e660ef6.png">

How can I resolve the error?

Thanks and hope to hear from you again .

G.V.

**Comment by nservant** [comment]
Hi,
Difficult to say ... as it seems to be more related to Juicer than HiC-Pro.
Could you try to replace the -g hg19, but the chrom_size file you used in HiC-Pro ?
Thanks

**Comment by gundalav** [comment]
Thanks. I fixed it by downloading the `juicer_tools.jar` directly from the [repo](https://github.com/aidenlab/juicer/wiki/Download), instead of compiling it using `ant`.

**Comment by nservant** [comment]
ok. Great.
Just one point ; my last comment is still true.
I advice to set -g with the HiC-Pro chromosome file. If you just set "hg19", it will use the Juicebox default annotation. And for instance, if you run HiC-Pro with UCSC annotation (chr1, chr2, chr3, etc), but Juicebox annotations are based on Ensembl (1,2,3, ...) the maps will be empty.
best
