### ISSUE TITLE
Exit: Error in input type.'.fastq|.bam|.validPairs|.allValidPairs|.matrix' files are expected. cat: /inputfiles_HiC_final.txt: No such file or directory; but files/directory exist

### ISSUE THREAD

**Issue by hwick** [nservant/HiC-Pro#195]
Just installed the newest version of HiC-Pro (2.11.0), and I'm getting the following errors:
Bowtie2 alignment step1 ...
find: `rawdata': No such file or directory
find: `rawdata': No such file or directory
find: `rawdata': No such file or directory
find: `rawdata': No such file or directory
find: `rawdata': No such file or directory
Exit: Error in input type.'.fastq|.bam|.validPairs|.allValidPairs|.matrix' files are expected.
cat: /inputfiles_HiC_final.txt: No such file or directory
Nothing to align ! Please check input files and R1/R2 extension.
make: *** [bowtie_global] Error 1

However, the files are very much there:
[hwick@zappalogin HiC-Pro_final_v2.11.0]$ ls -lht rawdata/*
rawdata/Ctrl_siCtrl:
total 1.0K
lrwxrwxrwx 1 hwick hwick 70 Sep 26 18:28 Ctrl_siCtrl_R2.fastq.gz -> /home/hwick/raw_data/our_data/MH8_R2.fastq.gz
lrwxrwxrwx 1 hwick hwick 70 Sep 26 18:28 Ctrl_siCtrl_R1.fastq.gz -> /home/hwick/raw_data/our_data/MH8_R1.fastq.gz
...

Here is what the input files text file looks like:
[hwick@zappalogin HiC-Pro_final_v2.11.0]$ cat inputfiles_HiC_final.txt
Ctrl_siCtrl/Ctrl_siCtrl_R1.fastq.gz
...

Does HiC-Pro no longer work with zipped fastq files? I ran the previous version of HiC-Pro on this same data set, same config file, with no such complaints

**Comment by nservant** [comment]
There is an issue with the input folder.
Could you show your command line please ?

**Comment by hwick** [comment]
I am running the job in parallel. These are the lines in the step1 and step2 scripts that run HiC-Pro:
HiCPro_step1_HiC_final.sh: 
cd $PBS_O_WORKDIR
FASTQFILE=$PBS_O_WORKDIR/inputfiles_HiC_final.txt; export FASTQFILE
make --file /cm/shared/jhmi/apps/hicpro/2.11.0/HiC-Pro_2.11.0-beta/scripts/Makefile CONFIG_FILE=/home/hwick/top2b/master/interaction/processed_data/our_data/HiC-Pro/config-hicpro.txt CONFIG_SYS=/cm/shared/jhmi/apps/hicpro/2.11.0/HiC-Pro_2.11.0-beta/config-system.txt all_sub 2>&1

HiCPro_step2_HiC_final.sh:
cd $PBS_O_WORKDIR
make --file /cm/shared/jhmi/apps/hicpro/2.11.0/HiC-Pro_2.11.0-beta/scripts/Makefile CONFIG_FILE=/home/hwick/top2b/master/interaction/processed_data/our_data/HiC-Pro/config-hicpro.txt CONFIG_SYS=/cm/shared/jhmi/apps/hicpro/2.11.0/HiC-Pro_2.11.0-beta/config-system.txt all_persample 2>&1

**Comment by nservant** [comment]
I would need to have:
- the content of your data folder
- the command line to use to run HiC-Pro
- As you are using the parallel mode, could you also show me the content of inputfiles_HiC_final.txt file ?

Did you enter the output folder before running the step1.sh file ?
N

**Comment by hwick** [comment]
Command to run HiC-Pro:
```
HiC-Pro -i /home/hwick/top2b/master/interaction/processed_data/our_data/HiC-Pro/rawdata -o /home/hwick/top2b/master/interaction/processed_data/our_data/HiC-Pro/HiC-Pro_final_v2.11.0 -c /home/hwick/top2b/master/interaction/processed_data/our_data/HiC-Pro/config-hicpro.txt -p 8
```

This generates 2 scripts, ```HiCPro_step1_HiC_final.sh``` and ```HiCPro_step2_HiC_final.sh```, in the output folder ```../processed_data/our_data/HiC-Pro/HiC-Pro_final_v2.11.0```. I go to that folder and run them from there with qsub (with a hold on the 2nd script to wait for the first to complete)

Content of rawdata folder. This folder contains a folder for each sample. rawdata folder is generated by the initial HiC-Pro script from the raw data folder specified by the -i flag. Each R1/R2 sample in that folder is a symbolic link to the actual samples which are in different folders, I'm not sure if that could potentially be a problem -- symbolic links have been an issue for programs like IGV, though it was not a problem for me with HicPro 2.10.
```
/home/hwick/top2b/master/interaction/processed_data/our_data/HiC-Pro/HiC-Pro_final_v2.11.0/rawdata
[hwick@zappalogin rawdata]$ ls *
Ctrl:
Ctrl_R1.fastq.gz  Ctrl_R2.fastq.gz

Ctrl_siCtrl:
Ctrl_siCtrl_R1.fastq.gz  Ctrl_siCtrl_R2.fastq.gz

Ctrl_siTOP2B:
Ctrl_siTOP2B_R1.fastq.gz  Ctrl_siTOP2B_R2.fastq.gz

DHT:
DHT_R1.fastq.gz  DHT_R2.fastq.gz

DHTMer:
DHTMer_R1.fastq.gz  DHTMer_R2.fastq.gz

DHT_siCtrl:
DHT_siCtrl_R1.fastq.gz  DHT_ssiCtrl_R2.fastq.gz

DHT_siTOP2B:
DHT_siTOP2B_R1.fastq.gz  DHT_siTOP2B_R2.fastq.gz

Mer:
Mer_R1.fastq.gz  Mer_R2.fastq.gz
```

Content of inputfiles_HiC_final.txt :
```
/home/hwick/top2b/master/interaction/processed_data/our_data/HiC-Pro/HiC-Pro_final_v2.11.0
[hwick@zappalogin HiC-Pro_final_v2.11.0]$ cat inputfiles_HiC_final.txt 
Ctrl/Ctrl_R1.fastq.gz
Ctrl_siCtrl/Ctrl_siCtrl_R1.fastq.gz
Ctrl_siTOP2B/Ctrl_siTOP2B_R1.fastq.gz
DHT/DHT_R1.fastq.gz
DHTMer/DHTMer_R1.fastq.gz
DHT_siCtrl/DHT_siCtrl_R1.fastq.gz
DHT_siCtrl/DHT_ssiCtrl_R1.fastq.gz
DHT_siTOP2B/DHT_siTOP2B_R1.fastq.gz
Mer/Mer_R1.fastq.gz
```
Let me know if you need any more info, thanks so much!

**Comment by hwick** [comment]
Hello, I am just checking in to see if there are any updates or suggestions about what may have gone wrong? Please let me know if I should provide more information

**Comment by nservant** [comment]
Sorry for the delay ... Everything looks good.
My feeling is that the variable ${PBS_O_WORDKIR} is not defined on your system.
Is that possible ?

If you look at the step1.sh script for instance.

```
cd $PBS_O_WORKDIR
FASTQFILE=$PBS_O_WORKDIR/inputfiles_hicpro_dekker.txt; export FASTQFILE

```
HiC-Pro first relocates in the directory you run it, ie. the $PBS_O_WORKDIR
This is where 'rawdata' should be.
In addition, when I see
 cat: /inputfiles_HiC_final.txt: No such file or directory
It really seems that the variable is not define.

I agree that it should be better to not use this variable if it is not stable for a system to another. I can think that it. In the meantime, does it work if you manually set it in the step1.sh script ?
Best

**Comment by hwick** [comment]
We have SGE, so I manually set the variable $PBS_O_WORKDIR to the working directory and reran the script, but this did not fix the issue. I noticed that when HiCPro parallel command is run it defaults to creating scripts to run with PBS, but it says it is SGE compatible. Is that still the case? I changed all of the headers to be compatible with our server system (with what worked with v2.10 on a subset of the same data set... though I am now having trouble running more than one sample in parallel with that version of HiC-Pro as well when I run on the full data set).

**Comment by nservant** [comment]
Ah yest, HiC-Pro is SGE compatible but you have to specify it at the installation process.
Could you look at the config-system.txt file in the installation folder ?
There is a variable CLUSTER_SCRIPT which is set according to the cluster info you provided during installation.
You should have a path with scripts/make_sge_script.sh at the end.
If necessary you can edit this file and specify the good cluster script, instead of reinstalling everything.

**Comment by nservant** [comment]
That's strange.
How many lines do you have in the input* file within the HiC-Pro output folder ?
In theory, you should have one job per input file.
The step2 is not included in the -t option. It has to be run independently once the first one is completed.

**Comment by cmonat** [comment]
Hi,

I have a similar error, here is an example for one of the sub-jobs log file:


ven. août 23 08:50:28 CEST 2019
Bowtie2 alignment step1 ...
find: ‘rawdata’: Aucun fichier ou dossier de ce type
find: ‘rawdata’: Aucun fichier ou dossier de ce type
find: ‘rawdata’: Aucun fichier ou dossier de ce type
find: ‘rawdata’: Aucun fichier ou dossier de ce type
find: ‘rawdata’: Aucun fichier ou dossier de ce type
Exit: Error in input type.'.fastq|.bam|.validPairs|.allValidPairs|.matrix' files are expected.
cat: /home/celmonat/WheatOMICS/inputfiles_.txt: Aucun fichier ou dossier de ce type
Nothing to align ! Please check input files and R1/R2 extension.
make: *** [bowtie_global] Erreur 1
slurm-12558027_8.out (END)


My output folder look like this:

ls hicProOutputs/
total 16K
-rwxr-x---. 1 celmonat gdec 3,2K 21 août  17:02 config-hicpro-renan.txt
-rwxr-xr-x. 1 celmonat gdec  550 21 août  17:07 HiCPro_step1_.sh
-rwxr-xr-x. 1 celmonat gdec  483 21 août  17:02 HiCPro_step2_.sh
-rw-r--r--. 1 celmonat gdec  112 21 août  17:02 inputfiles_.txt
drwxr-xr-x. 2 celmonat gdec    2 21 août  17:02 logs
lrwxrwxrwx. 1 celmonat gdec   32 21 août  17:02 rawdata -> /home/celmonat/WheatOMICS/hicPro
drwxr-xr-x. 2 celmonat gdec    2 21 août  17:02 tmp


and


ls -lht rawdata/*
rawdata/sample8:
total 144G
-rwxr-x---. 1 celmonat gdec 147G 21 août  16:32 8_combined_R2.fastq
-rwxr-x---. 1 celmonat gdec 147G 21 août  14:14 8_combined_R1.fastq

rawdata/sample7:
total 146G
-rwxr-x---. 1 celmonat gdec 150G 21 août  12:16 7_combined_R2.fastq
-rwxr-x---. 1 celmonat gdec 150G 21 août  11:07 7_combined_R1.fastq

rawdata/sample6:
total 147G
-rwxr-x---. 1 celmonat gdec 151G 21 août  10:08 6_combined_R2.fastq
-rwxr-x---. 1 celmonat gdec 151G 20 août  18:23 6_combined_R1.fastq

rawdata/sample5:
total 147G
-rwxr-x---. 1 celmonat gdec 152G 20 août  17:47 5_combined_R2.fastq
-rwxr-x---. 1 celmonat gdec 152G 20 août  15:22 5_combined_R1.fastq


I am working with a SLURM cluster. The command line I used to launch HiC-Pro is:
HiC-Pro -i /home/celmonat/WheatOMICS/hicPro -o /home/celmonat/WheatOMICS/hicProOutputs -c /home/celmonat/WheatOMICS/config-hicpro-renan.txt -p


after I tried to lauch directly the HiCPro_step1.sh and got the error presented in the begining. After reading here on the github I have tried to modified the HiCPro_step1.sh script to make it work on 8 jobs (4 samples * R1+R2 files =8 files so 8 jobs ?) but I got the exact same error message. 
Any idea what I'm doing wrong?

Thank you in advance for your help
Have a great day
Cheers
C.

**Comment by nservant** [comment]
Could you show me your config file please ? There are a few options to set for your cluster there ...

**Comment by cmonat** [comment]
Hi,

Here is the copy of my config file:



# Please change the variable settings below if necessary

#########################################################################
## Paths and Settings  - Do not edit !
#########################################################################

TMP_DIR = tmp
LOGS_DIR = logs
BOWTIE2_OUTPUT_DIR = bowtie_results
MAPC_OUTPUT = hic_results
RAW_DIR = rawdata

#######################################################################
## SYSTEM AND SCHEDULER - Start Editing Here !!
#######################################################################
N_CPU = 32
LOGFILE = hicpro.log

JOB_NAME = 
JOB_MEM = 
JOB_WALLTIME = 
JOB_QUEUE =
JOB_MAIL =

#########################################################################
## Data
#########################################################################

PAIR1_EXT = _R1
PAIR2_EXT = _R2

#######################################################################
## Alignment options
#######################################################################

MIN_MAPQ = 10

BOWTIE2_IDX_PATH = /home/celmonat/WheatOMICS/
BOWTIE2_GLOBAL_OPTIONS = --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder
BOWTIE2_LOCAL_OPTIONS =  --very-sensitive -L 20 --score-min L,-0.6,-0.2 --end-to-end --reorder

#######################################################################
## Annotation files
#######################################################################

REFERENCE_GENOME = IWGSC_CSRefSeqv1
GENOME_SIZE = /home/celmonat/WheatOMICS/IWGSC_CSRefSeqv1.sizes
#######################################################################
## Allele specific analysis
#######################################################################

ALLELE_SPECIFIC_SNP =

#######################################################################
## Capture Hi-C analysis
#######################################################################

CAPTURE_TARGET =
REPORT_CAPTURE_REPORTER = 1

#######################################################################
## Digestion Hi-C
#######################################################################

GENOME_FRAGMENT = /home/celmonat/WheatOMICS/Renan_rawont_v4_arimaKitDigested.bed
LIGATION_SITE = GATCGATC,GAATGATC,GATTGATC,GACTGATC,GAGTGATC,GATCAATC,GATCATTC,GATCACTC,GATCAGTC,GAATAATC,GAATACTC,GAATAGTC,GAATATTC,GACTAATC,GACTACTC,GACTAGTC,GACTATTC,GAGTAATC,GAGTACTC,GAGTAGTC,GAGTATTC,GATTAATC,GATTACTC,GATTAGTC,GATTATTC
MIN_FRAG_SIZE =
MAX_FRAG_SIZE =
MIN_INSERT_SIZE =
MAX_INSERT_SIZE =

#######################################################################
## Hi-C processing
#######################################################################

MIN_CIS_DIST = 0
GET_ALL_INTERACTION_CLASSES = 1
GET_PROCESS_SAM = 0
RM_SINGLETON = 1
RM_MULTI = 1
RM_DUP = 1

#######################################################################
## Contact Maps
#######################################################################

BIN_SIZE = 20000 40000 150000 500000 1000000
MATRIX_FORMAT = upper

#######################################################################
## Normalization
#######################################################################
MAX_ITER = 100
FILTER_LOW_COUNT_PERC = 0.02
FILTER_HIGH_COUNT_PERC = 0
EPS = 0.1




Thank you very muche for your help
C.

**Comment by nservant** [comment]
Could you first try to run it without '-p' option please ?
The idea is just to see if this is a HiC-Pro issue, or more a cluster configuration issue.

Then, to run HiC-Pro on a cluster, you need to set up the follwing options in the config file ;
JOB_NAME =
JOB_MEM =
JOB_WALLTIME =
JOB_QUEUE =
JOB_MAIL =
Thanks

**Comment by nservant** [comment]
Regarding the cluster usage, you need to submit your job where the HiCPro_step1/2.sh files are created. In addition, the inputfile.txt file should list all detected input files to submit to the cluster.

**Comment by cmonat** [comment]
Hi,

it's still running but so far, when running without the '-p' option, the log file is looking like this:


running on host hpcnode07

Run HiC-Pro 2.11.1
--------------------------------------------
mer. août 28 17:22:59 CEST 2019
Bowtie2 alignment step1 ...
Logs: logs/sample5/mapping_step1.log
Logs: logs/sample6/mapping_step1.log

In my case, I have a script to lauch the job looking like this:



#!/bin/bash

########################################
# configuration pour SLURM au CRRI     #
########################################
#SBATCH -n32
#SBATCH -N1
#SBATCH --mem=32G
#SBATCH -J hicproPipeline
#SBATCH --partition=long

########################################
#### faire les modules load nécessaire #
########################################
module load python/2.7.9 samtools pysam numpy scipy bowtie2 R
module swap gcc/4.8.4 gcc/8.1.0
module load hic-pro

##############################
# LAUNCH THE HICPRO PIPELINE #
##############################
echo "running on host `hostname`"
export CONFIG_SYS='/storage/groups/gdec/bin/tools/hic-pro/HiC-Pro-2.11.1/config-system.txt'

#/storage/groups/gdec/bin/tools/hic-pro/HiC-Pro-2.11.1/HiC-Pro_2.11.1/bin/HiC-Pro -i /home/celmonat/WheatOMICS/hicPro -o /home/celmonat/WheatOMICS/testhicProOutputs -c /home/celmonat/WheatOMICS/config-hicpro-renan.txt -p

HiC-Pro -i /home/celmonat/WheatOMICS/hicPro -o /home/celmonat/WheatOMICS/hicProOutputs -c /home/celmonat/WheatOMICS/config-hicpro-renan.txt



That's why I didn't put anything in the JOB_NAME & Cie parameters, but maybe I was wrong to do so ?
The files HiCPro_step1/2.sh are created in my output directory, that's why I cannot launch the initial job into it.
Should I re-run the job differently?

Thanks for your help
C.

**Comment by nservant** [comment]
Hi Cécile,
Actually, HiC-Pro should submit the job on the cluster by itself.
It works in three steps ;
- HiC-Pro -p prepares the output folder with the script to submit
- Then, you have to go in the output folder and submit the *step1.sh script
- Once it is done, do the same with the *step2.sh file

You can contact me directly by private email for further details, it might be easier ...
N
