### ISSUE TITLE
matrix

### ISSUE THREAD

**Issue by RuiqinZheng** [nservant/HiC-Pro#196]
Hi, I wanner know why the interaction bin pairs changed?
for example, following is the raw matrix, the biggest bin is 3747
$ tail hicpro/hic_results/matrix/liuchang/raw/100000/liuchang_100000.matrix 
3743	3747	1
3744	3744	11
3744	3745	8
3744	3746	8
3745	3745	545
3745	3746	142
3745	3747	16
3746	3746	583
3746	3747	48
3747	3747	30
 and the following is the iced matrix, but the biggest bin is 3739 
$ tail liuchang_100000_iced.matrix 
3736	3736	15280.104377
3736	3737	7944.507413
3736	3738	3006.044079
3736	3739	1606.489889
3737	3737	16600.549466
3737	3738	9469.807149
3737	3739	2741.444496
3738	3738	15944.638009
3738	3739	7915.471217
3739	3739	16929.878805

and I check the raw matrix, the interaction counts between 3740(3747) and others are not the smallest interaction counts, but why in the iced matrix, there's interaction among 3739 bins?
3734    3740    82
3735    3740    130
3736    3740    203
3737    3740    351
3738    3740    708
3739    3740    3320
3740    3740    2922

3745    3747    16
3746    3747    48
3747    3747    30

Thanks!

**Comment by nservant** [comment]
Hi,
When running iced, the x% of rows with lower counts are discarded from the analysis (by default 2%).
By discarded, it means set to zero. And thus, there are no longer present in the output file as zero values are not stored.
You can have a try setting FILTER_LOW_COUNT_PERC = 0
However, in the case, the algorithm might have some issue to converge, but you should be filter out any bin.
Does it make sense ?
N
