### ISSUE TITLE
split_reads.py bug in file path

### ISSUE THREAD

**Issue by mzhibo** [nservant/HiC-Pro#197]
When I set a absolute path to the output directory, if the file path contain a "fastq" directory, the name of the parent directory of the "fastq" directory will also be appended "_part" in the python process. This will cause an error of the split process. No problem if I split the .fastq.gz file.
Example:
fastqDir=/lustre1/username/hic/fastq/experiment1
split_reads.py --results_folder ${fastqDir}/splits --nreads 25000000 ${fastqDir}/SRR123456.fastq

It will return with an error:
split: /lustre1/username/hic_part/fastq/cavali_embryogenesis}/SRR6019756_pass_2.fastq_part00: No such file or directory
split file failed with return code %d 1

I found an easy work around of this issue by changing the working directory to the directory that hold the fastq file to be splitted first, then directly the file name and relative path to the output. But I feel it the original python script could be modified to avoid this.
example:
fastqDir=/lustre1/username/hic/fastq/experiment1
cd $fastqDir
split_reads.py --results_folder splits --nreads 25000000 SRR123456.fastq
The above lines run without problem

**Comment by nservant** [comment]
Seems good ...
