### ISSUE TITLE
How to multi-threads the step of "mergeSAM.py"

### ISSUE THREAD

**Issue by wk8910** [nservant/HiC-Pro#198]
Hi,
I found that after alignment with bowtie2, the following steps are not multi-threaded.
Especially the step of "Pairing of R1 and R2 tags" using "mergeSAM.py", it is very slow with single thread.
Is there any method to accelerate this step?
Thanks!
Best,
Kun

**Comment by nservant** [comment]
Yes, indeed !
I would suggest to split the fastq files into chunks, and to run HiC-pro on a cluster with -p option.
In this mode, all chunks are processed in parallel until the detection of valid interaction.
Best

**Comment by wk8910** [comment]
Thanks!
I tried the -p option as you suggested. Indeed it is now multi-thread.
However, the last step "Generate binned matrix files" using "build_matrix" is still not multi-thread.
Could we solve this?
Best,
Kun

**Comment by nservant** [comment]
Indeed. This is something I would like to do, but time is missing :)
However, the build_matrix step is pretty fast and has been optimized in C++.
It should not take more than a couple of minutes to generate the genome-wide contact maps.
Best

**Comment by wk8910** [comment]
Thanks for your explain!
However, it have already taken for over nine hours for the "build_matrix" step and it is still running.
I also tried this with a test data of only 250000 pairs of reads, but the "build_matrix" is also running with no end……
Is there something wrong?
Best,
Kun

**Comment by nservant** [comment]
When HiC-Pro the step2 of parallel mode, there is a first step to combine all reads chuncks and remove the duplicates (if specificed). This can take some times and is not parallelize.
I think that this is the most time consuming part.
Best
