### ISSUE TITLE
error in the installation of the new version

### ISSUE THREAD

**Issue by LeopoldC** [nservant/HiC-Pro#201]
Hey nicolas!
I'm trying to install the last version of the code and I have the following error :+1: 
/bin/sh: -c: ligne 0: erreur de syntaxe près du symbole inattendu « ( »
/bin/sh: -c: ligne 0: `dirname /home/lptl/HiC-Pro-master (2)/config-system.txt'
/bin/sh: -c: ligne 0: erreur de syntaxe près du symbole inattendu « ( »
/bin/sh: -c: ligne 0: `dirname /home/lptl/HiC-Pro-master (2)/config-system.txt'
/bin/sh: -c: ligne 0: erreur de syntaxe près du symbole inattendu « ( »
/bin/sh: -c: ligne 0: `dirname /home/lptl/HiC-Pro-master (2)/config-system.txt'
/bin/sh: -c: ligne 0: erreur de syntaxe près du symbole inattendu « ( »
/bin/sh: -c: ligne 0: `dirname /home/lptl/HiC-Pro-master (2)/config-system.txt'
make -f ./scripts/install/Makefile CONFIG_SYS=./config-install.txt
make[1] : on entre dans le répertoire « /home/lptl/HiC-Pro-master (2) »
/bin/sh: -c: ligne 0: erreur de syntaxe près du symbole inattendu « ( »
/bin/sh: -c: ligne 0: `dirname /home/lptl/HiC-Pro-master (2)/config-install.txt'
/bin/sh: /bin/HiC-Pro: No such file or directory
./scripts/install/install_dependencies.sh -c ./config-install.txt -o  /usr/local/bin/HiC-Pro_ -q

Did you change anything in the path install configuration?
Léopold

**Comment by nservant** [comment]
Hi Léopold
That's a bit surpising because the installation process has not been change for a while.
Could you show me the content of your config-system.txt file ?
It seems that there is an issue with this file ...
The config-system is generated from the config-install.txt file. Is there any special character in this file ?
N

**Comment by LeopoldC** [comment]
#######################################################################
## HiC-Pro - System settings
#######################################################################
#######################################################################
## Required Software - Specified the DIRECTORY name of the executables
## If not specified, the program will try to locate the executable
## using the 'which' command
#######################################################################
R_PATH = /usr/bin
BOWTIE2_PATH = /users/invites/carron/Documents/bowtie2-2.2.1
SAMTOOLS_PATH = /usr/local/bin
PYTHON_PATH = /usr/bin
INSTALL_PATH = /users/invites/carron/HiC-Pro_
SCRIPTS = /users/invites/carron/HiC-Pro_/scripts
SOURCES = /users/invites/carron/HiC-Pro_/scripts/src
ANNOT_DIR = /users/invites/carron/HiC-Pro_/annotation
CLUSTER_SCRIPT = /users/invites/carron/HiC-Pro_/scripts/make_torque_script.sh

It is really similar to the oldest one from every version that I install ( I'm currently at HiC-Pro_2.9.0 but I had another issue that I think is fix with the new one)

**Comment by nservant** [comment]
Hi
Looking at your log again, it seems that you downloaded the HiC-pro master in a folder named 
"/home/lptl/HiC-Pro-master (2)"
Actually, the " (2)" generated an error in the bash script.
If you simply change the name of your folder ... without "space" or "bracket", it should be better
N

**Comment by nservant** [comment]
ok. I close.
N
