### ISSUE TITLE
'N' base in ligation motif

### ISSUE THREAD

**Issue by nservant** [nservant/HiC-Pro#202]
Allow 'N' base to be used in the ligation motif
This could be useful for the Arima kit that is using a double digestion ^GATC and G^ANTC,

**Comment by ChenfuShi** [comment]
Hi Nicholas, I was just working on data from the Arima kit. 
Is there a workaround currently for this?

Thanks!

**Comment by nservant** [comment]
No. So far, you have to replace the 'N' by the 4 possible bases.
N

**Comment by ChenfuShi** [comment]
Thanks for your answer.
Just to be sure, the only bits that need to be expanded are the digest genome section and the ligation sites right?

**Comment by nservant** [comment]
yes !

**Comment by nservant** [comment]
'N' is now supported in the ligation motif sequence.
For Arima, the ligation motifs should be GATCGATC,GATCGANT,GANTGATC,GANTGANT
All N will be automatically replaced by A,C,G,T
This change has been implemented in v2.11.3 devel

**Comment by harish0201** [comment]
Hi!

Just to make sure that I understood the thread correctly, do I just pass the ^GATC and G^ANTC in the command line to digest the genome? Then the digest_genome.py would be able to recognize the various ligation motifs?

**Comment by nservant** [comment]
That's a very good point !!
I update the trimming script within HiC-Pro but not the digest_genome.py utility.
I will do it.
N

**Comment by dtemko** [comment]
Hi, just wondering if v2.11.3 is available, or whether this is already also fixed in the latest release, v2.11.1
Thanks.

**Comment by zyqfrog10** [comment]
Hi @nservant ,

Just want to make sure with you on the LIGATION_SITE setting. 
For Arima, it would be GATCGATC, GANTGATC, GANTANTC, GATCANTC for v2.11.3 (which has not been released yet?).
Can I set for v2.11.1 in LIGATION_SITE field as GATC,GAATC,GACTC,GAGTC,GATTC?
Thanks.
Ada

**Comment by zyqfrog10** [comment]
Or ?
LIGATION_SITE = GATCGATC GAATGATC GATTGATC GACTGATC GAGTGATC GATCAATC GATCATTC GATCACTC GATCAGTC GAATAATC GATTAATC GACTAATC GAGTAATC GAATATTC GATTATTC GACTATTC GAGTATTC GAATAGTC GATTAGTC GACTAGTC GAGTAGTC GAATACTC GATTACTC GACTACTC GAGTACTC

Would v2.11.1 take that many ligation motifs?
Thanks.

**Comment by nservant** [comment]
Hi,
here is what you can use for v2.11.1
LIGATION_SITE = GATCGATC,GAATGATC,GATTGATC,GACTGATC,GAGTGATC,GAATAATC,GAATATTC,GAATACTC,GAATAGTC,GTATAATC,GTATATTC,GTATACTC,GTATAGTC,GCATAATC,GCATATTC,GCATACTC,GCATAGTC,GGATAATC,GGATATTC,GGATACTC,GGATAGTC,GATCAATC,GATCATTC,GATCACTC,GATCAGTC

**Comment by ChenfuShi** [comment]
Hi Nicholas,
I was checking what I was using and it seems that our settings are different - here are the sites that I've been using:
LIGATION_SITE = GATCGATC,GAATGATC,GATTGATC,GAGTGATC,GACTGATC,GATCAATC,GATCATTC,GATCAGTC,GATCACTC,GAATAATC,GAATATTC,GAATAGTC,GAATACTC,GATTAATC,GATTATTC,GATTAGTC,GATTACTC,GAGTAATC,GAGTATTC,GAGTAGTC,GAGTACTC,GACTAATC,GACTATTC,GACTAGTC,GACTACTC


The difference are these 12 that you have in your setting above:
GTATAATC,GTATATTC,GTATACTC,GTATAGTC,GCATAATC,GCATATTC,GCATACTC,GCATAGTC,GGATAATC,GGATATTC,GGATACTC,GGATAGTC


but looking at the FAQ page from arima genomics they said to use these 4 (with the Ns)
possible ligation junction motifs: GATCGATC, GANTGATC, GANTANTC, GATCANTC.

Which does not cover those 12.
Can we double check to make sure we are using the right settings?

Thanks!

**Comment by nservant** [comment]
The possible combinations are a bit complicated, because any motif (GATC
or GANT) on one site can be fused to any motif on the other side.
If I'm correct, the enzymes are  ^GATC and G^ANTC, where N can be any of the 4 genomic bases.
producing the following possible ligation junction motifs: 
GATCGATC, GANTGATC, GANTANTC, GATCANTC.
See also https://arimagenomics.com/faq/

Now, let replace the Ns.
GATCGATC
GAATGATC GATTGATC GACTGATC GAGTGATC
GATCAATC GATCATTC GATCACTC GATCAGTC
GAATAATC GAATACTC GAATAGTC GAATATTC GACTAATC GACTACTC GACTAGTC GACTAATC GAGTAATC GAGTACTC GAGTAGTC GAGTATTC GATTAATC GATTACTC GATTAGTC GATTATTC

I think we should be good now !? What do you think ?
N

**Comment by ChenfuShi** [comment]
yeah, only difference is you typed GACTAATC twice instead of GACTATTC (from GANTANTC).

Then it would be equivalent to mine!

Best
Chenfu

**Comment by nservant** [comment]
ok just update my post to avoid futur error. Thanks !

**Comment by JoannaAch** [comment]
> That's a very good point !!
> I update the trimming script within HiC-Pro but not the digest_genome.py utility.
> I will do it.
> N

Hi Nicolas,
Have you had a chance to update the digest_genome.py script to accept N base in RE cut site?
If so, where can I find the updated version?

Thanks,
Jo

**Comment by nservant** [comment]
Hi Jo,
Yes. I just committed a new version on the devel branch.
Even if I did some quick checks, it would be great if you could validate that it works well on your side too.
Note that multiple restriction sites can be provided, but space separated.
Let me know if it works
Nicolas

**Comment by JoannaAch** [comment]
Hi Nicolas,
Thanks! I tried to run the new digest_genome.py script but it quits with a type error at the line you added:

  File "digest_genome_arima.py", line 154, in <module>
    sequences_without_N = sequences_without_N + replaceN(sequences[rs])
TypeError: can only concatenate list (not "str") to list

Here is the command I used: digest_genome_arima.py -r ^GATC G^ANTC -o Arima_resfrag_N_hg38.bed genome.fa

Jo

**Comment by nservant** [comment]
Hi,
Thanks for testing. A small typo ... it's fixed now (in the devel branch).
N

**Comment by JoannaAch** [comment]
Hi,
Thanks, that works perfectly.
Joanna

**Comment by nservant** [comment]
great ! Thanks again

**Comment by tanasa** [comment]
Dear Nicolas, in the continuation of the conversation above, if I may ask please, as we have received a set of HiC data from ARIMA Genomics in San Diego : could i specify the LIGATION_SITE as following : 

```
GENOME_FRAGMENT = mm10_GATC_GANTC.bed
LIGATION_SITE = GATCGATC GANTGATC GANTANTC GATCANTC
```

referring to the GENOME_FRAGMENT, we have downloaded those from : 
ftp://ftp-arimagenomics.sdsc.edu/pub/HiCPro_GENOME_FRAGMENT_FILES

thanks a lot, with much appreciation !

**Comment by nservant** [comment]
Hi Bogdan,

If you want you can regenerate the genome fragment file using the `bin/utils/digest_genome.py` file to double check.
You can specify `--restriction_sites ^GATC G^ANTC`

Then, in the config file, please you 'comma' between the motifs :+1: 
GATCGATC,GANTGATC,GANTANTC,GATCANTC

Best
Nicolas

**Comment by tanasa** [comment]
wonderful, thanks again ! i am very grateful for your help :)

**Comment by Simple53** [comment]
Hi, Nicolas.
I was using HiC-Pro v3.1.0 to analyze data from the Arima kit and specify the config file as following:
`LIGATION_SITE = GATCGATC, GANTGATC,GANTANTC,GATCANTC`

But I've got errors in log:
`HiC-Pro_3.1.0/scripts/cutsite_trimming: unknown option GANTGATC,GANTANTC,GATCANTC`
Does it mean the N base could not be recognize, how could I fix it?

Thanks,
Xinpei
