### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by hzaumsq** [nservant/HiC-Pro#206]
when I iced the matrix,I met a mistakes which  I tried many times ,I still  can't solve it now,I 'm confused.

/usr/local/bin/python /home/sqmao/tools/hicpro/HiC-Pro_2.11.1/scripts/ice --results_filename hic_results/matrix/egg_Rep1/iced/10000/egg_Rep1_10000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 --verbose 1 hic_results/matrix//egg_Rep1/raw/10000/egg_Rep1_10000.matrix
Using iced version 0.4.2
Loading files...
Traceback (most recent call last):
  File "/home/sqmao/tools/hicpro/HiC-Pro_2.11.1/scripts/ice", line 76, in <module>
    if min(i.min(), j.min()) == 0:
  File "/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by nservant** [comment]
are you sure that hic_results/matrix//egg_Rep1/raw/10000/egg_Rep1_10000.matrix is not empty ?

**Comment by nservant** [comment]
ok. Could you check if there is no annotation issue, ie. difference between chromosome name in the size file, and between the valid pairs. Check also if the allValidPairs file is not empty
