### ISSUE TITLE
error on parallele mode

### ISSUE THREAD

**Issue by jjjscuedu** [nservant/HiC-Pro#209]
Hi all,

Because my dataset is very large, I choose use the parallel model.
Totally, in step 1, I got 42 parallel jobs.

#!/bin/bash
#BSUB -M 300
#BSUB -W 200
#BSUB -N 
#BSUB -u nservant@curie.fr
#BSUB -J HiCpro_s1_align_split[1-42]
#BSUB -e HiCpro_s1_align_split.%J.e
#BSUB -o HiCpro_s1_align_split.%J.o
#BSUB -q normal
#BSUB -n 15
#BSUB -R "span[ptile=30]"
#BSUB -J HiCpro_s1_align_split[1-42]
FASTQFILE=inputfiles_align_split.txt; export FASTQFILE
make --file /gpfs01/software/bio/HiC-Pro-2.11.0/HiC-Pro_2.11.1/scripts/Makefile CONFIG_FILE=/gpfs02/home/jingjing/project/tobacco/HiC/HiC-pro/config_test_latest.txt CONFIG_SYS=/gpfs01/software/bio/HiC-Pro-2.11.0/HiC-Pro_2.11.1/config-system.txt all_sub 2>&1

However, when I submit this job, some alignment file is OK.

For some files, it has error in this place:

Wed Dec  5 12:57:37 CST 2018
Assign alignments to restriction fragments ...
Logs: logs/WT1/mapped_2hic_fragments.log

--------------------------------------------
Wed Dec  5 11:23:47 CST 2018
Bowtie2 alignment step1 ...
Logs: logs/WN/mapping_step1.log
/gpfs01/software/bio/HiC-Pro-2.11.0/HiC-Pro_2.11.1/scripts/bowtie_wrap.sh: line 1: 61431 User defined signal 2   end_to_end_align ${odir} ${R2} ${UNMAP} ${FILT_UNMAP} ${ldir} >> ${ldir}/mappi
ng_step1.log
--------------------------------------------
Wed Dec  5 11:23:47 CST 2018
Bowtie2 alignment step1 ...
Logs: logs/WN/mapping_step1.log
/gpfs01/software/bio/HiC-Pro-2.11.0/HiC-Pro_2.11.1/scripts/bowtie_wrap.sh: line 1: 61430 User defined signal 2   end_to_end_align ${odir} ${R1} ${UNMAP} ${FILT_UNMAP} ${ldir} >> ${ldir}/mappi
ng_step1.log
/gpfs01/software/bio/HiC-Pro-2.11.0/HiC-Pro_2.11.1/scripts/bowtie_wrap.sh: line 1: 61432 User defined signal 2   end_to_end_align ${odir} ${R2} ${UNMAP} ${FILT_UNMAP} ${ldir} >> ${ldir}/mappi
ng_step1.log
--------------------------------------------
Wed Dec  5 11:23:47 CST 2018
Bowtie2 alignment step1 ...
Logs: logs/WN/mapping_step1.log
/gpfs01/software/bio/HiC-Pro-2.11.0/HiC-Pro_2.11.1/scripts/bowtie_wrap.sh: line 1: 36750 User defined signal 2   end_to_end_align ${odir} ${R1} ${UNMAP} ${FILT_UNMAP} ${ldir} >> ${ldir}/mappi
ng_step1.log
/gpfs01/software/bio/HiC-Pro-2.11.0/HiC-Pro_2.11.1/scripts/bowtie_wrap.sh: line 1: 36752 User defined signal 2   end_to_end_align ${odir} ${R2} ${UNMAP} ${FILT_UNMAP} ${ldir} >> ${ldir}/mappi
ng_step1.log
--------------------------------------------

Can anyone give me some suggestion about how to fix this error?

Thanks a  lot!

jingjing

**Comment by nservant** [comment]
Hi,
Sorry, not sure to understand where the error occurs ?
Is it at the " Assign alignments to restriction fragments ..." step ?
Could you look at the log file to find a more precise error.
Thanks
