### ISSUE TITLE
Hi-C resolution selection

### ISSUE THREAD

**Issue by Bonnie19920126** [nservant/HiC-Pro#210]
Hi, does anyone known how to select a proper Hi-C resolution, as I know, in the paper entitled "A three-dimensional map of the human genome at kilobase resolution reveals principles of chromatin looping", the author described "We define “matrix resolution” as the locus size used to construct a particular contact matrix and “map resolution” as the smallest locus size such that 80% of loci have at least 1000 contacts." But when I run Hi-C pro, in the iced matrix results, the interaction counts is too small, may anyone give me some suggestions?

**Comment by reineckef** [comment]
The iced matrix is normalized, so numbers do not represent fragment counts. You need to check the raw matrix counts to calculate the resolution for your data, using the method described.

**Comment by Bonnie19920126** [comment]
> The iced matrix is normalized, so numbers do not represent fragment counts. You need to check the raw matrix counts to calculate the resolution for your data, using the method described.

Thank you!
