### ISSUE TITLE
NameError: name 'or1_fragname' is not defined in HiC-Pro_2.11.2

### ISSUE THREAD

**Issue by Bonnie19920126** [nservant/HiC-Pro#211]
Hi Nicolas,
   I meet the problem "make: *** [mapped_2hic_fragments] Error 1", could you help me? Thank you very much!
   This is my log file:
/pub2/lixin/software/conda/anaconda2/bin/python /pub2/lixin/software/HiC-Pro/HiC-Pro-install/HiC-Pro_2.11.2-beta/scripts/mapped_2hic_fragments.py -v -S -t 100 -m 100000 -s 100 -l 600 -a -f /pub2/lixin/software/HiC-Pro/HiC-Pro-install/HiC-Pro_2.11.2-beta/annotation/MboI_DpnII_resfrag_hg38.bed -r bowtie_results/bwt2/in_situ_GM12878/SRR1658573_Human_GRCh38.bwt2pairs.bam -o hic_results/data/in_situ_GM12878
## Loading Restriction File Intervals ' /pub2/lixin/software/HiC-Pro/HiC-Pro-install/HiC-Pro_2.11.2-beta/annotation/MboI_DpnII_resfrag_hg38.bed '...
Warning :  1452970 fragment(s) outside of range and discarded.  5746512  remaining.
load_restriction_fragment function took 92429.545 ms
## Classifying Interactions ...
Warning - no restriction fragments for  SRR1658573.6  at  18 : 55795013
Warning - no restriction fragments for  SRR1658573.6  at  20 : 22226299
Traceback (most recent call last):
  File "/pub2/lixin/software/HiC-Pro/HiC-Pro-install/HiC-Pro_2.11.2-beta/scripts/mapped_2hic_fragments.py", line 744, in <module>
    str(htag) + "\n")
NameError: name 'or1_fragname' is not defined

Thank you for your time. 
Best wishes.

**Comment by xing641** [comment]
I meet the same problem. Can tell me how to solve it? Thank you!

**Comment by Bonnie19920126** [comment]
> I meet the same problem. Can tell me how to solve it? Thank you!

Hi,
   Because of the annotation files I used is inconsistent, for examples, one used "chr1", the other used "1", I corrected it, and success.

**Comment by xing641** [comment]
> > I meet the same problem. Can tell me how to solve it? Thank you!
> 
> Hi,
> Because of the annotation files I used is inconsistent, for examples, one used "chr1", the other used "1", I corrected it, and success.

Hi, 
I find the annotation files which have the .sizes and the .bed files. So should I change all the "chr1" from these to "1"? And I think my index is based on "1". Thank you!

**Comment by Bonnie19920126** [comment]
> > > I meet the same problem. Can tell me how to solve it? Thank you!
> > 
> > 
> > Hi,
> > Because of the annotation files I used is inconsistent, for examples, one used "chr1", the other used "1", I corrected it, and success.
> 
> Hi,
> I find the annotation files which have the .sizes and the .bed files. So should I change all the "chr1" from these to "1"? And I think my index is based on "1". Thank you!

Yes, if your index is based on "1,2,3...", you should change the annotation files, make them consistent.
