### ISSUE TITLE
merging from 64 files and 8 in-memory blocks...

### ISSUE THREAD

**Issue by Bonnie19920126** [nservant/HiC-Pro#212]
Hi, thank you for your Hi-C pro program. when I run it with 33 samples (4T in total), I get the error, 
Mon Dec  3 03:01:18 CST 2018
Combine R1/R2 alignment files ...
Logs: logs/in_situ_GM12878/mapping_combine.log
/var/spool/torque/mom_priv/jobs/45728-1.admin.biocc.SC: line 12:  5046 Bus error               (core dumped) make --file /pub2/lixin/software/HiC-Pro/HiC-Pro-install/HiC-Pro_2.11.2-beta/scripts/Makefile CONFIG_FILE=/bioNSW/lixin/causal-lncRNA/Hi-C/Hi-C_Pro/in_situ_GM12878/config_GM12878.txt CONFIG_SYS=/pub2/lixin/software/HiC-Pro/HiC-Pro-install/HiC-Pro_2.11.2-beta/config-system.txt all_sub 2>&1,

This is my log file:
[bam_sort_core] merging from 64 files and 8 in-memory blocks...
[bam_sort_core] merging from 64 files and 8 in-memory blocks...
/pub2/lixin/software/HiC-Pro/HiC-Pro-install/HiC-Pro_2.11.2-beta/scripts/hic.inc.sh: line 86:  9219 Bus error               (core dumped) /pub2/zhihui/software/samtools-1.8/bin/samtools sort -@ 8 -n -T tmp/SRR1658570_2_Human_GRCh38 -o bowtie_results/bwt2/in_situ_GM12878/SRR1658570_2_Human_GRCh38.bwt2merged.sorted.bam bowtie_results/bwt2/in_situ_GM12878/SRR1658570_2_Human_GRCh38.bwt2merged.bam
/pub2/lixin/software/HiC-Pro/HiC-Pro-install/HiC-Pro_2.11.2-beta/scripts/hic.inc.sh: line 86:  9264 Bus error               (core dumped) /pub2/zhihui/software/samtools-1.8/bin/samtools sort -@ 8 -n -T tmp/SRR1658570_1_Human_GRCh38 -o bowtie_results/bwt2/in_situ_GM12878/SRR1658570_1_Human_GRCh38.bwt2merged.sorted.bam bowtie_results/bwt2/in_situ_GM12878/SRR1658570_1_Human_GRCh38.bwt2merged.bam

I was wondering wheather this problem is related with the limited memory.
Could you give me some suggestions?
Thank you,
Best wishes.

**Comment by nservant** [comment]
Hi,
Yes, this is clearly a samtools memory issue.
The current devel branch of HiC-Pro includes a merge request from @reineckef with a new parameter SORT_RAM, that can be use to set the maximum memory per thread used by samtools.
I think it could be useful in your case !
N
