### ISSUE TITLE
The FRAG_SIZE and INSERT_SIZE parameter

### ISSUE THREAD

**Issue by Bonnie19920126** [nservant/HiC-Pro#214]
Hi,
  I'm not so familiar with the Hi-C experiment. Does anyone know the proper parameter of MIN_FRAG_SIZE, MAX_FRAG_SIZE, MIN_INSERT_SIZE, MAX_INSERT_SIZE. I used the in situ Hi-C data with the 4bp MboI enzyme. I'm afraid to miss some interaction results because I used the default parameter.
 Thank you.
 Best wishes.

**Comment by nservant** [comment]
Hi,
I would suggest to let them blank first ... to be sure that you are not too stringent.
Then, the MIN/MAX_FRAG_SIZE will depend on your restriction enzyme ... but its effect should be very limited.
Regarding the MIN/MAX_INSERT_SIZE, this is just a matter of choice and threshold.
If you run it without any value, you will see the entire insert size distribution, and decide to cut (or not) this distribution.
Best

**Comment by Bonnie19920126** [comment]
Dear Servant,
Thank you!

Best wishes.
