### ISSUE TITLE
number of _1 and _2 file

### ISSUE THREAD

**Issue by sf-nevermore** [nservant/HiC-Pro#215]
Hi,

The initiation of HiC-Pro will check whether the number of _1 and _2 file is matched. I just paste your code here

```
#####################
## Check input files
#####################

if [[ $NEED_FASTQ == 1 ]]; then
    r1files=$(find -L $RAW_DIR -mindepth 2 -maxdepth 2 -name "*.fastq" -o -name "*.fastq.gz" | grep "$PAIR1_EXT" | wc -l)
    r2files=$(find -L $RAW_DIR -mindepth 2 -maxdepth 2 -name "*.fastq" -o -name "*.fastq.gz" | grep "$PAIR2_EXT" | wc -l)
    if [[ "$r1files" != "$r2files" ]]; then
	die "Number of $PAIR1_EXT files is different from $PAIR2_EXT [$r1files vs $r2files]."
    fi
fi
```
My sample folder name is treat_24hr/treat_24hr/*fastq.gz. Every files inside the folder will match _2 files (_24hr) and cause error.

**Comment by nservant** [comment]
Hi,
Indeed ... so far, just change your filenames please.
It's always difficult to deal with such cases and regular expression ... there are always some exceptions ... that's why HiC-Pro check that and return an error.
Best

**Comment by sf-nevermore** [comment]
Sure. Just post here for reference. It did take me awhile to realize what went wrong.

**Comment by sf-nevermore** [comment]
It is like the code

```
die "Number of $PAIR1_EXT files is different from $PAIR2_EXT [$r1files vs $r2files]."
```

"Number of _1 files is different from _2 [8 vs 16]"

I have 8 pairs of _1 _2 files. _1 are all counted as _2 files so "8 vs 16"

**Comment by nservant** [comment]
Ok, I will add an additional warning ;

"Please, note that the paired-end files are detected using the PAIR1_EXT/PAIR2_EXT parameters. Be sure that these extensions can be used to distinguish both file types."

Thanks !

**Comment by sf-nevermore** [comment]
More specific, the input folder name does not match PAIR1_EXT/PAIR2_EXT. Or maybe even output folder name, since when I only changed the input folder name and keeping output folder as "treatment**_2**4hr-output", it terminated after mapping step.
