### ISSUE TITLE
HiC-Pro iced normalization value and heatmap visualization

### ISSUE THREAD

**Issue by pkubgmlixs** [nservant/HiC-Pro#216]
Dear nservant,
After iced normalization of  raw matrix, I found some iced values are as large as 80000+ in 1Mb bin matrix, and its range is even larger than raw matrix. Is this a normal? And I don't know how to do heatmap visualization of this large range values. Should I do transformation of  when do heatmap visualization or  remove extreme large values? Thank you!

**Comment by nservant** [comment]
Hi,
The average signal of iced and raw matrices should be the same (@NelleV can you confirm ?). I guess this is just an outlier region.
Extreme values are usually shrinked during visualization.

**Comment by pkubgmlixs** [comment]
Thanks. And how to do heatmap visualization? Could I just plot a heatmap with iced contact matrix from HiC-Pro output?

**Comment by nservant** [comment]
Yes. You can use higlass, Juicebox or even R to do that.
You have a few tools to convert HiC-Pro outputs to visualization tool inputs in bin/utils/
best

**Comment by pkubgmlixs** [comment]
Many thanks! I will have a try.
