### ISSUE TITLE
question abount fragment_size

### ISSUE THREAD

**Issue by rysterzhu** [nservant/HiC-Pro#217]
I don't understand how the fragment_size calculated in validPairs.
Such as this two record in validPairs:
ST-E00523:391:HL3M2CCXY:7:1114:2970:22774	chrX	3050203	-	chrX	3216781	-	336	HIC_chrX_3	HIC_chrX_250	35	35
ST-E00523:391:HL3M2CCXY:7:1123:32268:60870	chrX	3050215	-	chrX	3216781	-	336	HIC_chrX_3	HIC_chrX_250	36	35
the two restrict fragments are:
chrX	3050105	3050249	HIC_chrX_3	0	+
chrX	3216693	3217167	HIC_chrX_250	0	+
how was the 336 figured out?

**Comment by rysterzhu** [comment]
Thanks for your answer!
Unfortunately that BAM file had been deleted, but I remembered this reads are 2x 150bp.
I check another data which had BAM, but I am still confusing.
##validPair:
SRR7556035.18670774	chr1	3108244	-	chr1	3118973	+	331	HIC_chr1_335	HIC_chr1_370	42	42
##resFragment
chr1	3107993	3108334	HIC_chr1_335	0	+
chr1	3118423	3118982	HIC_chr1_370	0	+
##BAM:
SRR7556035.18670774	83	chr1	3108183	42	125M	=	3118966	0	TTTTTGTTATTCCAGATGAATTTGCAGATTGTTCTTTCTACTTCGTTAAAGAATTGAGTTGGAATTTTGATGAGGATTGCATTGAATCTGTAGATAGCTTTTGGCAAGAAAGCCATTTTTAATGT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBB	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:125	YT:Z:UU	RG:Z:BMG
SRR7556035.18670774	163	chr1	3118966	42	17M	=	3108183	0	GAAGTTTGGAAGTGCCT	BBBBBFFFFFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:17	YT:Z:UU	RG:Z:BML
I'm not sure if the readlength is extract from BAM record?

**Comment by reineckef** [comment]
Using the BAM file coordinates I can still reconstruct the 331 insert size, but the reported locations for R1 and R2 are not clear - these might be the "middle" of the read, maybe? Nicolas could probably recall from coding, or find the code that makes these numbers quickly. 

Here is the math for the BAM and resFragment data for your example:

  | R1 | R2
-- | -- | --
mapped | 3108183 | 3118966
direction | - | +
corrected | 3108308 | 3118966
cut_site | 3107993 | 3118982
distance | 315 | 16
fragment_size | 331 |  

So, the bottom line is, the numbers are correct, but not reproducible from the valid pairs file alone.

**Comment by rysterzhu** [comment]
Yeah, my version exactly uses the middle of read as the read position, and the version is 2.9. It seems that you changed in version 2.11. Thanks a lot, I see how it works.
BTW, I'm not quit sure about MAX_FRAG_SIZE in config. Doesn't fragment_size filt by MAX_FRAG_SIZE? It seems that fragment_size filt by MAX_INSERT_SIZE, isn't it?

**Comment by nservant** [comment]
MIN/MAX_FRAGMENT_SIZE are used to filter restriction fragments. In practice, these values are used when the script loads the BED file of restriction fragments (fragments outside these ranges are not stored).
The MIN/MAX_INSERT_SIZE values are used to filter out read pairs based the distance between the two reads (as previously mentioned).
In the code, I think it's fine (do not hesitate if you see something strange), just that the terms are not always very clear ... for instance, the function get_PE_fragment_size should be renamed in get_PE_insert_size ;)
best

**Comment by rysterzhu** [comment]
Yeah, I just want to make sure of that. That's pretty clear, thank you for your patient answer!
