### ISSUE TITLE
HiC-Pro for BL-HiC 

### ISSUE THREAD

**Issue by TintingLi** [nservant/HiC-Pro#218]
Hi, I recently try to analysis Bridge-linker hic data by HiC-Pro, and found it very inconvenient to deal with the bridge linker sequences. As re-ligation sites of in situ Hi-C is plalindrome, and the sequence is both the same for R1 and R2 (e.g:GATCGATC for MboI), while bridge linkers are not. You have to trim this bridge-linker sequences separately.  Do you have any suggestions for this issue or consideration  to deal with BL-HiC data in future version of HiC-Pro?

**Comment by nservant** [comment]
Hi,
Sorry I'm not very familiar with BL-HiC.
Could you explain me the difference compared to standard in situ Hi-C ?
In you have several bridge linkers sequence, you can simply put them all in the config file (comma separated). Does it answer your need ?
best

**Comment by TintingLi** [comment]
hi,
for in situ hic, the re-ligation site sequences is always the same for both read1 and read2, so you can directly trim the fq files with this sequence (e.g: GATCGATC for MboI). 

For BL-HiC, take  5'ACGCGATATCTTATCTGACT3' (reverse-complementary: 5'TGCGCTATAGAATAGACTGA3') as a bridge-linker example, after the library construction step, both Read1 and read1 all contain 5'ACGCGATATCTTATCTGACT3' and reverse-complementary: 5'TGCGCTATAGAATAGACTGA3' sequences. Now my strategy to deal with these sequences is to use cutadapt to trim these seqeuences tandemly (trim twice), and as a result, the bowtie2 local alignment step become useless.

You mentioned that the bridge-linker sequences can be put in the config file with comma separation, and that seems to be OK to solve this problem.

THX.

**Comment by wbszhu** [comment]
hi,
I wanna know how the bridge-linker sequences can be put in the config file?

Thanks a lot .

**Comment by nservant** [comment]
I think it is in the LIGATION_SITE parameter of the configuration file

**Comment by wbszhu** [comment]
Thanks  for your reply ~
best~
