### ISSUE TITLE
How do I get a valid_bam?

### ISSUE THREAD

**Issue by Guoshuai1314** [nservant/HiC-Pro#219]
Hello!
I got a file, named *.allValidPairs. But I want to get a bam file of valid-pairs. What should I do?
Thank you!

**Comment by nservant** [comment]
Hi,
To do so, set the option GET_PROCESS_SAM to 1.
It will generate a BAM file with all reads and a flag (CT) saying if a read pair is a valid pairs or not.
You can just filter the BAM file keeping the reads with a flag to 'VI'
Best

**Comment by Guoshuai1314** [comment]
Many thanks! I will have a try.

**Comment by tinyhys** [comment]
> Hi,
> To do so, set the option GET_PROCESS_SAM to 1.
> It will generate a BAM file with all reads and a flag (CT) saying if a read pair is a valid pairs or not.
> You can just filter the BAM file keeping the reads with a flag to 'VI'
> Best

Hi dear Senior, 
I wanna know whether I can simply samtools view  bwt2pairs_interaction.bam | grep the "VI" tag to obtain the valid_bam file or not ? 
If you know about the ALLHiC pipeline #https://github.com/tangerzhang/ALLHiC/wiki#, could you please give me some suggestion if it is fine to use the valid_bam as the prunning.bam and the bwt2pairs_interaction.bam as sample.clean.bam?
Looking forward to your reply！ best wishes!

**Comment by nservant** [comment]
Hi
Yes, you can indeed create a bam file with valid pairs as you said.
I'm sorry, but I never used the ALLHIC pipeline, so I'm afraid I cannot be really helpful.
Best

**Comment by tinyhys** [comment]
> Hi
> Yes, you can indeed create a bam file with valid pairs as you said.
> I'm sorry, but I never used the ALLHIC pipeline, so I'm afraid I cannot be really helpful.
> Best

Many thanks to your reply! I will have a try ~

**Comment by StevenBai97** [comment]
> > Hi
> > Yes, you can indeed create a bam file with valid pairs as you said.
> > I'm sorry, but I never used the ALLHIC pipeline, so I'm afraid I cannot be really helpful.
> > Best
> 
> Many thanks to your reply! I will have a try ~

Hi
I also met the same problem when using HiC-Pro and AllHiC. According to your experience, whether bwt2pairs_interaction.bam can be used as the sample.clean.bam or not?

**Comment by nservant** [comment]
you should first filter the bam file to keep on the valid interaction. You can use the VI flag for that.
N

**Comment by StevenBai97** [comment]
> you should first filter the bam file to keep on the valid interaction. You can use the VI flag for that.
> N

 Excuse me. How to use the VI flag for filtering?

**Comment by nservant** [comment]
```
samtools view MY_FILEbwt2pairs_interaction.bam | grep "CT:Z:VI" 
```

**Comment by StevenBai97** [comment]
> ```
> samtools view MY_FILEbwt2pairs_interaction.bam | grep "CT:Z:VI" 
> ```

Thanks a lot for your timely reply and advice. I will have a try.
