### ISSUE TITLE
hicpro2juicebox    Error creating main window  No X11 DISPLAY variable was set, but this program performed an operation which requires it.

### ISSUE THREAD

**Issue by pkubgmlixs** [nservant/HiC-Pro#220]
When I ran hicpro2juicebox.sh  script, I got an 'No X11' error  shown as below. And does anyone know how to solve this kind of error?  Thank you very much!
my commad is " ./hicpro2juicebox.sh   -i HiC_merged.allValidPairs  -g chrom_hg19.sizes   -j Juicebox_1.9.8.jar   -r HindIII_resfrag_hg19.bed  -t tmp/ -o output/  2>HiC_merged.hicpro2juicebox.err  1>HiC_merged.hicpro2juicebox.log "

**Error creating main window 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
Exception in thread "main" java.lang.NullPointerException
        at juicebox.MainWindow.main(MainWindow.java:116)**

**Comment by nservant** [comment]
Hi,
I think the jar file you provided is the Juicebox visualisation tool !
The hicpro2Juicebox script needs the Juicer Toolbox jar file, not the visualization tool.
https://github.com/aidenlab/juicer/wiki/Juicer-Tools-Quick-Start
Best

**Comment by pkubgmlixs** [comment]
Many thanks！I have solved this problem! 

2019-01-12 

李向上 



发件人：Nicolas Servant <notifications@github.com>
发送时间：2019-01-11 21:39
主题：Re: [nservant/HiC-Pro] hicpro2juicebox Error creating main window No X11 DISPLAY variable was set, but this program performed an operation which requires it. (#220)
收件人："nservant/HiC-Pro"<HiC-Pro@noreply.github.com>
抄送："upleee"<17854201145@163.com>,"Author"<author@noreply.github.com>

Hi,
I think the jar file you provided is the Juicebox visualisation tool !
The hicpro2Juicebox script needs the Juicer Toolbox jar file, not the visualization tool.
https://github.com/aidenlab/juicer/wiki/Juicer-Tools-Quick-Start
Best
