### ISSUE TITLE
warning: gensub: third argument `sample1/sample1_R1.fastq.gz' treated as 1

### ISSUE THREAD

**Issue by jfass** [nservant/HiC-Pro#227]
I'm trying to run a parallel analysis on SLURM, and I keep getting this:

$ cat slurm-27423597_1.out 
--------------------------------------------
Sat Feb 23 18:25:35 PST 2019
Bowtie2 alignment step1 ...
awk: cmd. line:1: (FILENAME=- FNR=1) warning: gensub: third argument `sample1/sample1_R1.fastq.gz' treated as 1
Logs: logs/sample1/mapping_step1.log
Exit: Error in reads alignment - Exit
/share/biocore/projects/[redacted]/[redacted]/20-HiCPro/HiC-Pro-2.11.1/scripts/Makefile:85: recipe for target 'bowtie_global' failed
make: *** [bowtie_global] Error 1

I'm no awk-ster, but some googling reveals that gensub (the one on line 198 in hic.inc.sh) is supposed to take four arguments, not three. The third argument (which in this case is the fastq file's path underneath the raw data directory) is supposed to be "g" or the number of replacements to make ... so it's saying that it's treating the file path (string) as a value of 1. I think. Then maybe it fails because it doesn't see the 4th argument?

**Comment by jfass** [comment]
Retracted!

The actual problem turned out to be that I was using symbolic links for the raw data files, *and* I'd created the links incorrectly. This showed up as a "cannot stat" (file) error when I switched to running HiC-Pro in serial, rather than through SLURM. Once I fixed the links I went back to submit the SLURM jobs, and they're running.

**Comment by ckntav** [comment]
Hello,

I installed HiC-Pro on a cluster (SLURM) and splitted my fastq file in order to run a parallel analysis.
Even if it seems to work well (at least for the step1), I'm concern because I am getting that message in all the log.
Particularly the line saying that: **awk: ligne de commande:1: (FILENAME=- FNR=11) avertissement : gensub : le 3e argument « myHiCSample_rep1_1/10_myHiCSample_rep1_1_R1.fastq » sera traité comme un 1**

Do you have an idea of what is going on? According to the log file, do all the steps perform as expected?

Here is an example of the 10th chunk of the log file:

--------------------------------------------
mar déc 22 22:07:25 EST 2020
Bowtie2 alignment step1 ...
awk: ligne de commande:1: (FILENAME=- FNR=11) avertissement : gensub : le 3e argument « myHiCSample_rep1_1/10_myHiCSample_rep1_1_R1.fastq » sera traité comme un 1
Logs: logs/myHiCSample_rep1_1/mapping_step1.log
```

--------------------------------------------
mer déc 23 00:02:43 EST 2020
Bowtie2 alignment step2 ...

--------------------------------------------
mer déc 23 00:02:43 EST 2020
Combine R1/R2 alignment files ...
awk: ligne de commande:1: (FILENAME=- FNR=11) avertissement : gensub : le 3e argument « myHiCSample_rep1_1/10_myHiCSample_rep1_1_R1.fastq » sera traité comme un 1
Logs: logs/myHiCSample_rep1_1/mapping_combine.log

--------------------------------------------
mer déc 23 00:02:44 EST 2020
Mapping statistics for R1 and R2 tags ...
awk: ligne de commande:1: (FILENAME=- FNR=11) avertissement : gensub : le 3e argument « myHiCSample_rep1_1/10_myHiCSample_rep1_1_R1.fastq » sera traité comme un 1
Logs: logs/myHiCSample_rep1_1/mapping_stats.log

--------------------------------------------
mer déc 23 00:03:10 EST 2020
Pairing of R1 and R2 tags ...
awk: ligne de commande:1: (FILENAME=- FNR=11) avertissement : gensub : le 3e argument « myHiCSample_rep1_1/10_myHiCSample_rep1_1_R1.fastq » sera traité comme un 1
Logs: logs/myHiCSample_rep1_1/mergeSAM.log

--------------------------------------------
mer déc 23 00:05:28 EST 2020
Assign alignments to restriction fragments ...
awk: ligne de commande:1: (FILENAME=- FNR=11) avertissement : gensub : le 3e argument « myHiCSample_rep1_1/10_myHiCSample_rep1_1_R1.fastq » sera traité comme un 1
Logs: logs/myHiCSample_rep1_1/mapped_2hic_fragments.log

```

**Comment by ckntav** [comment]
I figured out that I tested the parallel implementation last week with the test data. We can see that the error message also appears here.
```
cat slurm-14466832_1.out 
--------------------------------------------
jeu déc 17 11:45:50 EST 2020
Bowtie2 alignment step1 ...
awk: ligne de commande:1: (FILENAME=- FNR=1) avertissement : gensub : le 3e argument « dixon_2M_2/SRR400264_01_R1.fastq.gz » sera traité comme un 1
Logs: logs/dixon_2M_2/mapping_step1.log

--------------------------------------------
jeu déc 17 11:47:05 EST 2020
Bowtie2 alignment step2 ...
awk: ligne de commande:1: (FILENAME=- FNR=1) avertissement : gensub : le 3e argument « dixon_2M_2/SRR400264_01_R1.fastq.gz » sera traité comme un 1
Logs: logs/dixon_2M_2/mapping_step2.log

--------------------------------------------
jeu déc 17 11:47:22 EST 2020
Combine R1/R2 alignment files ...
awk: ligne de commande:1: (FILENAME=- FNR=1) avertissement : gensub : le 3e argument « dixon_2M_2/SRR400264_01_R1.fastq.gz » sera traité comme un 1
Logs: logs/dixon_2M_2/mapping_combine.log

--------------------------------------------
jeu déc 17 11:47:41 EST 2020
Mapping statistics for R1 and R2 tags ...
awk: ligne de commande:1: (FILENAME=- FNR=1) avertissement : gensub : le 3e argument « dixon_2M_2/SRR400264_01_R1.fastq.gz » sera traité comme un 1
Logs: logs/dixon_2M_2/mapping_stats.log

--------------------------------------------
jeu déc 17 11:47:42 EST 2020
Pairing of R1 and R2 tags ...
awk: ligne de commande:1: (FILENAME=- FNR=1) avertissement : gensub : le 3e argument « dixon_2M_2/SRR400264_01_R1.fastq.gz » sera traité comme un 1
Logs: logs/dixon_2M_2/mergeSAM.log

--------------------------------------------
jeu déc 17 11:47:55 EST 2020
Assign alignments to restriction fragments ...
awk: ligne de commande:1: (FILENAME=- FNR=1) avertissement : gensub : le 3e argument « dixon_2M_2/SRR400264_01_R1.fastq.gz » sera traité comme un 1
Logs: logs/dixon_2M_2/mapped_2hic_fragments.log
```

According to the matrix output files (in hic_results/matrix), do those files seem to be as expected?
```
tree --du -h
.
├── [4.1M]  dixon_2M
│   ├── [2.4M]  iced
│   │   ├── [1.1M]  1000000
│   │   │   ├── [1007K]  dixon_2M_1000000_iced.matrix
│   │   │   └── [ 70K]  dixon_2M_1000000_iced.matrix.biases
│   │   └── [1.3M]  500000
│   │       ├── [1.2M]  dixon_2M_500000_iced.matrix
│   │       └── [139K]  dixon_2M_500000_iced.matrix.biases
│   └── [1.7M]  raw
│       ├── [734K]  1000000
│       │   ├── [ 87K]  dixon_2M_1000000_abs.bed
│       │   └── [623K]  dixon_2M_1000000.matrix
│       └── [953K]  500000
│           ├── [174K]  dixon_2M_500000_abs.bed
│           └── [754K]  dixon_2M_500000.matrix
└── [4.1M]  dixon_2M_2
    ├── [2.4M]  iced
    │   ├── [1.1M]  1000000
    │   │   ├── [1008K]  dixon_2M_2_1000000_iced.matrix
    │   │   └── [ 70K]  dixon_2M_2_1000000_iced.matrix.biases
    │   └── [1.3M]  500000
    │       ├── [1.2M]  dixon_2M_2_500000_iced.matrix
    │       └── [140K]  dixon_2M_2_500000_iced.matrix.biases
    └── [1.7M]  raw
        ├── [735K]  1000000
        │   ├── [ 87K]  dixon_2M_2_1000000_abs.bed
        │   └── [623K]  dixon_2M_2_1000000.matrix
        └── [956K]  500000
            ├── [174K]  dixon_2M_2_500000_abs.bed
            └── [757K]  dixon_2M_2_500000.matrix
```

Thank you

**Comment by varunkas** [comment]
I also get the same error. Is there any update? Thanks so much!
