### ISSUE TITLE
INFO:hicmatrix.HiCMatrix:Only init object, no matrix given.

### ISSUE THREAD

**Issue by abhisheksinghnl** [nservant/HiC-Pro#229]
Hi,

I have used following command to generate Hi-C matrix but it fails to give a matrix. However, the bam file is generated.

 qig hicBuildMatrix --samFiles file7.bam file8.bam --QCfolder hicU1 -bs 30000 --dangling GATC  --outBam U1.bam --minDistance 300 --maxLibraryInsertSize 1000 --restrictionSequence GATC --danglingSequence GATC --outFileName Matrix.HiC.U1 --minMappingQuality 5 --skipDuplicationCheck --threads 15 -ze hicU1.err -zmem 700G -zslot 15 -za

As the run was having memory issues, I had opted for the option --skipDuplicationCheck.

This lead to no interruptions but couldn't generate the matrix. Could anyone let me know, what is going wrong, here.

**Comment by nservant** [comment]
Hi,
I think this is a hiCexplorer command, not HiC-Pro ;)
