### ISSUE TITLE
Singularity Container Error: ICE Normalization

### ISSUE THREAD

**Issue by HollyRuess** [nservant/HiC-Pro#231]
I have to run the singularity container in an interactive session. 
singularity exec --contain --cleanenv -B /project /project/hicpro/hicpro-2.11.1.simg HiC-Pro -i /project/data/ -o /project/output_030719 -c /project/config-hicpro.txt

I get the following error:
Run ICE Normalization ...
Logs: logs/rep1/ice_20000.log
/usr/local/bin/HiC-Pro_2.11.1/bin/../scripts//Makefile:191: recipe for target 'ice_norm' failed
make: *** [ice_norm] Error 1

The log file states:
/usr/local/anaconda/bin/python /usr/local/bin/HiC-Pro_2.11.1/scripts/ice --results_filename hic_results/matrix/rep1/iced/20000/rep1_20000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 
0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 --verbose 1 hic_results/matrix//rep1/raw/20000/rep1_20000.matrix
Traceback (most recent call last):
  File "/usr/local/bin/HiC-Pro_2.11.1/scripts/ice", line 8, in <module>
    import iced
ImportError: No module named iced

We then looked for iced in the container
$ singularity shell /project/hicpro/hicpro-2.11.1.simg
~> python
>>> import iced
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named iced

**Comment by GitHub-Lujianjun** [comment]
I also have the  same question，Does anyone knows  how to fix it?
Many thanks！

**Comment by nservant** [comment]
Indeed ! let me check that and come back to you
N

**Comment by nservant** [comment]
Actually iced is installed in the root local python dir ... I think that's why it does not work 
I'll check why it is not installed in the global python dir ...
I'll come back to you
N

**Comment by GitHub-Lujianjun** [comment]
I re-installed iced  manually，the same error appeared，program failed in the last process  normalization.

**Comment by nservant** [comment]
Hi guys,
I made a few changes on the Singularity image to try to fix this.
I put here a new image ;
http://zerkalo.curie.fr/partage/HiC-Pro/singularity_images/hicpro_devel_ubuntu.img
And the devel branch of HiC-Pro has been updated accordingly.

Usage this image, if you do a 
```
singularity exec hicpro_devel_ubuntu.img python
>> import iced
```
It should work, meaning that iced is well installed and can be loaded.
Previously, iced was installed on the home of the 'root' user, so was able to be run only by root.
It should be better now.
Let me know !
N

**Comment by HollyRuess** [comment]
This new container completes without any errors, and the files are as expected. I still need to run a downstream analysis. Thanks!

**Comment by nservant** [comment]
Great. I still have a couple of issues for Singularity usage ... mainly to use it on a cluster in parallel mode.
i'll keep investigating this part in the coming weeks
N

**Comment by GitHub-Lujianjun** [comment]
Dear N:
Several questions about the new container you updated  as fellowing:
While download  hicpro_devel_ubuntu.img (nearly 3.2Gb),am I need to re-installed Hic-Pro？ or type  "singularity exec hicpro_devel_ubuntu.img python >> import iced" to exec it directly ? I alleardly tried the latter , but it took me a lot of time to exec it and failed finally.Just generated a file named import,Was my command wrong?
Need more kindly help.
Many thanks.

**Comment by nservant** [comment]
Hi,
The idea of Singularity is that you have nothing to install ... it provides a full image of the software and its dependencies.
Basically, `singularity exec hicpro_devel_ubuntu.img MY_COMMAND` is just a way to execute a command which is within the Singularity image.
If you already have part of the data such as the .allValidPairs files for instance, you should be able to run HiC-Pro in stepwise mode, with something like ;
` singularity exec hicpro_devel_ubuntu.img HiC-Pro \
-i FLODER_TO_VALIDPAIRS
-o OUTPUT
-c CONFIG
-s build_contact_maps -s ice_norm`
Hope it helps
Nicolas

**Comment by yzhang250** [comment]
Hi N,

Just a quick question, why is the hicpro_devel_ubuntu so much larger than the latest image?
