### ISSUE TITLE
row index exceeds matrix dimensions

### ISSUE THREAD

**Issue by QianzhaoJ** [nservant/HiC-Pro#232]
Hi：
   I  have extracted cis-interactions from **ValidPairs** 
  `awk -vOFS="\t" '{if($2 = $5) print $0}' $all > $cis`
   and  randomly sampled a given number of read pairs
  `shuf $cis -n $num -o $resample_cis`
   then I run HiC-Pro by adding "`-s build_contact_maps  -s ice_norm` " . It worked .
   But ,I found  that the **matrix** file didn't match the **bed** file , such as
> tail $matrix
77404	92414	3
77404	92415	2
77404	92417	1
77404	92421	3
77404	92422	2
77404	92423	1
77404	92424	1
77404	92436	1
77404	92440	1
77404	92442	2

> tail $bed
chrY	59040000	59080000	77395
chrY	59080000	59120000	77396
chrY	59120000	59160000	77397
chrY	59160000	59200000	77398
chrY	59200000	59240000	77399
chrY	59240000	59280000	77400
chrY	59280000	59320000	77401
chrY	59320000	59360000	77402
chrY	59360000	59373566	77403
chrM	0	16571	77404

and the **resample_cis** 
ST-E00144:688:HJFGVCCXY:6:1114:13250:57073	chr7	7567683	-	chr7	7627185	-	438	HIC_chr7_21203	HIC_chr7_21368	42	42
ST-E00144:688:HJFGVCCXY:4:2221:19674:49285	chr4	166197305	+	chr4	166197658	-	389	HIC_chr4_380398	HIC_chr4_380400	39	40
ST-E00192:610:HHVFHCCXY:5:2123:21704:11875	chr9	94271500	+	chr9	94385670	+	557	HIC_chr9_179433	HIC_chr9_179698	42	42
ST-E00142:625:HK73NCCXY:4:2204:27864:61011	chr6	162333756	+	chr6	162465015	-	376	HIC_chr6_386443	HIC_chr6_386806	42	42

I'm confused about it ,Can you give me some advice ?

**Comment by nservant** [comment]
Hi,
That's strange indeed ...
Without the reshuffling, do you have the same issue ?

I think there is an error in your first awk line
$2 = $5
should be 
$2 == $5

What does the 'shuf' command is doing ? Are you shuffling chromosome name and read position ?

**Comment by QianzhaoJ** [comment]
Hi :
    Thanks for your notice ! What a stupid mistake  I made !
    The mistake is due to the error in my first awk line and you are right ! 
    **shuf** is a command in linux which can write a random permutation of the input lines to standard output .
    Thanks for your help again !

Best wishes

**Comment by nservant** [comment]
ok. So that's fix the issue ??

**Comment by QianzhaoJ** [comment]
Yes!
