### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by cyz0315** [nservant/HiC-Pro#235]
Hi,
I tried to install HiC-pro using Anaconda simulation environment of python 2.7.15.
However, after installing pysam, all the modules cannot be imported. 

All the commands are as follows:
conda create -n HiC_pro_python2 python=2.7
source activate HiC-pro
conda install numpy
conda install scipy
conda install bx-python
conda install pysam
then I changed the path in config-install 
make configure

The error report is as follow:
make -f ./scripts/install/Makefile CONFIG_SYS=./config-install.txt
make[1]: Entering directory `/home/cheyizhuo/HiC_software/HiC_pro/HiC-Pro-master'
./scripts/install/install_dependencies.sh -c ./config-install.txt -o  /home/cheyizhuo/HiC_software/HiC_pro/HiC-Pro_2.11.1 -q
Make sure internet connection works for your shell prompt under current user's privilege ...
Starting HiC-Pro installation ...
export ~/anaconda3/envs/HiC_pro_python2/bin/bowtie2 in PATH
export ~/anaconda3/envs/HiC_pro_python2/bin/samtools in PATH
export /home/cheyizhuo/anaconda3/bin/R in PATH
export ~/anaconda3/envs/HiC_pro_python2/bin/python in PATH
Checking dependencies ... 
Checking Python libraries ...
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "../scripts/install/check_pythonlib.py", line 29, in <module>
    raise ImportError('Error - bx-python cannot be imported')  
ImportError: Error - bx-python cannot be imported
Can not proceed without the required Python libraries, please install them and re-run
make[1]: *** [configure] Error 1
make[1]: Leaving directory `/home/cheyizhuo/HiC_software/HiC_pro/HiC-Pro-master'
make: *** [configure] Error 2

The path is correct. The problem is brought by pysam. Because when I recreate a new environment, every modules can be imported before installing pysam. But they all failed after the installation of pysam.

How can I fix this bug?
Thanks a lot!

**Comment by nservant** [comment]
I'm sorry but I'm clearly not an expert of conda.
There is a Singularity image that you can use if you want ...
N
