### ISSUE TITLE
Can not run step by step

### ISSUE THREAD

**Issue by woshi0655** [nservant/HiC-Pro#236]
Hi , I had a lot of problem when I run the HIC-Pro. 
First, when I run the soft, everything seem OK, but the * .mapstat file  show R2 predix in the R1 .mapstat; and this cause fail to plot at last.
Second, then I want to run the HiC-Pro step by step, like the quality control(I try to change the R2 to R1 in the R1.mapstat file). But this just finish in 3 seconds, them I got nothing. 
Third, I rerun the same command as before, but I cannot even go futher then the first time. Got error like `bowtie_results/bwt2/data/PUB25_R1_Vpgenome.fasta.bwt2merged.sorted.bam': No such file or directory"" and "[W::bam_hdr_read] EOF marker is absent. The input is probably truncated" .

I really do not know what happened, hope you can help me!

**Comment by nservant** [comment]
Hi,
Could you give me;
- the HiC-Pro version
- command line
- configuration file
- input data organization
Best

**Comment by woshi0655** [comment]
Hi, 


   Thank you for your reply, I have figured out the problem now. Thank you!


Wolf










在 2019-04-11 17:46:07，"Nicolas Servant" <notifications@github.com> 写道：


Hi,
Could you give me;

the HiC-Pro version
command line
configuration file
input data organization
Best
