### ISSUE TITLE
R version: always R 3.5.0

### ISSUE THREAD

**Issue by zyqfrog10** [nservant/HiC-Pro#238]
Hi, 

Is R version hard wired into the pipeline? I've been trying to load other version of R that has ggplot2 installed on our cluster. But with automatically running the pipeline, it always uses R 3.5.0.  Is there an easy way to customize the process? Thanks.

Ying

**Comment by nservant** [comment]
Hi,
The paths are written in the config-system.txt file within the installation folder.
You can edit it, and change the R path

**Comment by zyqfrog10** [comment]
Found it. Thank you very much!
