### ISSUE TITLE
Capture target clarification

### ISSUE THREAD

**Issue by zyqfrog10** [nservant/HiC-Pro#244]
Hello,

I have a naive question/request for clarification. I can see we need to provide target regions.
"[CAPTURE_TARGET] | BED file of target regions to focus on (mainly used for capture Hi-C data)" 
Are the "target regions" targeted restriction fragments or the baits/probes positions? 
Thank you.
Ada

**Comment by nservant** [comment]
Hi Ada,
Actually, it is quite flexible. The idea is that only interactions involving these regions will be kept in the final output.
For instance, for capture-C analysis (ie. 4C like), I usually put in the BED the position of the restriction fragments. However for capture Hi-C (5C like), I'm just putting the ranges of the whole genomic regions (so a few Mb).
Hope it helps
Nicolas

**Comment by zyqfrog10** [comment]
Thanks for the timely response, Nicolas! That clears my confusion. Appreciated!
Ada
