### ISSUE TITLE
.bwt2paris_interaction.sam: contain valid pairs only or all pairs?

### ISSUE THREAD

**Issue by zyqfrog10** [nservant/HiC-Pro#245]
Hi Nicolas,

Are SAM files in hic_results/data/sample/*.bwt2paris_interaction.sam contain only valid pairs or all pairs (RE, SC, Single, DE, Dump and valid)?
Thanks.
Ada

**Comment by nservant** [comment]
Hi Ada,
Sorry for the delay ! all pairs.
Each pair type has a flag (RE, SC, Single, etc) in order to easily manage them, and color them on browser such as IGV.
N
