### ISSUE TITLE
hicpro2juicebox

### ISSUE THREAD

**Issue by nservant** [nservant/HiC-Pro#246]
But when I was trying to convert .allValidPairs using hicpro2juicebox.sh 
I got an error message:
Error : unknown format -  detected, whereas 8 (< v2.7.6) or 12 (> v2.7.5) fields are expected !
So I removed the last column (having allele information 0-1, 1-2 and so on) from the .allValidPairs files to make it 12 column file. I just wanted to know if its correct remove the last column and run the script or am I doing something wrong. Also Is there any way to use the file as it is without removing anything so that so that we can use maternal paternal information during visualization of .hic files.

**Comment by rcorces** [comment]
Just ran into this same issue myself and also fixed it by removing the last column. Would be great to see this one fixed in the next release.

**Comment by zyqfrog10** [comment]
In the hicpro2juicebox.sh code, the following lines require the format to be either 8 or 12
```
if [[ $nbfields == "12" ]]; then
    echo -e "HiC-Pro format > 2.7.5 detected ..."

elif [[ $nbfields == "8" ]]; then
    echo -e "HiC-Pro format < 2.7.6 detected ..."
    echo -e "Adjusting AllValidPairs format ..."
    awk '{OFS="\t"; print $0,0,1,42,42}' $VALIDPAIRS > ${TEMP}/$$_format_AllValidPairs
    VALIDPAIRS=${TEMP}/$$_format_AllValidPairs

else
    echo -e "Error : unknown format - $nbfields detected, whereas 8 (< v2.7.6) or 12 (> v2.7.5) fields are expected !"
    exit 1
fi
```

I think if the 13th column is merely the allele information and you don't want to separate the allelic .hic, may change the first line above to be  ```f [[ $nbfields == "12" || $nbfields == "13" ]]```. But if you want to obtain individual allelic .hic, it would be preferably to divide the .allValidPairs file into separate alleles first. Just a thought.

**Comment by zyqfrog10** [comment]
I ran into memory issue when transforming large .allValidPairs. Then I modified the 'awk' lines for reforming .allValidPairs at the sorting step,
```
awk '{$4=$4!="+"; $7=$7!="+"; n1=split($9, frag1, "_"); n2=split($10, frag2, "_"); } $2<=$5{print $1, $4, $2, $3, frag1[n1], $7, $5, $6, frag2[n2], $11, $12 }$5<$2{ print $1, $7, $5, $6, frag2[n2], $4, $2, $3, frag1[n1], $12, $11}' $VALIDPAIRS | LANG=C sort -T ${TEMP} -k3,3d -k7,7d -S 400M --parallel=4 --compress-program=gzip | gzip > ${TEMP}/$$_allValidPairs.pre_juicebox_sorted.gz
``` 
and 
```
awk '{$4=$4!="+"; $7=$7!="+"} $2<=$5{print $1, $4, $2, $3, 0, $7, $5, $6, 1, $11, $12 }$5<$2{ print $1, $7, $5, $6, 0, $4, $2, $3, 1, $12, $11 }' $VALIDPAIRS | LANG=C sort -T ${TEMP} -k3,3d  -k7,7d -S 400 --parallel=4 --compress-program=gzip | gzip > ${TEMP}/$$_allValidPairs.pre_juicebox_sorted.gz
```
But for ~6GB $$_allValidPairs.pre_juicebox_sorted.gz, juicer_tools ran into memory shortage too. 
May add some specifications at the juicer_tools pre line,
```
java -Xmx16g -jar ${JUICERJAR} pre -f ${TEMP}/$$_resfrag.juicebox ${TEMP}/$$_allValidPairs.pre_juicebox_sorted.gz ${OUTPUTFILE} ${GENOME}
```
Note, genome size didn't work for (I am using juicer_tools_1.11.09_jcuda.0.8.jar for HiCPro v2.11.1 output) so I set the genome ID instead.
So far the above modifications worked for me. 
Any better idea? THX.
