### ISSUE TITLE
make_lsf_script bug: #PBS -n in s2

### ISSUE THREAD

**Issue by zyqfrog10** [nservant/HiC-Pro#250]
Hi @nservant ,

I just switched to the v2.11.1 and started some test runs.
There is small bug in the "make_lsf_script.sh". 
"PPN=$(( ${N_CPU} * 2))" has been deleted in this version but it hasn't been updated for "lsf_script_s2" header generation.
Would you please update that?
Thank you very much for developing and maintaining HiC-Pro.
Ada

**Comment by nservant** [comment]
Hi,
Just to be sure, you mean simply replacing 
`#BSUB -n ${PPN}`
by
`#BSUB -n ${N_CPU}`
is that correct ?
Thanks

**Comment by zyqfrog10** [comment]
That's right, since ${PPN} is no longer set in v2.11.1. 
Thanks.
