### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by tlenz001** [nservant/HiC-Pro#253]
While attempting to install HiC-Pro I am receiving an error. I've read several posts that allude to this error but none of these solve my issue. Here is my complete output from download to installation:

guest-5-3-10-28-138-126:~ tlenz$ git clone https://github.com/nservant/HiC-Pro.git
Cloning into 'HiC-Pro'...
remote: Enumerating objects: 3486, done.
remote: Total 3486 (delta 0), reused 0 (delta 0), pack-reused 3486
Receiving objects: 100% (3486/3486), 46.93 MiB | 5.72 MiB/s, done.
Resolving deltas: 100% (2211/2211), done.
guest-5-3-10-28-138-126:~ tlenz$ cd hic-pro
guest-5-3-10-28-138-126:hic-pro tlenz$ make configure
make -f ./scripts/install/Makefile CONFIG_SYS=./config-install.txt
./scripts/install/install_dependencies.sh -c ./config-install.txt -o  /usr/local/bin/HiC-Pro_2.11.1 -q
Make sure internet connection works for your shell prompt under current user's privilege ...
Starting HiC-Pro installation ...
Checking dependencies ... 
Checking Python libraries ...
The required Python libraries appear to be already installed. 
Checking R installation ...
The required R packages appear to be already installed. 
Bowtie2 Aligner appears to be already installed. 
Samtools appears to be already installed. 
Dependencies checked !
Check HiC-Pro configuration ... 
Warning : Scheduler system not defined - Default is Torque/PBS
Configuration for TORQUE/PBS system.

guest-5-3-10-28-138-126:hic-pro tlenz$ make install
(g++ -Wall -O2 -std=c++0x -o build_matrix /Users/tlenz/HiC-Pro/scripts/src/build_matrix.cpp; mv build_matrix /Users/tlenz/HiC-Pro/scripts)
/Users/tlenz/HiC-Pro/scripts/src/build_matrix.cpp:249:7: warning: private
      field 'idx' is not used [-Wunused-private-field]
  int idx; // really needed ?
      ^
1 warning generated.
(g++ -Wall -O2 -std=c++0x -o cutsite_trimming /Users/tlenz/HiC-Pro/scripts/src/cutsite_trimming.cpp; mv cutsite_trimming /Users/tlenz/HiC-Pro/scripts)
runner=tlenz

Installing the iced package in --user repository
(cp /Users/tlenz/HiC-Pro/scripts/src/ice_mod/iced/scripts/ice /Users/tlenz/HiC-Pro/scripts; cd /Users/tlenz/HiC-Pro/scripts/src/ice_mod/; /usr/local/bin/python setup.py install --user;)
/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
Warning: Assuming default configuration (iced/utils/{setup_utils,setup}.py was not found)Appending iced.utils configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.utils')
Appending iced.datasets configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.datasets')
non-existing path in 'iced/io': '../src/cblas'
non-existing path in 'iced/io': '../src/cblas'
Appending iced.io configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.io')
non-existing path in 'iced': '../src/cblas'
non-existing path in 'iced': '../src/cblas'
Appending iced configuration to 
Ignoring attempt to set 'name' (from '' to 'iced')
running install
error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
make: *** [iced] Error 1

**Comment by nservant** [comment]
Hi,
It seems that the python installation command failed 
`python setup.py install --user`
Something wrong with the '--user' parameter ???
On which system are you ? could you try as root ?
Best

**Comment by tlenz001** [comment]
I have attempted to install on two separate computers, both running macOS 10.14.5. I tried both running `sudo make install` and enabling root user through the directory utility, neither of which worked.

**Comment by tlenz001** [comment]
I've been searching for answers for the past two weeks and still feel that I am no closer to a solution. I'm still receiving the error shown above. It's getting very frustrating and I could really use any help you can provide.

**Comment by nservant** [comment]
I think the easier for you would be to use the Singularity image.
Did you try that ?

**Comment by tlenz001** [comment]
I went through the tutorial on the Singularity website and used `vagrant ssh` to use the Singularity box. The next part is what is confusing me. Am I supposed to download everything (i.e. /HiC-Pro and hicpro_latest_ubuntu.img) to vagrant so that I can use Singularity from there? So far I just used `vagrant upload` to move everything to there and tried `sudo singularity build hicpro_latest_ubuntu.img HiC-Pro/Singularity` but I'm getting an error:
```
Executing transaction: failed
ERROR conda.core.link:_execute(543): An error occurred while installing package 'conda-forge::ipaddress-1.0.22-py_1'.
LookupError('unknown encoding: string-escape',)
Attempting to roll back.

Rolling back transaction: done

LookupError('unknown encoding: string-escape',)


ABORT: Aborting with RETVAL=255
Cleaning up...
```
I can't find anything on `string-escape` online, nor do I know what that is referring to. If this method is incorrect please tell me. I've never used any program like Singularity or vagrant so any help is appreciated.

**Comment by nservant** [comment]
Hi,
You have two options ; either you try to build your own Singularity image from the Singularity recette available on the HiC-Pro repro, or you can simply download the available pre-build image here :
https://zerkalo.curie.fr/partage/HiC-Pro/singularity_images/hicpro_latest_ubuntu.img
N
