### ISSUE TITLE
hicpro2higlass.sh error

### ISSUE THREAD

**Issue by DoaneAS** [nservant/HiC-Pro#254]
I'm using cooler 0.8.5, and `cooler zoomify` no longer takes the `--no-balance` argument.  Either `--balance` or the default which is no balancing.  The `--no-balance` flag causes an error and the script exits 1.

Also as an enhancement, you may want to let users specify the number of cores used for cooler commands.

thanks

**Comment by nservant** [comment]
ok. Thanks. Will open an issue for that !
