### ISSUE TITLE
multiple ligation sites in HiC-Pro config

### ISSUE THREAD

**Issue by rikrdo89** [nservant/HiC-Pro#255]
Hi, I was reading in the previous issues that HiC-Pro now supports multiple ligation sites in the coinfig files (e.g. for the Arima kit that uses multiple restriction enzymes). What is the formatting for specifying multiple sites in the config file? would a comma without spaces suffice?

**Comment by nservant** [comment]
Yes !

**Comment by nservant** [comment]
Not that the utility digest_genome.py to generate the fragments coordinate is not yet up-to-date, to handle several restriction enzymes. WIll try to do it in the coming weeks !

**Comment by auberginekenobi** [comment]
What would the Arima parameter look like? Given multiple restriction enzymes with motifs ^GATC and G^ANTC, then the parameter looks like
`LIGATION_SITE = GATCGATC,GANTCGANTC`
?

**Comment by nservant** [comment]
Yes, but you should use the devel version 
https://github.com/nservant/HiC-Pro/tree/devel

See also
https://github.com/nservant/HiC-Pro/blob/devel/doc/FAQ.md
