### ISSUE TITLE
plots and colors don't match

### ISSUE THREAD

**Issue by rikrdo89** [nservant/HiC-Pro#257]
The colors in the plots under hic_results/pics/ do not match with the legend-color combination used in the genomebiology paper. Here is an example of my data, bowtie2 reported an alignment rate of almost 90%, whereas the plots seem to indicate it was 10%.
![image](https://user-images.githubusercontent.com/24930604/60270716-f6014f80-98be-11e9-8cb7-10714855ada3.png)

**Comment by nservant** [comment]
Hey !
Could you specify your HiC-Pro, R, and ggplot versions please ?
For info, last HiC-Pro version is not compatible with multiQC.
I kept the R script for backward compatibility, but I would definitely advice to use MultiQC now.
Best

**Comment by rikrdo89** [comment]
HiC-Pro version 2.11.1
R version 3.5.1 (2018-07-02) -- "Feather Spray" 
> packageVersion("ggplot2")                                                                                                                                                                                                                  [1] ‘3.2.0’

**Comment by suipinpin** [comment]
Hi, I also met the same question. Have you succeeded? Thank u

**Comment by suipinpin** [comment]
MultiQC is a good selection!

**Comment by nservant** [comment]
Fixed in devel 2.11.3
