### ISSUE TITLE
Running HiC-Pro on one chromosome

### ISSUE THREAD

**Issue by rikrdo89** [nservant/HiC-Pro#258]
I am doing an exploratory analysis of my data, and I was wondering if HiC-Pro would support using only a subset of my reference genome (say one full chromosome) to avoid using a lot of computational time. Does anyone envision any issues if I were to index one chromosome and use that as the reference for my analysis?

**Comment by nservant** [comment]
Hi,
Good question. There is nothing automatic for that.
I would say, that you can still restrict all your annotations (bed files + index files) to one chromosome.
But it's a bit weird as you will force reads from anywhere on the genome to map on only one chromosome.
Instead, I would prefer to sub-sample the input data, for instance running HiC-Pro on 1M reads.
Best
