### ISSUE TITLE
Link for the test dataset and associated results is unavailable

### ISSUE THREAD

**Issue by lianggong24** [nservant/HiC-Pro#259]
Hello,

I can't download the test dataset through the link provided. Thanks.

Liang

**Comment by nservant** [comment]
Hi,
The wewbsite is still there. This is just that recent browser says that it is not secured.
http://zerkalo.curie.fr/partage/HiC-Pro
Just allow it please !
N

**Comment by lianggong24** [comment]
Hi,

Thanks for your reply. I tried three browsers. Didn't work. Is there any other way I can get the test dataset?

**Comment by nservant** [comment]
https://github.com/nf-core/test-datasets/raw/hic/data/SRR4292758_00_R1.fastq.gz 
https://github.com/nf-core/test-datasets/raw/hic/data/SRR4292758_00_R2.fastq.gz

**Comment by lianggong24** [comment]
Thanks.
