### ISSUE TITLE
ICE Normalization failed

### ISSUE THREAD

**Issue by duyphamuab** [nservant/HiC-Pro#26]
Hi, 

I ran the pipeline and it failed at ICE Normalization step with this error message "cannot find ice". Can you fix? 

Thanks, 
Duy

**Comment by nservant** [comment]
Hi Duy
It looks like the iced package is not well installed or at least not 
installed in the python path that HiCPro is using.
Can you check which python path you put in the config-system.txt file 
please ?
If you simply try ;
 >> python
 >> import iced
Does it work ?
Thanks
Nicolas

**Comment by duyphamuab** [comment]
Hi Nicolas, 
This is the config-system.txt file: 

R_PATH = /usr/bin
BOWTIE2_PATH = /usr/bin
SAMTOOLS_PATH = /usr/bin
PYTHON_PATH = /usr/bin
INSTALL_PATH = /home/duypham/HiCpro_2.7.1
SCRIPTS = /home/duypham/HiC-Pro_2.7.1/scripts
SOURCES = /home/duypham/HiC-Pro_2.7.1/scripts/src
ANNOT_DIR = /home/duypham/HiC-Pro_2.7.1/annotation

When I try to import iced, python couldn't find it. What should I do? 

Thanks, 
Duy

**Comment by nservant** [comment]
if you install iced manually using the /usr/bin/python it should work.
sources are available here  https://github.com/hiclib/iced 
or you can use pip install --user iced
Nicolas

**Comment by duyphamuab** [comment]
Thanks! Duy
