### ISSUE TITLE
[E::bgzf_flush] File write failed (wrong size)

### ISSUE THREAD

**Issue by TypicalSEE** [nservant/HiC-Pro#260]
Hi, I'm using HiC-Pro to process my Hi-C data. But I got this error message during the bowtie global mapping stage:

> [E::bgzf_flush] File write failed (wrong size)
samtools view: writing to standard output failed: Input/output error
samtools view: error closing standard output: -1

What do you think the reason for this error is? I would appreciate it very much if you could help me! Thanks.

**Comment by nservant** [comment]
Hi,
This is a samtools error.
Could you check the mapping logs ? do you have any additional information ?
N

**Comment by TypicalSEE** [comment]
Thanks for your reply. I tried again and HiC-Pro seems to work fine this time. By the way, I'm using samtools 1.9. I'm not sure whether it is about the version of samtools. Anyway, the STDOUT before is like this:

> Run HiC-Pro 2.11.1
>--------------------------------------------
>Wed Jul  3 10:54:08 CST 2019
>Bowtie2 alignment step1 ...
>Logs: logs/Entodon_seductrix/mapping_step1.log
>[E::bgzf_flush] File write failed (wrong size)
>samtools view: writing to standard output failed: Input/output error
>samtools view: error closing standard output: -1

Thanks again. By the way, I have another question: in the HI-C experiment, MboI enzyme was used. So I edited the config.txt and set the LIGATION_SITE to GATC, same as the restriction site of that enzyme. Is that correct? And what is the difference between "restriction site" and "LIGATION_SITE"? Appreciate it very much if you could answer my questions!

**Comment by nservant** [comment]
Hi,
Actually, it depends on your ligation protocol.
Usually, if you cut with GATC, it means that the ligation motif should be GATCGATC ?
If you have a doubt, you can have a quick look at some reads to check whether you find this motif.
Best

**Comment by ZHIDIHUAYUAN** [comment]
Hi,
  I encountered the same problem. 
  The STDOUT is:
Bowtie2 alignment step1 ...
Logs: logs/sample1/mapping_step1.log
[E::bgzf_flush] File write failed (wrong size)
samtools view: writing to standard output failed: No space left on device
[E::bgzf_close] File write failed
samtools view: error closing standard output: -1
[E::bgzf_flush] File write failed (wrong size)
samtools view: writing to standard output failed: No space left on device
[E::bgzf_close] File write failed
samtools view: error closing standard output: -1

The mapping_step1.log is :
`/amber2/users/myzhou/projects/GM12878/HiC/result/01.conda/conda_env/HiC-Pro/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/sample1/SRR6675327_1_bowtie2_hg38_masksnp.bwt2glob.unmap.fastq --rg-id BMG --rg SM:SRR6675327_1 -p 5 -x /amber2/users/myzhou/projects/GM12878/HiC/result/02.HiC-pro/bowtie2_index/bowtie2_hg38_masksnp -U rawdata/sample1/SRR6675327_1.fastq.gz 2>> logs/sample1/SRR6675327_1_bowtie2.log| /amber2/users/myzhou/projects/GM12878/HiC/result/01.conda/conda_env/HiC-Pro/bin/samtools view -F 4 -bS - > bowtie_results/bwt2_global/sample1/SRR6675327_1_bowtie2_hg38_masksnp.bwt2glob.bam
/amber2/users/myzhou/projects/GM12878/HiC/result/01.conda/conda_env/HiC-Pro/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/sample1/SRR6675327_2_bowtie2_hg38_masksnp.bwt2glob.unmap.fastq --rg-id BMG --rg SM:SRR6675327_2 -p 5 -x /amber2/users/myzhou/projects/GM12878/HiC/result/02.HiC-pro/bowtie2_index/bowtie2_hg38_masksnp -U rawdata/sample1/SRR6675327_2.fastq.gz 2>> logs/sample1/SRR6675327_2_bowtie2.log| /amber2/users/myzhou/projects/GM12878/HiC/result/01.conda/conda_env/HiC-Pro/bin/samtools view -F 4 -bS - > bowtie_results/bwt2_global/sample1/SRR6675327_2_bowtie2_hg38_masksnp.bwt2glob.bam`

The code is running . Will this error affect the results？ do I need to re-run？

Thanks
