### ISSUE TITLE
Problems with calling libraries from python

### ISSUE THREAD

**Issue by Rayko87** [nservant/HiC-Pro#261]
Hello all,

I am a postdoc in Columbia University trying to install HiC pro. I dowloaded and installed all the dependencies, but when I try to run the install command 'make configure' in the folder where I unzipped the HiC pro pipeline, I obtained this message:

export /Users/Robert/anaconda3/bin/bowtie2 in PATH export /usr/local/bin/samtools in PATH export /usr/local/bin/R in PATH Checking dependencies ... Checking Python libraries ... Traceback (most recent call last): File "../scripts/install/check_pythonlib.py", line 25, in <module> if vcmp(bx.__version__, '0.5.0') == -1: File "../scripts/install/check_pythonlib.py", line 19, in vcmp return cmp(normalize(version1), normalize(version2)) NameError: name 'cmp' is not defined Can not proceed without the required Python libraries, please install them and re-run

However, if I Install bx-python, this is the message: pip install bx-python Requirement already satisfied: bx-python in /usr/local/lib/python3.7/site-packages (0.8.4) Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from bx-python) (1.12.0) Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (from bx-python) (1.16.4)

So it seems that I have already it installed. Can you help me? May it be that it is installed, but the pipeline is not finding it? I know that many people have had problems to install this pipeline, but I see that they had different problems...

Thanks, Robert

**Comment by nservant** [comment]
Hi, 
HiC-Pro is not yet compatible with python3.
Please, use python2 !
N

**Comment by Rayko87** [comment]
Hello nservant,

Thanks for the fast answer.
However, even if I give the path to the python 2.7, this is what still appears:

bash-3.2$ make configure
make -f ./scripts/install/Makefile CONFIG_SYS=./config-install.txt
./scripts/install/install_dependencies.sh -c ./config-install.txt -o  /usr/local/bin/HiC-Pro_2.11.1 -q
Make sure internet connection works for your shell prompt under current user's privilege ...
Starting HiC-Pro installation ...
export /Users/Robert/anaconda3/bin/bowtie2 in PATH
export /usr/local/bin/samtools in PATH
export /usr/local/bin/R in PATH
export /usr/local/lib/python2.7/ in PATH
Checking dependencies ... 
Checking Python libraries ...
Traceback (most recent call last):
  File "../scripts/install/check_pythonlib.py", line 25, in <module>
    if vcmp(bx.__version__, '0.5.0') == -1:
  File "../scripts/install/check_pythonlib.py", line 19, in vcmp
    return cmp(normalize(version1), normalize(version2))
NameError: name 'cmp' is not defined
Can not proceed without the required Python libraries, please install them and re-run
make[1]: *** [configure] Error 1
make: *** [configure] Error 2

**Comment by nservant** [comment]
Do you have bx installed on your python  ?
If so, could open a python prompt and type 
>> bx.version
thanks

**Comment by Rayko87** [comment]
Sure!

Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 16:24:02) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> bx.version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'bx' is not defined

**Comment by nservant** [comment]
please import de bx python package first, before checking the version number.
N

**Comment by Rayko87** [comment]
Hello again,

Sorry, I am new in Python and I am not sure I am doing it correctly.

In terminal, I write

python2.7 -m pip install bx-python

and it seems it is installed:

Collecting bx-python
  Using cached https://files.pythonhosted.org/packages/02/74/ba10104095bb2c208b6bdf7164674aba07069c22f75da1be22a71364a18f/bx_python-0.8.4-cp27-cp27m-macosx_10_6_intel.whl
Requirement already satisfied: numpy in ./anaconda2/lib/python2.7/site-packages (from bx-python) (1.16.2)
Requirement already satisfied: six in ./anaconda2/lib/python2.7/site-packages (from bx-python) (1.12.0)
Installing collected packages: bx-python
Successfully installed bx-python-0.8.4


However, when I  enter to python2.7 and type: 
 print (help('modules'))

The module bx-python does not appear.

How do I import it? Why it is not installing it? Is it installing it in any other place?

Thanks for your help,
Robert

**Comment by nservant** [comment]
I think that indeed, it is not installed in the right place ...
If you do
>> python
>>> import bx
I guess it does not work ?

**Comment by Rayko87** [comment]
Hello nservant,

If I do python2 
import bx

Nothing happens. No error, nothing. And I try to run the pipeline and still the same message, that I have no bx installed.  

Maybe the problem is that, by default, it reads python3 (the version I have installed with bx?) and I cannot install bx in python2? Is there a way to install bx directly in python2 without using condo installer?

Thanks

**Comment by nservant** [comment]
could you do in the installation folder, and chech the config-system.txt file.
You should find in this file the python path that HiC-Pro is using. Be sure that it points to python2.
N

**Comment by Rayko87** [comment]
Hello again,

In confidence-install, this is my path:

PREFIX =
BOWTIE2_PATH = /Users/Robert/anaconda3/bin/bowtie2
SAMTOOLS_PATH = /usr/local/bin/samtools
R_PATH = /usr/local/bin/R
PYTHON_PATH= /Users/Robert/anaconda2/lib/python2.7
CLUSTER_SYS =

Inside the folder /Users/Robert/anaconda2/lib/python2.7/site-packages, there is the bx folder

What am I doing wrong?

**Comment by nservant** [comment]
I think there is a kind of conflict between your python2.7 and python3 installation.
In theory, the only thing that HiC-Pro is doing is (scripts/install/check_pythonlib.py)

>> /Users/Robert/anaconda2/lib/python2.7/python
>>> import bx.intervals
>>> bx.__version__

If it works in command line, I do not really know why it does not work during the installation ...

**Comment by Rayko87** [comment]
Hi,

The file 

/Users/Robert/anaconda2/lib/python2.7/python

 does not exist. Should the path point where I have the "executable" of python 2.7? IN addition, I do not have the bx.intervals. Is it something from HIC pro?

Thanks,

**Comment by nservant** [comment]
ok. Let's start from scratch.
- Remove your previous HiC-Pro installation.
- Download the latest version
- Edit the config-install.txt and put the path to the program executors (just the path, not the exec itself)
- To be 100% sure, update your PATH variable with the python you want to use
- Run the installation

In your python, you should have the bx.python package installed.
To check that the latter command (`import bx.intervals`) should work.
If you do not have it, please install it 
https://bx-python.readthedocs.io/en/latest/lib/bx.intervals.html

**Comment by Rayko87** [comment]
Hello,

Thanks for the patience. I've done this and it seems that the PATH is correct, because when I change it, the error changes. However, I am still in the same point, when I do make configure:

Checking Python libraries ...
Traceback (most recent call last):
  File "../scripts/install/check_pythonlib.py", line 25, in <module>
    if vcmp(bx.__version__, '0.5.0') == -1:
  File "../scripts/install/check_pythonlib.py", line 19, in vcmp
    return cmp(normalize(version1), normalize(version2))
NameError: name 'cmp' is not defined
Can not proceed without the required Python libraries, please install them and re-run
make[1]: *** [configure] Error 1
make: *** [configure] Error 2

When I do python2, it starts like this:

bash-3.2$ python2.7
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 16:24:02) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin

And inside python, I do:

help("modules")

And appear all the list, but only bx and bx_extras.  When I do import bx.intervals, nothing happens (no problems, but nothing else). Can I install bx.intervals from python2 command line? Is It part from bx?

Thanks,
Robert

**Comment by nservant** [comment]
Hi,
I think you have some conflicts between your python version.
As I told you, HiC-pro does not support python3 so far.
The error 
```
 NameError: name 'cmp' is not defined
```
is generated because the 'cmp' function does not exist in python3 (whereas it does in python2)

Then, for `bx-intervals`, you have to install bx-python package
See https://bx-python.readthedocs.io/en/latest/lib/bx.intervals.intersection.html for details.
N
