### ISSUE TITLE
CPU usage is still double in 2.11.1

### ISSUE THREAD

**Issue by ChenfuShi** [nservant/HiC-Pro#262]
Hi Nicholas,
I have received a complaint from our sysadmins because my jobs were using double the number of CPUs for bowtie. Looking at the bowtie_wrap.sh scripts I see that you set bwt_cpu=$(( $N_CPU / 2 )) but then that variable is not used and instead still uses 
cmd="${BOWTIE2_PATH}/bowtie2 ${BOWTIE2_GLOBAL_OPTIONS} --rg-id BMG --rg SM:${prefix} -p ${N_CPU} -x ${BOWTIE2_IDX} -U ${infile} 2>> ${ldir}/${prefix}_bowtie2.log"
     
This seems to result in calling bowtie with the full number of CPUs

Can you confirm this?
Thanks!

**Comment by nservant** [comment]
Hi,
Which version are you using please ?

**Comment by nservant** [comment]
Thanks. Fixed in devel
