### ISSUE TITLE
hic_qc Error 1 

### ISSUE THREAD

**Issue by bhill-17** [nservant/HiC-Pro#263]
Could someone help me with this error. 

I am having and error with Plot Mapping Portion. R 
In the  plot_mapping_portion.Rout file i get 
error: length(allmapstat_r1) >0 && length(allmapstat_r2) >0 is not true 
execution halted.

**Comment by nservant** [comment]
I think this is not really linked to R, but rather to the whole analysis.
Could you show me the content of the mmapstat files please ?

**Comment by bhill-17** [comment]
[CNL1_R2p_gens_index (copy).mapstat.txt](https://github.com/nservant/HiC-Pro/files/3377939/CNL1_R2p_gens_index.copy.mapstat.txt)
[CNL1_R1p_gens_index (copy).mapstat.txt](https://github.com/nservant/HiC-Pro/files/3377942/CNL1_R1p_gens_index.copy.mapstat.txt)

Here are those files

**Comment by nservant** [comment]
And do you have the other results ? such as .allValidPairs files ? .matrix files ?

**Comment by bhill-17** [comment]
[CNL1_allValidPairs (copy).mergestat.txt](https://github.com/nservant/HiC-Pro/files/3378305/CNL1_allValidPairs.copy.mergestat.txt)
The allValidPairs file was empty and there was only one of them. I have not matrix files at all

**Comment by nservant** [comment]
ok. So it does not run properly.
Could you show me 
- your command line
- how your input data are organized
- your config please

**Comment by bhill-17** [comment]
[config-hicpro.txt](https://github.com/nservant/HiC-Pro/files/3378405/config-hicpro.txt)
![Screenshot from 2019-07-10 11-12-16](https://user-images.githubusercontent.com/51204078/60985375-0247cc80-a303-11e9-9f03-ef0d3292a579.png)
![Screenshot from 2019-07-10 11-17-34](https://user-images.githubusercontent.com/51204078/60985798-c2cdb000-a303-11e9-9581-603d01a53d54.png)

**Comment by nservant** [comment]
ok. I did not really see how you run HiC-Pro, but :
- update the name of your fast files ! Here you have the same prefix twice, once with .fastq, the other with .fq. If this is two parts of the same sample, using something like CNL1_part1_R1.fastq.gz, CNL1_part1_R2.fastq.gz, CNL1_part2_R1.fastq.gz, CNL1_part2_R2.fastq.gz
- replace the PAIR1_EXT by _R1 and PAIR2_EXT by _R2
- run HiC-Pro with -i hicpro/raw_data 

N

**Comment by bhill-17** [comment]
here is better image how I run hic Pro, and I'm now experiencing another issue I fixed previous with it being unable to find my data when I put more than just raw_data in the in put 
![image](https://user-images.githubusercontent.com/51204078/60987369-12fa4180-a307-11e9-844f-6b8ec338f6d0.png)

**Comment by nservant** [comment]
Could you use `singularity exec` because it seems that the singularity cannot access your local input data ?
In addition, you need to specify the output folder (-o OUTPUT). Here I just see a `-output` in your command line
N
