### ISSUE TITLE
HiC-Pro downstream differential analysis

### ISSUE THREAD

**Issue by rikrdo89** [nservant/HiC-Pro#264]
This is not really an "issue", but could anyone recommend a downstream analysis tool to compare interaction differences between two groups (TADs, loops, etc) after running HiC-Pro? I was able to load the HiC-Pro matrix files into HiTC, but aside from plotting the interactions, I  didn't find a functionality to do some basic statistical comparisons of TADs or loops between two groups. Any help or pointer would be very much appreciated.

**Comment by zyqfrog10** [comment]
You may find this resource useful: [mdozmorov/HiC_tools](https://github.com/mdozmorov/HiC_tools)

**Comment by nservant** [comment]
Hi,
That's a very good question ... I would recommend to ask it on the HiC-Pro forum ? you might have more answer.
https://groups.google.com/forum/#!forum/hic-pro
N
