### ISSUE TITLE
SparseToDense.py_error with input matrix

### ISSUE THREAD

**Issue by zyqfrog10** [nservant/HiC-Pro#266]
Hi @nservant ,

I've encountered issues with sparseToDense.py in some of my samples.
The error looks like:
```
> sparseToDense.py -b GMP_KO_rep1_10000_abs.bed  --di --perchr GMP_KO_rep1_10000_iced.matrix
chr1...
chr10...
chr11...
chr12...
chr13...
chr13_ran...
Traceback (most recent call last):
  File "/data/cer/shared/software/HiC-Pro_2.11.1/bin/utils/sparseToDense.py", line 130, in <module>
    counts_perchr = np.hstack((bins[np.where(bins==str(chrnames[i-1]))[0]], counts_perchr))
  File "/data/cer/shared/venvs/cer_base/lib/python2.7/site-packages/numpy/core/shape_base.py", line 340, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```
In the above example, the process stopped at chr13_random. Dense matrices have been created for chr1, chr10, chr11, chr12, chr13.
Not all my samples have this issue. Some other samples can run successfully to the end.
And my HiC-Pro settings are the same for all. no clue why this could happen.
Could it be the problem in ice normalization? Or alignment in some of the samples? The weird thing is that it only happens in some samples.

Thank you,
Ada

**Comment by nservant** [comment]
Hi,
Could you share these files with me please ?
N

**Comment by zyqfrog10** [comment]
Hi @nservant ,

Thank you for getting back to me so quickly!
I've attached my data here: [Sample data set](https://drive.google.com/open?id=12sDTxyJoqPsTShr-p-3174FoZ5f_CnZM)
I tried other two resolutions over the weekend, 20K and 40K for this sample. However, the results turned out to be fine. So, looks like it's influenced by the sparsity of the matrix. But why this matters when transferring to a dense format? 

Thanks,
Ada

**Comment by nservant** [comment]
Humm ... I run the command on my laptop, and it works well.
Could you try with the version from the devel branch please ?
https://github.com/nservant/HiC-Pro/blob/devel/bin/utils/sparseToDense.py
Thanks
N

**Comment by zyqfrog10** [comment]
Sadly, still happening with the same error @nservant 
```
/data/cer/shared/venvs/cer_base/lib/python2.7/site-packages/iced/io/_io_pandas.p
y:32: FutureWarning: Method .as_matrix will be removed in a future version. Use 
.values instead.
  row, col, data = dataframe.as_matrix().T
chr1...
chr10...
chr11...
chr12...
chr13...
chr13_ran...
Traceback (most recent call last):
  File "/data/cer/shared/software/HiC-Pro_2.11.1/bin/utils/sparseToDense_v2.11.3.py", line 146, in <module>
    counts_perchr = np.hstack((bins[np.where(bins==str(chrnames[i-1]))[0]], counts_perchr))
  File "/data/cer/shared/venvs/cer_base/lib/python2.7/site-packages/numpy/core/shape_base.py", line 340, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```
Thanks,
Ada

**Comment by nservant** [comment]
bad news. Could you try to update the iced python package please ?

**Comment by zyqfrog10** [comment]
No luck. updated iced and numpy. ran ice_norm again and then sparseTodense.py.
The exact error messages appeared only for resolution 10k. 
Were you be able to run through all the chromosomes?
Thanks

**Comment by nservant** [comment]
Sorry for the delay. Do still have an issue ?
