### ISSUE TITLE
Identify unligated internal reads in Micro-C dataset

### ISSUE THREAD

**Issue by ZhangJiankun21** [nservant/HiC-Pro#267]
Hi nservant,

> In practice, HiC-Pro was successfully applied to many data-sets including dilution Hi-C, in situ Hi-C, DNase Hi-C, Micro-C, capture-C, capture Hi-C or HiChip data.

I'm curious how to remove invalid pairs in Micro-C dataset, such as unligated internal reads. I would appreciate it very much if you could explain the principle. Thank you!

**Comment by nservant** [comment]
Hi,
As soon as the protocol is not based on restriction fragments, it is more difficult to remove unligated fragments. In this case (DNase Hi-C, Micro-C, etc.), we usually 'just' remove read pairs with a very short distance between the two mates (<1000 bp) ...
A couple of years ago, I did some test on a few datasets, and removing read pairs with a distance < 1000 bp (MIN_CIS = 1000) actually removes 90% of unligated fragments (originally detected from restriction fragments information) ... which is pretty good.
Does it make sense for you ?
N

**Comment by ZhangJiankun21** [comment]
Sure, I see. Thanks a lot!
