### ISSUE TITLE
merge_valid_interactions Error 1 

### ISSUE THREAD

**Issue by bhill-17** [nservant/HiC-Pro#268]
![valid_interactions](https://user-images.githubusercontent.com/51204078/61228594-300a8800-a6ec-11e9-9c83-22ba2d676016.PNG)
 Hi Nicolas, 
I am working with the sample data set and keep getting this error. I've looked at previous posts with this issue and I have the validpairs file and I have 242 G free on my HD to run the sample data so I'm really not sure what is wrong. If you could provide some guidance on how to fix this issue I would greatly appreciate it.

**Comment by zyqfrog10** [comment]
It says 'hic_results/data' cannot be found. You may want to check your directory or supply full path.

**Comment by bhill-17** [comment]
I checked my paths and things and that isn't where my data is located. That is one that is supposed to be created in the output folder for the hic analysis results so I'm not sure why it wasn't created and how to fix that.

**Comment by nservant** [comment]
Hi,
Could you tell me on which system your are ?
And show me your command line ?
Could you also check what you have in output before it crashed ?
Thanks

**Comment by bhill-17** [comment]
![image](https://user-images.githubusercontent.com/51204078/61638007-26d66980-ac5e-11e9-8923-9f0af3a6cf0f.png)
![image](https://user-images.githubusercontent.com/51204078/61638080-4bcadc80-ac5e-11e9-8609-90f86e3144f9.png)
![image](https://user-images.githubusercontent.com/51204078/61638139-64d38d80-ac5e-11e9-8a49-8d34bf24f3c5.png)
![image](https://user-images.githubusercontent.com/51204078/61638166-761c9a00-ac5e-11e9-810a-636361fbcb2b.png)
I'm using ubuntu 16.04 LTS, and in my output folder I get  bowtie_results, logs, rawdata, tmp, and config_test_latest_2.txt. There is no hic_results folder created in the output at all.

**Comment by zijiangyang** [comment]
Hi, I got the same error, have you fix that problem and how? Many thanks!
