### ISSUE TITLE
Test dataset - no annotation

### ISSUE THREAD

**Issue by dvanic** [nservant/HiC-Pro#27]
For the test dataset, it would be nice if the bowtie2 index was also downloaded so that if you're not working with human you don't have to set up for human and build an hg19 index just to test that the software works. 

There is also no config-test.txt file in the test_data directory, or in the ../test_data directory. One can be generated from that in the ./HiC-Pro_2.7.1/ directory, but it would be nice if the test was self-sufficient, so that users could actually test the tool without having to edit files and search for things.

**Comment by nservant** [comment]
Hi Darya,
Bowtie2 indexes for Human are available on the Bowtie2 website :
ftp://ftp.ccb.jhu.edu/pub/data/bowtie2_indexes/hg19.zip
I will add a config file and short text to ease the test run.
Thank you for your comment.
