### ISSUE TITLE
 GENOME_FRAGMENT not found. The file  does not exist ?

### ISSUE THREAD

**Issue by jiexili** [nservant/HiC-Pro#271]
Hi,
Thank you for this wonderful program!
I'm using HiC-Pro_2.11.1 on the cluster and run into this error at the step of "Assign alignments to restriction fragments":
Exit: GENOME_FRAGMENT not found. The file  does not exist ?
make: *** [mapped_2hic_fragments] Error 1

I have the fragment file in the same folder where I run the HiC-Pro. And had the specification in the configuration file:
#######################################################################
#######################################################################

GENOME_FRAGMENT = mm9_mboi.bed
LIGATION_SITE = GATC
MIN_FRAG_SIZE = 100
MAX_FRAG_SIZE = 100000
MIN_INSERT_SIZE = 100
MAX_INSERT_SIZE = 600

What could be the possible reason of getting this error? Do I need to put the full path of this "GENOME_FRAGMENT" in the configuration file?

And once I correct this, what parameter should I add to the HiC-Pro command to run from where it stopped instead of running from the very first step?

Thank you and any input will be very much appreciated!

Regards,
Jiexi

**Comment by nservant** [comment]
Hi,
By default, HiC-Pro looks for all annotation files in the annotation folder (in the installation directory).
If you cannot write in the annotation folder, just provide the full path please.
Nicolas

**Comment by jiexili** [comment]
Thank you Nicolas! I will try the full path.
Regards,
Jiexi

**Comment by jiexili** [comment]
Hi Nicolas, the full path works! Thank you!
