### ISSUE TITLE
> Hi Tocci89,

### ISSUE THREAD

**Issue by benxiahu** [nservant/HiC-Pro#272]
> Hi Tocci89,
> HiC-Pro will consider as a sample all reads within one input folder ...
> If you run it with one replicate per input folder, let's say ;
> data
> ++ sample1
> ++++ fastq files of samples 1
> ++ sample2
> +++++ fastq files of samples2
> ....
> 
> You can then rerun HiC-pro starting from the validPairs files you get during the first analysis.
> For instance ;
> ++ data
> ++++ sample_merge
> ++++++++ validPairs replicate1
> ++++++++ validPairs replicate2
> ...
> In this case, all files within the same folder will be considered as coming from the same sample, and will be merged. Just rerun Hic-Pro in stepwise mode starting with option -s merge_persample -s build_contact_maps -s ice_norm
> Hope it helps

I have 3 replicates for Hi-C. I obtained 3 folders which included .allValidPairs and matrices after finishing HiC-Pro. I want to merge those replicates.
I firstly put all replicated .allValidPairs into one folder: merge
inputfiles_HiCHIP.txt 
/proj/HiC_activity/Hi-C/home_output/hic_results/data/merge/validPairs_replicate1
/proj/HiC_activity/Hi-C/home_output/hic_results/data/merge/validPairs_replicate2
/proj/HiC_activity/Hi-C/home_output/hic_results/data/merge/validPairs_replicate3

I did not change the ./config-hicpro_home.txt which was used in "HiC-Pro -i ./home -o ./home_output -c ./config-hicpro_home.txt -p"

HiC-Pro -i ./merge -o ./merge_output  -p -s merge_persample -s build_contact_maps -s ice_norm -c ./config-hicpro_home.txt. When I ran this command, I got the following error:

Exit: Error: Directory Hierarchy of rawdata '/proj/HiC_activity/Hi-C/home_output/hic_results/data/merge' is not correct. No '.validPairs' files detected

Do I need to fix the config-hicpro_home.txt?
Thanks in advance.

_Originally posted by @benxiahu in https://github.com/nservant/HiC-Pro/issues/121#issuecomment-518685698_

**Comment by nservant** [comment]
Hi,
I just answered on the forum
N
