### ISSUE TITLE
Using validPairs file to create  .hic and .assembly files

### ISSUE THREAD

**Issue by wlhCNU** [nservant/HiC-Pro#275]
hi,
    Now, I have a ordering and orientation genome final.fasta file. Can we use the validPairs file and final.fasta file to created .hic and .assembly files, which can be loaded by Juicebox Assembly Tools to  correct assembly errors.
Thanks

**Comment by nservant** [comment]
Hi,
For the .hic file, please look at the hicpro2juicebox.py utility, that should create a .hic file.
For the .assembly, I'm afraid I cannot help you as I never see these files before.
But let me know if it works :) or feel free to propose a new utility to generate these files !
Thanks
