### ISSUE TITLE
removing duplicates from .validPairs files

### ISSUE THREAD

**Issue by rikrdo89** [nservant/HiC-Pro#276]
Is there a HiC-Pro tool that allow us to remove duplicates from the .validPairs file? I know that if "remove duplicates" is set to 1 in the config file, it will do it automatically and create a .allValidPairs file, but I was looking for a way to do this manually. (I have multiple fastq files per sample that I already pre-processed with HiC-Pro for which I would like to remove the duplicates without having to run the HiC-Pro mapping step again). Thank you for your help.

**Comment by nservant** [comment]
Hi,
You can use HiC-Pro is stepwise mode.
Put allvalidPairs file in a folder (following the same organisation than your input data)
And run HiC-Pro with -s merge_persample.
Note that you can combine several "-s" options.
Hope it helps
