### ISSUE TITLE
value in iced biases file is different from the results of HICPRO2FITHIC.PY.

### ISSUE THREAD

**Issue by yangxiaofeill** [nservant/HiC-Pro#280]
Dear author,
I want to convert my HiC-Pro results to FITHIC, and want to use `fit-hi-c` to detect significant loops/peaks.
However, I found the values in the biases file is different. For example:

40000 resolution,  head of `40000_iced.matrix.biases` file
```
1.063859460037971605e+00
1.350390699968959218e+00
7.935900137834444035e-01
3.279966020299127649e-01
4.975697643044702523e-01
5.582720395722967632e-01
3.500019474360890337e-01
1.189815019958696124e-01
1.105550750517650505e+00
1.424542395899923708e+00
```

I use hicpro2fithic.py command like
`hicpro2fithic.py -i 40000_iced.matrix" -b 40000_abs.bed -s 40000_iced.matrix.biases`

the head of `fithic.biases.gz` file is
```
chr1    20000   1.08006364588e-19
chr1    60000   1.37095918921e-19
chr1    100000  8.05677587893e-20
chr1    140000  3.32992485503e-20
chr1    180000  5.05148503069e-20
chr1    220000  5.6677536564e-20
chr1    260000  3.55333005545e-20
chr1    300000  1.20793769915e-20
chr1    340000  1.12238995766e-19
chr1    380000  1.44624032743e-19
```

I don't know why, and could you help me to explain this?

Best
Xiaofei

**Comment by nservant** [comment]
I'm afraid I cannot help you.
Please use the FitHiC group instead
https://groups.google.com/forum/#!forum/fithic
