### ISSUE TITLE
A suggestion regarding "GENOME_FRAGMENT not found.  The file  does not exist ?"

### ISSUE THREAD

**Issue by hwick** [nservant/HiC-Pro#282]
I am running HiC-Pro (latest version) using hg19_MboI_resfrag.bed which was put into the HiC-Pro annotation folder with -rw-r--r-- permissions, and GENOME_FRAGMENT = hg19_MboI_resfrag.bed in the config file, but we get the error "GENOME_FRAGMENT not found.  The file  does not exist ?" I suspect the issue is that I did not generate this with HiC-Pro's genome digest script and it was missing a column. As a suggestion, though, It would be very useful if HiC-Pro checked for necessary files up-front so that issues such as this can be caught quickly -- this analysis ran for 3 days before failing with this error. It is also not clear at which point the mapping step is done and which step the hic_proc step starts (I am unable to tell if I can skip the mapping step or whether I need to restart the 3-day+ analysis from scratch). I am hoping the analysis will work with the corrected file and full file path, but it looks like I will have to wait 3 days to find that information out?
Thank you

**Comment by nservant** [comment]
Hi. Thanks for this comment.
Actually, HicPro already checks if the file are there, but it didn't check if there are readable.
I just change this in the devel version 2.11.3-beta
N
