### ISSUE TITLE
How can I convert HiC-Pro output into homer format

### ISSUE THREAD

**Issue by QianzhaoJ** [nservant/HiC-Pro#287]
Hi :
I tried to convert HiC-Pro output into homer format for downstream analysis, and I found that `makeTagDirectory` function in homer can accept "Hi-C Summary" files. These files are tab-delimited text files with the following column assignments:
Hi-C Summary Format (columns):

> 1. Read Name (can be blank)
> 2. chromosome for read 1
> 3. positions for read 1 (5' end of read, one-indexed)
> 4. strand of read 1 (+ or -)
> 5. chromosome for read 2
> 6. positions for read 2 (5' end of read, one-indexed)
> 7. strand of read 2 (+ or -) 

The format looks like `ValidPairs` files in HiC-Pro , maybe I can just use the `ValidPairs` files as `Hi-C Summary` files ? 
But I don’t know if it is right , Counld you give me some suggestions ?
Thanks a lot !
Best wishes 
Qianzhao

**Comment by lconcia** [comment]
The conversion is trivial; just select the first 7 columns from the *validPairs file 

cut -f 1-7 validPairs  > validPairs.homer

**Comment by QianzhaoJ** [comment]
Thanks a lot!
