### ISSUE TITLE
stripes without scores

### ISSUE THREAD

**Issue by rikrdo89** [nservant/HiC-Pro#288]
Hi,
I have observed that when I plot my iced matrices created using the HIC-Pro pipeline, I usually see areas that seem to lack any interaction across a given region. (Picture below). 
![image](https://user-images.githubusercontent.com/24930604/67028394-34728280-f0d9-11e9-845a-20322d93a9c8.png)

However, if I convert the the valid pairs to hic files to visualize them in Juicebox, those white stripes (regions without interaction score) are not longer there, under any type of normalization. 
![image](https://user-images.githubusercontent.com/24930604/67028432-481de900-f0d9-11e9-824c-440442d04b20.png)

Does anyone know if this is because some reads are being discarded during the matrix generation step of the HiC-Pro pipeline due to some obscure parameter? I would very much appreciate any help with this issue.

**Comment by nservant** [comment]
Hi,
There is no filtering when we create the raw contact maps with HiC-Pro.
However, there are a filtering step in the normalization procedure. Basically, rows with exterme (low/high) counts are removed to ensure that the iced algorithm is able to converge.
For instance, if you plot the raw HiC-Pro matrices, what do you see ?
Regarding Juicebox, are you looking at raw data ? or normalize ones ?
Best
