### ISSUE TITLE
System Config file not Found

### ISSUE THREAD

**Issue by yihengp2** [nservant/HiC-Pro#289]
Hello,

I am new to Linux. I tried to run Hi-C Pro on Slurm following the pepline. However, the HiC Pro installed on the Slurm seems do not have system config file and exit with **System Config file not Found.**
How could I fix this problem?

**Comment by nservant** [comment]
It means that you did not install HiC-Pro successfully. Please follow the manual for that.
N

**Comment by sillysean** [comment]
The same problem occurs to me though I can run the command _HiC-Pro -v_ successfully.

```
/public/home/qmxiang/Hi-ChIP/HiC-Pro/bin/../scripts//Makefile:48: /public/home/qmxiang/Hi-ChIP/config-system.txt: No such file or directory
make: *** No rule to make target '/public/home/qmxiang/Hi-ChIP/config-system.txt'.  Stop.
```

**Comment by nservant** [comment]
The `config-system.txt` file is a file which should be within the installation folder.
Where and how did you install HiC-Pro ?
