### ISSUE TITLE
label misplacement in statistics pdf

### ISSUE THREAD

**Issue by TypicalSEE** [nservant/HiC-Pro#290]
Hi, I noticed that one of the pdf files seems to have a label misplacement problem, as is mentioned in issue #109. This bug seems to still exist in the current stable version(2.11.1) and the ggplot2 package I'm using is v3.2.1. Any plans on fixing it?
Thanks.

**Comment by nservant** [comment]
Hi
Thanks. I'll keep it in mind but it is not in the top priority as my idea is clearly to favor multiQC to generate a much nicer report than R.
Thanks

**Comment by nservant** [comment]
Fixed in devel 2.11.3
