### ISSUE TITLE
NameError: name 'or2_fragname' is not defined

### ISSUE THREAD

**Issue by jennymoon90** [nservant/HiC-Pro#291]
I was running HiC-Pro on paired-end fastq files of a bunch of samples. One of them consistently give me the following error, whereas all the other samples were fine, and I don't know how to solve it.

I looked up the log:
less mapped_2hic_fragments.log

And got the following messages:
## Loading Restriction File Intervals ' /u/project/geschwind/jennybea/Hi-C_tools/HiC-Pro_2.11.1/annotation/hg19_GATC_GANTC.bed '...
Warning :  6625991 fragment(s) outside of range and discarded.  9083611  remaining.
load_restriction_fragment function took 152530.718 ms
## Classifying Interactions ...
Warning - no restriction fragments for  A00454:262:HWM3VDSXX:3:1101:1054:1470  at  chrUn_gl000220 : 119149
Traceback (most recent call last):
  File "/u/local/apps/hicpro/2.11.1/python_2.7.13/HiC-Pro_2.11.1/scripts/mapped_2hic_fragments.py", line 744, in <module>
    str(htag) + "\n")
NameError: name 'or2_fragname' is not defined

Thanks,
Jenny

**Comment by nservant** [comment]
Hi,
Please use the devel version which fix this issue.
I will release a new version in a couple of days.
N
