### ISSUE TITLE
Exit: Error in reads alignment

### ISSUE THREAD

**Issue by wuxiaopei0509** [nservant/HiC-Pro#295]
Hi.
When I perform HiC-pro ,it stopped at the alignment step,like follow described:
~/software/HiC-Pro_2.11.1/scripts/hic.inc.sh: line 86: bowtie_results/bwt2_global/Hi-C_clean/Hi-C_R1_./01ref/mayinhua.fasta.bwt2glob.bam: No such file or directory
~/software/HiC-Pro_2.11.1/scripts/hic.inc.sh: line 86: bowtie_results/bwt2_global/Hi-C_clean/Hi-C_R2_./01ref/mayinhua.fasta.bwt2glob.bam: No such file or directory
Exit: Error in reads alignment - Exit
make: *** [bowtie_global] Error 1

What's the problem ？ 
Thank you

**Comment by nservant** [comment]
Hi
Could you show me your command line ? and how the data folder is organized please ?
Thanks

**Comment by wuxiaopei0509** [comment]
my command is '~/software/HiC-Pro_2.11.1/bin/HiC-Pro -i ./02Hi-C_reads/ -o ./04hicpro_output -c mayinhua.config-hicpro.txt -s mapping -s proc_hic -s quality_checks' and the data folder is 
![图片](https://user-images.githubusercontent.com/52643750/70782981-444dd080-1dc3-11ea-9bd3-7d89e6f8a908.png)
the reads fold is 
02Hi-C_reads
        Hi-C_clean
              Hi-C_R1.fastq.gz
              Hi-C_R2.fastq.gz

Thank you!
Best

**Comment by nservant** [comment]
it looks ok. What about your config file please ?

**Comment by wuxiaopei0509** [comment]
# Please change the variable settings below if necessary


#########################################################################
## Paths and Settings  - Do not edit !
#########################################################################

TMP_DIR = tmp
LOGS_DIR = logs
BOWTIE2_OUTPUT_DIR = bowtie_results
MAPC_OUTPUT = hic_results
RAW_DIR = rawdata

#######################################################################
## SYSTEM AND SCHEDULER - Start Editing Here !!
#######################################################################
N_CPU = 30
LOGFILE = hicpro.log

JOB_NAME = sample
JOB_MEM = 100
JOB_WALLTIME = 
JOB_QUEUE = hicpro
JOB_MAIL = 

#########################################################################
## Data
#########################################################################

PAIR1_EXT = _R1
PAIR2_EXT = _R2

#######################################################################
## Alignment options
#######################################################################

MIN_MAPQ = 10

BOWTIE2_IDX_PATH = ./01ref/
BOWTIE2_GLOBAL_OPTIONS = --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder
BOWTIE2_LOCAL_OPTIONS =  --very-sensitive -L 20 --score-min L,-0.6,-0.2 --end-to-end --reorder

#######################################################################
## Annotation files
#######################################################################

REFERENCE_GENOME = ./01ref/sample.fasta
GENOME_SIZE = ./01ref/sample.fasta.size

#######################################################################
## Allele specific analysis
#######################################################################

ALLELE_SPECIFIC_SNP = 

#######################################################################
## Capture Hi-C analysis
#######################################################################

CAPTURE_TARGET =
REPORT_CAPTURE_REPORTER = 1

#######################################################################
## Digestion Hi-C
#######################################################################

GENOME_FRAGMENT = ./03restriction_sites/sample.fasta_mboi_dpnii.bed
LIGATION_SITE = GATCGATC
MIN_FRAG_SIZE = 100
MAX_FRAG_SIZE = 100000
MIN_INSERT_SIZE = 100
MAX_INSERT_SIZE = 600

#######################################################################
## Hi-C processing
#######################################################################

MIN_CIS_DIST =
GET_ALL_INTERACTION_CLASSES = 1
GET_PROCESS_SAM = 0
RM_SINGLETON = 1
RM_MULTI = 1
RM_DUP = 1

#######################################################################
## Contact Maps
#######################################################################

BIN_SIZE = 20000 40000 150000 500000 1000000
MATRIX_FORMAT = upper

#######################################################################
## Normalization
#######################################################################
MAX_ITER = 100
FILTER_LOW_COUNT_PERC = 0.02
FILTER_HIGH_COUNT_PERC = 0
EPS = 0.1

Above is my config file

**Comment by nservant** [comment]
Hi,
Please use absolute path in the config file.
Then REFERENCE_GENOME should be the prefix of your bowtie indexes (for instance  'hg19')
Basically the files index that you have in BOWTIE2_IDX_PATH
Thanks

**Comment by wuxiaopei0509** [comment]
Hi， I have used the absolute path in the config file and change the REFERENCE_GENOME to the prefix of  bowtie indexes, However is also have the same error. I have no idea  how to deal  with it now
Thank you

**Comment by wuxiaopei0509** [comment]
sorry，it works now

**Comment by wzhjlau2009** [comment]
@wuxiaopei0509 ，Hi
I got the same error as you list，can you tell me how you solve the problem？ Thanks！

The Best！

**Comment by wuxiaopei0509** [comment]
what's your problem?

**Comment by wzhjlau2009** [comment]
@wuxiaopei0509 ，Hi
When I perform HiC-pro ,it stopped at the alignment step,like follow described:
~/software/HiC-Pro_2.11.1/scripts/hic.inc.sh: line 86: bowtie_results/bwt2_global/Hi-C_clean/Hi-C_R1_./01ref/mayinhua.fasta.bwt2glob.bam: No such file or directory
~/software/HiC-Pro_2.11.1/scripts/hic.inc.sh: line 86: bowtie_results/bwt2_global/Hi-C_clean/Hi-C_R2_./01ref/mayinhua.fasta.bwt2glob.bam: No such file or directory
Exit: Error in reads alignment - Exit
make: *** [bowtie_global] Error 1

I got the same error，can you tell me how you solve the problem？ Thanks！

**Comment by wuxiaopei0509** [comment]
Maybe the 'BOWTIE2_IDX_PATH' and 'REFERENCE_GENOME' in the config file is not right , or you can install the software again. By the way ,can you show me the config file and your diretory structure?

**Comment by nservant** [comment]
Hi,
Indeed, please send your config file, data folder organization and command line in order to help you
Best

**Comment by wzhjlau2009** [comment]
@wuxiaopei0509 @nservant ，Hi
This is my config file 
[config-hicpro.txt](https://github.com/nservant/HiC-Pro/files/4024813/config-hicpro.txt)

my reads is in this path  share/home/HiC-Pro2/PBSQ/test/Novo-1-reads/PBSQ/reads-1.fastq.gz reads-2.fastq.gz 
Thanks！

**Comment by wuxiaopei0509** [comment]
your reads reads-1.fastq.gz reads-2.fastq.gz is not right ,must contain _R1 and _R2 in the filename of reads
