### ISSUE TITLE
[Bug] Sequential mode doesn't generate all quality check figures

### ISSUE THREAD

**Issue by auberginekenobi** [nservant/HiC-Pro#296]
Repro: running full HiC-Pro on the test data using the command eg. 
`time ( HiC-Pro -c config_test_latest.txt -i test_data/ -o hicpro_full ) > logs/hicpro_full.log 2>&1`
produces 5 pdf plots in hic_results/pic/dixon_2M: 
- plotHiCContactRanges_dixon_2M.pdf  
- plotHiCFragmentSize_dixon_2M.pdf  
- plotMappingPairing_dixon_2M.pdf
- plotHiCFragment_dixon_2M.pdf       
- plotMapping_dixon_2M.pdf

Running sequential HiC-Pro on the same data using the commands eg.
```
time ( HiC-Pro -c config_test_latest.txt -i test_data/ -o hicpro_test_1cpu/ -s mapping ) > logs/test_1cpu_proc_hic.log 2>&1
time ( HiC-Pro -c config_test_latest.txt -i hicpro_test_1cpu/bowtie_results/bwt2 -o hicpro_test_1cpu/ -s proc_hic ) > logs/test_1cpu_proc_hic.log 2>&1
time ( HiC-Pro -c config_test_latest.txt -i hicpro_test_1cpu/bowtie_results/bwt2 -o hicpro_test_1cpu/ -s quality_checks ) > logs/test_1cpu_quality_checks.log 2>&1
time ( HiC-Pro -c config_test_latest.txt -i hicpro_test_1cpu/hic_results/data -o hicpro_test_1cpu/ -s merge_persample -s build_contact_maps ) > logs/test_1cpu_build_contact_maps.log 2>&1
time ( HiC-Pro -c config_test_latest.txt -i hicpro_test_1cpu/hic_results/matrix/ -o hicpro_test_1cpu/ -s ice_norm ) > logs/test_1cpu_ice_norm.log 2>&1
```
only generates the latter 3 figures.

**Comment by nservant** [comment]
Hi,
This is because you run the `quality_checks` before the merge_presample ...
Could you run it at the end please ?
N

**Comment by nservant** [comment]
Hi,
This is because you run the `quality_checks` before the `merge_presample` ...
Could you run it at the end please ?
N

**Comment by auberginekenobi** [comment]
I see, if I add multiple -s flags to the HiC-Pro command, are they run in that order? The original command I noticed this issue was 
`time ( HiC-Pro -c config_template_tumor.txt -i bowtie_results/bwt2 -o . -s proc_hic -s quality_checks -s merge_persample  -s build_contact_maps -s ice_norm ) > all_other_steps.log 2>&1`
but could I fix this by running 
`time ( HiC-Pro -c config_template_tumor.txt -i bowtie_results/bwt2 -o . -s proc_hic -s merge_persample -s quality_checks -s build_contact_maps -s ice_norm ) > all_other_steps.log 2>&1`

**Comment by nservant** [comment]
yes, it should work
