### ISSUE TITLE
Error in HiC-Pro alignment step！help！

### ISSUE THREAD

**Issue by wzhjlau2009** [nservant/HiC-Pro#297]
Hi， @nservant 
Thanks for so powerful tools for HiC research. Recently i use HiC-Pro and get some problems , i have one pair reads , when i do the alignment step ,i get some error  and i don't know how to fix it. I will very appreciate if you give me some advice. Thanks.
![(3 AG~_)(3I5CS3N})6GZ7M](https://user-images.githubusercontent.com/6326115/71391761-8b985480-2640-11ea-95a5-edcd4e7954ed.png)

![56{DJ`07 Y29OJB)V%POK5](https://user-images.githubusercontent.com/6326115/71391722-60156a00-2640-11ea-8598-2518ec7aee3e.png)
![PAS( GHSSIC~1VB$OZ8{P3S](https://user-images.githubusercontent.com/6326115/71391723-63105a80-2640-11ea-8f34-f11ec80b7837.png)

**Comment by wzhjlau2009** [comment]
![~RZT JR(LOY {B)8 2WBK](https://user-images.githubusercontent.com/6326115/71399280-0cb21480-265e-11ea-884c-ec89fb844b77.png)
i run another sample , also get an error in the output mapping log file.

**Comment by nservant** [comment]
Hi,
Regarding your last error, there is something wrong with your input file.
In fastq file, you would expect to have one quality value per base, which doesn't seem to be the case here.
The error you have is launched by bowtie2, not really by HiC-Pro.
Best

**Comment by wzhjlau2009** [comment]
@nservant ，Hi
How about this error ? 
![image](https://user-images.githubusercontent.com/6326115/71496192-f1791c00-288c-11ea-84be-7d0092c75353.png)

**Comment by nservant** [comment]
I do not understand why you have a alignment error, while the contact maps normalization looks ok !!
Please, have a look into the `log` folder, and repoirt any error message in the `bowtie` logs.

**Comment by wzhjlau2009** [comment]
![image](https://user-images.githubusercontent.com/6326115/71537442-2f427700-2957-11ea-9206-3a7fc9165127.png)
@nservant，hi
this is the R1_bwt2glob.unmap_bowtie2.log file

**Comment by nservant** [comment]
Hi
There is something wrong with your input data ...
bowtie crashed because some qality are missing. Are you sure that your data are not truncated ?
