### ISSUE TITLE
Is the final output matrix in log scale or normalized count number?

### ISSUE THREAD

**Issue by jennymoon90** [nservant/HiC-Pro#299]
Dear Dr. Servant,
I have a basic question. In the hic_results/matrix/.. folder, are the values in the matrix count numbers or are they in log2 or log10 scale?
Thanks,
Jenny

**Comment by nservant** [comment]
Hi Jenny
The raw matrix are just raw counts (no log), and the 'iced' matrix are normalized counts (no log either).
Hope it helps
Nicolas
