### ISSUE TITLE
Error for hicpro2juicebox.sh processing. Help

### ISSUE THREAD

**Issue by clementmo** [nservant/HiC-Pro#300]
Dear Dr. Servant,
Recently I am using hicpro2juicebox.sh to transfer the allValidPairs to *.hic file for following analysis.
The code is as following:
bash /public/home/lqiao/WPC/HiC-Pro_2.11.1/bin/utils/hicpro2juicebox.sh\
-i Ga_rep1.allValidPairs\
-g /public/home/lqiao/WPC/HiC-Pro_2.11.1/annotation/chrom_GhAt.size\ 
-j /public/home/lqiao/WPC/softwares/juicer/juicer_tools_1.14.08.jar\
-r /public/home/lqiao/WPC/HiC-Pro_2.11.1/annotation/HindIII_resfrag_GhAt.bed

The input files are in the following format:
head -5 Ga_rep1.allValidPairs  ##Lachesis_group0_ERROPOS100000 is the chr name. It was generated by HiC-pro-2.11, with each row in 12 colume.
Ga_Hi_C_rep1.340989953	Lachesis_group0_ERROPOS100000	12584	+	Lachesis_group2_ERROPOS103218803	42135	-	452	HIC_Lachesis_group0_ERROPOS100000_2	HIC_Lachesis_group2_ERROPOS103218803_27	30	37

head -5 chrom_GhAt.size
Lachesis_group10_ERROPOS100000	100000
Lachesis_group10_ERROPOS200000	100000
Lachesis_group10_ERROPOS300000	100000
Lachesis_group10_ERROPOS400000	100000
Lachesis_group10_ERROPOS500000	100000

head -5 HindIII_resfrag_GhAt.bed
Lachesis_group10_ERROPOS100000	0	579	HIC_Lachesis_group10_ERROPOS100000_1	0	+
Lachesis_group10_ERROPOS100000	579	1885	HIC_Lachesis_group10_ERROPOS100000_2	0	+
Lachesis_group10_ERROPOS100000	1885	2726	HIC_Lachesis_group10_ERROPOS100000_3	0	+
Lachesis_group10_ERROPOS100000	2726	3494	HIC_Lachesis_group10_ERROPOS100000_4	0	+
Lachesis_group10_ERROPOS100000	3494	8496	HIC_Lachesis_group10_ERROPOS100000_5	0	+

The juicer_tools_1.14.08.jar is the original file downloaded from https://github.com/aidenlab/juicer/wiki/Download .

It produce the error:
Running Juicebox ...
Start preprocess
Writing header
Writing body
.................................Error: the chromosome combination 5001_6138 appears in multiple blocks
done !

I can't find 5001_6138 in the above files. 
What might be the problem?
I need your help. Thank you so much.

Clement

**Comment by nservant** [comment]
Hi Clement,
I just say that this is a bit hard to help you like that ...
Last line of the `hicpro2juicebox.sh` script, you have a `rm` command that clean all intermediate files. Maybe you should comment this cleaning, and manually check what's going on at each step of the process ...
N
