### ISSUE TITLE
*DEpairs or the *SCpairs files 

### ISSUE THREAD

**Issue by francisfa** [nservant/HiC-Pro#302]
Hi, there is a question. I use HiC-Pro (version 2.10.0) to generate the hic_results, like this:
```
HiCH_H_allValidPairs
HiCH_H_allValidPairs.mergestat
HiCH_H_HG19.bwt2pairs.RSstat
HiCH_H_HG19.bwt2pairs.validPairs
HiCH_H.mRSstat
```

But, I want to generate the *DEpairs or the *SCpairs files, how should I do?
```
d1_allValidPairs
d1_hg19.bwt2pairs.DEPairs
d1_hg19.bwt2pairs.DumpPairs
d1_hg19.bwt2pairs.RSstat
d1_hg19.bwt2pairs.SCPairs
d1_hg19.bwt2pairs.SinglePairs
d1_hg19.bwt2pairs.validPairs
```
Thanks!

**Comment by nservant** [comment]
Hi,
You need to run HiC-Pro with `GET_ALL_INTERACTION_CLASSES = 1`
best

**Comment by francisfa** [comment]
It works. Thank you very much!
