### ISSUE TITLE
ICE normalisation step fail

### ISSUE THREAD

**Issue by rob123king** [nservant/HiC-Pro#304]
The last step of normalisation is not working for me after installing the devel version 2 days a go. Running the command that fails I assume the iced version that comes with python via pip is not the correct version. Taking the one in the hic-Pro installation and copying over to my lib I get a different error. I assume as I have not installed the hic-Pro version correctly? Any suggestions on how to fix?

```
/home/data/bioinf_resources/programming_tools/proc10xG-master/27python/bin/python /home/data/bioinf_resources/programming_tools/HiCpro/HiC-Pro_2.11.3-beta/scripts/ice --results_filename hic_results/matrix/data/iced/500000/data_500000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 --verbose 1 hic_results/matrix//data/raw/500000/data_500000.matrix

/home/data/bioinf_resources/programming_tools/proc10xG-master/27python/lib/python2.7/site-packages/iced/normalization/_ca_utils.py:9: UserWarning: The API of this module is likely to change. Use only for testing purposes
  "The API of this module is likely to change. "
Using iced version 0.5.2
Loading files...
Traceback (most recent call last):
  File "/home/data/bioinf_resources/programming_tools/HiCpro/HiC-Pro_2.11.3-beta/scripts/ice", line 76, in <module>
    if min(i.min(), j.min()) == 0:
  File "/home/data/bioinf_resources/programming_tools/proc10xG-master/27python/lib/python2.7/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity
(27python) -bash-4.1$
(27python) -bash-4.1$
(27python) -bash-4.1$ /home/data/bioinf_resources/programming_tools/proc10xG-master/27python/bin/python /home/data/bioinf_resources/programming_tools/HiCpro/HiC-Pro_2.11.3-beta/scripts/ice --results_filename hic_results/matrix/data/iced/500000/data_500000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 --verbose 1 hic_results/matrix//data/raw/500000/data_500000.matrix
Traceback (most recent call last):
  File "/home/data/bioinf_resources/programming_tools/HiCpro/HiC-Pro_2.11.3-beta/scripts/ice", line 8, in <module>
    import iced
  File "/home/data/bioinf_resources/programming_tools/proc10xG-master/27python/lib/python2.7/site-packages/iced/__init__.py", line 1, in <module>
    from . import normalization
  File "/home/data/bioinf_resources/programming_tools/proc10xG-master/27python/lib/python2.7/site-packages/iced/normalization.py", line 3, in <module>
    from ._normalization_ import _update_normalization_csr
ImportError: No module named _normalization_

```

**Comment by nservant** [comment]
Hi,
I'm almost sure there was something wrong in the installation of iced ...
You can install the one available through pip
N

**Comment by rob123king** [comment]
I installed it via pip originally. I tried again. But it's already installed.
(27python) -bash-4.1$ pip install iced
Requirement already satisfied: iced in /home/data/bioinf_resources/programming_tools/proc10xG-master/27python/lib/python2.7/site-packages (0.5.2)
You are using pip version 18.0, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(27python) -bash-4.1$ pip install iced --upgrade
Requirement already up-to-date: iced in /home/data/bioinf_resources/programming_tools/proc10xG-master/27python/lib/python2.7/site-packages (0.5.2)
You are using pip version 18.0, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(27python) -bash-4.1$

 I removed also and put in again. 
```
(27python) -bash-4.1$ /home/data/bioinf_resources/programming_tools/proc10xG-master/27python/bin/python /home/data/bioinf_resources/programming_tools/HiCpro/HiC-Pro_2.11.3-beta/scripts/ice --results_filename hic_results/matrix/data/iced/500000/data_500000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 --verbose 1 hic_results/matrix//data/raw/500000/data_500000.matrix
/home/data/bioinf_resources/programming_tools/proc10xG-master/27python/lib/python2.7/site-packages/iced/normalization/_ca_utils.py:9: UserWarning: The API of this module is likely to change. Use only for testing purposes
  "The API of this module is likely to change. "
Using iced version 0.5.2
Loading files...
Traceback (most recent call last):
  File "/home/data/bioinf_resources/programming_tools/HiCpro/HiC-Pro_2.11.3-beta/scripts/ice", line 76, in <module>
    if min(i.min(), j.min()) == 0:
  File "/home/data/bioinf_resources/programming_tools/proc10xG-master/27python/lib/python2.7/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity
(27python) -bash-4.1$
```
Example bed file that is created
`"scaffold1,13783949,f72Z13783949_pilon"	0	500000	1
"scaffold1,13783949,f72Z13783949_pilon"	500000	1000000	2
"scaffold1,13783949,f72Z13783949_pilon"	1000000	1500000	3
"scaffold1,13783949,f72Z13783949_pilon"	1500000	2000000	4
"scaffold1,13783949,f72Z13783949_pilon"	2000000	2500000	5
"scaffold1,13783949,f72Z13783949_pilon"	2500000	3000000	6
"scaffold1,13783949,f72Z13783949_pilon"	3000000	3500000	`

**Comment by rob123king** [comment]
perhaps I need to use an earlier version? or the prior step did not work correctly?

**Comment by rob123king** [comment]
Its worked fine with another data set so it must be data specific and something to do with reference headers or data. so installation is fine. I'll see if I can compare the two and work out what is wrong.

**Comment by nservant** [comment]
ok let me know. Maybe something wrong with the input matrix file ...

**Comment by rob123king** [comment]
seems to have worked now. I must have been using the wrong input data. I went back to original files before concatenating.
