### ISSUE TITLE
Error at contact maps step

### ISSUE THREAD

**Issue by vtartaglio** [nservant/HiC-Pro#309]
Hi,

I am getting a strange error and I'm not sure if the problem is something with my cluster, or my usage of HiC-Pro.

My run is failing at the build_contact_maps step. I have already merged four biological replicates by creating a directory called rawdata/sample_merge, then I put the four *.bwt2pairs.validPairs files in it, then I did: 
`$HICPRO/bin/HiC-Pro -i $HICWORK/rawdata -o $HICWORK/results -c $HICPRO/config-hicpro.txt -s merge_persample -s quality_checks` and that ran without problems.

Then I copied sample_merge.allValidPairs to rawdata/sample_merge. I checked that the file is not empty. Then I tried running -s build_contact_maps.
The std out looks like this:
```
--------------------------------------------
Wed Jan 29 08:53:18 PST 2020
Generate binned matrix files ...
Logs: logs/sample_merge/build_raw_maps.log
make: *** [/global/projectb/sandbox/plant/hybridum/software/HiC-Pro_2.11.1/scripts/Makefile:174: build_raw_maps] Error 134
```

The log file looks like this:
```
## Generate contact maps at 20000 resolution ...
cat rawdata/sample_merge/sample_merge.allValidPairs | /global/projectb/sandbox/plant/hybridum/software/HiC-Pro_2.11.1/scripts/build_matrix --matrix-format upper --binsize 20000 --chrsizes /global/projectb/scratch/vstartag/dongTPJ2018_SRA/references/Osativa.chrom.sizes --ifile /dev/stdin --oprefix hic_results/matrix/sample_merge/raw/20000/sample_merge_${bsize}
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
/global/projectb/sandbox/plant/hybridum/software/HiC-Pro_2.11.1/scripts/hic.inc.sh: line 86: 19270 Broken pipe             cat rawdata/sample_merge/sample_merge.allValidPairs
     19271 Aborted                 | /global/projectb/sandbox/plant/hybridum/software/HiC-Pro_2.11.1/scripts/build_matrix --matrix-format upper --binsize 20000 --chrsizes /global/projectb/scratch/vstartag/dongTPJ2018_SRA/references/Osativa.chrom.sizes --ifile /dev/stdin --oprefix hic_results/matrix/sample_merge/raw/20000/sample_merge_${bsize}
```

Do you have any suggestions for how I should troubleshoot this? I have successfully run HiC-Pro on this cluster before, although this is my first time merging multiple samples. Perhaps I am not understanding how to merge correctly. Thanks in advance!

**Comment by nservant** [comment]
Hi,
Either this is a cluster error, or a C++ compilation issue during the installation.
Could you try to run the script `build_matrix` as a standalone tool to check that ?
The input is the list of valid pairs, and the output the matrices ...
Thanks
N

**Comment by vtartaglio** [comment]
It failed! I recently re-installed Hi-C Pro the way I did before, in case things on the cluster changed, but that didn't help. I will talk to our sys admins. Here's the command I tried: 
`/global/projectb/sandbox/plant/hybridum/software/HiC-Pro_2.11.1/scripts/build_matrix --binsize 500000 --chrsizes $HICWORK/references/Osativa.chrom.sizes --ifile $HICWORK/rawdata/sample_merge/sample_merge.allValidPairs --oprefix rice_merged`

And here is the error message:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
```

**Comment by vtartaglio** [comment]
Never figured out the problem. The sys admins performed some maintenance on our cluster, and now HiC-Pro works again! So this bug remains a mystery.
