### ISSUE TITLE
Bowtie2 global alignment error - file path specification bug

### ISSUE THREAD

**Issue by rmurray2** [nservant/HiC-Pro#31]
It seems there may be a bug in the way folder paths are defined in `bowtie_wrap.sh`. Specifically, the `R1` and probably `R2` variables

During reads mapping, specifically when `global_align()` is called, several files are created, including ones of the form: `x_R1_mm9.bwt2glob.unmap.fastq`. All of those files seem to be created without error.

The next task seems to be to generate files of the form `R1_mm9.bwt2glob.bam`, and this is where the errors is.

Looking at the error log, the culprit is the following command:

`/home/ubuntu/HCP/bowtie2-2.2.4/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/fastq/00_SRR1300754_R1_mm9.bwt2glob.unmap.fastq --rg-id BMG --rg SM:00_SRR1300754_R1 --phred33-quals -p 8 -x /home/ubuntu/mm9_bowtie2_index/mm9 -U rawdata/fastq/00_SRR1300754_R1.fastq 2> logs/fastq/bowtie_00_SRR1300754_R1_global_mm9.log | /usr/bin/samtools view -F 4 -bS - > bowtie_results/bwt2_global/fastq/00_SRR1300754_R1_mm9.bwt2glob.bam`

I noticed that the folder path that comes after the `-U` option doesn't exist, and that all of the .fastq files that are being referenced are actually in the `/rawdata` main dir. 

When I manually did the same command but setting the `-U` option to `rawdata/00_SRR1300754_R1.fastq`, the files of the form `mm9.bwt2glob.bam` were sussessfully created. 

This leads me to suspect that somewhere along the line, there is a file path specification bug that is causing this error.

**Comment by nservant** [comment]
Hi,
This look strange. I'm wondering whether it can be due to the way you specified the input data.
HiC-Pro requires one folder per sample.
For instance, if you have two samples, you need to organize the data as follow ;
* mydata
  ** sample1
  ***** file1_R1.fastq
  ***** file1_R2.fastq
  ** sample2
  ***** file1_2_R1.fastq
  ***** file1_2_R2.fastq
etc.
Would you mind checking if your data are well organized ?
Thanks

**Comment by rmurray2** [comment]
Hi, thanks for your prompt reply. 

I reran the run, and this alignment step was completed successfully this time. ATM the run is on Bowtie alignment step 2. 

One of the differences between the failed run and this new run was, as you mentioned, that each sample (only one in this case) had it's own folder (as in https://zerkalo.curie.fr/partage/HiC-Pro/) in the latter, but not the former case. 

Another difference was in the way the input fastq files were preprocessed, but I would guess that the input folder structure was the problem. 

Thanks again

**Comment by nservant** [comment]
Great ! Let me know if you have any other questions/comments
