### ISSUE TITLE
HiC-Pro use with non-reference genomes

### ISSUE THREAD

**Issue by joeplanta** [nservant/HiC-Pro#313]
Hi,

I am working on non-reference genomes for a few grass species. We do not have chromosome sizes for our assemblies and so can we use HiC-Pro to process our Hi-C data? The HiC-Pro paper used the annotated human genome and the program requires chromosome sizes so I am not sure if we can use HiC-Pro.

Thanks,
Jose

**Comment by nservant** [comment]
Hi Jose,
What do you mean by "non-reference genomes" ?
If you do not have any reference genome, you should use other software design for de-novo assembly for instance
Best

**Comment by joeplanta** [comment]
Hi Nicolas,

By "non-reference genomes" I mean those that have not been sequenced yet. Thank you. I will check out other programs.
