### ISSUE TITLE
the error everyone got but with different causes 

### ISSUE THREAD

**Issue by AhlemBoudell** [nservant/HiC-Pro#315]
Hello HiC-pro folks,

so when I run the command:

HiC-Pro -i AllSamples -o AllResults -c config-hicpro.txt

i get the error:

/sw/csi/hicpro/2.10.0/el7_gnu6.4.0/HiC-Pro_2.10.0/scripts/bowtie_wrap.sh -c /ibex/scratch/projects/c2053/config-hicpro.txt -u >> hicpro.log
Exit: Error in Bowtie alignment
make: *** [bowtie_global] Error 1

here is the config file:
[config-hicpro.txt](https://github.com/nservant/HiC-Pro/files/4255589/config-hicpro.txt)

Hicpro log file:
[hicpro.log](https://github.com/nservant/HiC-Pro/files/4255607/hicpro.log)

and one of the 2 log files of the 2 replicas:
[bowtie_H3K9_me_dimut_H5LGHCCX2_L5_R1_global_ce11.log](https://github.com/nservant/HiC-Pro/files/4255610/bowtie_H3K9_me_dimut_H5LGHCCX2_L5_R1_global_ce11.log)

Any idea how to solve this?

**Comment by nservant** [comment]
Hi,
Actually, the config file you are using is not the one from the HiC-pro 2.10 version.
The `FORMAT` parameter is missing in the config.

I would suggest to update HiC-Pro to the latest version 2.11.XX, which should match your config and which does not need any quality format.
best

**Comment by AhlemBoudell** [comment]
Thanks alot for the fast response!

I am using this version in our cluster and thats the only version we have apparently.
Is there a way I can just modify my config file to make it work?

**Comment by nservant** [comment]
Just download the 2.10 version, and use the config file within this version.
In theory, you should have a FORMAT option which is passed to bowtie2, using --${FORMAT}-quals
With the previous bowtie2 version, it supported --phred33-quals options ... the point is that according to the manual, it doesn't see it is still the case with recent version.
So have a look at your bowtie version first

**Comment by AhlemBoudell** [comment]
bowtie2 version: bowtie2/2.3.3.1

**Comment by AhlemBoudell** [comment]
It worked!

the command is running in the cluster for almost 18 hrs but with no errors at least.

Thanks alot .. was not going to figure it out by my self!

**Comment by AhlemBoudell** [comment]
Wed Feb 26 17:41:43 +03 2020
Bowtie2 alignment step1 ...
/sw/csi/hicpro/2.10.0/el7_gnu6.4.0/HiC-Pro_2.10.0/scripts/bowtie_wrap.sh -c /ibex/scratch/projects/c2053/config-hicpro.txt -u >> hicpro.log


It has been on the first step since yesterday, and I just noticed that in other examples it didnt take nearly as much time as that!
Is this ok?

**Comment by nservant** [comment]
Well, I would say it depends how many reads you have in input.
did you split the reads per chunck to speed up the process ?
