### ISSUE TITLE
Running HiC pro in both modes

### ISSUE THREAD

**Issue by AhlemBoudell** [nservant/HiC-Pro#319]
Hello HiC-pro folks,

so I ran the first step of HiCpro in the cluster, and that step is done correctly, but our cluster is going to have a maintenance session for a whole week and i was wondering if is it possible to run the second step locally? which analysis steps should i run and is there any other adjustments to the commands needed?

**Comment by nservant** [comment]
Hi,
Yes. You can use `-s merge_persample -s build_contact_maps -s ice_norm`
Best

**Comment by AhlemBoudell** [comment]
Hi,

Sorry for disturbing again but when i ran the second step in the cluster it terminated with the errors in the following files, any idea what caused that?

[config-hicproNew.txt](https://github.com/nservant/HiC-Pro/files/4380177/config-hicproNew.txt)
[slurm-9815462_2.log](https://github.com/nservant/HiC-Pro/files/4380182/slurm-9815462_2.log)
[slurm-9815462_1.log](https://github.com/nservant/HiC-Pro/files/4380183/slurm-9815462_1.log)
