### ISSUE TITLE
Run quality checks failed

### ISSUE THREAD

**Issue by AhlemBoudell** [nservant/HiC-Pro#324]
Hi,

Sorry for disturbing again but when i ran the second step in the cluster it terminated with the errors in the following files, any idea what caused that?

[slurm-9815462_2.log](https://github.com/nservant/HiC-Pro/files/4380214/slurm-9815462_2.log)
[slurm-9815462_1.log](https://github.com/nservant/HiC-Pro/files/4380215/slurm-9815462_1.log)
[config-hicproNew.txt](https://github.com/nservant/HiC-Pro/files/4380216/config-hicproNew.txt)

**Comment by nservant** [comment]
Hi
Could you check if you have another log file with a clear error ? in the log folder ? 
In addition, note that
`LIGATION_SITE = ^GATC`
is not correct. Here, HiC-Pro is expecting the LIGATION motif, not the RESTRICTION one.
So, in case of DpnII enzyme, it should be `GATCGATC`
Best

**Comment by AhlemBoudell** [comment]
Thanks for the note!
Will correct that now, but should i re-run the first step then?

[hicproNew.log](https://github.com/nservant/HiC-Pro/files/4381957/hicproNew.log)

**Comment by nservant** [comment]
yes it would be better ... sorry for that.
Could you check in the Rout files (in the logs) if you see any error ?

**Comment by AhlemBoudell** [comment]
Among the log files, those are the ones that show an issue i think
one is warnings about the restriction fragments u mentioned . i will re-run it now .. thanks alot!
but i also faced the issue with the previous run when i didnt provide any ligation site

[mapped_2hic_fragments.log](https://github.com/nservant/HiC-Pro/files/4381977/mapped_2hic_fragments.log)
[plot_hic_contacts.log](https://github.com/nservant/HiC-Pro/files/4381983/plot_hic_contacts.log)

**Comment by nservant** [comment]
There are no errors in your logs file ?
Indeed you have quite a lot of "reads not assigned to restriction fragments", but this is not related to the LIGATION_SITE parameter.
This is more a matter of restriction fragment BED file. For instance a common mistake is to use different chromosomes names between the bowtie2 indexes and the Bed files ...

**Comment by AhlemBoudell** [comment]
those are all the log files for on of my 2 samples. 

and i double checked the bed file with the fasta file that i digested and both had the same chromosomes names. 


[bowtie_CEC_4_H7KG7CCX2_L1_2P_global_ce11.log](https://github.com/nservant/HiC-Pro/files/4382148/bowtie_CEC_4_H7KG7CCX2_L1_2P_global_ce11.log)

[bowtie_CEC_4_H7KG7CCX2_L1_2P_ce11.bwt2glob.unmap_local.log](https://github.com/nservant/HiC-Pro/files/4382147/bowtie_CEC_4_H7KG7CCX2_L1_2P_ce11.bwt2glob.unmap_local.log)
[bowtie_CEC_4_H7KG7CCX2_L1_1P_ce11.bwt2glob.unmap_local.log](https://github.com/nservant/HiC-Pro/files/4382145/bowtie_CEC_4_H7KG7CCX2_L1_1P_ce11.bwt2glob.unmap_local.log)
[bowtie_CEC_4_H7KG7CCX2_L1_1P_global_ce11.log](https://github.com/nservant/HiC-Pro/files/4382146/bowtie_CEC_4_H7KG7CCX2_L1_1P_global_ce11.log)

**Comment by AhlemBoudell** [comment]
[mapped_2hic_fragments.log](https://github.com/nservant/HiC-Pro/files/4382173/mapped_2hic_fragments.log)
[mergeSAM.log](https://github.com/nservant/HiC-Pro/files/4382176/mergeSAM.log)
[merge_stat.log](https://github.com/nservant/HiC-Pro/files/4382177/merge_stat.log)
[merge_stats.log](https://github.com/nservant/HiC-Pro/files/4382178/merge_stats.log)

**Comment by AhlemBoudell** [comment]
[merge_valid_interactions.log](https://github.com/nservant/HiC-Pro/files/4382181/merge_valid_interactions.log)
[readsTrimming.log](https://github.com/nservant/HiC-Pro/files/4382182/readsTrimming.log)

**Comment by AhlemBoudell** [comment]
Hi,

In the new run I found this error in one of the log files:

/sw/csi/R/3.5.0/el7_intel2018/lib64/R/bin/exec/R: error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory

after it exited with this error:
Fri Mar 27 03:09:39 +03 2020
Run quality checks for all samples ...
/sw/csi/hicpro/2.10.0/el7_gnu6.4.0/HiC-Pro_2.10.0/scripts/make_plots.sh -c /ibex/scratch/projects/c2055/config-hicproNew.txt -p "all" >> hicproNew.log
make: *** [hic_qc] Error 127

Any idea?

**Comment by nservant** [comment]
Hi
It looks like your R installation has some issue ...
N

**Comment by AhlemBoudell** [comment]
Thanks alot for all the help!
