### ISSUE TITLE
bowtie_global Error 1

### ISSUE THREAD

**Issue by Ferossitiziano** [nservant/HiC-Pro#326]
Dear Nicolas,

I made a test run in interactive mode with both test_data and my own data, using the following command, and it worked. 

HiC-Pro -c config-hicpro.txt -i test_data/ -o Results

When I tried to repeat the analysis by adding "-p" to the previous command line to the submit the job with qsub, I had the following error message:

Exit: Error in reads alignment - Exit
make: *** [HiC-Pro_2.11.3/scripts/Makefile:88: bowtie_global] Error 1 

I checked the logs and they reported the following:

##HiC-Pro mapping
stat: Bad file descriptor
Warning: Could not open read file "rawdata/dixon_2M/SRR400264_00_R1.fq" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1

The test fastq files are dixon_2M/SRR400264_00_R1.fastq.gz and dixon_2M/SRR400264_00_R2.fastq.gz

Could you help me with this issue?

Federico

**Comment by nservant** [comment]
Hi,
Please which HiC-Pro version are you using ? Could you try to install the latest version ? 2.11.3
Thanks

**Comment by Ferossitiziano** [comment]
Hi,

I am already using version 2.11.3

It looks to me the pipeline is expecting the read file to be named with "fq" instead of "fastq.gz", but the "fq" file has not been created.

Thanks,
Federico

**Comment by nservant** [comment]
H,
Strange, we did a lot of test on this version.
Could you check that you have rights on the test_data ? it seems that the file are not readable ?
What about the bowte log ? could you check in the log what is the bowtie command ?

**Comment by Ferossitiziano** [comment]
Hi, 

I think I have permission to access the test_data folder as it comes with "drwxr-xr-x".

This is the bowtie command:

bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/WT/WTRing1bFP75m_00_R1_mm10.bwt2glob.unmap.fastq --rg-id BMG --rg SM:WTRing1bFP75m_00_R1 -p 3 -x bowtie2_index/mm10 -U rawdata/WT/WTRing1bFP75m_00_R1.fastq.gz 2>> logs/WT/WTRing1bFP75m_00_R1_bowtie2.log| /hpcnfs/home/ieo5073/miniconda3/envs/HiCpro/bin/samtools view -F 4 -bS - > bowtie_results/bwt2_global/WT/WTRing1bFP75m_00_R1_mm10.bwt2glob.bam

**Comment by nservant** [comment]
I'm not able to reproduce the issue :(
Where is the error ? because your bowtie command looks good with `.fastq` file (not `.fq`)
Is it in the bowtie2 log file ?

**Comment by nservant** [comment]
or could you check the rawdata folder please ? it should contain links to the rawdata file.
Are they correct ?

**Comment by Ferossitiziano** [comment]
Yes, the bowtie2 command works fine, I tried it myself as well straight from the command line. 
I am running a generic bowtie2 alignment in local mode as this should be the following step in the pipeline, if I'm not wrong. It is working fine.

The link to rawdata looks fine, it points to my raw data. The "inputfiles_test.txt" looks wired to me as in only include the R1 file and not the corresponding R2 file. Is that fine?

**Comment by Ferossitiziano** [comment]
I added the R2 file to the "inputfiles_test.txt" and it gave me the same issue: bowtie_global Error 1.
So that was not the problem.

**Comment by nservant** [comment]
Yes, it's normal. You are using the '-p' option ?

**Comment by Ferossitiziano** [comment]
Yes, I have used the command

HiC-Pro -c config-hicpro.txt -i test_data/ -o Results -p

**Comment by nservant** [comment]
indeed ! I do have an error on my side too ... let me check that and I come back to you ...
Does it work without -p option ?

**Comment by Ferossitiziano** [comment]
Using the interactive mode without "-p" all the jobs work fine.
Thanks

**Comment by nservant** [comment]
Hi Frederico, 
I just make a fix on the devel branch. Many thanks for reporting this issue.
I removed the 2.11.3 tag, and will release the 2.11.4 as soon as I will be sure that this version is ok.
Thanks again !

**Comment by Ferossitiziano** [comment]
Thank you for your help!! I will try to download the files you modified on the devel branch and I will test them.

**Comment by nservant** [comment]
Hi,
I just made a pre-relase 2.11.4 if you want to test.
I hope this one is fine ! thanks

**Comment by Ferossitiziano** [comment]
Hi, 

I have downloaded all the files on the level branch on the Github page and installed HiC-Pro again.
Unfortunately, as already occurred, HiC-Pro works fine in the interactive mode but fail when it is launched with the -p option.

The error I get is still the same:

##HiC-Pro mapping
stat: Bad file descriptor
Warning: Could not open read file "rawdata/dixon_2M/SRR400264_00_R2.fq" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1

It cannot find the file rawdata/dixon_2M/SRR400264_00_R2.fq, but I don't really know why it is not looking for rawdata/dixon_2M/SRR400264_00_R2.fastq.gz, which exist.

Best,
Federico

**Comment by Ferossitiziano** [comment]
Sorry, it looks like I still got version 2.11.3, I'll try to download 2.11.4.

Federico

**Comment by Ferossitiziano** [comment]
The pipeline in parallel mode worked fine with test_data using version 2.11.4.
Thank you very much!

**Comment by nservant** [comment]
great !

**Comment by Mlad22** [comment]
Hi! I have the same problem with the Bowtie_global error 1.
How do I get the 2.11.4 version? 
I somehow always end up installing version 2.11.3. 

Thanks,
Best,
Mlad

**Comment by nservant** [comment]
https://github.com/nservant/HiC-Pro/releases

**Comment by Mlad22** [comment]
thank you!

**Comment by baishengjun** [comment]
Hi，
 I have the same problem with the Bowtie_global error 1. and I use hic-pro version 2.11.4 .
my genome size 530M , I get errors.
when I run genome size 430M , no errors.
I use the same operation with hicpro.  that is strange .
how can I fix it ? 

thanks

**Comment by nservant** [comment]
Hi,
Would you have more info ? logs please ?
Look at the bowtie logs please.
Nicolas

Le 15/05/2020 à 15:20, baishengjun a écrit :

**Comment by Oksanak22** [comment]
Hi. I am suing HiC-Pro 3.1.0 
When I run ./bin/HiC-Pro -i rawdata -o hic_results -c config-hicpro.txt

Run HiC-Pro 3.1.0
--------------------------------------------
Fri Oct 27 10:33:53 PDT 2023
Bowtie2 alignment step1 ...
Logs: logs/Sample1/mapping_step1.log
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
Exit: Error in reads alignment - Exit
make: *** [/home/HiC-Pro_3.1.0/bin/../scripts//Makefile:88: bowtie_global] Error 1

**Comment by BERICP01** [comment]
> Hi. I am suing HiC-Pro 3.1.0 When I run ./bin/HiC-Pro -i rawdata -o hic_results -c config-hicpro.txt
> 
> ## Run HiC-Pro 3.1.0
> Fri Oct 27 10:33:53 PDT 2023 Bowtie2 alignment step1 ... Logs: logs/Sample1/mapping_step1.log [main_samview] fail to read the header from "-". [main_samview] fail to read the header from "-". Exit: Error in reads alignment - Exit make: *** [/home/HiC-Pro_3.1.0/bin/../scripts//Makefile:88: bowtie_global] Error 1

I have the same issue!
Some samples are working, others I get this error, here is the log which seems related to the file descriptor:

##HiC-Pro mapping
stat: Bad file descriptor
Warning: Could not open read file "rawdata/501mel_sgCHD7-2/501mel-sgCHD7-2_S15_L004_R1_001.fastq.gz.fastq" for reading; skipping...
Error: No input read files were valid

@nservant any help would be extremely grateful, I am using the last release of HiC-Pro 3.1.0 like @Oksanak22 

Best
Pietro
