### ISSUE TITLE
'Pre-flight' checks

### ISSUE THREAD

**Issue by biobenkj** [nservant/HiC-Pro#327]
Thanks for HiC-Pro! This is likely an enhancement and am happy to take a swing at it and submit a PR, but it would be awesome to run some 'pre-flight' checks on whether files exist, memory request is sane, number of processors requested exist, etc. before launching the pipeline. I recognize that putting this on the user is reasonable, but would be cool if it could break earlier rather than later.

Again, thanks for HiC-Pro!

**Comment by nservant** [comment]
Hi,
Thanks for your suggestion. In theory, all about input files is already checked by the main script before starting to run.
For everything about RAM, CPUs, etc it's more tricky and I do not think `bash` is the best way to deal with that.
However, we are moving on the nf-core-hic (https://github.com/nf-core/hic) pipeline which is a Nextflow clone of HiC-Pro (so far), and which is much more powerfull to manage all questions about resources, containers, etc.
Best

**Comment by biobenkj** [comment]
Very cool about moving to nf-core! I'll definitely have to check that out since we use nextflow for most of our pipelines! Also, I agree writing some ```bash`` to deal with this could get tricky across platforms. 

I'm running HiC-Pro in allele-specific mode and when I specify the VCF without an absolute path (it sits in the same directory as the config file - and now that I think about it the restriction site bed file also didn't have an absolute path) it will launch the bowtie alignments without complaining and then promptly break because it can't find the VCF post-alignment and sorting. Happy to close this issue and start another if you'd like to pursue it, though the issue is resolved if I specify the full path in front of the file.

Thanks again!

**Comment by biobenkj** [comment]
Also, I'm using the latest version (v2.11.3) as a singularity container. Singularity v3.5.2

**Comment by nservant** [comment]
ok Just to let you know that I just removed the 2.11.3 because we found a bug in the parallel mode.
I just released a pre-built version 2.11.4 which fix this bug.
I'm going to test it again in the coming days to release it at the end of the week.
So please, do not use the 2.11.3. Sorry !!

**Comment by nservant** [comment]
And the nf-core version does not support allele-specific mode so far.
That why HiC-Pro will continue to live :)

**Comment by biobenkj** [comment]
No worries at all. Thanks so much for the insane amount of time, effort, and expertise you've put in to HiC-Pro and HiTC to make analyzing HiC data rather straight forward!
