### ISSUE TITLE
Error in "Combine both alignment" step

### ISSUE THREAD

**Issue by rmurray2** [nservant/HiC-Pro#33]

**Comment by rmurray2** [comment]
Hi,

I'm getting an error in the "Combine both Alignment" step. 

```
Combine both alignment ...
/home/ubuntu/HCP/HiC-Pro_2.7.4b/scripts/bowtie_combine.sh -c /home/ubuntu/HCP/HiC-Pro_2.7.4b/config-hicpro.txt >> hicpro.log
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_header_read] invalid BAM binary header (this is not a BAM file).
/home/ubuntu/HCP/HiC-Pro_2.7.4b/scripts/hic.inc.sh: line 91:  2453 Segmentation fault      (core dumped) /usr/bin/samtools merge -@ 8 -n -f bowtie_results/bwt2/MEF/SRR1300754_R2_mm9.bwt2merged.bam bowtie_results/bwt2_global/MEF/SRR1300754_R2_mm9.bwt2glob.bam bowtie_results/bwt2_local/MEF/SRR1300754_R2_mm9.bwt2glob.unmap_bwt2loc.bam
/home/ubuntu/HCP/HiC-Pro_2.7.4b/scripts/hic.inc.sh: line 91:  2452 Segmentation fault      (core dumped) /usr/bin/samtools merge -@ 8 -n -f bowtie_results/bwt2/MEF/SRR1300754_R1_mm9.bwt2merged.bam bowtie_results/bwt2_global/MEF/SRR1300754_R1_mm9.bwt2glob.bam bowtie_results/bwt2_local/MEF/SRR1300754_R1_mm9.bwt2glob.unmap_bwt2loc.bam

```
Despite this error, the next four steps were carried out, until the "Merge multiple files from the same sample ..." step which threw the error:
```
find: `hic_results/data/': No such file or directory                           │
make: *** [merge_valid_interactions] Error 1                           
```

I haven't looked deeply into what the reason could be for this yet, but could it be an issue with the input fastq data? 

Thanks again

**Comment by nservant** [comment]
Hi,
Yes there is something wrong at the mapping step.
"|invalid BAM binary header (this is not a BAM file).|"

I'm just wondering, how do you set the variable PAIR1_EXT and PAIR2_EXT ?
Could you just make a "samtools view" on the aligned BAM file please ?
You can alos look at the log/bowtie.log file ...
Thank you
N

**Comment by rmurray2** [comment]
The output of running "samtools view" on the globally aligned BAM files seems fine, but I'm getting an error on the locally aligned ones:
```
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from "SRR1300754_R2_mm9.bwt2glob.unmap_bwt2loc.bam".
```

The local alignment log files are present in /logs, but are empty.

**Comment by nservant** [comment]
ok. Would you please try to run the test dataset available at
https://zerkalo.curie.fr/partage/HiC-Pro/
with the configuration file https://zerkalo.curie.fr/partage/HiC-Pro/annotations_4test_data/config_test_latest.txt
This sould tell us if the issue come from you dataset or from your installation.

Then, could you check if you have unmap_trimmed.fastq files in the bwt2_global folder ? These are the inputs of the second mapping steps. Thank you

**Comment by rmurray2** [comment]
Hi, thanks for your suggestions. 

PAIR1_EXT and PAIR2_EXT are _R1 and _R2 respectively

I was eventually able to set up a run which successfully completed this "Combine both alignment" step (not with the test datset), but I don't know for sure what the reason is. I increased my instance's HD space to ~320 GB in the second run (was ~120GB in the first case), and believe this is the only thing I changed, so I would guess that this is the reason for the failure in the first case. 

Not sure if it would be possible to accurately project the maximum size of all temp/data files the pipeline will generate in a given run based on the input fastq file sizes, but it may be helpful to have some kind of check to see if enough space is available on the HD at the beginning of the run. 

In the failed case the R1 and R2 fastq files were each ~35GB and the remaining ~50GB was not enough to support the temp files generate in the mapping step

Thanks

**Comment by nservant** [comment]
Yes indeed
For a 300Gb dataset (zipped fastq files), HiCPro output is around 1.7 Tb 
(factor 5-6)
The mapping itsef step requires 1.4 Tb ... because R1 and R2 are mapped 
independantly (800Gb in this case, almost x3), and then merged (600Gb of 
final BAM)
At the end, I would say that the mapping files can be discarded, as well 
as intermediate results, to keep only the final results (ie. the maps) 
which have a size of 35Gb.
