### ISSUE TITLE
SyntaxError: invalid syntax when running split_sparse.py    

### ISSUE THREAD

**Issue by chenggang108** [nservant/HiC-Pro#331]
Hi,

I am running split_sparse.py to split matrix to each individual chromosome. I ran into a SyntaxError.
Here is how it shows: 

File "HiC-Pro/bin/utils/split_sparse.py", line 77
    print str(chrnames[i-1]) + "..."
            ^
SyntaxError: invalid syntax

Anyone can help with it?

Thanks

Gang

**Comment by nservant** [comment]
Hi,
I think you are using python 3.
The current version of HiC-Pro only works with python 2.
Best
