### ISSUE TITLE
High percentage invalid pairs

### ISSUE THREAD

**Issue by Ferossitiziano** [nservant/HiC-Pro#332]
Dear all,

My statistics of Read Pairs Alignment on Restriction Fragments reported the 90% of my interactions were invalid pairs. The 76.2% of these were Dangling_end_pairs. I was wondering if any other user got the same problem or what is the average value users had on this parameter. That would be really helpful for my experiment optimisation.

Federico

**Comment by nservant** [comment]
Hi Frederico,
t means that the ligation step did not work .. So to me this is more an experimental issue ...
Best
Nicolas
