### ISSUE TITLE
Trooble to launch HiCpro from building raw map step

### ISSUE THREAD

**Issue by El-Castor** [nservant/HiC-Pro#333]
Hi !
Thanks a lot for this amazing tool. I have some difficulties to relaunch HiCpro from the buiilding raw matrix step ( with the aargument -s).

here you can see my command that I launch : 

`bash
<PATH_To_HICpro>  -i /PATH_to_HiCPro_output/hic_results/data -o outputHicProLeafPacBioGM2 -c config_leaf_pacbio.txt -s build_contact_maps -s ice_norm 
`

but I have an error in which HiCpro doesn't find the all_validParis file, that I use to produced map before...

Do You have an Idea ?thanks in advance

**Comment by El-Castor** [comment]
this is the error from HiCpro : 
`Directory Hierarchy of rawdata '.../hic_results/data/leaf' is not correct. No '_allValidPairs' files detected
`
But there are in this directory, and they are not corrupt.

**Comment by nservant** [comment]
Issue closed. I guess it's ok ?

**Comment by El-Castor** [comment]
Hi !
Yes sorry It was my fault. the directory that I give was not good.

Thanks

Le mar. 21 avr. 2020 à 12:37, Nicolas Servant <notifications@github.com> a
écrit :
