### ISSUE TITLE
Is there any description about the .allValidPairs?

### ISSUE THREAD

**Issue by LeopoldC** [nservant/HiC-Pro#338]
Hi Nicolas,
I want to convert the result of read mapping output, is there any description of each column of the .allValidPairs file somewhere? Didn't find it in the manual.

Best
Léopold

**Comment by nservant** [comment]
Hi Léopold,
https://nservant.github.io/HiC-Pro/RESULTS.html#list-of-valid-interaction-products
But it is not upd-to-date :)

read name / chr_reads1 / pos_reads1 / strand_reads1 / chr_reads2 / pos_reads2 / strand_reads2 / fragment_size / res_frag1/ mapq1 / res_frag2 / mapq2 [/ allele_specific_tag]

N

**Comment by LeopoldC** [comment]
perfect thanks, sorry to didn't find it :D

**Comment by hanshanmengqi** [comment]
Hi @nservant,
I just wonder the pos_reads1 means the start of read1 position?
Another point, the fragment_size means the length of read1 and read2?

Thank you for your time.
Best,
Han
