### ISSUE TITLE
make: *** [hic_qc] Error 1

### ISSUE THREAD

**Issue by DRosen1996** [nservant/HiC-Pro#340]
Hello
When I use HIC-PRO
make: *** [hic_qc] Error 1
![QQ截图20200618112903](https://user-images.githubusercontent.com/30267741/84975250-761b6780-b157-11ea-9b52-c8ed95d5a923.png)
This error occurs when I run the software with my own data and test data，What is the general reason?

![image](https://user-images.githubusercontent.com/30267741/84975613-710ae800-b158-11ea-9f62-e067992c5dd6.png)

Is it about merge？

**Comment by nservant** [comment]
Hi
Yes, there was an error at the merging step.
I pretty sure this is a sort issue.
Could you try to look into the log folder, any error message at this step ?
N

**Comment by DRosen1996** [comment]
> Hi
> Yes, there was an error at the merging step.
> I pretty sure this is a sort issue.
> Could you try to look into the log folder, any error message at this step ?
> N

Thank you for your reply.
I found out that the reason for my previous error was that I didn't correct the "PAIR1_EXT" in the configuration file, but after the modification, the same problem still appears in the end.

![image](https://user-images.githubusercontent.com/30267741/84998933-133fc580-b183-11ea-9d0b-736acf8fd9f4.png)

[config_test_latest.txt](https://github.com/nservant/HiC-Pro/files/4802036/config_test_latest.txt)
[mergeSAM.log](https://github.com/nservant/HiC-Pro/files/4802044/mergeSAM.log)
mapped_2hic_fragments.log：
![image](https://user-images.githubusercontent.com/30267741/85089017-0b7c3180-b214-11ea-819f-37d8967e436b.png)

[plot_hic_contacts.Rout.txt](https://github.com/nservant/HiC-Pro/files/4802068/plot_hic_contacts.Rout.txt)
[plot_hic_fragment.Rout.txt](https://github.com/nservant/HiC-Pro/files/4802069/plot_hic_fragment.Rout.txt)
[plot_mapping_portion.Rout.txt](https://github.com/nservant/HiC-Pro/files/4802070/plot_mapping_portion.Rout.txt)
[plot_pairing_portion.Rout.txt](https://github.com/nservant/HiC-Pro/files/4802071/plot_pairing_portion.Rout.txt)

**Comment by DRosen1996** [comment]
I found error in plot_hic_contacts.Rout
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
Calls: lapply -> FUN -> read.table
Execution halted

**Comment by DRosen1996** [comment]
I've solved the problem that the names of my chromosomes don't match the reference genome
