### ISSUE TITLE
some stripe without any scores

### ISSUE THREAD

**Issue by biohubx** [nservant/HiC-Pro#345]
Hi,
   I converted iced matrix to mcool format, and visualize it using HiGlass, but there are a lot of stripes without any scores.
 
  I ran step1 to map every paired-end fastq files to genome.
   After the step1, I merged all .validPairs. BTW, my Hi-C data is consisted of 5 replicates(hereafter refer to as cluster). each replicate (cluster) is consisted of 4 replicates.

   Do you know what is wrong?
![image](https://user-images.githubusercontent.com/12387462/86621833-e534f080-bf8c-11ea-8f25-f236318e79b4.png)

**Comment by nservant** [comment]
Hi,
Do you have the same if you start from raw data ?
The iced normalization usually removes low counts rows/columns. The threshold can be changed in the config.
But as cooler is able to normalize on the fly the data, I usually advice to convert the raw data into cool file.
N
