### ISSUE TITLE
Pipeline Fails while ICE Normalization

### ISSUE THREAD

**Issue by rkash** [nservant/HiC-Pro#349]
Hi,

I have the following libraries installed.

bx==0.3.0
bx-python==0.8.9
iced==0.5.7
numpy==1.16.6
pandas==0.24.2
pysam==0.16.0.1
python-dateutil==2.8.1
pytz==2020.1
scipy==1.2.3
[ice_500000.log](https://github.com/nservant/HiC-Pro/files/5014920/ice_500000.log)

six==1.15.0

While running ICE normalization I am facing the following error.
I am running the pipeline on test data provided in the software

Traceback (most recent call last):
  File "/usr/local/bin/HiC-Pro_2.11.1/scripts/ice", line 83, in <module>
    counts = sparse.coo_matrix((data, (i - 1, j - 1)), shape=(N, N), dtype=float)
  File "/home/kaustavs/.local/lib/python2.7/site-packages/scipy/sparse/coo.py", line 154, in __init__
    self._shape = check_shape((M, N))
  File "/home/kaustavs/.local/lib/python2.7/site-packages/scipy/sparse/sputils.py", line 286, in check_shape
    new_shape = tuple(operator.index(arg) for arg in args)
  File "/home/kaustavs/.local/lib/python2.7/site-packages/scipy/sparse/sputils.py", line 286, in <genexpr>
    new_shape = tuple(operator.index(arg) for arg in args)
TypeError: 'numpy.float64' object cannot be interpreted as an index

Thanks in advance

**Comment by nservant** [comment]
@NelleV , any idea ?
@rkash , anyway I would advice to move to the last HiC-Pro stable version 2.11.4 (or even 3.0.0 from the devel branch which is not yet release). The main difference is that these versions are now simply using `iced` and no longer include it within HiC-Pro.

**Comment by NelleV** [comment]
This error should have been fixed in recent version of iced. Indeed, upgrading to the last version of HiC-pro should fix the issue.
