### ISSUE TITLE
Pairing of R1 and R2 tags Error

### ISSUE THREAD

**Issue by rmurray2** [nservant/HiC-Pro#35]
The last command run in the main log file is running mergeSAM.py and the error it produced is: 

> Forward and reverse reads not paired. Check that BAM files are sorted. 

The mergeSAM.log file last line says:

> Forward and reverse reads not paired. Check that BAM files are sorted.

Using samtools Version: 1.3 (using htslib 1.3) and HiC-Pro 2.7.4b

**Comment by nservant** [comment]
Not sure why the SAM file are not sorted. Could check this ? the 
bowtie_results/bwt2/*bwt2merged.bam files should be sorted. Could you 
give me the content of bowtie_results folder please ?
Are you using the test data or your own data ?
Thank you

**Comment by rmurray2** [comment]
> Could you give me the content of bowtie_results folder please ?

I can give you ssh access to the Amazon instance I've been working on, if by this you mean that you're interested in seeing the actual files.

> Are you using the test data or your own data ?

In this case with the error I was not using the test data. The data I used was originally in a combined-read single SRR file which I split into _R1, R2 read files by doing

`fastq-dump -I --split-files SRR_file.srr`
(original file available via FTP [here](ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByStudy/sra/SRP/SRP042/SRP042275/SRR1300754/))

I processed the _test_ data successfully to the end, however, so I'm thinking now there's a problem with my input data rather than with the installation

**Comment by rmurray2** [comment]
I'm pretty sure I found the reason this error was occurring. 

To remind you of the situation, HiC-Pro runs with my own input data weren't working (as described above), but runs with the test data were completing successfully. So - makes sense that there was some problem with my input data. 

My input data came in `.sra` format, with the reads combined instead of split into R1, R2, as HiC-Pro requires. So, to prepare my data, I used `fastq-dump` to split the reads using 

`fastq-dump -I --split-files srafile.sra`

as far as I can tell, the `-I` option was the culprit in producing the incompatible input data. The NCBI description for this option is:

> Append read id after spot id as 'accession.spot.readid' on defline.

this command results in two fastq files which don't have entries with exactly the same IDs for entries that came from the same read. In other words, for a given read in the R1 file with a particular ID, there is no corresponding read in the R2 file with exactly the same ID. For the HiC-Pro test data, exact matching IDs could be found between the R1 and R2 files. 

When removing the `-I` option from the `fastq-dump` command,  the run completed successfully. 

Not sure if this requirement (exact matches in ID between R1/R2 files) is mentioned somewhere in the docs, but it would be useful, I think, to handle situations in which users have paired read files as input; in my case a lot of time would have been saved.

**Comment by nservant** [comment]
Thank you very much for your feedback. Indeed, R1 and R2 must have the same name at the pairing step. I will add something in the manual and in the FAQ.
Thanks again !
N

**Comment by werhoog** [comment]
I met the same problem.what can I do ?I used the same  name at the pairing in the same fold. Just look like this:
Pol-I_1.clean_mm10.bwt2pairs.bam  
Pol-I_1_R1.clean_mm10.bwt2merged.bam  
Pol-I_1_R1.clean_mm10.mapstat  
Pol-I_1_R2.clean_mm10.bwt2merged.bam  
Pol-I_1_R2.clean_mm10.mapstat


It is my data.However ,I think any R1 and R2 can pairing .But I failed .
What is wrong?

**Comment by werhoog** [comment]
Actually . for some low quality reads.I have filter them.Is  this reason counts?

**Comment by milkcookie** [comment]
Hi all:
I also met this problem, when I use my data, but this data is ok before? I don't know why error happen?
why not it unpaired or have diff name?
this is log
## mergeBAM.py
## forward= bowtie_results/bwt2/sample1/Mg_R1_reference.fasta.bwt2merged.bam
## reverse= bowtie_results/bwt2/sample1/Mg_R2_reference.fasta.bwt2merged.bam
## output= bowtie_results/bwt2/sample1/Mg_reference.fasta.bwt2pairs.bam
## min mapq= 0
## report_single= False
## report_multi= False
## verbose= True
## Merging forward and reverse tags ...
## 1000000
## 2000000
## 3000000
## 4000000
## 5000000
## 6000000
## 7000000
## 8000000
## 9000000
## 10000000
## 11000000
## 12000000
## 13000000
## 14000000
## 15000000
## 16000000
## 17000000
## 18000000
## 19000000
## 20000000
## 21000000
## 22000000
......
## 208000000
## 209000000
## 210000000
## 211000000
## 212000000
## 213000000
## 214000000
## 215000000
## 216000000
## 217000000
## 218000000
## 219000000
## 220000000
## 221000000
## 222000000
## 223000000
## 224000000
Forward and reverse reads not paired. Check that BAM files have the same read names and are sorted.
can you help me to solve the problem?
I can run successful with this data before with a old genome? becouse of the genome ?

**Comment by ChenfuShi** [comment]
Hi, I'm having the same issue. My files have indeed the .1 and .2 after each read depending if they are coming from read 1 or read 2. Is there any way to solve this problem? possibly without having to write a function to remove the .1 and .2 from the reads :)?

**Comment by milkcookie** [comment]
Hi @ChenfuShi 
You can solve the problem by remove the single reads in two fastq file, the command:
bwa index -a bwtsw reference.fasta
samtools faidx reference.fasta
bwa mem -t 24 -R "@RG\tID:<ID>\tLB:<LIBRARY_78>\tSM:<78>\tPL:ILLUMINA" reference.fasta Mg_R1.fq.gz Mg_R2.fq.gz | samtools view -bS > out.bamsamtools sort -n out.bam > sorted.bam
bamToFastq -i sorted.bam -fq out.R1.fastq -fq2 out.R2.fastq
gzip out.R1.fastq
gzip out.R2.fastq
if it not working, you can use bowtie2 to do align in the command.
Best wishes.
Hansong Yan
FAFU

**Comment by nservant** [comment]
I fyou wait a couple of days, I'll try to release a new version that fix this bug ;)

**Comment by ChenfuShi** [comment]
Hi @nservant and @milkcookie ,
Thanks for your answers. In the meantime I wrote a small script that fixes the problem on the fastq level although it works only on files from the NCBI SRA (which might be the only ones that are affected by this problem?)

[fastq_qname_cleaner.zip](https://github.com/nservant/HiC-Pro/files/2249253/fastq_qname_cleaner.zip)

**Comment by zyqfrog10** [comment]
Thank you very much, @ChenfuShi 
That's very helpful!
It would be nice if this problem was mentioned in the manual.
