### ISSUE TITLE
NameError: name 'or1_fragname' is not defined

### ISSUE THREAD

**Issue by jeffpkamp** [nservant/HiC-Pro#353]
HiCPRO version: HiC-Pro version 2.11.1

I've seen several people have this issue and it's usually because they had differently named chromosomes between their index and their.  I don't think this is the issue for me.  I have 4 samples from a sequencing run and three of them run file while one of them keeps failing with this in the log.
```
## maxInsertSize= None
## minFragSize= None
## maxFragSize= None
## allOuput= True
## SAM ouput= False
## verbose= True

## Loading Restriction File Intervals ' /uufs/chpc.utah.edu/common/home/gertz-group1/u6004424/hg19/hg19_GATC_resfrag.bed '...
load_restriction_fragment function took 54114.587 ms
## Opening SAM/BAM file ' bowtie_results/bwt2/18111X2_hicpro_input/18111X2_200731_A00421_0225_BHMKWHDRXX_S10_L002_001_hg19.bwt2pairs.bam '...
## Classifying Interactions ...
Warning - no restriction fragments for  A00421:225:HMKWHDRXX:2:1101:1000:1094  at  chrUn_gl000224 : 37751
Warning - no restriction fragments for  A00421:225:HMKWHDRXX:2:1101:1000:1094  at  chrUn_gl000224 : 37439
Traceback (most recent call last):
  File "/usr/local/bin/HiC-Pro_2.11.1/scripts/mapped_2hic_fragments.py", line 744, in <module>
    str(htag) + "\n")
NameError: name 'or1_fragname' is not defined
```
  I left out the chrUn_* samples from my restriction fragment map because they are uninformative.  
also in my other samples, there are numerouse warnings about no restriction fragments for these extra-chromosome regions and they finish just fine.

Let me know what else I can share to help figure this out.

**Comment by nservant** [comment]
Could you please try the 2.11.4 version, which should fix the issue ?
Thanks

**Comment by jeffpkamp** [comment]
That fixed it.  Just thought I would let you know your build recipe for the singularity is a little messed up for the dev build.  It requests program versions that the make says are too old.

**Comment by nservant** [comment]
Yes, thanks. I should release a new version 3.0 soon. The version is ready on the devel branch and now uses python3
