### ISSUE TITLE
Ice normalization failed 

### ISSUE THREAD

**Issue by AhlemBoudell** [nservant/HiC-Pro#354]
Hi,

I have the following issue while running the 2nd step of hic-pro in our cluster:
Logs: logs/CEC_4/ice_40000.log
make: *** [ice_norm] Error 127

and in the log file, it says:

ice --results_filename hic_results/matrix/CEC_4/iced/40000/CEC_4_40000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 --verbose 1 hic_results/matrix//CEC_4/raw/40000/CEC_4_40000.matrix
/ibex/sw/csi/hic-pro/2.11.4/el7.7_python2.7/HiC-Pro_2.11.4/scripts/hic.inc.sh: line 86: ice: command not found

Any idea why is this the case?

**Comment by nservant** [comment]
It seems that the `iced` python package is not installed. Could you please install it and try again ?

**Comment by AhlemBoudell** [comment]
I was running it in our cluster when i got this error. I checked the ice package first and it was there so it didnt make sense.
I am sunning the normalization stem locally and its working.
Thanks for the input.

Ahlem
