### ISSUE TITLE
running on cluster Slurm

### ISSUE THREAD

**Issue by ahmedabbas81** [nservant/HiC-Pro#356]
Hello,

I am trying to run on slurm

However it produces two .sh files and ask to run them using qsub (not sbatch although I am running on slurm)

and when using `sbatch HiCPro_step1_.sh` , it says sbatch command not found. And also when trying `qsub HiCPro_step1_.sh`, it says qsub command not found.

Any suggestions

Thank you

**Comment by ahmedabbas81** [comment]
It is worth noting that I am using singularity

**Comment by nservant** [comment]
Hi
I not sure to understand why the `sbatch` command is not working.
How do you submit jobs on your cluster ?
Or how are you using singularity ?

I never really try singularity with the parallel mode ... I guess you migth need to update the `.sh` file to call singularity within these files ... I can try to take time to make additional tests.
N
