### ISSUE TITLE
Merging replicates and downstream analysis with HOMER

### ISSUE THREAD

**Issue by sanchari24** [nservant/HiC-Pro#357]
Hello,
I have the paired end fastq files for two replicates.
I want to merge them to increase the depth and run HOMER on the combined valid pairs. 

Looking for suggestion for the best way to do this. Thank you.

**Comment by nservant** [comment]
Hi,
If you put all fastq files in the same input folder, you will have one `.validPairs` file per fastq pair, and one `.allValidPairs` which is the merge of the two first.
Otherwise, you can simply merge them by hand !
Best

**Comment by sanchari24** [comment]
Hi thanks for the input, I could merge them. 
By the way, I wanted to ask if you have any idea about .AppleDouble files being created whenever I run HiC-Pro ?

./HiC_pro_result_V2/logs/CHiC_swnclf_mutant/.AppleDouble
./HiC_pro_result_V2/logs/CHiC_Col_control/.AppleDouble

**Comment by nservant** [comment]
Nope. Never heard about that :)
