### ISSUE TITLE
hicpro2juicebox

### ISSUE THREAD

**Issue by biohubx** [nservant/HiC-Pro#358]
Hi,
   when I ran hicpro2juicebox.sh, I got the file suitable for juicebox. However, I want to know whether hicpro2juicebox.sh produced normalized matrix or not.
Best,

**Comment by nservant** [comment]
Juicer requires the valid pairs to build the `.hic` file.
Regarding the normalization, I'm not 100% sure, you should check in the Juicer manual if it normalizes the data on-the-fly when it creates the `.hic` file ?
Best
