### ISSUE TITLE
errors when job array is large

### ISSUE THREAD

**Issue by adippolito12** [nservant/HiC-Pro#36]
Hey Nicolas,

I'm noticing an issue that I sometimes have when I run Step1 of the pipeline with large datasets (which have large job arrays -- 100s of jobs). Sometimes a few of these array jobs fail to complete successfully, but when I go back and re-execute commands on the input data used in that specific array job, it completes successfully. Here is an example of one of these errors (I wish I had more examples of this to show, but I've just reran the pipeline in the past, and everything seems to go to completion):

---

Thu Mar  3 14:48:45 EST 2016
Bowtie2 alignment step1 ...
## /gpfs/fs0/data/lab/Tony/tools/HiC-Pro_2.7.2b/scripts/bowtie_wrap.sh -c /data/lab/Tony/HiC/folder/config-hicpro.txt -u >> hicpro.log

Thu Mar  3 15:00:56 EST 2016
Bowtie2 alignment step2 ...
## /gpfs/fs0/data/lab/Tony/tools/HiC-Pro_2.7.2b/scripts/bowtie_wrap.sh -c /data/lab/Tony/HiC/folder/config-hicpro.txt -l >> hicpro.log

Thu Mar  3 15:05:29 EST 2016
Combine both alignment ...
/gpfs/fs0/data/lab/Tony/tools/HiC-Pro_2.7.2b/scripts/bowtie_combine.sh -c /data/lab/Tony/HiC/folder/config-hicpro.txt >> hicpro.log
## [pretty_header] invalid header

Thu Mar  3 15:06:21 EST 2016
Bowtie2 mapping statistics for R1 and R2 tags ...
/gpfs/fs0/data/lab/Tony/tools/HiC-Pro_2.7.2b/scripts/mapping_stat.sh -c /data/lab/Tony/HiC/folder/config-hicpro.txt >> hicpro.log
[E::hts_open] fail to open file 'bowtie_results/bwt2/REP2/AMD240_S8_L001_ad_R1_hg19.bwt2merged.bam'
## samtools: failed to open "bowtie_results/bwt2/REP2/AMD240_S8_L001_ad_R1_hg19.bwt2merged.bam" for reading: No such file or directory

Thu Mar  3 15:06:42 EST 2016
Pairing of R1 and R2 tags ...
/gpfs/fs0/data/lab/Tony/tools/HiC-Pro_2.7.2b/scripts/bowtie_pairing.sh -c /data/lab/Tony/HiC/folder/config-hicpro.txt >> hicpro.log
Traceback (most recent call last):
  File "/gpfs/fs0/data/lab/Tony/tools/HiC-Pro_2.7.2b/scripts/mergeSAM.py", line 216, in <module>
    with  pysam.Samfile(R1file, "rb") as hr1,  pysam.Samfile(R2file, "rb") as hr2: 
  File "pysam/calignmentfile.pyx", line 318, in pysam.calignmentfile.AlignmentFile.**cinit** (pysam/calignmentfile.c:4730)
  File "pysam/calignmentfile.pyx", line 534, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7261)
IOError: file `bowtie_results/bwt2/REP2/AMD240_S8_L001_ad_R1_hg19.bwt2merged.bam` not found
make: **\* [bowtie_pairing] Error 1

**Comment by nservant** [comment]
Hi Tony
Thanks for your feedbacks.
Difficult to know if this is something due to HiC-Pro itself or if this 
is something due to the cluster. It seems that for some jobs, the 
mapping does not run properly ?
I would like to take time to improve the reporting errors. I can plan to 
make some tests.
N

Le 15/03/2016 20:14, adippolito12 a écrit :
>
> Hey Nicolas,
>
> I'm noticing an issue that I sometimes have when I run Step1 of the 
> pipeline with large datasets (which have large job arrays -- 100s of 
> jobs). Sometimes a few of these array jobs fail to complete 
> successfully, but when I go back and re-execute commands on the input 
> data used in that specific array job, it completes successfully. Here 
> is an example of one of these errors (I wish I had more examples of 
> this to show, but I've just reran the pipeline in the past, and 
> everything seems to go to completion):
>
> ------------------------------------------------------------------------
>
> Thu Mar 3 14:48:45 EST 2016
> Bowtie2 alignment step1 ...
>
>
>     /gpfs/fs0/data/reddylab/Tony/tools/HiC-Pro_2.7.2b/scripts/bowtie_wrap.sh
>     -c /data/reddylab/Tony/HiC/folder/config-hicpro.txt -u >> hicpro.log
>
> Thu Mar 3 15:00:56 EST 2016
> Bowtie2 alignment step2 ...
>
>
>     /gpfs/fs0/data/reddylab/Tony/tools/HiC-Pro_2.7.2b/scripts/bowtie_wrap.sh
>     -c /data/reddylab/Tony/HiC/folder/config-hicpro.txt -l >> hicpro.log
>
> Thu Mar 3 15:05:29 EST 2016
> Combine both alignment ...
> /gpfs/fs0/data/reddylab/Tony/tools/HiC-Pro_2.7.2b/scripts/bowtie_combine.sh 
> -c /data/reddylab/Tony/HiC/folder/config-hicpro.txt >> hicpro.log
>
>
>     [pretty_header] invalid header
>
> Thu Mar 3 15:06:21 EST 2016
> Bowtie2 mapping statistics for R1 and R2 tags ...
> /gpfs/fs0/data/reddylab/Tony/tools/HiC-Pro_2.7.2b/scripts/mapping_stat.sh 
> -c /data/reddylab/Tony/HiC/folder/config-hicpro.txt >> hicpro.log
> [E::hts_open] fail to open file 
> 'bowtie_results/bwt2/REP2/AMD240_S8_L001_ad_R1_hg19.bwt2merged.bam'
>
>
>     samtools: failed to open
>     "bowtie_results/bwt2/REP2/AMD240_S8_L001_ad_R1_hg19.bwt2merged.bam" for
>     reading: No such file or directory
>
> Thu Mar 3 15:06:42 EST 2016
> Pairing of R1 and R2 tags ...
> /gpfs/fs0/data/reddylab/Tony/tools/HiC-Pro_2.7.2b/scripts/bowtie_pairing.sh 
> -c /data/reddylab/Tony/HiC/folder/config-hicpro.txt >> hicpro.log
> Traceback (most recent call last):
> File 
> "/gpfs/fs0/data/reddylab/Tony/tools/HiC-Pro_2.7.2b/scripts/mergeSAM.py", 
> line 216, in
> with pysam.Samfile(R1file, "rb") as hr1, pysam.Samfile(R2file, "rb") 
> as hr2:
> File "pysam/calignmentfile.pyx", line 318, in 
> pysam.calignmentfile.AlignmentFile.*cinit* (pysam/calignmentfile.c:4730)
> File "pysam/calignmentfile.pyx", line 534, in 
> pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7261)
> IOError: file 
> |bowtie_results/bwt2/REP2/AMD240_S8_L001_ad_R1_hg19.bwt2merged.bam| 
> not found
> make: *** [bowtie_pairing] Error 1
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nservant/HiC-Pro/issues/36>
>


-- 
Nicolas Servant
Equipe NGS Analyse

Institut Curie, Plateforme de Bioinformatique
Unité 900 : Institut Curie - Inserm - Mines ParisTech
26, rue d'Ulm - 75248 Paris Cedex 05 - FRANCE
Email: Nicolas.Servant@curie.fr
Tel: 01 56 24 69 85
