### ISSUE TITLE
allvalidpairs to bedpe format

### ISSUE THREAD

**Issue by KunFang93** [nservant/HiC-Pro#362]
Hi, Nservant

I was wondering if there is a way to convert allvalidpairs results to bedpe format like this  

```
chr1   9945	10095	chr1	  248946216	248946366	.	.	+	+
```

I found that in this [thread](https://groups.google.com/g/hic-pro/c/qhHNbQVJfYY), you mentioned that 3rd and 6th cols is the middle of the reads. So I guess this conversion will be good? 
```
chrom    3rd-(read-len)/2    3rd+(read-len)/2  chrom    6th-(read-len)/2    6th+(read-len)/2  .   .   strand1    strand2
```

Thanks!
Best,
Kun

**Comment by nservant** [comment]
Hi Kun,
Yes, it should be ok.
Of note, the position which is in the allvalidpairs files are now the 5' of the reads.
In the first HiC-Pro versions, I was indeed using the middle of the reads, but this has been change in the latest versions.
Best

**Comment by KunFang93** [comment]
Understand~Thanks for your reply!

Best,
Kun
