### ISSUE TITLE
Allele specific analysis

### ISSUE THREAD

**Issue by AROMDLAB** [nservant/HiC-Pro#363]
Hello Nicholas
Have you modified the allele specific analysis in HiC Pro for human samples?  
Thanks
Annabelle

**Comment by nservant** [comment]
Dear Annabelle,
What do you mean exactly ?
In any case, HiC-Pro requires the phased SNPs information to distinguish parental alleles.
Then, the analysis should be the same for Mouse or Human ?
Best

**Comment by AROMDLAB** [comment]
Thanks Nicholas for the quick reply.  I’m particularly interested in the effect of a single SNP on chromatin architecture.  I have generated 6 HiC libraries from 6 individuals with 3 representing the minor allele and 3 representing the reference allele.  Do I need to impute a haplotype to distinguish parental alleles?
Thanks again
Annabelle

**Comment by nservant** [comment]
Sorry for the delay.
That's a very nice question. As you only have one SNP, I'm not sure that the allele-specific mode of HiC-Pro is the best way to go, as it was designed for whole parental mapping.
As a first approach, I think I would go for a simple comparison of the contact maps. In this case, you should be able to see how this SNP impacts the local interaction.
The allele specific mode only has some interest if within a single sample, you would like to distinguish reads from two (or more) alleles. But as far as I understood, this is not your case ? Your individuals are all homozygous at the SNP position ?
Best

**Comment by AROMDLAB** [comment]
Hi Nicolas
Yes, all samples are homozygous at the SNP site.  Thanks for the explanation about the allele specific analysis.  It was very helpful and I will proceed with the comparison study and not use this analysis.
Thanks
Annabelle

**Comment by AROMDLAB** [comment]
Hi Nicholas
Would you be interested in being a coauthor on the paper?  I’m writing it up based on HiC capture of cells carrying the reference and risk cardiovascular alleles.  It would be great to have your expertise.
Thanks
Annabelle

**Comment by nservant** [comment]
Thank you Annabelle. that's very kind, but I do not think the small advices I can give to you would deserve a co-authorship ;)
And i do not have enough time to do much more myself. But if you have any question, i'll be happy to help.
Nicolas

**Comment by AROMDLAB** [comment]
Thank you Nicolas.  I will followup with you on the paper as it advances.
Thanks for your generosity
Annabelle

**Comment by AROMDLAB** [comment]
Hi Nicholas
I hope all is well with you and yours.  I’m having success publishing work with our HiC data and your HiCPro program.  I recently came across HiCeekR but the package doesn’t run very well.  I’ve reached out to Claudia Angeliini, but have not gotten a response.  Have you worked on integrating omics datasets, such as RNASeq, into HiCPro or HiTC?
Thanks for any help you can provide
Annabelle
