### ISSUE TITLE
the input file for diffhic

### ISSUE THREAD

**Issue by QianzhaoJ** [nservant/HiC-Pro#364]
Hi
   I tried to use `diffhic` for differential analysis of Hi-C data, and I found that the input files for `diffhic` need to be a name-sorted BAM file, so can I used the bam files provided by `HiC-Pro` directly ? By the way, I found that I need to assign and filtering fragments in `diffhic `, so maybe I can use the ValidPairs file in `HiC-Pro` as input files ?
   Thanks in advance !
Best wishes
Qianzhao

**Comment by nservant** [comment]
Hi,
If you run HiC-Pro with GET_PROCESS_SAM=1, it will generate a BAM file with all mapped reads and a flag 'CT' specifying if this a valid interaction (VI) or not.
So you should be able to easily extract from the BAM file, the reads coming from valid interactions.
Then, I'm not an expert of `diffhic`, but if there is a way to directly give valid interaction, then validPais should be ok.
Best
