### ISSUE TITLE
Error about bx-python during the installation of HiC-Pro

### ISSUE THREAD

**Issue by Jerry-Zhao** [nservant/HiC-Pro#366]
I have a problem with the installation of HiC-Pro in Ubuntu 18.04.3. 
1. I tried the singularity container, but it did not work on my test data. (BTW, use bind to mount other HDDs is not convenient). 
2. I tried to install HiC-Pro from source, got an error message during "make configure", 
   "raise ImportError('Error - bx-python cannot be imported')"
  I tried four possible solutions, but all failed. 
  A. Use system python2.7, installed the bx-python versions of 0.5.0, 0.7.1, and 0.7.3, but all failed. 
  B. I re-installed python2.7.18 from source, and configure it with "--enable-unicode=ucs2", failed. 
  C. I tried to insatll an older version, HiC-Pro-2.11.1, failed. 
  D. I used conda to install every dependencies and HiC-Pro, tried bx-python versions of 0.7.3 and 0.8.9, failed. 

  For every one of these solutions, I tried "import bx.intervals" in python, and no problem. 

I am wondering is there a way to solve this "bx-python" problem? 

Thanks. 

Best,
Jerry

**Comment by nservant** [comment]
Hi
I can advice to try to use the latest version on the devel branch.
I iwll release it soon. This is a new python3 based version, with a full conda env available.
I hope it will help
Best

**Comment by Jerry-Zhao** [comment]
Sure. Thanks. 
I will try the Python3 version. 

Best,
Jerry
