### ISSUE TITLE
Allele-specific - markAllelicStatus.py issue for HiC-Pro_2.11.4

### ISSUE THREAD

**Issue by StephF-1130** [nservant/HiC-Pro#367]
markallelicstatus does not support compressed vcf files.
I added this
 if ".gz" in in_file :
        import gzip
        vcf_handle = gzip.open( in_file, 'r')
    else:
        ...
for this to work. 
Thanks

**Comment by nservant** [comment]
Thanks for your comment !

**Comment by nservant** [comment]
done in 3.0.0
