### ISSUE TITLE
build_raw_maps error

### ISSUE THREAD

**Issue by shiyi-pan** [nservant/HiC-Pro#368]
hi, I run HiC-Pro in test data and it run well but when I used it on my data , I met a error like this:
--------------------------------------------
Mon Sep 21 14:58:24 CST 2020
Pairing of R1 and R2 tags ...
Logs: logs/sample1/mergeSAM.log

--------------------------------------------
Mon Sep 21 19:48:08 CST 2020
Assign alignments to restriction fragments ...
Logs: logs/sample1/mapped_2hic_fragments.log

--------------------------------------------
Tue Sep 22 03:19:53 CST 2020
Merge chunks from the same sample ...
Logs: logs/sample1/merge_valid_interactions.log

--------------------------------------------
Tue Sep 22 03:24:08 CST 2020
Merge stat files per sample ...
Logs: logs/sample1/merge_stats.log

--------------------------------------------
Tue Sep 22 03:24:09 CST 2020
Run quality checks for all samples ...
Logs: logs/sample1/make_Rplots.log

--------------------------------------------
Tue Sep 22 03:24:32 CST 2020
Generate binned matrix files ...
Logs: logs/sample1/build_raw_maps.log
make: *** [build_raw_maps] Error 134

I tracked the error and found the logs when it happended. here is the logs:

cat hic_results/data//sample1/sample1.allValidPairs | /ds3512/home/panyp/ruanjian/hic-pro/HiC-Pro_2.11.1/scripts/build_matrix --matrix-format upper --binsize 500000 --chrsizes /ds3512/home/panyp/ru
anjian/hic-pro/HiC-Pro_2.11.1/annotation/genome.fasta.size --ifile /dev/stdin --oprefix hic_results/matrix/sample1/raw/500000/sample1_${bsize}
build_matrix: /ds3512/home/panyp/Hi-C/HiC-Pro-2.11.1/scripts/src/build_matrix.cpp:225: Chromosome::Chromosome(const std::string&, chrsize_t, chrsize_t, chrsize_t, bool, const ChrRegions*): Assertio
n `chr_map.find(name) == chr_map.end()' failed.
/ds3512/home/panyp/ruanjian/hic-pro/HiC-Pro_2.11.1/scripts/hic.inc.sh: line 86:  3404 Broken pipe             cat hic_results/data//sample1/sample1.allValidPairs
      3405 Aborted                 | /ds3512/home/panyp/ruanjian/hic-pro/HiC-Pro_2.11.1/scripts/build_matrix --matrix-format upper --binsize 500000 --chrsizes /ds3512/home/panyp/ruanjian/hic-pro/Hi
C-Pro_2.11.1/annotation/genome.fasta.size --ifile /dev/stdin --oprefix hic_results/matrix/sample1/raw/500000/sample1_${bsize}

could you give me some advise ?  Thank you very much.

**Comment by nservant** [comment]
Hi
Could you first check that the allvalidPairs file in `data` is not empty ?
Thanks

**Comment by shiyi-pan** [comment]
Hi，thank you for your response, the sample1.allValidPairs in data file is 6Gb.

**Comment by nservant** [comment]
hum... could you check if the list of chromosmes in the file ` /ds3512/home/panyp/ruanjian/hic-pro/HiC-Pro_2.11.1/annotation/genome.fasta.size` correspond to the one you have in the `allValidPairs` one please ?

**Comment by shiyi-pan** [comment]
Thank you for your reply,they are not correspond . Maybe this is the problem . I will correct it and try again . Thank you again for your help.

**Comment by nservant** [comment]
Yes. HiC-Pro builds the maps for the chromosomes which are in the `chromosome.size` file
