### ISSUE TITLE
Run parallel HiC-Pro without a scheduler

### ISSUE THREAD

**Issue by fanc-WU** [nservant/HiC-Pro#370]
Hi~

Our lab has a powerful server with 20+ cores. However, we don't have a scheduler at all. I was wondering if parallel without a scheduler is supported. 
Thanks!!

**Comment by nservant** [comment]
Hi
Not really, the only parallelized step is the mapping in this case. All downstream analysis steps will run on one CPU.
If you have billions of reads, it will take time ...
Best
