### ISSUE TITLE
Urgent: Installation Issue

### ISSUE THREAD

**Issue by sanchari24** [nservant/HiC-Pro#374]
Hello, I have been trying to install HiC-Pro past couple of days, but no luck and have lost too much time. I am working in a cluster environment, and was trying to install it for my environment. 
I keep getting an error for the Test data on Human: make: *** No targets.  Stop.

I have provided the logs and the config file info. Will be very very grateful for some insights. Thanks

**config-system.txt**

R_PATH = /opt/share/Debian-Buster/CRAN-R/R-3.6.2/bin
BOWTIE2_PATH = /opt/share/Linux_x86_64/bowtie2/bowtie2-2.3.4.1
SAMTOOLS_PATH = /opt/share/Debian-Buster/samtools-1.9/bin
PYTHON_PATH = /usr/bin
INSTALL_PATH = /ips2/users/ssircar/cluster/.local/bin/HiC-Pro_2.11.4
SCRIPTS = /ips2/users/ssircar/cluster/.local/bin/HiC-Pro_2.11.4/scripts
SOURCES = /ips2/users/ssircar/cluster/.local/bin/HiC-Pro_2.11.4/scripts/src
ANNOT_DIR = /ips2/users/ssircar/cluster/.local/bin/HiC-Pro_2.11.4/annotation
CLUSTER_SCRIPT = /ips2/users/ssircar/cluster/.local/bin/HiC-Pro_2.11.4/scripts/make_torque_script.sh

**ssircar@node9:~/HiC-Pro$ make configure**

make -f ./scripts/install/Makefile CONFIG_SYS=./config-install.txt
make[1]: Entering directory '/ips2/users/ssircar/cluster/HiC-Pro'
./scripts/install/install_dependencies.sh -c ./config-install.txt -o  /ips2/users/ssircar/cluster/.local/bin/HiC-Pro_2.11.4 -q
Make sure internet connection works for your shell prompt under current user's privilege ...
Starting HiC-Pro installation ...
Checking dependencies ...
Checking Python libraries ...
The required Python libraries appear to be already installed.
Checking R installation ...
The required R packages appear to be already installed.
Bowtie2 Aligner appears to be already installed.
Samtools appears to be already installed.
Dependencies checked !
Check HiC-Pro configuration ...
Warning : Scheduler system not defined - Default is Torque/PBS
Configuration for TORQUE/PBS system.

make[1]: Leaving directory '/ips2/users/ssircar/cluster/HiC-Pro'

**ssircar@node9:~/HiC-Pro$ make install**

(g++ -Wall -O2 -std=c++0x -o build_matrix /ips2/users/ssircar/cluster/HiC-Pro/scripts/src/build_matrix.cpp; mv build_matrix /ips2/users/ssircar/cluster/HiC-Pro/scripts)
(g++ -Wall -O2 -std=c++0x -o cutsite_trimming /ips2/users/ssircar/cluster/HiC-Pro/scripts/src/cutsite_trimming.cpp; mv cutsite_trimming /ips2/users/ssircar/cluster/HiC-Pro/scripts)
Installing the iced package in --user repository [runner=ssircar]
(cd /ips2/users/ssircar/cluster/HiC-Pro/scripts/src/ice_mod/; /usr/bin/python setup.py install --user;)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
Warning: Assuming default configuration (iced/utils/{setup_utils,setup}.py was not found)Appending iced.utils configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.utils')
Appending iced.datasets configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.datasets')
non-existing path in 'iced/io': '../src/cblas'
non-existing path in 'iced/io': '../src/cblas'
Appending iced.io configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.io')
non-existing path in 'iced': '../src/cblas'
non-existing path in 'iced': '../src/cblas'
Appending iced configuration to
Ignoring attempt to set 'name' (from '' to 'iced')
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "iced.io.fastio_" sources
building extension "iced.io.read" sources
building extension "iced._normalization_" sources
building extension "iced._filter_" sources
building data_files sources
build_src: building npy-pkg config files
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/iced
copying iced/normalization.py -> build/lib.linux-x86_64-2.7/iced
copying iced/filter.py -> build/lib.linux-x86_64-2.7/iced
copying iced/setup.py -> build/lib.linux-x86_64-2.7/iced
copying iced/__init__.py -> build/lib.linux-x86_64-2.7/iced
creating build/lib.linux-x86_64-2.7/iced/utils
copying iced/utils/_genome.py -> build/lib.linux-x86_64-2.7/iced/utils
copying iced/utils/_validation.py -> build/lib.linux-x86_64-2.7/iced/utils
copying iced/utils/validation.py -> build/lib.linux-x86_64-2.7/iced/utils
copying iced/utils/__init__.py -> build/lib.linux-x86_64-2.7/iced/utils
creating build/lib.linux-x86_64-2.7/iced/datasets
copying iced/datasets/setup.py -> build/lib.linux-x86_64-2.7/iced/datasets
copying iced/datasets/base.py -> build/lib.linux-x86_64-2.7/iced/datasets
copying iced/datasets/__init__.py -> build/lib.linux-x86_64-2.7/iced/datasets
creating build/lib.linux-x86_64-2.7/iced/io
copying iced/io/_io_else.py -> build/lib.linux-x86_64-2.7/iced/io
copying iced/io/setup.py -> build/lib.linux-x86_64-2.7/iced/io
copying iced/io/_io_pandas.py -> build/lib.linux-x86_64-2.7/iced/io
copying iced/io/__init__.py -> build/lib.linux-x86_64-2.7/iced/io
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
building 'iced.io.fastio_' extension
compiling C sources
C compiler: x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC

creating build/temp.linux-x86_64-2.7/iced
creating build/temp.linux-x86_64-2.7/iced/io
compile options: '-I../src/cblas -I/ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include -I/ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c'
x86_64-linux-gnu-gcc: iced/io/fastio_.c
In file included from /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822,
                 from /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from iced/io/fastio_.c:435:
/ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/iced/io/fastio_.o -lm -o build/lib.linux-x86_64-2.7/iced/io/fastio_.so
building 'iced.io.read' extension
compiling C sources
C compiler: x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC

compile options: '-I../src/cblas -I/ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include -I/ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c'
x86_64-linux-gnu-gcc: iced/io/read.c
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/iced/io/read.o -lm -o build/lib.linux-x86_64-2.7/iced/io/read.so
building 'iced._normalization_' extension
compiling C sources
C compiler: x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC

compile options: '-I../src/cblas -I/ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include -I/ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c'
x86_64-linux-gnu-gcc: iced/_normalization_.c
In file included from /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822,
                 from /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from iced/_normalization_.c:435:
/ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/iced/_normalization_.o -lm -o build/lib.linux-x86_64-2.7/iced/_normalization_.so
building 'iced._filter_' extension
compiling C sources
C compiler: x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC

compile options: '-I../src/cblas -I/ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include -I/ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c'
x86_64-linux-gnu-gcc: iced/_filter_.c
In file included from /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822,
                 from /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from iced/_filter_.c:435:
/ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/iced/_filter_.o -lm -o build/lib.linux-x86_64-2.7/iced/_filter_.so
running build_scripts
creating build/scripts.linux-x86_64-2.7
copying and adjusting iced/scripts/ice -> build/scripts.linux-x86_64-2.7
running install_lib
copying build/lib.linux-x86_64-2.7/iced/io/read.so -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/io
copying build/lib.linux-x86_64-2.7/iced/io/fastio_.so -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/io
copying build/lib.linux-x86_64-2.7/iced/io/_io_else.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/io
copying build/lib.linux-x86_64-2.7/iced/io/setup.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/io
copying build/lib.linux-x86_64-2.7/iced/io/_io_pandas.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/io
copying build/lib.linux-x86_64-2.7/iced/io/__init__.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/io
copying build/lib.linux-x86_64-2.7/iced/utils/_genome.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/utils
copying build/lib.linux-x86_64-2.7/iced/utils/_validation.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/utils
copying build/lib.linux-x86_64-2.7/iced/utils/validation.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/utils
copying build/lib.linux-x86_64-2.7/iced/utils/__init__.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/utils
copying build/lib.linux-x86_64-2.7/iced/normalization.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced
copying build/lib.linux-x86_64-2.7/iced/filter.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced
copying build/lib.linux-x86_64-2.7/iced/_filter_.so -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced
copying build/lib.linux-x86_64-2.7/iced/setup.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced
copying build/lib.linux-x86_64-2.7/iced/datasets/setup.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/datasets
copying build/lib.linux-x86_64-2.7/iced/datasets/base.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/datasets
copying build/lib.linux-x86_64-2.7/iced/datasets/__init__.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/datasets
copying build/lib.linux-x86_64-2.7/iced/_normalization_.so -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced
copying build/lib.linux-x86_64-2.7/iced/__init__.py -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/io/_io_else.py to _io_else.pyc
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/io/setup.py to setup.pyc
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/io/_io_pandas.py to _io_pandas.pyc
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/io/__init__.py to __init__.pyc
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/utils/_genome.py to _genome.pyc
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/utils/_validation.py to _validation.pyc
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/utils/validation.py to validation.pyc
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/utils/__init__.py to __init__.pyc
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/normalization.py to normalization.pyc
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/filter.py to filter.pyc
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/setup.py to setup.pyc
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/datasets/setup.py to setup.pyc
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/datasets/base.py to base.pyc
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/datasets/__init__.py to __init__.pyc
byte-compiling /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/__init__.py to __init__.pyc
running install_scripts
copying build/scripts.linux-x86_64-2.7/ice -> /ips2/users/ssircar/cluster/.local/bin
changing mode of /ips2/users/ssircar/cluster/.local/bin/ice to 777
running install_data
copying iced/datasets/data/duan2009/duan.SC.10000.raw_sub.matrix -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/datasets/data/duan2009
copying iced/datasets/data/duan2009/duan.SC.10000.raw_sub.bed -> /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced/datasets/data/duan2009
running install_egg_info
Removing /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced-0.4.2.egg-info
Writing /ips2/users/ssircar/cluster/.local/lib/python2.7/site-packages/iced-0.4.2.egg-info
running install_clib
customize UnixCCompiler
cp -Ri /ips2/users/ssircar/cluster/HiC-Pro /ips2/users/ssircar/cluster/.local/bin/HiC-Pro_2.11.4
HiC-Pro installed in /ips2/users/ssircar/cluster/.local/bin/HiC-Pro_2.11.4 !

**HiC-Pro config file:**

TMP_DIR = tmp
LOGS_DIR = logs
BOWTIE2_OUTPUT_DIR = bowtie_results
MAPC_OUTPUT = hic_results
RAW_DIR = rawdata

**ssircar@node9:~/.local/bin/HiC-Pro_2.11.4/bin$ workingDir="/NetScratch/sanchari/hicpro_test"**

**ssircar@node9:~/.local/bin/HiC-Pro_2.11.4/bin$ ./HiC-Pro -i $workingDir/HiCPro_testdata/test_data -o $workingDir/out_put_test_data -c $workingDir/hicpro_config.txt**

**make: *** No targets.  Stop.**

**Comment by nservant** [comment]
not sure to see what's going wrong. The only thing I can tell you is that this is usually not a good idea to work on the installation folder ... 
Does it chang something if you call HiC-pro using its full path ?

**Comment by liwang0307** [comment]
Hi, I have the exact same issue. How did you solve it? Thanks, @sanchari24
