### ISSUE TITLE
Run HiC-Pro smoothly but can't generate any statistical figures in hic_results/pic/  

### ISSUE THREAD

**Issue by lugols** [nservant/HiC-Pro#382]
Hi Nicholas,

I can run HiC-Pro successfully with test data and my own data, the XX_abs.bed and XX_iced.matrix can be used for generating interaction maps. However, there is no files in the hic_results/pic. Do you have any idea for this problem or receive similar issue report? Do you think something is wrong with R-plotting? I found that there is no R-related logs files in the results files.

HiC-Pro version: 2.11.4; R version: 3.4.1; ggplot2 version: 3.1.0;

Here are the testdata log files:
build_raw_maps.log
ice_500000.log
ice_1000000.log
mapped_2hic_fragments.log
mapping_combine.log
mapping_stats.log
mapping_step1.log
mapping_step2.log
merge_stats.log
merge_valid_interactions.log
mergeSAM.log
SRR400264_00_R1_bowtie2.log
SRR400264_00_R1_hg19.bwt2glob.unmap_bowtie2.log
SRR400264_00_R1_hg19.bwt2glob.unmap_readsTrimming.log
SRR400264_00_R2_bowtie2.log
SRR400264_00_R2_hg19.bwt2glob.unmap_bowtie2.log
SRR400264_00_R2_hg19.bwt2glob.unmap_readsTrimming.log

I am so appreciated for your help!

Best

**Comment by nservant** [comment]
Hi,
Could you please look into the logs folder and the `Rout` files if there is any error ?
Otherwise, I would now suggest to use MultiQC to have the plots, by simply running MultiQC from the HiC-Pro results folder.
Best

**Comment by lugols** [comment]
Hi Nicolas,


Thanks for your reply! I didn't find any Rout files in the logs folder. Do you know or can you guess what may happen?

I have used MultiQC to draw the plots, thanks for the suggestion:)


Best,

Min

________________________________

**Comment by nservant** [comment]
humm ... did you run HiC-Pro in stepwise mode with `-s` ?
Otherwise, I do not really see why the plotQC step has been skipped ... without any error ...
I guess you already checked that R is up and running ... ?

**Comment by lugols** [comment]
Hi Nicolas,


I run it in a parallel mode, and I also tried a step-by-step mode, both of them didn't generate any Routput files in Logs.

They can run successfully and generate all results files except for plots.

Wed Oct 21 11:49:31 EDT 2020

Run ICE Normalization ...

Logs: logs/sample1/ice_20000.log

Logs: logs/sample1/ice_40000.log

Logs: logs/sample1/ice_150000.log

Logs: logs/sample1/ice_500000.log

Logs: logs/sample1/ice_1000000.log


Sorry I don't quite understand this very well, I checked the R version (3.4.1) and other necessary packages, and I can run R individually in command line. Do you know how checked R is up and running during HiC-Pro processing?


Best,

Min


________________________________

**Comment by nservant** [comment]
Could you try to run the same command with `-s quality_checks` please ?
This step should only run the R scripts ... if there is anything wrong, I guess you should have an error message ...

**Comment by lugols** [comment]
Hi Nicolas,


Message as below (without ant warning message):


Run HiC-Pro 2.11.4

--------------------------------------------

Wed Dec  2 16:20:51 EST 2020

Run quality checks for all samples ...



No warning/error message. But there is no any files in the logs folder this time.


Best,

Min

________________________________

**Comment by nservant** [comment]
Could you show me the output folder ? do you have a data/ folder with .RSstat files ?
do you have a stats folder with .mergestat files for instance ?

**Comment by lugols** [comment]
Yes, in the parallel/complete mode, there is a sample0_allValidPairs.mergestat and sample0.mRSstat under the path ~/Downloads/hic_results/stats/sample0/.


~/Downloads/201120_results/hic_results/stats/sample0/ contains files:

sample0_allValidPairs.mergestat

sample0_R1.mmapstat

sample0_R2.mmapstat

sample0.mpairstat

sample0.mRSstat




________________________________

**Comment by nservant** [comment]
I have no idea :(
If you want to resolve this mystery, I guess you will need to add traces in the script/make_plots.sh file.
Basically, you have a couple of 'if' statement that check if the output folders/files are available.
My feeling is that it does not enter into this statement ... but no idea why ...

Otherwise, using the MultiQC files is much nicer ;)

**Comment by lugols** [comment]
Hi Nicolas,


:) Thank you so much for your time and suggestions!


Best,

Min

________________________________
