### ISSUE TITLE
../\scripts//Makefile:194: ice_norm] Error 139

### ISSUE THREAD

**Issue by zhanwen-cheng** [nservant/HiC-Pro#383]
Hi, nservant, many thanks for HiC-Pro.
Recently I was runing my data using HiC-Pro with HiC-Pro 2.11.4 in our HPC clusters:
####
(hic) [iese-chengzw@fat03 ~]$ ~/softwares/hic/HiC-Pro_2.11.4/bin/HiC-Pro -h
usage : HiC-Pro -i INPUT -o OUTPUT -c CONFIG [-s ANALYSIS_STEP] [-p] [-h] [-v]
Use option -h|--help for more information

HiC-Pro 2.11.4
---------------
OPTIONS

   -i|--input INPUT : input data folder; Must contains a folder per sample with input files
   -o|--output OUTPUT : output folder
   -c|--conf CONFIG : configuration file for Hi-C processing
   [-p|--parallel] : if specified run HiC-Pro on a cluster
   [-s|--step ANALYSIS_STEP] : run only a subset of the HiC-Pro workflow; if not specified the complete workflow is run
      mapping: perform reads alignment - require fast files
      proc_hic: perform Hi-C filtering - require BAM files
      quality_checks: run Hi-C quality control plots
      merge_persample: merge multiple inputs and remove duplicates if specified - require .validPairs files
      build_contact_maps: Build raw inter/intrachromosomal contact maps - require .allValidPairs files
      ice_norm : run ICE normalization on contact maps - require .matrix files
   [-h|--help]: help
   [-v|--version]: version
####

Everything went well but a error occuried during ICE normalization like this:
####
……
Thu Nov 19 15:27:54 Local time zone must be set--see zic manual page 2020
Generate binned matrix files ...
Logs: logs/fastp/build_raw_maps.log

--------------------------------------------
Thu Nov 19 15:27:58 Local time zone must be set--see zic manual page 2020
Run ICE Normalization ...
Logs: logs/fastp/ice_20000.log
make: *** [/home/iese-chengzw/softwares/hic/HiC-Pro_2.11.4/bin/../scripts//Makefile:194: ice_norm] Error 139
####

And in ice_20000.log file, it shows:
`ice --results_filename hic_results/matrix/fastp/iced/20000/fastp_20000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 --verbose 1 hic_results/matrix//fastp/raw/20000/fastp_20000.matrix
/home/iese-chengzw/anaconda3/envs/hic/lib/python2.7/site-packages/iced/normalization/_ca_utils.py:9: UserWarning: The API of this module is likely to change. Use only for testing purposes
  "The API of this module is likely to change. "
/home/iese-chengzw/softwares/hic/HiC-Pro_2.11.4/scripts/hic.inc.sh: line 86: 56424 Segmentation fault      (core dumped) ice --results_filename hic_results/matrix/fastp/iced/20000/fastp_20000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 --verbose 1 hic_results/matrix//fastp/raw/20000/fastp_20000.matrix
####

I checked my iced version, the version and the path was right like below:
####
(hic) [iese-chengzw@fat03 fastp]$ python
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iced
/home/iese-chengzw/anaconda3/envs/hic/lib/python2.7/site-packages/iced/normalization/_ca_utils.py:9: UserWarning: The API of this module is likely to change. Use only for testing purposes
  "The API of this module is likely to change. "
>>> iced.__version__
'0.5.6'
>>> iced.__path__
['/home/iese-chengzw/anaconda3/envs/hic/lib/python2.7/site-packages/iced']
####

And if I log into my calculating nodes to execute the sgematation fault command, it succeeded:
####
(hic) [iese-chengzw@fat03 yca30]$ cd result/
(hic) [iese-chengzw@fat03 result]$ ll
total 20
drwxr-xr-x 5 iese-chengzw iese-xiayu 4096 Nov 19 22:46 bowtie_results
-rwxr-xr-x 1 iese-chengzw iese-xiayu 3025 Nov 19 21:09 config-hicpro.txt
drwxr-xr-x 6 iese-chengzw iese-xiayu 4096 Nov 19 23:27 hic_results
drwxr-xr-x 3 iese-chengzw iese-xiayu 4096 Nov 19 21:09 logs
lrwxrwxrwx 1 iese-chengzw iese-xiayu   36 Nov 19 21:09 rawdata -> /work/iese-chengzw/hic/yca30/rawdata
drwxr-xr-x 2 iese-chengzw iese-xiayu 4096 Nov 19 21:09 tmp
(hic) [iese-chengzw@fat03 result]$ ice --results_filename hic_results/matrix/fastp/iced/20000/fastp_20000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 --verbose 1 hic_results/matrix//fastp/raw/20000/fastp_20000.matrix
/home/iese-chengzw/anaconda3/envs/hic/lib/python2.7/site-packages/iced/normalization/_ca_utils.py:9: UserWarning: The API of this module is likely to change. Use only for testing purposes
  "The API of this module is likely to change. "
Using iced version 0.5.6
Loading files...
Normalizing...
Filter 212661 out of 215355 bins ...
Matrix is triangular superior
Writing results...
####

I think the iced pacakage is alright but can't be called if I run it in complete workflow.
The attachments are my .PBS file and my config-hicpro.txt.
Can you help me to fix that?
[config-hicpro.txt](https://github.com/nservant/HiC-Pro/files/5571839/config-hicpro.txt)
[hic_yca30.pbs.txt.txt](https://github.com/nservant/HiC-Pro/files/5571843/hic_yca30.pbs.txt.txt)

**Comment by zhanwen-cheng** [comment]
I noticed that under matirx raw path, there are 20000/40000/500000/1000000 file, but under matrix iced path, only exits 20000 file. Considering I only haven't finished iced normalization, can I just finish the left step but '-s ice_norm' with my 'matrix' file as input? Would there be some differences between this way and complete work flow?

**Comment by nservant** [comment]
Hi,
It's not clear to me why iced crashed, but yes you can run the normalization only using `-s ice_norm`.
Note that in this case, the input folder should contains the matrix files (and no longer the fastq files).
Let me know if you have any other trouble
best

**Comment by zhanwen-cheng** [comment]
OK, IC. Thanks~
