### ISSUE TITLE
build_raw_maps error

### ISSUE THREAD

**Issue by hilaryhy** [nservant/HiC-Pro#384]
Hi, I run HiC-pro met the problem about build_raw_maps error, the mainly error is in "build_raw_maps.log" below:
## Generate contact maps at 5000 resolution ...
cat hic_results/data//sample/sample.allValidPairs | /public/home/HiC-Pro_2.11.4/HiC-Pro_2.11.4/scripts/build_matrix --matrix-format upper --binsize 5000 --chrsizes /public/home/HiC-Pro_2.11.4/HiC-Pro_2.11.4/annotation/TAIR10.chrom.sizes --ifile /dev/stdin --oprefix hic_results/matrix/sample/raw/5000/sample_${bsize}
/public/home/HiC-Pro_2.11.4/HiC-Pro_2.11.4/scripts/build_matrix: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /public/home/HiC-Pro_2.11.4/HiC-Pro_2.11.4/scripts/build_matrix)
/public/home/HiC-Pro_2.11.4/HiC-Pro_2.11.4/scripts/build_matrix: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /public/home/HiC-Pro_2.11.4/HiC-Pro_2.11.4/scripts/build_matrix)
cat: 写入错误: 断开的管道

I am so appreciated for your help!

**Comment by nservant** [comment]
Hi,
Something is wrong with your gcc version I think, and the build_matrix code was not properly compiled and installed.
You should fixe this before re-installing HiC-Pro
N
