### ISSUE TITLE
regarding HiC data in IMR90

### ISSUE THREAD

**Issue by tanasa** [nservant/HiC-Pro#385]
Dear Nicolas, thank you again for a great package ! hope that my email finds you well. 

as i am reading again your manuscript on HiC-Pro, and on HiTC : 

http://bioconductor.org/packages/release/bioc/vignettes/HiTC/inst/doc/HiC_analysis.pdf

i was wondering if the LOOPS in IMR90 cell line (Dixon, Rao datasets) are available in "Dixon2012_IMR90" / "HiCDataHumanIMR90" or on the website (likely, i have missed it). thanks again, and best regards :)

**Comment by nservant** [comment]
Dear Bogdan,
No, the package only contains the contact maps.
The TADs are available on the original publication website here : http://chromosome.sdsc.edu/mouse/hi-c/download.html
However, to my knowledge, the Dixon 2012 data was not resolutive enough to call loops.
Hope it helps
Nicolas

**Comment by tanasa** [comment]
thank you Nicolas ! have a good weekend, and ttyl ;)
