### ISSUE TITLE
running the singularity image on a SLURM cluster with CentOS 

### ISSUE THREAD

**Issue by tanasa** [nservant/HiC-Pro#386]
Dear Nicolas, thank you for all the work on HiC-Pro !

if I may ask a naive question please : would "singularity exec hicpro_latest_ubuntu.img" run on a CentOS (SLURM) cluster ?

finally, we made some changes in the CONFIGURATION FILE, as mentioned in : 
http://bioinformatics.age.mpg.de/presentations-tutorials/presentations/modules/hiC/HiC-tutorial.html

particularly, we have included : 

```
**BOWTIE2_IDX_PATH=mm10/**
**REFERENCE_GENOME = mm10**
```

and the pipeline starts working, although ...for only a few seconds, as we get the following message : 

```
singularity exec hicpro_latest_ubuntu.img HiC-Pro -c config_test_latest.3.txt -i RGC_HiC_samples1and2 -o RGC_results

Run HiC-Pro 2.11.4
--------------------------------------------
Fri Dec  4 23:18:46 PST 2020
Bowtie2 alignment step1 ...
Logs: logs/sample1/mapping_step1.log
Exit: Error in reads alignment - Exit
make: *** [/usr/local/bin/HiC-Pro_2.11.4/bin/../scripts//Makefile:88: bowtie_global] Error 1
```

when we take a look in the file "mapping_step1.log", it writes : 
 
```
/usr/local/anaconda/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/sample1/P1_RGCs_1m_R2_.bwt2glob.unmap.fastq --rg-id BMG --rg SM:P1_RGCs_1m_R2 -p 1 -x / -U rawdata/sample1/P1_
RGCs_1m_R2.fastq.gz 2>> logs/sample1/P1_RGCs_1m_R2_bowtie2.log| /usr/local/anaconda/bin/samtools view -F 4 -bS - > bowtie_results/bwt2_global/sample1/P1_RGCs_1m_R2_.bwt2glob.bam
/usr/local/anaconda/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/sample1/P1_RGCs_1m_R1_.bwt2glob.unmap.fastq --rg-id BMG --rg SM:P1_RGCs_1m_R1 -p 1 -x / -U rawdata/sample1/P1_
RGCs_1m_R1.fastq.gz 2>> logs/sample1/P1_RGCs_1m_R1_bowtie2.log| /usr/local/anaconda/bin/samtools view -F 4 -bS - > bowtie_results/bwt2_global/sample1/P1_RGCs_1m_R1_.bwt2glob.bam
(base) [btanasa@smsh11dsu-srcf-d15-38 sample1]$ ls -1 /usr/local/anaconda/bin/bowtie2
```
I believe that bowtie2 is called from the singularity image, correct ?
 
we do not have the folder "/usr/local/anaconda/bin/bowtie2" on our computer system, although (just to make sure) i have loaded the packages : 

```
module load python/2.7.9
module load bowtie2/2.4.2
module load samtools/1.9
module load r/3.6.3
```

any comments, suggestions would be welcome, and much appreciated ! we wish you a good weekend, 

-- bogdan

**Comment by nservant** [comment]
Hi Bogdan,
I think the indexes are not found. Do you have any errors in logs/sample1/P1_RGCs_1m_R2_bowtie2.log ?

BOWTIE2_IDX_PATH should be the path to your index folder
and REFERENCE_GENOME, the prefix of the indexes.

best

**Comment by tanasa** [comment]
Dear Nicolas, thank you. I will make the changes in the script during the day, and will let you know. thanks.
