### ISSUE TITLE
Error in multiplot

### ISSUE THREAD

**Issue by rosaak** [nservant/HiC-Pro#388]
Hello Nicolas, 

- I run HiC-Pro on HPC SLURM  and met the problem with the second step.
- It was running smoothly earlier when I used ```BIN_SIZE = 200000 1000000``` . 
- After I changed the bin size to ```BIN_SIZE 5000 10000```
- I checked the slurm log file and it points to error in line 181 

```
...
--------------------------------------------
Thu Dec 10 02:09:37 EST 2020
Run quality checks for all samples ...
Logs: logs/Macro-ko-k2b/make_Rplots.log
make: *** [/home/rxp463/.local/bin/HiC-Pro_2.11.4/scripts/Makefile:181: hic_qc] Error 1
```
- line 181 points to running the R script  via  ```make_plots.sh```
- looking at the log ```logs/Macro-ko-k2b/plot_mapping_portion.Rout``` shows that there is a ```loadNamespace error```
- and no package called labeling
- tail of plot_mapping_portion.Rout
```
> ## Make plots
> mat_r1 <- getMapMat(stats_per_sample_r1[1], stats_per_sample_r1[2], stats_per_sample_r1[3], stats_per_sample_r1[4])
> mat_r1$lab <- factor(mat_r1$lab, levels=c("n.un","n.loc","n.glob","n.map"))
> p1 <- ploMapStat(mat_r1, sampleName=sampleName, tag="R1")
Loading required package: RColorBrewer
Loading required package: ggplot2
Registered S3 methods overwritten by 'ggplot2':
  method         from
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Loading required package: grid
> mat_r2 <- getMapMat(stats_per_sample_r2[1], stats_per_sample_r2[2], stats_per_sample_r2[3], stats_per_sample_r2[4])
> mat_r2$lab <- factor(mat_r2$lab, levels=c("n.un","n.loc","n.glob","n.map"))
> p2 <- ploMapStat(mat_r2, sampleName=sampleName, tag="R2", legend=FALSE)
> pdf(file.path(picDir, paste0("plotMapping_",sampleName,".pdf")), width=7, height=4)
> multiplot(p1, p2, cols=2)
Error in loadNamespace(name) : there is no package called ‘labeling’
Calls: multiplot ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```

- The package labeling is already installed in the conda env
```
r-labeling                0.4.2             r36h142f84f_0    conda-forge
```

- Because of this error the step2 script doesn't make any pdfs and no ice normalization files.
- But it created the raw contact matrix for 5000 and 10000
- Is this error because of the bin size?

Any suggestions !!!

-- Roshan

**Comment by nservant** [comment]
Hi Roshan
Many thanks for the detailed logs.
So for sure, this error has nothing to see with the bin size !!
In the header of the Rout file, can you check if it is really using the R version you have in conda.
Otherwise, I would suspected either an update in R, and something in the conda.
You can simply check by
```
conda active YOUR_CONDA
R
>> library('labeling')
```

Otherwise, don't forget that you can still use HiC-Pro in stepwise mode with -s option, just to run the ICE norm for instance.
In that case, be sure that the input folder (-i) was defined to your raw count table folder and run HiC-Pro with `-s ice_norm`
Best

**Comment by rosaak** [comment]
Hi Nicolas, 

Installing labeling solved the issue. 
Thank you for your suggestions. 

-- Roshan
