### ISSUE TITLE
Issue with bowtie2

### ISSUE THREAD

**Issue by ckntav** [nservant/HiC-Pro#390]
Hello,
I'm trying to run HiC-Pro through the singularity container with the test data.
It seems that there is an error with bowtie2:
>Run HiC-Pro 2.11.4
>
>Mon Dec 14 15:19:17 EST 2020
>Bowtie2 alignment step1 ...
>Logs: logs/dixon_2M/mapping_step1.log
>Exit: Error in reads alignment - Exit
>make: *** [/usr/local/bin/HiC-Pro_2.11.4/bin/../scripts//Makefile:88: bowtie_global] Error 1

Here is what it is written in SRR400264_00_R2_bowtie2.log:
>##HiC-Pro mapping
>perl: warning: Setting locale failed.
>perl: warning: Please check that your locale settings:
>	LANGUAGE = (unset),
>	LC_ALL = (unset),
>	LC_CTYPE = "fr_CA.UTF-8",
>	LANG = "C"
>    are supported and installed on your system.
>perl: warning: Falling back to the standard locale ("C").
>Error: Bad function type 'sL'.  Should be C (constant), L (linear), S (square root) or G (natural log).
>Error: Encountered internal Bowtie 2 exception (#1)
>Command: /usr/local/anaconda/bin/bowtie2-align-s --wrapper basic-0 --very-sensitive -L 30 --score-min sL,-0.6,-0.2 --end-to-end --reorder --rg-id BMG --rg SM:SRR400264_00_R2 -p 1 -x path_to/input/bowtie_indexes/hg19 --passthrough -U rawdata/dixon_2M/SRR400264_00_R2.fastq.gz 
(ERR): bowtie2-align exited with value 1

NB: I replace the absolute path of bowtie2 indexes with path_to

Do you have an idea of what happened?

Thanks,

Chris

**Comment by nservant** [comment]
Hi Chris,
I think it has nothing to do with HiC-Pro itself ... but more with bowtie2.
My feeling is that bowtie2 is not proprely installed.
best

**Comment by ckntav** [comment]
Hello, thank you for your feedback. I finally installed HiC-Pro from source on the cluster.
It seems to run well but I'm concerned about one message in the log file.
That message is described in Issue #227, so I commented there.
Best
