### ISSUE TITLE
Can't Install HiC-Pro

### ISSUE THREAD

**Issue by Jacobvazquez18** [nservant/HiC-Pro#393]
Hello, after installing all the necessary libraries, I am getting an error when I enter the "make configure" command. It is shown below: 

Starting HiC-Pro installation ...
Checking dependencies ... 
Checking Python libraries ...
/home/helix2/miniconda3/lib/python3.8/site-packages/iced/normalization/_ca_utils.py:8: UserWarning: The API of this module is likely to change. Use only for testing purposes
  warnings.warn(
The required Python libraries appear to be already installed. 
Checking R installation ...
The required R packages appear to be already installed. 
Bowtie2 Aligner appears to be already installed. 
Samtools appears to be already installed. 
Dependencies checked !
Check HiC-Pro configuration ... 
Warning : Scheduler system not defined - Default is Torque/PBS
Configuration for TORQUE/PBS system.

make[1]: Leaving directory '/home/helix2/Downloads/HiC-Pro-3.0.0'

Do you know how to avoid this? It's stopping me from installing HiC Pro

**Comment by nservant** [comment]
Hi,
I do not see any error message ?
Did you run `make install` after the '`configure` ?

**Comment by Jacobvazquez18** [comment]
Yes, after I run "make install" I get the following output:

make install
(g++ -Wall -O2 -std=c++0x -o build_matrix /home/helix2/Downloads/HiC-Pro-3.0.0/scripts/src/build_matrix.cpp; mv build_matrix /home/helix2/Downloads/HiC-Pro-3.0.0/scripts)
(g++ -Wall -O2 -std=c++0x -o cutsite_trimming /home/helix2/Downloads/HiC-Pro-3.0.0/scripts/src/cutsite_trimming.cpp; mv cutsite_trimming /home/helix2/Downloads/HiC-Pro-3.0.0/scripts)
cp -Ri /home/helix2/Downloads/HiC-Pro-3.0.0 /usr/local/bin//HiC-Pro_3.0.0
cp: cannot create directory '/usr/local/bin//HiC-Pro_3.0.0': Permission denied
make: *** [Makefile:78: cp] Error 1

**Comment by nservant** [comment]
you do not have the rigths to install HiC-Pro in /usr/local/bin
Update the `PREFIX=` in the `config-install.txt` file before running the installation

**Comment by Jacobvazquez18** [comment]
Ok so I updated the PREFIX= and did "make configure" and then "make install" and I'm asked if I want to overwrite all of the files one by one? 

make install
(g++ -Wall -O2 -std=c++0x -o build_matrix /home/helix2/Downloads/HiC-Pro/scripts/src/build_matrix.cpp; mv build_matrix /home/helix2/Downloads/HiC-Pro/scripts)
(g++ -Wall -O2 -std=c++0x -o cutsite_trimming /home/helix2/Downloads/HiC-Pro/scripts/src/cutsite_trimming.cpp; mv cutsite_trimming /home/helix2/Downloads/HiC-Pro/scripts)
cp -Ri /home/helix2/Downloads/HiC-Pro /home/helix2/Downloads/HiC-Pro/HiC-Pro_3.0.0
cp: overwrite '/home/helix2/Downloads/HiC-Pro/HiC-Pro_3.0.0/HiC-Pro/.gitignore'?

**Comment by Jacobvazquez18** [comment]
Now after saying it was downloaded in a folder called HiC-Pro_3.0.0, it's saying I need to re install it when I enter "HiC-Pro --help". Here's the output: 

HiC-Pro --help
usage : HiC-Pro -i INPUT -o OUTPUT -c CONFIG [-s ANALYSIS_STEP] [-p] [-h] [-v]
Use option -h|--help for more information
Error - Installation - config system not detected. Please (re) install HiC-Pro !

**Comment by nservant** [comment]
```
cp -Ri /home/helix2/Downloads/HiC-Pro /home/helix2/Downloads/HiC-Pro/HiC-Pro_3.0.0
cp: overwrite '/home/helix2/Downloads/HiC-Pro/HiC-Pro_3.0.0/HiC-Pro/.gitignore'?
```
You cannot install it in the path where you have downloaded it !
Please set another prefix. 
Note that it will create the HiC-Pro_3.0.0 folder by itself
