### ISSUE TITLE
What Do I use for Restriction Fragment Digestion if using DNASE

### ISSUE THREAD

**Issue by Max-Highsmith** [nservant/HiC-Pro#394]
In Situ DNASE circumvents the use of restriction enzymes. https://www.nature.com/articles/nprot.2016.126.
The ReadMe for HiC-Pro says that this tool can be used for DNASE-HiC, however, the READme also says annotation files for restriction sites are required.  How do I generate such a file to run HiC-Pro on DNASE-HiC data when no sequence-specific restriction enzyme sites exist?

**Comment by nservant** [comment]
Hi Max,
Yes HiC-pro can process data without restriction enzymes information.
Actually, all config related to restriction are just optional.
So in your config, you should have something like this ;

```
#######################################################################
## Digestion Hi-C
#######################################################################

GENOME_FRAGMENT = 
LIGATION_SITE = 
MIN_FRAG_SIZE = 
MAX_FRAG_SIZE = 
MIN_INSERT_SIZE = 
MAX_INSERT_SIZE = 

#######################################################################
## Hi-C processing
#######################################################################

MIN_CIS_DIST = 1000
```

Note that, as the restriction enzyme cannot be use to filter out spurious ligation events, the `MIN_CIS_DIST` parameter is important as it will filter all interactions within this distance range (which are likely to be unligated fragment for instance)
Best

**Comment by Max-Highsmith** [comment]
Thank You!
