### ISSUE TITLE
Low level of trimmed reads and alignment rate

### ISSUE THREAD

**Issue by zhang-jiankun** [nservant/HiC-Pro#395]
Hi,

I managed to map reads to hg19 using HiC-Pro. The results, however, were somewhat weired. It showed that both the level of trimmed reads and the alignment rate of the second step of mapping were extremely low. To check the quality of input, reads were mapped using bwa mem, which reported 99.35% alignment rate. Thus I guess there might be someting wrong but I cannot figure out why. I would appreciate it very much if you have any suggestions.

> combined_R2_bowtie2.log (mapping step1)
##HiC-Pro mapping
134171981 reads; of these:
  134171981 (100.00%) were unpaired; of these:
    112231893 (83.65%) aligned 0 times
    20019662 (14.92%) aligned exactly 1 time
    1920426 (1.43%) aligned >1 times
16.35% overall alignment rate

> bwt2glob.unmap_readsTrimming.log
##Fastq file: bowtie_results/bwt2_global/T210/P-27ac-210_combined_R2_hg19.bwt2glob.unmap.fastq
##Restriction sites (n=1):
CATGCATG
##Output File: bowtie_results/bwt2_local/T210/P-27ac-210_combined_R2_hg19.bwt2glob.unmap_trimmed.fastq
##Trimmed reads: 115602

> bwt2glob.unmap_bowtie2.log (mapping step2)
112231893 reads; of these:
  112231893 (100.00%) were unpaired; of these:
    112142506 (99.92%) aligned 0 times
    56690 (0.05%) aligned exactly 1 time
    32697 (0.03%) aligned >1 times
0.08% overall alignment rate

Thanks!
Jiankun

**Comment by nservant** [comment]
Hi Jiankun
That's weird indeed, as you should not have much difference between BWA-mem and bowtie2, although BWA is more permissive ...

A few idea to investigate ;
- first carrefully check your bowtie2  indexes. Are sure that you are aligning on the good reference ?
- the default parameter for bowtie2 mapping are quite stringent in HiC-Pro. You can change them in the config file, tunning  the `BOWTIE2_GLOBAL_OPTIONS` and `BOWTIE2_LOCAL_OPTIONS` with something more standard like `--very-sensitive --end-to-end --reorder`
- This is the first time I'm seeing this ligation motif "CATGCATG" ... are you sure about that ? what is your restriction enzyme ?

Best

**Comment by zhang-jiankun** [comment]
Hi Nicholas,

As you suggested, I carefully check my data, bowtie2 indexes and experimental details. It turns out that my partner may have used Mboi instead of Nlaiii (the ligation motif of Nlaiii is CATGCATG). This problem is easy to solve now. Apologies. Thank you for your advice.

Best,
Jiankun
