### ISSUE TITLE
find: File System Loop Detected

### ISSUE THREAD

**Issue by Jacobvazquez18** [nservant/HiC-Pro#398]
Hello, I'm trying to use HiC-Pro but running into an error with a file system loop. In the folder I'm in, it creates a folder called "hicpro_output" and there's a file with the config file I used and also another folder called "rawdata". However, if I click into "rawdata" folder, it's endless loop of the same content. Here is my code I ran and the error below:

HiC-Pro -i /home/helix2/Project/HiC/RenLab_Cortex/cortex/cortex_zip/ -o hicpro_output -c /home/helix2/Project/HiC/RenLab_Cortex/cortex/HiCPro/config-hicpro_mm10.txt

find: File system loop detected; ‘rawdata/hicpro_output/rawdata’ is part of the same file system loop as ‘rawdata’.

**Comment by Jacobvazquez18** [comment]
Now, the error message isn't appearing but the program stops in not even a second and all I get is a folder in the directory I'm in with a new rawdata folder that contains the data I used for input.

**Comment by nservant** [comment]
Hi,
Did you find the issue ?
best
