### ISSUE TITLE
HiC-Pro without reference genome

### ISSUE THREAD

**Issue by B10inform** [nservant/HiC-Pro#404]
Hi,

Can HiC-Pro work without a reference genome? How distant genome (similar species) can work as a reference genome?

Thanks

**Comment by nservant** [comment]
Hi
No, HiC-Pro requires a reference genome.
What do you mean by distant genome ? not sure to see your point ?
N

**Comment by B10inform** [comment]
I meant if Rubus occidentalis (black raspbarry) could be used as reference for Rubus idaeus (red raspberry) or Citrus sinensis (Orange) could be used as a reference for lime.

**Comment by nservant** [comment]
Well, this is up to you ! I have no idea how different are these reference genomes.
This is a general question which is also true when we are working with human, mouse, etc. 
How different are our genome from the reference ?
In practice, you can still modify the bowtie2 parameters if you want to be a bit more flexible in the mapping.
best

**Comment by kishor2019** [comment]
Hi @nservant 
can you please tell about the quality of the of reference genome? Beaucse in my case i want to make a denovo assembly of a fish genome. In that case, the closest reference species is from another genus and it was also not in chromosome level. If i want to seek for chromosome level reference assembly i need to go for Danio which is little bit far, actually a diiferent family. So it will be helpful for me if i get some idea about selecting reference species (in context of distance as well as in context of quality of assembly).

**Comment by nservant** [comment]
Hi,
Well, for sure the more different your reference genome is from your real data, the more complicated will be the reads mapping.
If you think your genome is too divergent from Danio, you should not use it.
One thing you could do would be to use your Hi-C data for genome assembly.
HiC-Pro is not designed for that, but there are other tools dedicated to this question.
Best

**Comment by kishor2019** [comment]
Thanks.
