### ISSUE TITLE
hic-pro mistake, zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by jimie0311** [nservant/HiC-Pro#407]
Hi everyone,
I am using hic-pro to see hic connection map. Here is an error:

ice --results_filename hic_results/matrix/91scaffolds/iced/20000/91scaffolds_20000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 --verbose 1 hic_results/matrix/91scaffolds/raw/20000/91scaffolds_20000.matrix
Using iced version 0.4.2
Loading files...
Traceback (most recent call last):
  File "/data/Liangjunmin/.local/bin/ice", line 76, in <module>
    if min(i.min(), j.min()) == 0:
  File "/data/Liangjunmin/opt/biosoft/miniconda3_for_pb-assembly/envs/hicpro/lib/python2.7/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity

This issue is similar to mistake #206, however, the files of hic_results/matrix/91scaffolds/raw/20000/91scaffolds_20000.matrix in my case are empty!

Anybody know how to resolve it? Your help will be appreciate.

**Comment by nservant** [comment]
Hi,
If the matrix file is empty, it means that something went wrong before.
What about the .validPairs file ? are they empty too ?

**Comment by jimie0311** [comment]
Hi Nservant,
Thanks for your reply. The .validParis file are not empty. The problem is that I input a wrong path for size file. It was run succesuffully now. Thanks.
