### ISSUE TITLE
potential bug: RM_MULTI in bowtie_pairing.sh

### ISSUE THREAD

**Issue by rschwess** [nservant/HiC-Pro#41]
Hi there,

First of all very nice pipeline, enjoying working with it! 

One potential bug I recognized today:

In the bowtie_pairing.sh script, the option "-m" for mergeSAM.py is set if RM_MULTI == 0.
RM_MULTI is referred to as removing multiple aligned reads in the documentation, but the option "-m" in mergeSAM.py actually enables the reporting of multiple alignments.

This shouldn't make make any difference when running bowtie2 with default parameters but may lead to false behavior when actually allowing multiple reads in the alignment. 

Potentially the same issue with RM_SINGLETON.

Easy to workaround but would be probably worth adjusting.

Cheers

**Comment by nservant** [comment]
Hi Ron,
Thank you for your comment and sorry for the delay. 
Actually, I'm not sure to see your point.
If RM_MULTI = 0, it means "I want to keep multi hits", and so the "-m" option of mergeSAM.py is used, ie. "Report the multi hits"
If RM_MUTLI = 1, i.e "Please remove multi hits", -m is not use and so multi hits are discarded (the default behavior).
So, it sounds good, isn't it ?
N

**Comment by rschwess** [comment]
Hi N,

Sorry you're right of course. Not sure why it didn't make sense in my eyes last Friday. Maybe I should stop looking at code close to the weekend :] 

Sorry for wasting time here and thanks for taking a look

**Comment by nservant** [comment]
Don't worry ! Do not hesitate if you have any other comments or idea to improve the pipeline ;)
Have a nice day
Nicolas
