### ISSUE TITLE
matrix converstion

### ISSUE THREAD

**Issue by BioEpi** [nservant/HiC-Pro#410]
Hi,
    I have run HiC-Pro to obtained ICED normalized matrix. Now I want to convert the matrix generated by HiC-Pro to the following format:
![image](https://user-images.githubusercontent.com/12387462/109570622-52ffd080-7ab8-11eb-8c0a-30766d5e9228.png)

Do you have any suggestions?
Best,

**Comment by nservant** [comment]
Hi
It doesn't seem to be very different from the .matrix file format generated by HiC-Pro.
A simple awk/python scripting should do the job.
Best

**Comment by biohubx** [comment]
here is result from 10kb normalized .matrix:
![image](https://user-images.githubusercontent.com/12387462/109668752-7588fc80-7b3f-11eb-8d2d-f1eaed23a1ec.png)

So the first 2 columns are multiplied by 10kb, right?
Best,

**Comment by nservant** [comment]
ah sorry, I just understood.
No. This file is a triplet sparese format file, with i, j, k
i and j are the indices in the matrix. k is the count.

To make the correspondance between i, j and the genome coordinate, you have a bed file with the matrix.
Usually, the bed file is only with the raw data, and normalized and raw data have the same coordinates.

**Comment by biohubx** [comment]
Thanks.
here is the bed file:
![image](https://user-images.githubusercontent.com/12387462/109681902-ed5d2400-7b4b-11eb-8fe7-6347eaa51779.png)
the screenshot of matrix file:
![image](https://user-images.githubusercontent.com/12387462/109681960-fcdc6d00-7b4b-11eb-8caa-c6fb9250802f.png)

the row number of bed file is different from that of matrix file.
I am a little confused about how to define the genome coordinates for the bed file.

**Comment by nservant** [comment]
In the BED file you have ;
chr / start / end / BIN_ID

In the matrix file you have :
BIN_ID / BIN_ID / counts

Is that better ?

**Comment by biohubx** [comment]
got it. thanks.
