### ISSUE TITLE
problem first user

### ISSUE THREAD

**Issue by robeach78** [nservant/HiC-Pro#411]
sudo /usr/local/bin/HiC-Pro_3.0.0/bin/HiC-Pro -i mydata -o prova -c config-hicpro.txt 

Run HiC-Pro 3.0.0
--------------------------------------------
Thu Mar  4 13:28:01 CET 2021
Bowtie2 alignment step1 ...
Logs: logs/sample1/mapping_step1.log
Exit: Error in reads alignment - Exit
make: *** [/usr/local/bin/HiC-Pro_3.0.0/bin/../scripts//Makefile:88: bowtie_global] Error 1

CONFIG FILE:

# Please change the variable settings below if necessary

#########################################################################
#########################################################################

TMP_DIR = tmp
LOGS_DIR = logs
BOWTIE2_OUTPUT_DIR = bowtie_results
MAPC_OUTPUT = hic_results
RAW_DIR = rawdata

#######################################################################
#######################################################################
N_CPU = 2
SORT_RAM = 1000M
LOGFILE = hicpro.log

JOB_NAME = CTCF 
JOB_MEM = 10gb
JOB_WALLTIME = 6:00:00 
JOB_QUEUE = batch
JOB_MAIL = roberto.ferrari@crg.es

#########################################################################
#########################################################################

PAIR1_EXT = _R1
PAIR2_EXT = _R2

#######################################################################
#######################################################################

MIN_MAPQ = 10

BOWTIE2_IDX_PATH = /Users/RobertoFerrari/Downloads/bowtie_indexes/ 
BOWTIE2_GLOBAL_OPTIONS = --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder
BOWTIE2_LOCAL_OPTIONS =  --very-sensitive -L 20 --score-min L,-0.6,-0.2 --end-to-end --reorder

#######################################################################
#######################################################################

REFERENCE_GENOME = hg38
GENOME_SIZE = hg38.genome

#######################################################################
#######################################################################

ALLELE_SPECIFIC_SNP = 

#######################################################################
#######################################################################

CAPTURE_TARGET =
REPORT_CAPTURE_REPORTER = 1

#######################################################################
#######################################################################

GENOME_FRAGMENT = 
LIGATION_SITE = 
MIN_FRAG_SIZE = 
MAX_FRAG_SIZE =
MIN_INSERT_SIZE =
MAX_INSERT_SIZE =

#######################################################################
#######################################################################

MIN_CIS_DIST =
GET_ALL_INTERACTION_CLASSES = 1
GET_PROCESS_SAM = 0
RM_SINGLETON = 1
RM_MULTI = 1
RM_DUP = 1

#######################################################################
#######################################################################

BIN_SIZE = 20000 40000 150000 500000 1000000
MATRIX_FORMAT = upper

#######################################################################
#######################################################################
MAX_ITER = 100
FILTER_LOW_COUNT_PERC = 0.02
FILTER_HIGH_COUNT_PERC = 0
EPS = 0.1

**Comment by robeach78** [comment]
here the log:

/Applications/anaconda3/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/sample1/HiChiP_CTCF_2M_R2_hg38.bwt2glob.unmap.fastq --rg-id BMG --rg SM:HiChiP_CTCF_2M_R2 -p 1 -x /Users/RobertoFerrari/Downloads/bowtie_indexes//hg38 -U rawdata/sample1/HiChiP_CTCF_2M_R2.fastq.gz 2>> logs/sample1/HiChiP_CTCF_2M_R2_bowtie2.log> bowtie_results/bwt2_global/sample1/HiChiP_CTCF_2M_R2_hg38.bwt2glob.bam
/Applications/anaconda3/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/sample1/HiChiP_CTCF_2M_R1_hg38.bwt2glob.unmap.fastq --rg-id BMG --rg SM:HiChiP_CTCF_2M_R1 -p 1 -x /Users/RobertoFerrari/Downloads/bowtie_indexes//hg38 -U rawdata/sample1/HiChiP_CTCF_2M_R1.fastq.gz 2>> logs/sample1/HiChiP_CTCF_2M_R1_bowtie2.log> bowtie_results/bwt2_global/sample1/HiChiP_CTCF_2M_R1_hg38.bwt2glob.bam

**Comment by robeach78** [comment]
when I try to run the command:

(base) ➜  HiC-Pro-master /Applications/anaconda3/bin/bowtie2
dyld: Library not loaded: @rpath/libtbb.dylib
  Referenced from: /Applications/anaconda3/bin/bowtie2-align-s
  Reason: image not found
(ERR): Description of arguments failed!
Exiting now ...

**Comment by robeach78** [comment]
bowtie2 index:

/Users/RobertoFerrari/Downloads/bowtie_indexes
(base) ➜  bowtie_indexes ls
hg38.1.bt2  hg38.2.bt2	hg38.3.bt2  hg38.4.bt2	hg38.rev.1.bt2	hg38.rev.2.bt2

**Comment by robeach78** [comment]
log:

##HiC-Pro mapping
dyld: Library not loaded: @rpath/libtbb.dylib
  Referenced from: /Applications/anaconda3/bin/bowtie2-align-s
  Reason: image not found
(ERR): Description of arguments failed!
Exiting now ...
HiChiP_CTCF_2M_R1_bowtie2.log (END)

**Comment by robeach78** [comment]
no it does not:

/Applications/anaconda3/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/sample1/HiChiP_CTCF_2M_R2_hg38.bwt2glob.unmap.fastq --rg-id BMG --rg SM:HiChiP_CTCF_2M_R2 -p 1 -x /Users/RobertoFerrari/Downloads/bowtie_indexes//hg38 -U rawdata/sample1/HiChiP_CTCF_2M_R2.fastq.gz 2>> logs/sample1/HiChiP_CTCF_2M_R2_bowtie2.log> bowtie_results/bwt2_global/sample1/HiChiP_CTCF_2M_R2_hg38.bwt2glob.bam
zsh: no such file or directory: logs/sample1/HiChiP_CTCF_2M_R2_bowtie2.log

**Comment by robeach78** [comment]
what about this: libtbb.dylib

I dont have it

(base) ➜  HiC-Pro-master /usr/bin/lib
libnetcfg*      libnetcfg5.18*  libnetcfg5.28*  libtool*

**Comment by nservant** [comment]
this is not the same error ... remove the log part, and be sure that paths to the data are correct
```
Applications/anaconda3/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/sample1/HiChiP_CTCF_2M_R2_hg38.bwt2glob.unmap.fastq --rg-id BMG --rg SM:HiChiP_CTCF_2M_R2 -p 1 -x /Users/RobertoFerrari/Downloads/bowtie_indexes//hg38 -U rawdata/sample1/HiChiP_CTCF_2M_R2.fastq.gz
```

**Comment by nservant** [comment]
How to do you generate your conda ? did you use the `environment.yml` file ?

**Comment by robeach78** [comment]
yes I used the enviromental.yml

this is the error now:

/Applications/anaconda3/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/sample1/HiChiP_CTCF_2M_R2_hg38.bwt2glob.unmap.fastq --rg-id BMG --rg SM:HiChiP_CTCF_2M_R2 -p 1 -x /Users/RobertoFerrari/Downloads/bowtie_indexes//hg38 -U rawdata/sample1/HiChiP_CTCF_2M_R2.fastq.gz
dyld: Library not loaded: @rpath/libtbb.dylib
  Referenced from: /Applications/anaconda3/bin/bowtie2-align-s
  Reason: image not found
(ERR): Description of arguments failed!

**Comment by nservant** [comment]
are you on mac OS ?

**Comment by robeach78** [comment]
yes mac OS Catalina 10.15.7

**Comment by nservant** [comment]
I think that's a pure system issue. Difficult to help you.
here is the first link I found on google ... you should investigate this issue
https://stackoverflow.com/questions/17703510/dyld-library-not-loaded-reason-image-not-found

**Comment by robeach78** [comment]
Thanks I ll look into it...

**Comment by robeach78** [comment]
> I think that's a pure system issue. Difficult to help you.
> here is the first link I found on google ... you should investigate this issue
> https://stackoverflow.com/questions/17703510/dyld-library-not-loaded-reason-image-not-found

if it happens to someone the solution seemed to be "brew install bowtie2"

**Comment by robeach78** [comment]
another error

Thu Mar  4 21:18:22 CET 2021
Generate binned matrix files ...
hg38.genome not found. Exit
make: *** [/usr/local/bin/HiC-Pro_3.0.0/bin/../scripts//Makefile:174: build_raw_maps] Error 255

**Comment by nservant** [comment]
please provide the chromosome size file for hg18

```
GENOME_SIZE = hg38.genome
```

**Comment by robeach78** [comment]
I did:

Annotation files

#######################################################################

REFERENCE_GENOME = hg38
GENOME_SIZE = hg38.genome

#######################################################################
Allele specific analysis

see above.

the file is in the same folder

**Comment by nservant** [comment]
by default, HiC-Pro is looking for annotation in the `annotation` folder (in the installation repo).
Otherwise, you can provide the full path to the file

**Comment by robeach78** [comment]
got it... thanks a lot!

Great support (live) ;)
