### ISSUE TITLE
How to generate Bed containing the locus pairs (binned) and the contact count

### ISSUE THREAD

**Issue by robeach78** [nservant/HiC-Pro#412]
Hi I got to the point of running FitHiChIP,
but I don't see a way of finding this file to input in the FitHiChIP:

Bed containing the locus pairs (binned) and the contact count:

# Pre-computed locus pair file
# of the format:
# chr1  start1  end1    chr2    start2  end2    contactcounts
Bed=

Where do I get this file from HiC-Pro?

Thanks a lot,
Roberto

**Comment by nservant** [comment]
Dear Roberto.
Not sure whether FitHiChIP starts from the list of valid pairs (`allValidPairs` file extension).
Or from a contact maps with the bins (bed format) and the counts (`.matrix`) files.
N
