### ISSUE TITLE
libtbb.so.2 shared object file 

### ISSUE THREAD

**Issue by trum994** [nservant/HiC-Pro#413]
Hi Nicolas, 

I'm using the docker container on our HPC environment via singularity (using --containall). I'm seeing this error: 

> ##HiC-Pro mapping
> /usr/local/anaconda/envs/HiC-Pro_v3.0.0/bin/bowtie2-align-s: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory
> (ERR): Description of arguments failed!

Version 3.0.0

> Singularity> HiC-Pro -v
> HiC-Pro version 3.0.0

Any idea what the cause could be? Thanks in advance!

**Comment by nservant** [comment]
Hi
That's clearly a bowtie2 issue. It looks for a system librarie that it doesn't find.
But I don't know why exactly :(
Did you try to construct the singularity image by yourself using the recipe ?
N
