### ISSUE TITLE
Error in reads alignment

### ISSUE THREAD

**Issue by summus-kong** [nservant/HiC-Pro#420]
Hi, when i run hic-pro, i got error.

bin=/mnt/data/hwb/hi_c/GES82185/HiC-Pro-2.11.1/bin/HiC-Pro
$bin -i fq/ -o result/ -c config-hicpro.txt

Run HiC-Pro 2.11.1
--------------------------------------------
Thu Mar 25 02:26:47 EDT 2021
Bowtie2 alignment step1 ...
Logs: logs/sample1/mapping_step1.log
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
Exit: Error in reads alignment - Exit
/mnt/data/hwb/hi_c/GES82185/HiC-Pro-2.11.1/bin/../scripts//Makefile:85: recipe for target 'bowtie_global' failed
make: *** [bowtie_global] Error 1

**Comment by nservant** [comment]
Hi,
Please have a look in the logs folder and look for an error message in the bowtie output files.
Best

**Comment by FengjuanjuanCMS** [comment]
I encountered the same error，R1_bowtie2.log error message：(ERR): Description of arguments failed!  How do I correct this error?  Thank you very much.

**Comment by RuoYinLee** [comment]
Run HiC-Pro 3.1.0
--------------------------------------------
2022年 04月 14日 星期四 12:16:12 CST
Bowtie2 alignment step1 ...
Logs: logs/sample/mapping_step1.log
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
Exit: Error in reads alignment - Exit
make: *** [/home/lishiyong/HI-C/HIC-PRO/HiC-Pro-3.1.0/HiC-Pro_3.1.0/bin/../scripts//Makefile:88: bowtie_global] Error 1

mapping_step1.log
/home/lishiyong/HI-C/HIC-PRO/bowtie2-2.4.5/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/sample/HIC003_S2_L001_R1_hg19_index.bwt2glob.unmap.fastq --rg-id BMG --rg SM:HIC003_S2_L001_R1 -p 1 -x reference/hg19_index -U rawdata/sample/HIC003_S2_L001_R1.fastq 2>> logs/sample/HIC003_S2_L001_R1_bowtie2.log| /home/lishiyong/HI-C/JUICER/samtools-1-15.1/bin/samtools view -F 4 -bS - > bowtie_results/bwt2_global/sample/HIC003_S2_L001_R1_hg19_index.bwt2glob.bam
/home/lishiyong/HI-C/HIC-PRO/bowtie2-2.4.5/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/sample/HIC003_S2_L001_R2_hg19_index.bwt2glob.unmap.fastq --rg-id BMG --rg SM:HIC003_S2_L001_R2 -p 1 -x reference/hg19_index -U rawdata/sample/HIC003_S2_L001_R2.fastq 2>> logs/sample/HIC003_S2_L001_R2_bowtie2.log| /home/lishiyong/HI-C/JUICER/samtools-1-15.1/bin/samtools view -F 4 -bS - > bowtie_results/bwt2_global/sample/HIC003_S2_L001_R2_hg19_index.bwt2glob.bam

HIC003_S2_L001_R2_bowtie2.log
##HiC-Pro mapping
(ERR): "reference/hg19_index" does not exist or is not a Bowtie 2 index
Exiting now ...

I have the same problem, I re-built the hg19_index files, but same result.

is there less storage left for program? I have only 25Gb for it and I run this program in vmware-ubuntu.

thank you

**Comment by nservant** [comment]
Hi,
Could you show me how you set up the INDEXES and GENOME in the configuration file please ?

**Comment by RuoYinLee** [comment]
Hi,

   I found the problem,  there was wrong index files I made.  the index files the bowtie2 built is not right. I downloaded six of index files from the  [index files ](http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml) , then  all goes right, the HiC-Pro runs well.  I am not sure what goes wrong with my bowtie2, I am sure I installed it right, but the sizes of index files I made with my laptop is not the same with I  downloaded. So  I think this is the problem.  Thank you  so much.
















At 2022-04-20 00:27:04, "Nicolas Servant" ***@***.***> wrote:

Hi,
Could you show me how you set up the INDEXES and GENOME in the configuration file please ?

**Comment by Jiangjiangzhang6** [comment]
I met the same error , how to debug

**Comment by RuoYinLee** [comment]
in bowtie2 web site download the six index files for your running not built index files by yourself

**Comment by elenadelpup** [comment]
I have run HiC pro in several species following the very same steps and scripts, including Bowtie2 index creation, and I have this same error occurring only in one species: 

--------------------------------------------

Bowtie2 alignment step1 ...
Logs: logs/SRR12034715/mapping_step1.log
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
Exit: Error in reads alignment - Exit



Log files are: 
/carnegie/binaries/centos7/conda/3.7/envs/HiC-Pro_3.1.0/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/SRR12034702/SRR12034702_1_bowtie2.bwt2glob.unmap.fastq --rg-id BMG --rg SM:SRR12034702_1 -p 4 -x /carnegie/data/Shared/Labs/Rhee/Everyone/ElenaDelPup/HiCdata/genomes/wheat/bowtie2 -U rawdata/SRR12034702/SRR12034702_1.fastq 2>> logs/SRR12034702/SRR12034702_1_bowtie2.log| /carnegie/binaries/centos7/conda/3.7/envs/HiC-Pro_3.1.0/bin/samtools view -F 4 -bS - > bowtie_results/bwt2_global/SRR12034702/SRR12034702_1_bowtie2.bwt2glob.bam
/carnegie/binaries/centos7/conda/3.7/envs/HiC-Pro_3.1.0/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/SRR12034702/SRR12034702_2_bowtie2.bwt2glob.unmap.fastq --rg-id BMG --rg SM:SRR12034702_2 -p 4 -x /carnegie/data/Shared/Labs/Rhee/Everyone/ElenaDelPup/HiCdata/genomes/wheat/bowtie2 -U rawdata/SRR12034702/SRR12034702_2.fastq 2>> logs/SRR12034702/SRR12034702_2_bowtie2.log| /carnegie/binaries/centos7/conda/3.7/envs/HiC-Pro_3.1.0/bin/samtools view -F 4 -bS - > bowtie_results/bwt2_global/SRR12034702/SRR12034702_2_bowtie2.bwt2glob.bam

**Comment by elenadelpup** [comment]
I have tried experimenting with the options --noauto --large-index of Bowtie2, in the case the defaults were not good anymore for the large genome I am using now (Triticum aestivum) but it is still not working. 
Best, 
Elena

**Comment by shRDJr** [comment]
Hello, I also encountered the same error, checked that the index and genome path were correct, but it still showed that it does not exist or is not a Bowtie 2 index, and my genome was not a model species and could not be downloaded in bowtie2 web. What should I do?

I found a solution in another issue
