### ISSUE TITLE
hicpro2higlass.sh

### ISSUE THREAD

**Issue by gvcaldas** [nservant/HiC-Pro#421]
Hi,
I want to use hicpro2higlass.sh to convert .allvalidpairs and .matrix files to cooler format. In the past I did it w/o this util tool (converting files manually) but now that is available I would really like to use it. However I am bit confused about how get it running. I use HiC pro in a specific conda environment, cooler in a different conda environment (both of those run in the cluster), and HiGlass on docker in my local machine. In the documentation for hicpro2higlass.sh says that I need to have cooler and higlass in the same environment as HiCpro, but all requirements for those env are different with HiCpro I think. Do you have an idea on how to make this util work in the way I have HiCpro already set up in its own env? - or is the solution to have hiCpro also in docker? - but in that case, would I need some kind of docker image that contains the 3? 
Thanks!

**Comment by nservant** [comment]
Hi,
Actually, almost all utilies can work outside of HiC-Pro. Most of them are just bash or python scripts.
So you should try to use it in your cooler environment.
Best
N
