### ISSUE TITLE
There was an error with the ice step，Ask for help.

### ISSUE THREAD

**Issue by JWDu0122** [nservant/HiC-Pro#425]
![image](https://user-images.githubusercontent.com/49836989/113380393-a95d7900-93ae-11eb-8f9a-0068fd7774cb.png)
thx!

**Comment by nservant** [comment]
the iced version you are using is for python2, but I guess you are working with python3.
Please update to the last iced version.
N

**Comment by nservant** [comment]
Note that the iced v0.5.4 were bugged ...

**Comment by JWDu0122** [comment]
ok thx！

发自我的iPhone
