### ISSUE TITLE
Valid Pair format explanation

### ISSUE THREAD

**Issue by shanwai1234** [nservant/HiC-Pro#426]
Hello,

I have used HiCPro to generate valid pairs using allele-specific mode as below, however, I want to use these valid pairs to do some further analysis, but I can not find the meaning of the format in the manual and am not sure about the format meaning of this valid pair data. Could you give me some ideas? Thank you so much!
```
E00513:63:H2V37CCX2:8:2116:16498:70574  Chr1     1767    -       Chr1      8888    +       182     HIC_Chr1_8        HIC_Chr1_33       8       42
      0-0
```

**Comment by nservant** [comment]
Hi

read_name / chr_A / start_A / strand_A / chr_B / start_B / strand_B / insert size / fragment_name_A / fragment_name_B / mapQ_A / mapQ_B / allele-specific info

**Comment by shanwai1234** [comment]
Thank you @nservant !

**Comment by Gemma-Zhang-326** [comment]
> Hi
> 
> read_name / chr_A / start_A / strand_A / chr_B / start_B / strand_B / insert size / fragment_name_A / fragment_name_B / mapQ_A / mapQ_B / allele-specific info

Hi I wonder what this insert size means? And whether I can use this criteria to sample interactions which ranges from 5Kb to 2Mb from `validPairs` files.
Many thanks.

**Comment by YichaoOU** [comment]
@nservant, why there are reads with the same start but belong to different fragment name?

```
NB551526:131:HC7YWAFX2:2:21112:13180:17535      ABC   861     +       ABC   3640    +       328     HIC_ABC_10    HIC_ABC_22    42      40      
NB551526:131:HC7YWAFX2:1:11111:2623:11403       ABC   861     -       ABC   3762    +       213     HIC_ABC_8     HIC_ABC_22    3       42  
```
