### ISSUE TITLE
found issue and self-solved on iced

### ISSUE THREAD

**Issue by takeiga** [nservant/HiC-Pro#428]
Hi, Nicolas,
I found issue on ice step using ice 0.5.7 in the conda environment. It looked finished normally without error, but iced matrix was bugged with full of meaningless values. I realized this because HiTC importC didn't finish eternally.
This was self-solved by updating ice to 0.5.8.
Thanks,

**Comment by nservant** [comment]
Hi,
Yes absolutely, iced v0.5.7 is bugged !
Thanks
