### ISSUE TITLE
Possible mistake in digest_genome.py

### ISSUE THREAD

**Issue by DavideBrex** [nservant/HiC-Pro#429]
Running the script, If I set the **"-r"** flag equal to an enzyme name (e.g. hindiii), the program will halt with this message: 

> Find unexpected character in restriction motif. 

I think the problem is here:
https://github.com/nservant/HiC-Pro/blob/351471bde0bff2985ec40ee22934c3f03612b6e8/bin/utils/digest_genome.py#L144-L149

Where `for nuc in list(set(cs)):` should be instead` for nuc in list(set(cseq)):`

Let me know what you think please! and thank you for the amazing pipeline.
Davide

**Comment by nservant** [comment]
Hi ! yes, indeed, I think you're right !

**Comment by nservant** [comment]
I'll fix that in the devel ! many thanks

**Comment by nservant** [comment]
done !
