### ISSUE TITLE
Read data to HiTC

### ISSUE THREAD

**Issue by zji90** [nservant/HiC-Pro#436]
Hi,

I am very new to Hi-C analysis and sorry if the question is dumb. I got the output from HiC-pro and would like to read into HiTC for further analysis. I think I should use importC but I am not sure what files I should use as input arguments (con, xgi.bed, ygi.bed). I guess con should be something like iced/20000/20000_iced.matrix, right?

Also I see that under iced folder there are multiple subfolders 20000, 40000,150000, .... I wonder which one should I use?

Thanks!

**Comment by BioEpi** [comment]
it depends on which resolution you want. 
what do you want to do when you read Hi-C contact matrix using HiTC?

**Comment by jiangpuxuan** [comment]
Hello, I am also new to Hi-C. 
I download a zebrafish genome and finish the Hic-pro pipeline.
Finally I found that there are too may strange chromosomes in my iced.matrix, appeared like "chr1_KZ115012v1_alt", etc.

It is known that zebrafish only have 25 chromosome. So I want to know the meaning of "chr1_KZ115012v1_alt".

Thank you for your help!

**Comment by nservant** [comment]
Hi,
Look at your reference genome. Basically, you should have the 'canonical' chromosomes chr1, 2, 3... + many scaffolds or haplotypes which are not well assembled and appear in the reference as "chr*_alt".
You can remove them from your reference genome if you only want to focus on the canonical chromosomes.
Best
