### ISSUE TITLE
error with HiCPlotter (ValueError: invalid literal for int() with base 10: )

### ISSUE THREAD

**Issue by canfeng-HUA** [nservant/HiC-Pro#437]
Hi,

Thanks a lot for providing such great tools.

When I try to visualized HI-C data by HiCplotter,  I meet a problem.

I want to use iced matrix to a visualized my HI-C data, the code is:
`python /mnt/d/bioinformatic/package/hicplotter/HiCPlotter.py -f hic_results/matrix/WT/iced/10000/WT_10000_iced.matrix -o exemple -r 10000 -tri 1 -bed hic_results/matrix/WT/raw/10000/WT_10000_abs.bed -n test -chr chr1 -ptr 1`
but I meet this error:

> ValueError: invalid literal for int() with base 10: '1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00 4.000000000000000000e+00 5.000000000000000000e+00 6.000000000000000000e+00 7.000000000000000000e+00 8.000000000000000000e+00

But When I used the raw matrix, everything goes well. The code is:
`python /mnt/d/bioinformatic/package/hicplotter/HiCPlotter.py -f hic_results/matrix/WT/raw/10000/WT_10000.matrix -o example -r 10000 -tri 1 -bed hic_results/matrix/WT/raw/10000/WT_10000_abs.bed -n test -chr chr1 -ptr 1`
Could you please tell me why I can not use the iced matrix?

**Comment by nservant** [comment]
Hi,
Could please show me the first lines of the iced matrix please ?
I'm just wondering if there is something wrong in the matrix itself.
best

**Comment by canfeng-HUA** [comment]
The first line is like this:
> 1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00 4.000000000000000000e+00 5.000000000000000000e+00 6.000000000000000000e+00 7.000000000000000000e+00 8.000000000000000000e+00 9.000000000000000000e+00 1.000000000000000000e+01 1.100000000000000000e+01 1.200000000000000000e+01 1.300000000000000000e+01 1.400000000000000000e+01 1.500000000000000000e+01 1.600000000000000000e+01 1.700000000000000000e+01 1.800000000000000000e+01 1.900000000000000000e+01 2.000000000000000000e+01 2.100000000000000000e+01 2.200000000000000000e+01 2.300000000000000000e+01 2.400000000000000000e+01 2.500000000000000000e+01 2.600000000000000000e+01 2.700000000000000000e+01 2.800000000000000000e+01 2.900000000000000000e+01 3.000000000000000000e+01 3.100000000000000000e+01 3.200000000000000000e+01 3.300000000000000000e+01 3.400000000000000000e+01 3.500000000000000000e+01 3.600000000000000000e+01 3.700000000000000000e+01 3.800000000000000000e+01 3.900000000000000000e+01 4.000000000000000000e+01 4.100000000000000000e+01 4.200000000000000000e+01 4.300000000000000000e+01 4.400000000000000000e+01 4.500000000000000000e+01 4.600000000000000000e+01 4.700000000000000000e+01 4.800000000000000000e+01 4.900000000000000000e+01 5.000000000000000000e+01 5.100000000000000000e+01 5.200000000000000000e+01 5.300000000000000000e+01 5.400000000000000000e+01 5.500000000000000000e+01 5.600000000000000000e+01 5.700000000000000000e+01 5.800000000000000000e+01 5.900000000000000000e+01 6.000000000000000000e+01 6.100000000000000000e+01 6.200000000000000000e+01 6.300000000000000000e+01 6.400000000000000000e+01 6.500000000000000000e+01 6.600000000000000000e+01 6.700000000000000000e+01

I am working with bacteria.

the code I used for the HI-C pro is this:
`nohup bash /mnt/d/bioinformatic/package/HiC-Pro-master/HiC-Pro-master/bin//HiC-Pro -i fq -o out -c config-hicpro.txt 1> run.log 2>&1 &`

**Comment by nservant** [comment]
There is something wrong.
Which iced version did you use ? I think you used the 0.5.4 which actually is bugged.
Could you please update it to the lastest one, and re-run the normalization ?
Sorry for that

**Comment by canfeng-HUA** [comment]
It works! thanks a lot for your help!
