### ISSUE TITLE
Old GNU version of sort does not have the option `--parallel`

### ISSUE THREAD

**Issue by YiweiNiu** [nservant/HiC-Pro#442]
Hi,

I wanted to report a potential bug of `hicpro2juicebox.sh` in case of using old version of `sort`.

The old version of `sort` command does not have the option of `--parallel`. And it would throw an error of `unrecognized option '--parallel=4'` when using `hicpro2juicebox.sh`.

The sort version of our server is `8.4`. I do not know the lowest version of `sort` supporting `--parallel` option.

**Comment by nservant** [comment]
Thanks for reporting the issue
