### ISSUE TITLE
Error in HicPro's normalization in the last step

### ISSUE THREAD

**Issue by xumu3333** [nservant/HiC-Pro#444]
I completed the HIC installation using sample files ：dixon_2M\dixon_2M_2
The rest of the steps are basically done, but when the last step is normalized, an error occurs
Run ICE Normalization ...
Logs: logs/dixon_2M/ice_20000.log
make: *** [/home/gaoyuan/HiC/HiC-Pro_3.0.0/bin/../scripts//Makefile:194: ice_norm] Error 1

I reinstall iced,but It's the same mistake
How should i solve this problem?

Many thanks

**Comment by nservant** [comment]
Hi
Could you have a look into `logs/dixon_2M/ice_20000.log` if you have any error message ? thanks

**Comment by xumu3333** [comment]
Thank you very much for your reply！！
logs/dixon_2M/ice_20000.log's all content:

ice --results_filename hic_results/matrix/dixon_2M/iced/20000/dixon_2M_20000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 hic_results/matrix//dixon_2M/raw/20000/dixon_2M_20000.matrix
/home/gaoyuan/anaconda3/bin/ice:65: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if "--filtering_perc" is None and "--filter_low_counts_perc" not in sys.argv:
/home/gaoyuan/anaconda3/lib/python3.9/site-packages/iced/normalization/_ca_utils.py:8: UserWarning: The API of this module is likely to change. Use only for testing purposes
  warnings.warn(
Assuming the file is 1-based. If this is not the desired option, set option --base to 0
Traceback (most recent call last):
  File "/home/gaoyuan/anaconda3/bin/ice", line 82, in <module>
    counts = load_counts(filename, base=base)
  File "/home/gaoyuan/anaconda3/lib/python3.9/site-packages/iced/io/_io_pandas.py", line 34, in load_counts
    dataframe = pd.read_csv(filename, sep="\t", comment="#", header=None)
  File "/home/gaoyuan/anaconda3/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/gaoyuan/anaconda3/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/gaoyuan/anaconda3/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/gaoyuan/anaconda3/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/gaoyuan/anaconda3/lib/python3.9/site-packages/pandas/io/parsers.py", line 1898, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 521, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file


My pandas was installed
Requirement already satisfied: pandas in ./anaconda3/envs/python_3.7.2/lib/python3.7/site-packages (1.2.4)

But when I use ICE, it returns this error
(python_3.7.2) [gaoyuan@localhost ~]$ ice -h
  File "/home/gaoyuan/anaconda3/envs/python_3.7.2/bin/ice", line 58
    print "--filtering_perc is deprecated. Please use filter_low_counts_perc"
                                                                            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("--filtering_perc is deprecated. Please use filter_low_counts_perc")?

How should I solve this problem of my ICE?
Many thanks!

**Comment by xumu3333** [comment]
when I import iced in my python,it is appear these error

(python_3.7.2) [gaoyuan@localhost example]$ python
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iced
/home/gaoyuan/anaconda3/envs/python_3.7.2/lib/python3.7/site-packages/iced/normalization/_ca_utils.py:9: UserWarning: The API of this module is likely to change. Use only for testing purposes
  "The API of this module is likely to change. "

**Comment by nservant** [comment]
Hi
The latter is just a warning.
But it seems that there is something wrong with python3 and iced.
You should use HiC-Pro version > 3.0.0 and python3 with the latest iced version.
Could you check that please ?

**Comment by xumu3333** [comment]
Thank you very much for your reply！！

(python_3.7.2) [gaoyuan@localhost example]$ /home/gaoyuan/HiC/HiC-Pro_3.0.0/bin/HiC-Pro -v
HiC-Pro version 3.0.0

this is my HiC-Pro and python version

**Comment by xumu3333** [comment]
but my raw matrix is empty.
I don't know if that's the problem

**Comment by nservant** [comment]
:) indeed ! if the matrix is empty the normalization can not work !
Could you look at logs downstream to see why your matrix is empty ?

**Comment by xumu3333** [comment]
I'm sorry to have disturbed you!!

I found that there was an error in generating the file SIZES, all because of my carelessness.

I'm sorry to disturb you again. Wish you happiness
