### ISSUE TITLE
/Makefile:144: bowtie_pairing] Error 1

### ISSUE THREAD

**Issue by xumu3333** [nservant/HiC-Pro#445]
Hello, I have a problem with Pairing of R1 and R2 tags ...
My error is as follows：

Pairing of R1 and R2 tags ...
Logs: logs/m1/mergeSAM.log
make: *** [/home/gaoyuan/HiC/HiC-Pro_3.0.0/bin/../scripts//Makefile:144: bowtie_pairing] Error 1

I checked mergesam.log
content is as follows：

[E::idx_find_and_load] Could not retrieve index file for 'bowtie_results/bwt2/m1/m1_TKD181102273_R1.clean_sc19.bwt2merged.bam'
[E::idx_find_and_load] Could not retrieve index file for 'bowtie_results/bwt2/m1/m1_TKD181102273_R2.clean_sc19.bwt2merged.bam'
## Merging forward and reverse tags ...
Forward and reverse reads not paired. Check that BAM files have the same read names and are sorted.

I don't know what's wrong with my files?
How can I solve this problem?
Thanks for any answers!

**Comment by xumu3333** [comment]
how to check my .bam files

**Comment by Peggy1998** [comment]
I meet the same question, how can I solve it ?
