### ISSUE TITLE
python dependencies

### ISSUE THREAD

**Issue by scholtalbers** [nservant/HiC-Pro#45]
The doc. might be updated to indicate a more specific python module dependencies i.e. including minimum version number - I ran into issues with an outdated pysam (.AlignmentFile() missing). Furthermore, the module iced is required.
My current (working on the testdata) pip freeze:
```
bx-python==0.7.3
iced==0.2.2
numpy==1.11.0
pysam==0.8.4
scipy==0.17.1
```

**Comment by nservant** [comment]
Thank you. Indeed, I will add these points in the manual, and update the code to check the python version during the installation. The iced package is included into HiC-Pro and should be installed during the installation process.
Nicolas

**Comment by nservant** [comment]
I have updated the scripts/install/check_pythonlib.py script and the manual.
Thank you
Nicolas
