### ISSUE TITLE
Warning : Scheduler system not defined - Default is Torque/PBS

### ISSUE THREAD

**Issue by ld9866** [nservant/HiC-Pro#450]
make configure
make -f ./scripts/install/Makefile CONFIG_SYS=./config-install.txt
make[1]: Entering directory '/HiC-Pro_3.0.0'
./scripts/install/install_dependencies.sh -c ./config-install.txt -p /usr/local/bin/ -o /usr/local/bin//HiC-Pro_3.0.0 -q
Make sure internet connection works for your shell prompt under current user's privilege ...
Starting HiC-Pro installation ...
Checking dependencies ... 
Checking Python libraries ...
/usr/local/anaconda/envs/HiC-Pro_v3.0.0/lib/python3.7/site-packages/iced/normalization/_ca_utils.py:9: UserWarning: The API of this module is likely to change. Use only for testing purposes
  "The API of this module is likely to change. "
The required Python libraries appear to be already installed. 
Checking R installation ...
The required R packages appear to be already installed. 
Bowtie2 Aligner appears to be already installed. 
Samtools appears to be already installed. 
Dependencies checked !
Check HiC-Pro configuration ... 
Warning : Scheduler system not defined - Default is Torque/PBS
Configuration for TORQUE/PBS system.

**Comment by ld9866** [comment]
l am trying to install it through docker and conda, l ues ubuntu20.04 and l want to know how to solve it.

**Comment by nservant** [comment]
Hi,
Could you explain me what is the issue here ? I do not see any error message ?
N
