### ISSUE TITLE
bowtie2 mapping step

### ISSUE THREAD

**Issue by yussufhajjaj** [nservant/HiC-Pro#455]
Hi Nicolas,

I have HiChIP fastq files I would like to process them with hicpro, I downloaded the reference genome hg38, and digested it according to MboI restriction sites, and now I am trying to run bowtie2 mapping step from the hicpro pipeline using this code:

$bin/HiC-Pro -i /hichip_data/hichip_fastq -o /hichip_data/hichip_output_hg38 -c /hicpro_installation/HiC-Pro_3.0.0/config-hicpro.txt -s mapping

but this error message appear
Bowtie2 alignment step1 ...
Logs: logs/sample1/mapping_step1.log
Exit: Error in reads alignment - Exit
make: *** [/HiC-Pro_3.0.0/bin/../scripts//Makefile:88: bowtie_global] Error 1

and the log file says:
bin/bowtie2-align-s: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory
(ERR): Description of arguments failed!
Exiting now ...

I don't know what I did wrong here, but I could use some help, and thanks in  advance.

best, Yussuf.

**Config file:**

# Please change the variable settings below if necessary

#########################################################################
#########################################################################

TMP_DIR = tmp
LOGS_DIR = logs
BOWTIE2_OUTPUT_DIR = bowtie_results
MAPC_OUTPUT = hic_results
RAW_DIR = rawdata

#######################################################################
#######################################################################
N_CPU = 16
SORT_RAM = 10000M
LOGFILE = hicpro.log

JOB_NAME = 
JOB_MEM = 
JOB_WALLTIME = 
JOB_QUEUE = 
JOB_MAIL = 

#########################################################################
#########################################################################

PAIR1_EXT = _R1
PAIR2_EXT = _R2

#######################################################################
#######################################################################

MIN_MAPQ = 10

BOWTIE2_IDX_PATH = 
BOWTIE2_GLOBAL_OPTIONS = --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder
BOWTIE2_LOCAL_OPTIONS =  --very-sensitive -L 20 --score-min L,-0.6,-0.2 --end-to-end --reorder

#######################################################################
#######################################################################

REFERENCE_GENOME = hg38
GENOME_SIZE = hg38.chrom.sizes

#######################################################################
#######################################################################

ALLELE_SPECIFIC_SNP = 

#######################################################################
#######################################################################

CAPTURE_TARGET =
REPORT_CAPTURE_REPORTER = 1

#######################################################################
#######################################################################

GENOME_FRAGMENT = hg38_MboI_resfrag.bed
LIGATION_SITE = GATCGATC
MIN_FRAG_SIZE = 
MAX_FRAG_SIZE =
MIN_INSERT_SIZE =
MAX_INSERT_SIZE =

#######################################################################
#######################################################################

MIN_CIS_DIST =
GET_ALL_INTERACTION_CLASSES = 1
GET_PROCESS_SAM = 0
RM_SINGLETON = 1
RM_MULTI = 1
RM_DUP = 1

#######################################################################
#######################################################################

BIN_SIZE = 20000 40000 500000
MATRIX_FORMAT = upper

#######################################################################
#######################################################################
MAX_ITER = 100
FILTER_LOW_COUNT_PERC = 0.02
FILTER_HIGH_COUNT_PERC = 0
EPS = 0.1
****

**Comment by esebesty** [comment]
I had a similar problem, and it seems that bowtie needs a specific version of tbb, also discussed in #441.

**Comment by yussufhajjaj** [comment]
Thanks alot for the help Endre, it did solve the problem. 

I would like to ask you if you have an example of the bowtie2 index file, I decided to use a different genome assembly and I have an ready made bowtie indexes, do you maybe know an example file list that are needed for hicpro and how to add them to the config file? and Thanks in advance.
