### ISSUE TITLE
Read Pairs Alignment on Restriction Fragments 100% dumped

### ISSUE THREAD

**Issue by yinshiyi** [nservant/HiC-Pro#458]
Hi,

My bowtie2 was fine with 60% unique aligned
but then in the hindiii fragment bed file part, 100% of the reads pairs were dumped

Any ideas?
Thank you.
Also got an error saying 

Run quality checks for all samples ...
Logs: logs/sample2/make_Rplots.log
make: *** [/usr/local/bin/HiC-Pro_3.0.0/bin/../scripts//Makefile:181: hic_qc] Error 1

**Comment by yinshiyi** [comment]
/usr/bin/python /usr/local/bin//HiC-Pro_3.0.0/scripts/mapped_2hic_fragments.py -v -a -f /home/shiyi/pig_DpnII.bed -r bowtie_results/bwt2/sample1/_Sscrofa11.1.bwt2pairs.bam -o hic_results/data/sample1
[E::idx_find_and_load] Could not retrieve index file for 'bowtie_results/bwt2/sample1/_Sscrofa11.1.bwt2pairs.bam'
## overlapMapped2HiCFragments.py
## mappedReadsFile= bowtie_results/bwt2/sample1/_Sscrofa11.1.bwt2pairs.bam
## fragmentFile= /home/shiyi/pig_DpnII.bed
## minInsertSize= None
## maxInsertSize= None
## minFragSize= None
## maxFragSize= None
## allOuput= True
## SAM ouput= False
## verbose=True

## Loading Restriction File Intervals /home/shiyi/pig_DpnII.bed ...
load_restriction_fragment function took 63384.249ms
## Opening SAM/BAM file bowtie_results/bwt2/sample1/_Sscrofa11.1.bwt2pairs.bam ...
## Classifying Interactions ...
Warning - no restriction fragments for GWNJ-0850:721:GW2002102893rd:2:1101:1509:35537 at NC_010457.5 : 112159388
Warning - no restriction fragments for GWNJ-0850:721:GW2002102893rd:2:1101:1509:35537 at NC_010457.5 : 112159050
Warning - no restriction fragments for GWNJ-0850:721:GW2002102893rd:2:1101:1803:37840 at NC_010443.5 : 28984637
Warning - no restriction fragments for GWNJ-0850:721:GW2002102893rd:2:1101:1803:37840 at NC_010443.5 : 28984696
Warning - no restriction fragments for GWNJ-0850:721:GW2002102893rd:2:1101:1966:43220 at NC_010450.4 : 89508133
Warning - no restriction fragments for GWNJ-0850:721:GW2002102893rd:2:1101:1966:43220 at NC_010450.4 : 89507958
Warning - no restriction fragments for GWNJ-0850:721:GW2002102893rd:2:1101:1976:20700 at NC_010443.5 : 219511418

**Comment by Xueyuan-Zhao** [comment]
How can you fix first issue-Makefile:181: hic_qc] Error 1？
