### ISSUE TITLE
Assignment to  restriction fragments

### ISSUE THREAD

**Issue by ajazwani** [nservant/HiC-Pro#460]
I have run Hic-Pro successfully on yeast data several times and now I am trying it on data from Drosophila but I am getting error at assignment to restriction fragments 

Assign alignments to restriction fragments ...
Exit: GENOME_FRAGMENT not found. The file  does not exist ?
make: *** [mapped_2hic_fragments] Error 1

There is nothing in logs related to this step, but logs for previous steps seem to be OK. 
I am using DpnII for digestion. I have created the DpnII restriction_fragment.bed using Hic-pro utility and inspected the file manually, it seem OK. Below is my configuration file.

# Please change the variable settings below if necessary

#########################################################################
#########################################################################

TMP_DIR = mp
LOGS_DIR = logs
BOWTIE2_OUTPUT_DIR = bowtie_results
MAPC_OUTPUT = hic_results
RAW_DIR = rawdata

#######################################################################
#######################################################################
N_CPU = 2
LOGFILE = hicpro_testop.log

JOB_NAME = hicpro-test
JOB_MEM = 10gb
JOB_WALLTIME = 12:00:00
JOB_QUEUE = batch
JOB_MAIL = waniajazjk@gmail.com

#########################################################################
#########################################################################

PAIR1_EXT = _R1
PAIR2_EXT = _R2

#######################################################################
#######################################################################
FORMAT = phred33
MIN_MAPQ = 2

BOWTIE2_IDX_PATH = /Users/ajazwani/analysis/bowtie_indexesdroso
BOWTIE2_GLOBAL_OPTIONS = --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder
BOWTIE2_LOCAL_OPTIONS =  --very-sensitive -L 20 --score-min L,-0.6,-0.2 --end-to-end --reorder

#######################################################################
#######################################################################

REFERENCE_GENOME = dm3
GENOME_SIZE = chrom_dm3.sizes

#######################################################################
#######################################################################

ALLELE_SPECIFIC_SNP = 

#######################################################################
#######################################################################

GENOME_FRAGMENT = dpnii_resfrag_dm3.bed
LIGATION_SITE = ATCG
MIN_FRAG_SIZE = 100
MAX_FRAG_SIZE = 100000
MIN_INSERT_SIZE = 100
MAX_INSERT_SIZE = 600

#######################################################################
#######################################################################

MIN_CIS_DIST =
GET_ALL_INTERACTION_CLASSES = 1
GET_PROCESS_SAM = 1
RM_SINGLETON = 1
RM_MULTI = 1
RM_DUP = 1

#######################################################################
#######################################################################

BIN_SIZE = 100000 300000 600000
MATRIX_FORMAT = upper

#######################################################################
#######################################################################
MAX_ITER = 100
FILTER_LOW_COUNT_PERC = 0.02
FILTER_HIGH_COUNT_PERC = 0
EPS = 0.1

**Comment by nservant** [comment]
Hi
Please provide the full path of your file to `GENOME_FRAGMENT`
best

**Comment by ajazwani** [comment]
thanks, providing full path worked
