### ISSUE TITLE
testing data set cannot be downloaded

### ISSUE THREAD

**Issue by yinshiyi** [nservant/HiC-Pro#461]
wget https://zerkalo.curie.fr/partage/HiC-Pro/HiCPro_testdata.tar.gz && tar -zxvf HiCPro_testdata.tar.gz

The data is not accessible anymore.

Is there a new link?
Thank you.

**Comment by pocession** [comment]
@yinshiyi Hey, did you finally find the resource to download the sample data? I encountered similar problem.

tsunghan.hsieh@ru.nl
