### ISSUE TITLE
make: *** [bowtie_global] Error 1

### ISSUE THREAD

**Issue by NZhang487** [nservant/HiC-Pro#462]
Hello!

First of all, thank you for developing this amazing tool!

I'm new to hic analysis and was trying to run HiC-Pro 3.0.0 on the test dataset. Here is my command:
/data/huangfu/ZhangN/bin/HiC-Pro-3.0.0/bin/HiC-Pro -c config_test_latest.txt -i test_data -o hicpro_latest_test

I run it on a cluster and got the following error message:

Run HiC-Pro 3.0.0
--------------------------------------------
Sat Jul 24 21:05:23 EDT 2021
Bowtie2 alignment step1 ...
Logs: /data/huangfu/ZhangN/HiCAR/ES/hicpro_latest_test/logs/dixon_2M_2/mapping_step1.log
Exit: Error in reads alignment - Exit
make: *** [bowtie_global] Error 1

Here are my log files:

> cat mapping_step1.log 
/home/zhangn2/bin/bowtie2-2.4.4/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un /data/huangfu/ZhangN/HiCAR/ES/hicpro_latest_test/bowtie_results/bwt2_global/dixon_2M_2/SRR400264_01_R1_hg19.bwt2glob.unmap.fastq --rg-id BMG --rg SM:SRR400264_01_R1 -p 1 -x /lila/data/leslie/genome_index/hg19.bowtie2/hg19 -U rawdata/dixon_2M_2/SRR400264_01_R1.fastq.gz 2>> /data/huangfu/ZhangN/HiCAR/ES/hicpro_latest_test/logs/dixon_2M_2/SRR400264_01_R1_bowtie2.log| /opt/common/CentOS_7/samtools/samtools-1.8/bin/samtools view -F 4 -bS - > /data/huangfu/ZhangN/HiCAR/ES/hicpro_latest_test/bowtie_results/bwt2_global/dixon_2M_2/SRR400264_01_R1_hg19.bwt2glob.bam
/home/zhangn2/bin/bowtie2-2.4.4/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un /data/huangfu/ZhangN/HiCAR/ES/hicpro_latest_test/bowtie_results/bwt2_global/dixon_2M_2/SRR400264_01_R2_hg19.bwt2glob.unmap.fastq --rg-id BMG --rg SM:SRR400264_01_R2 -p 1 -x /lila/data/leslie/genome_index/hg19.bowtie2/hg19 -U rawdata/dixon_2M_2/SRR400264_01_R2.fastq.gz 2>> /data/huangfu/ZhangN/HiCAR/ES/hicpro_latest_test/logs/dixon_2M_2/SRR400264_01_R2_bowtie2.log| /opt/common/CentOS_7/samtools/samtools-1.8/bin/samtools view -F 4 -bS - > /data/huangfu/ZhangN/HiCAR/ES/hicpro_latest_test/bowtie_results/bwt2_global/dixon_2M_2/SRR400264_01_R2_hg19.bwt2glob.bam

> cat SRR400264_01_R2_bowtie2.log
##HiC-Pro mapping
(ERR): bowtie2-align died with signal 7 (BUS) 

I tried to directly run bowtie2 on the test fastq files and it worked fine. So it seems not a problem with bowtie2... Do you have any idea what is going wrong here?

Thanks a lot for your help!
Nan

**Comment by nservant** [comment]
Hi,
It seems that this is more a bowtie2 issue than a HiC-pro one.
If you goodle the error "(ERR): bowtie2-align died with signal 7 (BUS)", you may find some help.
Maybe corrupted index files ? https://github.com/FelixKrueger/Bismark/issues/339
N

**Comment by NZhang487** [comment]
Hi,
Thank you for your prompt reply!
I tried to regenerate bowtie2 index, but still got the same error. I even tried to reinstall HiC-Pro, but it did not help either.
The strange thing is that when I directly run bowtie2 on the files, I can generate the output files without any error:

[zhangn2@lilac-ln02 ES]$ /home/zhangn2/bin/bowtie2-2.4.4/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un /data/huangfu/ZhangN/HiCAR/ES/hicpro_latest_test/bowtie_results/bwt2_global/dixon_2M_2/SRR400264_01_R2_hg19.bwt2glob.unmap.fastq --rg-id BMG --rg SM:SRR400264_01_R2 -p 1 -x /data/huangfu/ZhangN/genome/hg19/hg19 -U test_data/dixon_2M_2/SRR400264_01_R2.fastq.gz 2>> /data/huangfu/ZhangN/HiCAR/ES/hicpro_latest_test/logs/dixon_2M_2/SRR400264_01_R2_bowtie2.log| /opt/common/CentOS_7/samtools/samtools-1.8/bin/samtools view -F 4 -bS - > /data/huangfu/ZhangN/HiCAR/ES/hicpro_latest_test/bowtie_results/bwt2_global/dixon_2M_2/SRR400264_01_R2_hg19.bwt2glob.bam

[zhangn2@lilac-ln02 ES]$ ll hicpro_latest_test/bowtie_results/bwt2_global/dixon_2M_2/
total 15441
-rw-r--r-- 1 zhangn2 huangfu      62 Jul 25 16:44 SRR400264_01_R1_hg19.bwt2glob.bam
-rw-r--r-- 1 zhangn2 huangfu       0 Jul 25 16:44 SRR400264_01_R1_hg19.bwt2glob.unmap.fastq
-rw-r--r-- 1 zhangn2 huangfu 8699402 Jul 25 16:46 SRR400264_01_R2_hg19.bwt2glob.bam
-rw-r--r-- 1 zhangn2 huangfu 7108574 Jul 25 16:46 SRR400264_01_R2_hg19.bwt2glob.unmap.fastq

I'm confused ...

**Comment by nservant** [comment]
And if you try to run bowtie2 on the cluster ?

**Comment by NZhang487** [comment]
Yes, directly running bowtie2 on the cluster can generate the output bam file.

**Comment by mengying0714** [comment]
Hello, I got the same error, Do you know the wrong reason? Thank you.
