### ISSUE TITLE
Error when using Dockerfile to create image

### ISSUE THREAD

**Issue by gf0927** [nservant/HiC-Pro#465]
I copied the latest Dockerfile and environment.yml tried create my own image , but it failed at (12/13) step .. 
I had successfully built the image in the previous version, so I guess the path in the new version has been change ?

Here's my error message : 

make[1]: Leaving directory '/tmp/HiC-Pro-master'
(g++ -Wall -O2 -std=c++0x -o build_matrix /tmp/HiC-Pro-master/scripts/src/build_matrix.cpp; mv build_matrix /tmp/HiC-Pro-master/scripts)
(g++ -Wall -O2 -std=c++0x -o cutsite_trimming /tmp/HiC-Pro-master/scripts/src/cutsite_trimming.cpp; mv cutsite_trimming /tmp/HiC-Pro-master/scripts)
realpath: /home/nservant/Apps//HiC-Pro_3.1.0: No such file or directory
cp -Ri /tmp/HiC-Pro-master /home/nservant/Apps//HiC-Pro_3.1.0
cp: cannot create directory '/home/nservant/Apps//HiC-Pro_3.1.0': No such file or directory
make: *** [Makefile:78: cp] Error 1
The command '/bin/sh -c cd /tmp &&     echo "master.zip" | wget --base=http://github.com/nservant/HiC-Pro/archive/ -i - -O hicpro_latest.zip &&     unzip hicpro_latest.zip &&     cd HiC-Pro-master  &&     make configure prefix=/ &&     make install &&     cd .. &&     rm -fr HiC-Pro*' returned a non-zero code: 2

**Comment by nservant** [comment]
Hi,
Indeed, sorry, this is because I fixed the installation path in my home folder (in the `config-install.txt` file).
I have just updated the devel and master branches.
Of note, I didn't finish all the tests for the 3.1.0 ... I'll do it at the end of the month !
N

**Comment by gf0927** [comment]
Thanks for efficiency ! I built it successfully !
