### ISSUE TITLE
Checking python libraries

### ISSUE THREAD

**Issue by Krannich479** [nservant/HiC-Pro#47]
Hi, 
I currently had an issue with a "too up-to-date" scipy version. I am using the 0.18.1 developer version which causes an error within the scripts/install/check_pythonlib.py because the vcmp() can't catch the developer name tag suffix. I know it's a minor issue, but the error message is kind of a cryptic mess if you aren't a python programmer and is easy to fix/catch.

Best, 
TK

**Comment by nservant** [comment]
Hi,
Thank you for your comment.
Do you have any idea to fix this ?
>>>> vcmp('0.18.1','0.15.1')
1
Is it linked to the way I'm detecting the version ? scipy.version.version ?
Best
N

**Comment by Krannich479** [comment]
Hej,
the following problem occurred in particular:
With the developer release comes the version name "0.18.0.dev0+609facc". The RE substitution of your vcmp() function does not catch the developer suffix.
So I suggest the following possible fixes:
1.) Either catch a developers tag in the normalize() function, like 
```
>>> "dev" in "0.18.0.dev0+609facc"
True
```
Where "0.18.0.dev0+609facc" is your "version1" parameter or
2.) you add the lookup for the "dev" into the re.sub() function. 

Suggestion 2.) is probably a little cleaner and less code, but both should work.

Best,
TK

**Comment by nservant** [comment]
Great. Should be fixed now.
Thank you for your help
Nicolas
