### ISSUE TITLE
Singularity image 

### ISSUE THREAD

**Issue by clagiamba** [nservant/HiC-Pro#478]
Hi,
Indeed, the qusb script is not set up to run with Singularity.
Running `singularity exec` should do the job. Does it work ?
N

_Originally posted by @nservant in https://github.com/nservant/HiC-Pro/issues/432#issuecomment-822212102_

**Comment by clagiamba** [comment]
It seems to find the command, but it does not execute. Also tried inside "singularity shell hicpro_latest_ubuntu.img", Singularity> HiC-Pro -i INOUT -c CONFIG", but it does not seem to recognize the commands... 
I am wondering if to try to install the Singularity image in another way (? maybe through docker) or to try a different route all together... Thank you!

**Comment by nservant** [comment]
Hi @clagiamba 
Which Singularity image are you using please ? I just release a couple of days ago a new Singularity recipe (3.1.0).
Could you try this one please ?
N

**Comment by clagiamba** [comment]
Hi! thank you, I just tried the one linked in the main README (https://zerkalo.curie.fr/partage/HiC-Pro/singularity_images/hicpro_latest_ubuntu.img) but I have not tried creating the image myself - let me try doing that then...

**Comment by clagiamba** [comment]
Thank you! This works great and it is very easy to use. 
Basically just by downloading the image and using in the script HiCPro_step1_hic.sh: "singularity exec hicpro_3.1.0_ubuntu.img HiC-Pro -i 3_hicpro/rawdata -o hic_results -c config_test_latest.txt". 
Thank you!
