### ISSUE TITLE
The ice.log reported an error, but my raw matrix had been iced successfully.

### ISSUE THREAD

**Issue by jiangpuxuan** [nservant/HiC-Pro#494]
When I `head` /ice_1000000.log, it looks like `ice`  encountered an error:

> /Array-Tuqiang/pxjiang/miniconda3/envs/hicpro3.1/bin/python /Array-Tuqiang/pxjiang/packages//HiC-Pro_3.1.0/scripts/ice --results_filename hic_results/matrix/SRR14670388/iced/1000000/SRR14670388_1000000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 hic_results/matrix//SRR14670388/raw/1000000/SRR14670388_1000000.matrix
/Array-Tuqiang/pxjiang/packages//HiC-Pro_3.1.0/scripts/ice:65: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if "--filtering_perc" is None and "--filter_low_counts_perc" not in sys.argv:
/Array-Tuqiang/pxjiang/miniconda3/envs/hicpro3.1/lib/python3.8/site-packages/iced/normalization/_ca_utils.py:8: UserWarning: The API of this module is likely to change. Use only for testing purposes
  warnings.warn(
Assuming the file is 1-based. If this is not the desired option, set option --base to 0

However, it appeared normal in my `log` for `~/packages/HiC-Pro-master/bin/HiC-Pro`, no error was reported :

> Logs: logs/SRR12435868/ice_20000.log
Logs: logs/SRR12435868/ice_40000.log
Logs: logs/SRR12435868/ice_150000.log
Logs: logs/SRR12435868/ice_500000.log
Logs: logs/SRR12435868/ice_1000000.log
Logs: logs/SRR14670388/ice_20000.log
Logs: logs/SRR14670388/ice_40000.log
Logs: logs/SRR14670388/ice_150000.log
Logs: logs/SRR14670388/ice_500000.log
Logs: logs/SRR14670388/ice_1000000.log

When I look into my matrix, **it seems that they have been iced successfully**.
Raw:

> 1       1       112
1       2       28
1       3       2
1       6       2
1       7       5
1       8       2
1       11      2
1       12      2
1       13      1
1       14      1

Iced:

> 1       1       3910.979146
1       2       841.528309
1       3       64.079865
1       6       84.466665
1       7       151.959959
1       8       63.944928
1       11      93.948140
1       12      69.718344
1       13      60.303662
1       14      40.049700

Very appreciate for your help!

**Comment by nservant** [comment]
Hi,
I think these are just warnings !
Best

**Comment by jiangpuxuan** [comment]
> Hi, I think these are just warnings ! Best

Thank you for your help.
