### ISSUE TITLE
HiC-Pro and Chromap

### ISSUE THREAD

**Issue by BioEpi** [nservant/HiC-Pro#495]
Hello,
     based on this paper (https://www.nature.com/articles/s41467-021-26865-w), Chromap looks better than BWA and Bowtie2.  Do you think whether we can call Chromap when running HiC-Pro?
Best,
Benxia

**Comment by nservant** [comment]
Hi
HiC-Pro is not going to integrate Chromap. It is not flexible enough to change the mapper.
However, this is something we can keep in mind for the nf-core-hic pipeline.
Could please open an issue at https://github.com/nf-core/hic
Thanks
