### ISSUE TITLE
Error in reads alignment

### ISSUE THREAD

**Issue by LlChangSub** [nservant/HiC-Pro#496]
hello, I download HiC-Pro from github, version3.1.0, and download demo test data, but the step "Bowtie2 alignment step2 ..." always getting wrong, The error information is as follows
Run HiC-Pro 3.1.0
--------------------------------------------
Mon Nov 15 09:57:54 CST 2021
Bowtie2 alignment step1 ...
Logs: logs/dixon_2M_2/mapping_step1.log
Logs: logs/dixon_2M/mapping_step1.log

--------------------------------------------
Mon Nov 15 09:58:57 CST 2021
Bowtie2 alignment step2 ...
Logs: logs/dixon_2M_2/mapping_step2.log
Exit: Error in reads alignment - Exit
make: *** [biosoft/hicpro/HiC-Pro-3.1.0/bin/../scripts//Makefile:101: bowtie_local] Error 1
can you tell me how to solve this problem?
Thank you!

**Comment by nservant** [comment]
Hi,
Please, have a look at the `logs/dixon_2M_2/mapping_step2.log` file.
Do you have a clear error message ?
Best

**Comment by TonFerreira** [comment]
Hi, I have a similar issue in "Combine R1/R2 alignment files ..."

slurmstepd: error: Job 40131247 exceeded memory limit (204802220 > 204800000), being killed
slurmstepd: error: Exceeded job memory limit

I put in my config-hicpro file:
N_CPU = 8
SORT_RAM = 12000M

And in my slurm file: 
#SBATCH -c 16
#SBATCH --mem=200000
#SBATCH -N 1

I have read that Sort_bam x CPUs will give the memory limits of Hi-C Pro to work:
so 8 CPUs x 12 gb = 96 gb, but apparently, this did not work. 

In my mapping_combine.log apparently there is no error:
"/usr/local/anaconda/bin/samtools sort -@ 8 -m 12000M -n -T tmp/hiC_ppufv02_R2_ppufv.p_ctg_v1 -o bowtie_results/bwt2/rawdata/hiC_ppufv02_R2_ppufv.p_ctg_v1.bwt2merged.sorted.bam bowtie_results/bwt2/rawdata/hiC_ppufv02_R2_ppufv.p_ctg_v1.bwt2merged.bam"

Inside the bwt2 folder, there are two bam files, with one with 24 gb...
But the script did not run after that...
