### ISSUE TITLE
how to generate the annotation file of Arabidopsis_thaliana?

### ISSUE THREAD

**Issue by RuiqinZheng** [nservant/HiC-Pro#50]
Hi 
I`m interested in your softeware,and I have somen data of Arabidopsis_thaliana,but there`s no annotation file in you software`s annotation,so how can I get the annotation file of Arabidopsis_thaliana?
Can I use bowtie2 and then samtools 、bedtools to generate the Arabidopsis_thaliana.bed file?
Thanks a lot

**Comment by nservant** [comment]
Hi,
To generate your annotation files, please have a look at the manual ;
http://nservant.github.io/HiC-Pro/QUICKSTART.html#annotation-files

We describe two different way of generating the restriction fragment file, but the easiest one should be to use the digest_genome utils.
See http://nservant.github.io/HiC-Pro/UTILS.html#utils

If you have any other question, do not hesitate.
Best wishes
Nicolas

**Comment by RuiqinZheng** [comment]
Thank you very much!That`s means a lot to me
