### ISSUE TITLE
Multiple Pairs 

### ISSUE THREAD

**Issue by ustcahwry** [nservant/HiC-Pro#51]
Hi, 
When I was using mergeSAM.py to merge the two mapped reads file and get the pairing statistics, the results showed my pairs are 80% multiple pairs which is not reasonable. And I checked the script and found that " read.is_unique" function is only for bowtie2 mapped files.  Since I was using SNAP to align the reads but not Bowtie2, could you please help me that is there an another option to find multiple pairs? Thanks a lot!

Best

**Comment by nservant** [comment]
Hi,
Yes indeed I developed this script for bowtie2.
If you want to use another mapper, you will have to update the script.
I think that most of the functions are common to many mappers, but some of them, as the multiple hits, are specific.
Or, maybe you can try to switch of the RM_MUTLI option from the config file. In this case, multiple hits should be conserved. I guess the stat file will still be wrong, but at least the reads should not be discarded for the downstream analysis.
N

**Comment by ustcahwry** [comment]
Hi, 
Thanks a lot for you kindly advice. I've solved the multiple hits problem. But after I merged the valid pairs and quality controls, I found that there was about 89% PCR duplicates in my validpairs of Hi-C library.
![image](https://cloud.githubusercontent.com/assets/12220712/17129557/6a60c7be-5346-11e6-9d9b-4f5bfc697bde.png)
Could you please help me about this? 
Great thanks

**Comment by nservant** [comment]
humm ... duplicates are detected from the list of valid 3C products. All interactions where read1 and read2 mapped exactly at the same position are considered as duplicates. So duplicates are usually PCR artefacts and we advice to remove them. Do you have any biological/technical explanation first ?
Then, if you really want to keep up, just turn off the option RM_DUP=0 ...
Nicolas
