### ISSUE TITLE
Restarting after BAM pairing

### ISSUE THREAD

**Issue by pna059** [nservant/HiC-Pro#517]
Hi, my HiC-pro run (with singularity) has stopped right after BAM file pairing.
The last LOG file is the mergeSAM.log
bowtie results sem to be in place including the .bwt2pairs.bam and .bwt2pairs.pairstat being the last output files
When I attempt to continue from the stage -s quality_checks it runs only the R output and the stats plot. When running from -s proc_hic, the error says: 
Exit: Error: Directory Hierarchy of rawdata '/storage/budejovice1/home/pavlan/Morex_HiChIP/24DAP/H3K4me3_1' is not correct. Paired '.bam' files with _R1/_R2 are required for 'proc_hic' step(s)

Do I need to reorganize the files in order to start from the second step? I really don`t want to run the mapping again, my genome and data files are big.

Thanks for the help!

**Comment by pna059** [comment]
I think I solved my issue by changing the -i to the results directory, specifically the bowtie_results/bwt2. It is pairing the files again, but I hope that the rest of the pipeline will finish.

**Comment by lilongjuan** [comment]
I run it step by step, completing the "mapping" step. For the next "-s proc_hic" step, I indeed used the result from the previous "mapping" step, but I still encounter this error. Here are my commands:/media/desk15/iy1702/newstools/HiC-Pro_3.1.0/bin/HiC-Pro -s proc_hic -c /media/desk15/iy1702/newstools/HiC-Pro_3.1.0/config-hicpro.txt -i /media/desk15/iy1702/newstools/HiC-Pro_3.1.0/output_data/bowtie_results/bwt2 -o /media/desk15/iy1702/newstools/HiC-Pro_3.1.0/output_procdata。My error report is as follows：Exit: Error: Directory Hierarchy of rawdata '/media/desk15/iy1702/newstools/HiC-Pro_3.1.0/output_data/bowtie_results/bwt2' is not correct. Paired '.bam' files with _R1/_R2 are required for 'proc_hic' step(s)
