### ISSUE TITLE
Cannot generate contact maps

### ISSUE THREAD

**Issue by ghar1821** [nservant/HiC-Pro#525]
Hi there,

I am testing HiC-Pro 3.1.0 on the dixon dataset before running it on my dataset, and am having trouble generating the contact maps. I used the default config file supplied with the dataset, and the hg19 index file downloaded from bowtie2 website. 

Here is the error message in the build_raw_maps.log file:
```
## Generate contact maps at 500000 resolution ...
cat hic_results/data//dixon_2M/dixon_2M.allValidPairs | /apps/hicpro/3.1.0/scripts/build_matrix --matrix-format upper --binsize 500000 --chrsizes /home/z35****/softwares/HiC-Pro/annotation/chrom_hg19.sizes --ifile /dev/stdin --oprefix hic_results/matrix/dixon_2M/raw/500000/dixon_2M_${bsize}
/apps/hicpro/3.1.0/scripts/hic.inc.sh: line 86: /apps/hicpro/3.1.0/scripts/build_matrix: No such file or directory
cat: write error: Broken pipe
``` 

My initial thought was that maybe the script cannot find the allValidPairs file, but I've checked the output folder (hic_results/data/dixon_2M), and it's there. 

All helps are appreciated! Thanks!

**Comment by nservant** [comment]
Hi,
Did you install HiC-Pro following the manual, with `make configure / make install`, etc.
The point here is that the `build_matrix` code was not compiled during the installation process.
I would suggest to (re) install HiC-Pro.
Best

**Comment by ghar1821** [comment]
Thanks @nservant. I suspected that could be the problem as I couldn't find the `build_matrix` compiled file in the repo.
I'll check with the IT people who installed HiC-Pro in the cluster and report back.

**Comment by ghar1821** [comment]
@nservant, I've checked with the IT people, and they have resolved the issue. They accidentally used `make` rather than `make install` when installing, which causes the `build_matrix` to not be compiled. Closing the issue. Thank you again for your quick response.
