### ISSUE TITLE
some questions about the bowtie_pairing error

### ISSUE THREAD

**Issue by RuiqinZheng** [nservant/HiC-Pro#53]
Hi
When I try to  run the hicpro using my own data of Arabidopsis_thaliana TAIR10,it showed me error messages:
Sun Jul 24 11:06:44 CST 2016
Pairing of R1 and R2 tags ...
/public/home/rqzheng/bin/HiC-Pro_2.7.8/scripts/bowtie_pairing.sh -c /public/home/rqzheng/t
est/hicprotest/config_test_latest.txt >> hicpro.logmake: *** [bowtie_pairing] Error 1
How can I solve this problem?
Thanks a lot!

**Comment by nservant** [comment]
Hi
Could you please look into the log folder and send me the content of mergeSAM.log.
Could you also check if the mapping works properly ? You should get a bowtie_results folder with 3 sub-dirs.
>>ls bowtie_results/
bwt2/  bwt2_global/  bwt2_local/
Thanks
N

**Comment by nservant** [comment]
Hi,
Did you fix your issue ?
Nicolas
