### ISSUE TITLE
installing issue - dist.py

### ISSUE THREAD

**Issue by abe115** [nservant/HiC-Pro#54]
When I run make CONFIG_SYS=config-install.txt install, I get the following error message: 

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'

and then these errors: 
Warning: Assuming default configuration (iced/utils/{setup_utils,setup}.py was not found)Appending iced.utils configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.utils')
Appending iced.datasets configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.datasets')
non-existing path in 'iced/io': '../src/cblas'
non-existing path in 'iced/io': '../src/cblas'
Appending iced.io configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.io')
non-existing path in 'iced': '../src/cblas'
non-existing path in 'iced': '../src/cblas'
Appending iced configuration to 
Ignoring attempt to set 'name' (from '' to 'iced')
running install
error: [Errno 13] Permission denied: '/home/neuertlab/.local/lib/python2.7'
Makefile:57: recipe for target 'iced' failed
make: *** [iced] Error 1

could you advise? I already made sure that I had all the dependencies.

**Comment by nservant** [comment]
Hi
it looks like you do not have the rights to install new packages in your home !??

 error: [Errno 13] Permission denied: '/home/neuertlab/.local/lib/python2.7'

**Comment by abe115** [comment]
thank you! sorry I missed that.
