### ISSUE TITLE
/tmp/hicmk.4655:68: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by Liangyan-1996** [nservant/HiC-Pro#542]
Dear authors,

I downloaded the latest version HiC-Pro and install following the README step-by-step.

When I tested it, it works.

`~/software/HiC-Pro/HiC-Pro_3.1.0/bin/HiC-Pro -h`
 
However，when I run HiC-Pro using my own config-hicpro.txt, I met an error:

`~/software/HiC-Pro/HiC-Pro_3.1.0/bin/HiC-Pro -c config-hicpro.txt -i fastq -o ./ -s mapping -s quality_checks`

>/tmp/hicmk.4655:68: *** missing separator.  Stop.

I search it in /tmp but there is no `*hicmk*`.

[config-hicpro.txt](https://github.com/nservant/HiC-Pro/files/9078643/config-hicpro.txt)

This is my config file and it seems normal. How should I solve this error?

Best
Yan

**Comment by Liangyan-1996** [comment]
I noticed that there is an issue mention the same error. https://github.com/nservant/HiC-Pro/issues/193
They solved the problems through using the latest version of config file. However, I used the `config-hicpro.txt` file which is under the installing directory of HiC-Pro-3.1.0.

**Comment by Clark1016** [comment]
I had the same question. ~/bin/HiC-Pro-3.1.0/bin/HiC-Pro -i ~/project_HiC-Pro/HiC_data/ -o ./HiC-Pro_output/ -c config-hicpro.txt
/tmp/hicmk.171631:15: *** missing separator.  Stop.
How did you resolve it?
