### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by zhanyinx** [nservant/HiC-Pro#55]
Hello,

in the Makefile at the line:

iced: $(SOURCES)/ice_mod
        (cp $(SOURCES)/ice_mod/iced/scripts/ice ${SCRIPTS}; cd $(SOURCES)/ice_mod/; **python** setup.py install --user;)

It would be better to have a makefile that uses the **python** set in config-install.txt

When I used the local version of python and the relative libraries, I had an error during installation. The way to solve it was giving the full path of python in the Makefile

Thanks

Zhan

**Comment by nservant** [comment]
Hi Zhan
Thank you for your comment. This is a good. I will add it in the TODO list.
Nicolas

**Comment by nservant** [comment]
Hi 
This is now fixed in the Master. I updated the way HiC-Pro has to be installed.
Thanks for the comment
Best
N
