### ISSUE TITLE
HiC scaffolding

### ISSUE THREAD

**Issue by tangerzhang** [nservant/HiC-Pro#57]
Hi,
Just curious, is it possible to use Hic-Pro for contig scaffolding?
Thanks!

**Comment by nservant** [comment]
Hi
What do you need by contig scaffolding ?
HiC-Pro is using bowtie2 for the mapping step. As soon as you have a reference and a bowtie2 index it should work ! However, you will have N^2 interaction maps at the end, where N is the number of scaffold ...
Another approach would be to try to improve the scaffolding using the Hi-C data themselves. I think that the Bing Ren's group proposed method for that.
Best
