### ISSUE TITLE
Comparing Heatmaps

### ISSUE THREAD

**Issue by ustcahwry** [nservant/HiC-Pro#58]
Hi, 
I am wondering that if I want to compare two Hi-C heatmaps, which one is better ? using one raw heatmap to subtract another raw heatmap or using one iced heatmap to subtract another iced heatmap?

Thank you very much!

**Comment by nservant** [comment]
Hi,
Good question. I would say the ICE normalized maps ...
Maybe you can have a look at the diffHiC R package.
Hope it helps
Nicolas

**Comment by ustcahwry** [comment]
Thanks for your advice.  I still have two points to make sure: Does the generated raw matrix value stand for read pair counts between two bins? and how about  the iced matrix value?

Best

**Comment by nservant** [comment]
Yes. The raw matrix is a count matrix with C_ij is the number of time that we sequenced an interaction product involving bin i and j. 
Regarding the iced matrix, it is the same, but normalized in the sense that bias such GC content, mappabilty, fragment length, etc. should be corrected. You can have a look to the Imakaev 2012 paper for more details. So in practice, the output are float values, and no longer integer ...
Best

**Comment by ustcahwry** [comment]
So, are iced matrix values normalized by sequencing  depth?I can directly compare two Hi-C iced heatmaps which have different sequencing depth?

**Comment by nservant** [comment]
Indeed good point. ICE is an intra-sample normalization. So there is no sequencing depth normalization. I guess you will have to apply another step of normalization before the comparison

**Comment by ustcahwry** [comment]
So can I just simply do the normalization by dividing the matrix value with sequencing depth? Thanks!

**Comment by nservant** [comment]
I think so, but I'm not an expert. Maybe you could ask the question on the forum if someone have other idea
https://groups.google.com/forum/#!forum/hic-pro
