### ISSUE TITLE
Assign alignments to restriction fragments

### ISSUE THREAD

**Issue by LHXqwq** [nservant/HiC-Pro#582]
Wed Jun 28 17:31:17 CST 2023
Assign alignments to restriction fragments ...
Logs: logs/W2-6/mapped_2hic_fragments.log
make: *** [/xtdisk/zhangzhh_group/lizijian/HiC-Pro/bin/../scripts//Makefile:152: mapped_2hic_fragments] Error 137

(base) [lizijian@vmloginb2 W2-6]$ tail mapped_2hic_fragments.log 
## Sorting valid interaction file ...
LANG=en; sort -T tmp -k2,2V -k3,3n -k5,5V -k6,6n -o hic_results/data/W2-6/W2-6_val_genome.bwt2pairs.validPairs hic_results/data/W2-6/W2-6_val_genome.bwt2pairs.validPairs
/xtdisk/zhangzhh_group/lizijian/HiC-Pro/scripts/hic.inc.sh: line 86:  4365 Killed                  sort -T tmp -k2,2V -k3,3n -k5,5V -k6,6n -o hic_results/data/W2-6/W2-6_val_genome.bwt2pairs.validPairs hic_results/data/W2-6/W2-6_val_genome.bwt2pairs.validPairs

Hello, I have an error in the step of assigning alignments to restriction fragments, what is the possible reason？

**Comment by nservant** [comment]
Look like a memory issue ... I guess the 'sort' command is requiring too much memory
