### ISSUE TITLE
Unable to download test dataset

### ISSUE THREAD

**Issue by varunkas** [nservant/HiC-Pro#589]
Hi, I am unable to download the test dataset, as per the instructions:
` wget https://zerkalo.curie.fr/partage/HiC-Pro/HiCPro_testdata.tar.gz`
 
 The link does not seem to exist.

**Comment by nservant** [comment]
https://zenodo.org/records/10401822

**Comment by rikrdo89** [comment]
Use:
`wget https://zenodo.org/records/10401822/files/HiCPro_testdata.tar.gz && tar -zxvf HiCPro_testdata.tar.gz`
