### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by IIrfan57** [nservant/HiC-Pro#597]
Hello,

I am installing HiC-pro on a cluster. Make configure step gets completed but at the make install step, I am getting the following error:

Starting HiC-Pro installation !
export /HPC/miniconda3/envs/HiC-Pro/bin/bowtie2 in PATH
export /HPC/miniconda3/envs/HiC-Pro/bin/samtools in PATH
export /HPC/miniconda3/envs/HiC-Pro/bin/R in PATH
export /HPC/miniconda3/envs/HiC-Pro/bin/python3.8 in PATH
Checking dependencies
- Python libraries ...OK
- R installation ...OK
- Bowtie2 installation ...OK
- Samtools installation ...OK

Checking HiC-Pro configuration
- Configuration for SLURM system ...OK

done !
make[1]: Leaving directory '/HiC-Pro'
(HiC-Pro) [HiC-Pro]$ make install
(g++ -Wall -O2 -std=c++0x -o build_matrix /HiC-Pro/scripts/src/build_matrix.cpp; mv build_matrix /HiC-Pro/scripts)
(g++ -Wall -O2 -std=c++0x -o cutsite_trimming /HiC-Pro/scripts/src/cutsite_trimming.cpp; mv cutsite_trimming /HiC-Pro/scripts)
cp -Ri /HPC/HiC-Pro /usr/local/bin//HiC-Pro_3.1.0
cp: cannot create directory '/usr/local/bin//HiC-Pro_3.1.0': Permission denied
make: *** [Makefile:78: cp] Error 1

P.s. I have installed all the dependencies through Conda environment.yml along with the all the required tools such as bowtie2, samtools, R, python in a separate environment.

**Comment by Blosers** [comment]
您好，可以请问您是怎么解决这个问题的吗？我在安装过程中也出现了这样的问题，需要有管理员权限，进行sudo吗？

**Comment by Fish18Sunny** [comment]
你在HiC-Pro-3.1.0目录下找到config-system.txt，然后修改/usr/local/bin//HiC-Pro_3.1.0为你自己安装HiC-Pro_3.1.0当前的路径就行
