### ISSUE TITLE
Exit: Read pairs extensions not defined

### ISSUE THREAD

**Issue by usernicai** [nservant/HiC-Pro#605]
Hi,I got a error **"grep: (standard input): binary file matches
Exit: Read pairs extensions not defined. Exit“**  when i start running hic-pro,
###**1,the organization of my data :**
![image](https://github.com/nservant/HiC-Pro/assets/117134739/b1f71c91-c509-4192-9cde-16ac5264adc1)
### **2,my command line:**
HiC-Pro -i hicdata -o BT549_rep2 -c ~/software/HiC-Pro-3.1.0/config-hicpro.txt
### **3,my hic-pro config file:** 
                  
# Please change the variable settings below if necessary

#########################################################################
#########################################################################

TMP_DIR = tmp
LOGS_DIR = logs
BOWTIE2_OUTPUT_DIR = bowtie_results
MAPC_OUTPUT = hic_results
RAW_DIR = rawdata

#######################################################################
#######################################################################
N_CPU = 10                    
SORT_RAM = 50000M                
LOGFILE = hicpro.log         

JOB_NAME = zht_hic               
JOB_MEM = 50gb                   
JOB_WALLTIME = 6:00:00             
JOB_QUEUE = 
JOB_MAIL = 

#########################################################################
#########################################################################

PAIR1_EXT =_R1          
PAIR2_EXT =_R2

#######################################################################
#######################################################################

MIN_MAPQ = 10             

BOWTIE2_IDX_PATH = /mnt/disk4/haitao/bysj_seu/ref_genome/ucsc_hg19            
BOWTIE2_GLOBAL_OPTIONS = --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder
BOWTIE2_LOCAL_OPTIONS =  --very-sensitive -L 20 --score-min L,-0.6,-0.2 --end-to-end --reorder

#######################################################################
#######################################################################

REFERENCE_GENOME = hg19                           
GENOME_SIZE =/mnt/disk4/haitao/bysj_seu/ref_genome/ucsc_hg19/hg19.sizes                 

#######################################################################
#######################################################################

ALLELE_SPECIFIC_SNP = 

#######################################################################
#######################################################################

CAPTURE_TARGET =
REPORT_CAPTURE_REPORTER = 1

#######################################################################
#######################################################################

GENOME_FRAGMENT = /mnt/disk4/haitao/bysj_seu/ref_genome/hg19_arimakit.bed        
LIGATION_SITE = GATCGATC,GANTGATC,GANTANTC,GATCANTC              
MAX_FRAG_SIZE =                   
MIN_INSERT_SIZE =                      
MAX_INSERT_SIZE =                   

#######################################################################
#######################################################################

MIN_CIS_DIST =                     
GET_ALL_INTERACTION_CLASSES = 1     
GET_PROCESS_SAM = 0
RM_SINGLETON = 1
RM_MULTI = 1
RM_DUP = 1

#######################################################################
#######################################################################

BIN_SIZE = 10000 20000 40000 100000 500000         
MATRIX_FORMAT = complete           
#######################################################################
#######################################################################
MAX_ITER = 100                            
FILTER_LOW_COUNT_PERC = 0.02
FILTER_HIGH_COUNT_PERC = 0
EPS = 0.1

I don't know what went wrong. I don't think I made any mistakes in PAIR EXTENSION

**Comment by usernicai** [comment]
HiC-Pro version 3.1.0

**Comment by candice826** [comment]
Hi,I got a error "Exit: Read pairs extensions not defined.Exit“ when i start running hic-pro(HiC-Pro version 3.1.0),
the organization of my data :
```
data
└── N54
    ├── N54_R1.fastq.gz
    └── N54_R2.fastq.gz

```

command line:
`/path/to/HiC-Pro-3.1.0/bin/HiC-Pro -i data -o test -c /path/to/HiC-Pro-3.1.0/config-hicpro.txt`

my config file:
Please change the variable settings below if necessary
```
.....
#########################################################################

PAIR1_EXT =_R1
PAIR2_EXT =_R2

#######################################################################

Alignment options
#######################################################################

MIN_MAPQ = 10

......
```

Finally,
I can't find what the problem is, could you please help me solve it,i'll really appreciate .best wishes！

**Comment by nservant** [comment]
Hi, 
The parsing of the config file is very stringent. Could you try adding a space between the "=" and "_R1"
The same for R2 ...
N

**Comment by candice826** [comment]
here is all I have in my config file： ``` # Please change the variable settings below if necessary ######################################################################### ## Paths and Settings  - Do not edit ! ######################################################################### TMP_DIR = tmp LOGS_DIR = logs BOWTIE2_OUTPUT_DIR = bowtie_results MAPC_OUTPUT = hic_results RAW_DIR = rawdata ####################################################################### ## SYSTEM AND SCHEDULER - Start Editing Here !! ####################################################################### N_CPU = 2 SORT_RAM = 1000M LOGFILE = hicpro.log JOB_NAME = JOB_MEM = JOB_WALLTIME = JOB_QUEUE = JOB_MAIL = ######################################################################### ## Data ######################################################################### PAIR1_EXT = _R1 PAIR1_EXT = _R2 ####################################################################### ## Alignment options ####################################################################### MIN_MAPQ = 10 BOWTIE2_IDX_PATH = /path/to/ref BOWTIE2_GLOBAL_OPTIONS = --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder BOWTIE2_LOCAL_OPTIONS =  --very-sensitive -L 20 --score-min L,-0.6,-0.2 --end-to-end --reorder ####################################################################### ## Annotation files ####################################################################### REFERENCE_GENOME = ref GENOME_SIZE = /path/to/ref/ref.size ####################################################################### ## Allele specific analysis ####################################################################### ALLELE_SPECIFIC_SNP = ####################################################################### ## Capture Hi-C analysis ####################################################################### CAPTURE_TARGET = REPORT_CAPTURE_REPORTER = 1 ####################################################################### ## Digestion Hi-C ####################################################################### GENOME_FRAGMENT = /path/to/ref/ref.dpnII.txt LIGATION_SITE = GATCGATC MIN_FRAG_SIZE = MAX_FRAG_SIZE = MIN_INSERT_SIZE = MAX_INSERT_SIZE = ####################################################################### ## Hi-C processing ####################################################################### MIN_CIS_DIST = GET_ALL_INTERACTION_CLASSES = 1 GET_PROCESS_SAM = 0 RM_SINGLETON = 1 RM_MULTI = 1 RM_DUP = 1 ####################################################################### ## Contact Maps ####################################################################### BIN_SIZE = 20000 40000 150000 500000 1000000 MATRIX_FORMAT = upper ####################################################################### ## Normalization ####################################################################### MAX_ITER = 100 FILTER_LOW_COUNT_PERC = 0.02 FILTER_HIGH_COUNT_PERC = 0 EPS = 0.1 ``` &nbsp;


梅亚杰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月10日(星期三) 下午5:20
收件人: "nservant/HiC-Pro";
抄送: "Comment";
主题: Re: [nservant/HiC-Pro] Exit: Read pairs extensions not defined (Issue #605)





 
Hi,
 The parsing of the config file is very stringent. Could you try adding a space between the "=" and "_R1"
 The same for R2 ...
 N
 
&mdash;
