### ISSUE TITLE
test dataset link not working HiCPro_testdata.tar.gz

### ISSUE THREAD

**Issue by dksenthil** [nservant/HiC-Pro#607]
` wget https://zerkalo.curie.fr/partage/HiC-Pro/HiCPro_testdata.tar.gz && tar -zxvf HiCPro_testdata.tar.gz`

Resolving zerkalo.curie.fr (zerkalo.curie.fr)... 193.49.205.28
Connecting to zerkalo.curie.fr (zerkalo.curie.fr)|193.49.205.28|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-12-11 11:38:23 ERROR 404: Not Found.

**Comment by nservant** [comment]
Hi
the test dataset is now on Zenodo
https://zenodo.org/records/10401822

**Comment by rikrdo89** [comment]
the correct command in the docs should be updated to:
`wget https://zenodo.org/records/10401822/files/HiCPro_testdata.tar.gz && tar -zxvf HiCPro_testdata.tar.gz`

**Comment by suzebr4** [comment]
Hi, professor

I need the standard **output of test_data** to verify whether my run is correct. Could you please provide a valid download link? The file link in the _HiC-Pro Quick Start Guide_ is no longer accessible.

looking forward to your reply!!! And thank you for your selfless dedication!
