### ISSUE TITLE
Bowtie global error

### ISSUE THREAD

**Issue by CarolWuuu** [nservant/HiC-Pro#608]
Hi I am getting error in step 1 from samtools and bowtie2. I installed HiC-Pro using environement.yml provided. Is there incompatibility with bowtie2 version? 
<img width="590" alt="Screenshot 2023-12-22 at 3 07 42 AM" src="https://github.com/nservant/HiC-Pro/assets/107639371/efd81bcc-2c2d-4a81-ba7b-b5fc23f65b53">
<img width="915" alt="Screenshot 2023-12-22 at 3 06 45 AM" src="https://github.com/nservant/HiC-Pro/assets/107639371/69e857a3-d0d5-4a50-abbd-330cd7a1c7d2">

**Comment by nservant** [comment]
You have the explanation in your post ;)
`SEQ and QUAL are of different lenght`

Check your fastq files ... there is something wrong there !
