### ISSUE TITLE
Can I use hic-pro for Hi-C 3.0 ?

### ISSUE THREAD

**Issue by hanshanmengqi** [nservant/HiC-Pro#609]
Hi,

Thanks for developing such a helpful tool!
But I saw a paper (https://www.frontiersin.org/articles/10.3389/fpls.2023.1223591/full) that said hic-pro is unsuitable for Hi-C 3.0.
Because Hi-C 3.0 involves fragmenting with two enzymes and hence a diversity of ligation events.

So, what do you think?

Best,
Han

**Comment by nservant** [comment]
Hi,
The `digest_genome.py` file can support multiple restriction enzymes, so as soon as you do have the restriction fragment digested with all these enzmes, I do not see why HiC-Pro could not work ...
For instance, HiC-Pro was successully used with the Arima kit which is based on multiple restrictions ...
Best
Nicolas
