### ISSUE TITLE
HiC-Pro --help

### ISSUE THREAD

**Issue by ryao-mdanderson** [nservant/HiC-Pro#611]
Dear author,

I installed HiC-Pro 3.1.0 as a conda environment on our institution HPC cluster, it does not report an error. 

 However, I git clone the source code and use the following command seeing a message:
$ ./bin/HiC-Pro --help
usage : HiC-Pro -i INPUT -o OUTPUT -c CONFIG [-s ANALYSIS_STEP] [-p] [-h] [-v]
Use option -h|--help for more information
Error - Installation - config system not detected. Please (re) install HiC-Pro !

 HiC-Pro script looks for file config-system.txt, but this file seems not to exist. Did I overlook anything?

Thank you for your help.

**Comment by nservant** [comment]
Hi,
You need to activate your conda env, and then install HiC-Pro from the git clone.
```
## Edit config-install.txt file if necessary
make configure
make install
```
You can not use it as is.

**Comment by ryao-mdanderson** [comment]
Dear Nicolas, @nservant 

Thank you for your reply. I did the make steps and it works.
