### ISSUE TITLE
merge allValidPairs and convert to .hic

### ISSUE THREAD

**Issue by mw18f** [nservant/HiC-Pro#614]
Hi nservant,

Can I use cat to merge biological replicates of allValidPairs and then convert to .hic by hicpro2juicebox.sh ? 
Thanks

**Comment by nservant** [comment]
yes of course.

**Comment by shRDJr** [comment]
Hi nservant,
I want to ask, do biological replicates always merge in this way?
That is, build the *.allValidPairs file and then use cat?

**Comment by nservant** [comment]
you can also sum the contact maps

**Comment by shRDJr** [comment]
> you can also sum the contact maps

Thank you!
