### ISSUE TITLE
hicpro2juicebox.sh: line 152: java: command not found

### ISSUE THREAD

**Issue by qqyanyang** [nservant/HiC-Pro#617]
Hi, I have a issue about the hicpro2juicebox.sh. When I use the commond ''bash hicpro2juicebox.sh -i /mypath/GSM.allValidPairs -j /juicertools_path/juicer_tools.1.9.9_jcuda.0.8.jar -g hg19 -o /myoutpath, there is a issue that:  
HiC-Pro format > 2.7.5 detected ...
Generating Juicebox input files ...
Running Juicebox ...
hicpro2juicebox.sh: line 152: java: command not found
done !

How could I solve this issue?Thanks~

**Comment by nservant** [comment]
Just add your JAVA in your PATH
