### ISSUE TITLE
GENOME_FRAGMENT not Found 

### ISSUE THREAD

**Issue by dorcus** [nservant/HiC-Pro#63]
Dear Nicolas,

Thank you for your hard work in creating this useful pipeline and taking the time to read this. I have a quick question:
The pipeline is automatically going into DNase Mode (according to log files) despite a restriction.BED being specified in the config file (I have tried both adding the file to the annotation folder and specifying a full path from the locale folder). 

Thanks in advanced!

**Comment by nservant** [comment]
Fixed in 2.8.0
