### ISSUE TITLE
Polyploidy 

### ISSUE THREAD

**Issue by rsandean** [nservant/HiC-Pro#630]
Hi there, I am working on a few hexaploid genome assemblies and wanted to try this tool for providing the inputs for EndHiC. I was wondering if this would be able to handle high ploidy levels? I have now ran HiC-pro over night and it is still making the bam files in bwt2_global and they're around 4G each currently, is it normal to take this long in just making these files or should I stop it? 

Thank you!

**Comment by nservant** [comment]
Hi,
I do not see any reason why the running time would be correlated with the ploidy of the data. Just let it run ;)
