### ISSUE TITLE
Restriction fragments difference generated from HiC-Pro (digest_genome.py) and Juicer  for Arima

### ISSUE THREAD

**Issue by vikaskumar1019** [nservant/HiC-Pro#631]
Hi,

Command used for Hic-Pro: ./digest_genome.py -r ^GATC,G^ANTC  -o mm10_Arima.bed mm10.fa

I find that the restriction file generated from the output of Hic-Pro and Juicer have discrepancies

Hi-C pro result:
chr1    0       3000185 HIC_chr1_1      0       +
chr1    3000185 3000190 HIC_chr1_2      0       + (Difference)
chr1    3000190 3000449 HIC_chr1_3      0       +
chr1    3000449 3000812 HIC_chr1_4      0       + (Difference)
chr1    3000812 3001047 HIC_chr1_5      0       + (Difference)
chr1    3001047 3001118 HIC_chr1_6      0       + (Difference)
chr1    3001118 3001460 HIC_chr1_7      0       +
chr1    3001460 3001532 HIC_chr1_8      0       + 
chr1    3001532 3001652 HIC_chr1_9      0       +
chr1    3001652 3001794 HIC_chr1_10     0       + (Difference)
chr1    3001794 3003153 HIC_chr1_11     0       + 
chr1    3003153 3003208 HIC_chr1_12     0       + (Difference)
chr1    3003208 3003262 HIC_chr1_13     0       + (Difference)

Juicer result:
chr1 3000185 3000191 3000449 3000813 3001048 3001119 3001460 3001532 3001652 3001795 3003153 3003209 3003263 3003350

Can you please suggest what can be the reason for this? 

Best Regards,
Vikas

**Comment by nservant** [comment]
Hi Vikas,
I do not see any major differences ?
I have no experience with Juicer, but it seems to report only the cutting sites, while HiC-Pro provides a BED file.
Of note the BED files are 0-based (meaning that the 1rst base is 0 not 1, which may explain the minor differences you have)
N
