### ISSUE TITLE
Error in HiC-Pro 3.1.0 step1

### ISSUE THREAD

**Issue by AnushkaChaturvedi** [nservant/HiC-Pro#637]
#Error in step1 of HiC-Pro

Run HiC-Pro 3.1.0
--------------------------------------------
Tuesday 16 July 2024 10:06:51 AM IST
Bowtie2 alignment step1 ...
Logs: logs/1/mapping_step1.log
[main_samview] fail to read the header from "-".
Exit: Error in reads alignment - Exit
make: *** [/home/angad/Vikash/HiC-Pro_3.1.0/bin/../scripts//Makefile:88: bowtie_global] Error 1

real	33m40.708s
user	143m50.507s
sys	2m14.070s

Command : time /home/angad/Vikash/HiC-Pro_3.1.0/bin/HiC-Pro -c /home/angad/Vikash/tools/Hic-Pro/Plant_test/config-hicpro.txt -i /home/angad/Vikash/tools/Hic-Pro/Plant_test/raw_data/qc_data/Sample_1/ -o hicproarabidop_test

Message in logs file
##HiC-Pro mapping
stat: Bad file descriptor
Warning: Could not open read file "rawdata/1/qc_SRR11149054_2.fastq" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1

**Comment by nservant** [comment]
Usually, it comes from errors in the input file organization, or in the PAIR1_EXT / PAIR2_EXT

**Comment by AnushkaChaturvedi** [comment]
I checked the input file organization and the PAIR1_EXT / PAIR2__EXT both these things look fine. 
File organization-
Rawdata
   - Sample_1
        - 1
            -SRR_1.fastq
        - 2
            -SRR_2.fastq

**Comment by AnushkaChaturvedi** [comment]
You were right the error was in input file organization. Thankyou so much.
