### ISSUE TITLE
 I would like to understand if the software supports specifying multiple values ​​for LIGATION_SITE in a single config file

### ISSUE THREAD

**Issue by tangyueting** [nservant/HiC-Pro#639]
Hi, I am Ting,I used two enzymes and got four ligation sites, I would like to understand if the software supports specifying multiple values ​​for LIGATION_SITE in a single config file.Looking forward to your reply, thanks.

**Comment by nservant** [comment]
Hi
Yes, just add your ligation motifs comma separated
best
