### ISSUE TITLE
Valid_interaction_pairs is 0

### ISSUE THREAD

**Issue by Hanjiangna** [nservant/HiC-Pro#647]
Hi nservant：
I'm trying to mount chromosomes using Hi-C data for subsequent visualization, but I'm encountering issues and would like your help.
error:
Logs: logs/sample1/make_Rplots.log
make: *** [/public/home/kangzhensheng/Software/HiC-Pro_3.1.0/bin/../scripts//Makefile:181: hic_qc] Error 1

my file : sample.bwt2pairs.validPairs is empty
this is sample1.mRSstat
![image](https://github.com/user-attachments/assets/c928fb78-2c4c-4f7b-beef-8785da32c8f3)
Best wishes!

**Comment by nservant** [comment]
same as #648
