### ISSUE TITLE
Error in Bowtie alignment

### ISSUE THREAD

**Issue by Rhine86** [nservant/HiC-Pro#68]
Hi,

When running HiC-Pro with the test data, I encounter an error like this:

Run HiC-Pro 2.7.9
--------------------------------------------
Bowtie2 alignment step1 ...
/home/yzhang/Software/HiC-Pro_2.7.9/scripts/bowtie_wrap.sh -c /home/yzhang/projects/HiC/config_test_latest_edit.txt -u >> hicpro.log
--------------------------------------------
Bowtie2 alignment step2 ...
/home/yzhang/Software/HiC-Pro_2.7.9/scripts/bowtie_wrap.sh -c /home/yzhang/projects/HiC/config_test_latest_edit.txt -l >> hicpro.log
Exit: Error in Bowtie alignment
make: *** [bowtie_local] Error 1

real	0m51.381s
user	2m24.650s
sys	0m39.616s

The only changes I have done were:
BOWTIE2_IDX_PATH = /pub/iGenomes/Homo_sapiens/UCSC/hg19/Sequence/Bowtie2Index
REFERENCE_GENOME = genome

Any help will be highly appreciated, Thank you.

Yan

**Comment by nservant** [comment]
Hi,
In the logs folder, you should find the bowtie log file. Could you please have a look at it.
Thanks

**Comment by Rhine86** [comment]
Hi nservant,
Thank you very much.
readsTrimming.log shows that There is not /home/yzhang/Software/HiC-Pro_2.7.9/scripts/cutsite_trimming, It seems that I have not install HiC-Pro successfully.

**Comment by nservant** [comment]
This is a C++ code. I think that there was something wrong at the compilation during the installation !
Nicolas

**Comment by Rhine86** [comment]
It works now. Thank you.
Yan

**Comment by rogerzzw** [comment]
Hi, @Rhine86 

I came across the same problem as you did. How did you make it work? 

Thank you

**Comment by Rhine86** [comment]
@rogerzzw 
Hi,
I reinstall HiC-Pro, make sure it is installed correctly, and then it works. You can see comments above for details.
