### ISSUE TITLE
bin information for interaction matrix

### ISSUE THREAD

**Issue by skyingg** [nservant/HiC-Pro#71]
I go through HiCPro, and for test data I get the interaction map in hic_results/matrix/iced/500000/dixon_2M_2_500000_iced.matrix. The first few lines are like this
2	2	22.436044
2	2523	3.925787
3	84	25.687973
4	4	7.730917
I did not get error when I run hicpro. Does the result look right?

I would like to use result from HiCPro in juicer or fit-hi-c to call significant interactions. How can I convert the resulted interaction matrix to the format juicer required as:
Short with score format
str1 chr1 pos1 frag1 str2 chr2 pos2 frag2 score

or to the format fit-hi-c required as:
"chr1     fragmentMid1    chr2    fragmentMid2    contactCount"

Where can I get the information (cur, pos) file for the bin in the interaction matrix?

**Comment by skyingg** [comment]
Could you also post example of your result for the test data? By that freshman to hicpro could know whether what we get is right or not.

**Comment by rschwess** [comment]
The bin --> chr coord information are in the .bed files under ../matrix/yourid/raw/binsize/*abs.bed and *ord.bed for the x and y coordinate bins respectively. They are in format (chr start end binID) From there its just a matter of matching with any sort of script. Output format of the matrix looks alright from the head you posted.

**Comment by nservant** [comment]
HiC-Pro results are available hereHiC-Pro results are available here
https://zerkalo.curie.fr/partage/HiC-Pro/HiCPro_results/
We do not have exactly the same results ... I do not know why !?
Regarding the format conversion, Ron already answered your question. I can just add that you have an utility in bin/utils/hicpro2juicebox.sh to create Juicebox input (it should work with Juicer too ?)
And last point, if you write a script forfit-hic convertion, I will be happy to add it in the utils ;)
N

**Comment by nservant** [comment]
Hi,
Just to tell you that I commit a new utility hicpro2fithic.py written by the FitHiC developpers.
best
Nicolas
