### ISSUE TITLE
Filtering pre-ICE error 

### ISSUE THREAD

**Issue by ilyco** [nservant/HiC-Pro#72]
Hi,

I am getting the following error when I attempt to perform ICE normalisation either as part of pipeline or as a separate step run -s ice_norm. 

```
Traceback (most recent call last):
  File "HiCPro/HiC-Pro_2.8.1_devel/scripts/ice", line 98, in <module>
    copy=False, sparsity=False, verbose=args.verbose)
  File "/Users/olan01/.local/lib/python2.7/site-packages/iced/filter.py", line 63, in filter_low_counts
    verbose=verbose)
  File "/Users/olan01/.local/lib/python2.7/site-packages/iced/filter.py", line 158, in _filter_low_sum
    x = X_sum[len(X_sum[X_sum > 0]) * percentage + num_noninteracting_loci]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
make: *** [ice_norm] Error 1
```

I tried different data sets and HiC-Pro version 2.8.0_devel, 2.8.0 and 2.8.1_devel, iced package version 0.4.0, default parameters from the config file (100 iteration, 0.2 low count filter and 0.1 eps)

Please let me know if you can advise me on this.

Thanks

**Comment by ilyco** [comment]
FIXED by amending the filter.py file in iced. 

In your commits, before you make synchro iced, a line in filter_low_sum is: 
` x = X_sum[int(len(X_sum[X_sum > 0]) * percentage) + num_noninteracting_loci]`
but in your HiC-Pro release it is: 
` x = X_sum[len(X_sum[X_sum > 0]) * percentage + num_noninteracting_loci]`

**Comment by nservant** [comment]
Tank you very much. I'll fix it
N
