### ISSUE TITLE
problem for hardware requirement

### ISSUE THREAD

**Issue by skyingg** [nservant/HiC-Pro#73]
Hi,

I install HiCPro and run successfully with test data. However, when I run it for a data with around 70M reads (about 6G for each end of the pair), I get errors. If I split the data and test a chunk of the data, it works fine. But when I try the whole data, there is always errors. My PC is 32G memory and 1T Disk. 

For the first time, I split the data to 10M chunk, and it returns error at  'Combine both alignment' step. Then I split the data to 2M chunk, 'Combine both alignment' step is fine. But now it returns error at 'Merge multiple files from the same sample' step like following. 

Is it because of not enough space? But there is more than 700G left on the disk. 

Run HiC-Pro 2.8.1_devel
--------------------------------------------
Sat Feb 11 11:53:21 CST 2017
Bowtie2 alignment step1 ...
/Users/lab2116/Desktop/analysis/HiC-Pro_2.8.1_devel/scripts/bowtie_wrap.sh -c /Users/lab2116/desktop/analysis/HiC-Pro_2.8.1_devel/data/S6/config_test_latest.txt -u >> hicpro.log
--------------------------------------------
Sat Feb 11 15:51:01 CST 2017
Bowtie2 alignment step2 ...
/Users/lab2116/Desktop/analysis/HiC-Pro_2.8.1_devel/scripts/bowtie_wrap.sh -c /Users/lab2116/desktop/analysis/HiC-Pro_2.8.1_devel/data/S6/config_test_latest.txt -l >> hicpro.log
--------------------------------------------
Sat Feb 11 16:23:07 CST 2017
Combine both alignment ...
/Users/lab2116/Desktop/analysis/HiC-Pro_2.8.1_devel/scripts/bowtie_combine.sh -c /Users/lab2116/desktop/analysis/HiC-Pro_2.8.1_devel/data/S6/config_test_latest.txt >> hicpro.log
--------------------------------------------
Sat Feb 11 16:40:04 CST 2017
Bowtie2 mapping statistics for R1 and R2 tags ...
/Users/lab2116/Desktop/analysis/HiC-Pro_2.8.1_devel/scripts/mapping_stat.sh -c /Users/lab2116/desktop/analysis/HiC-Pro_2.8.1_devel/data/S6/config_test_latest.txt >> hicpro.log
--------------------------------------------
Sat Feb 11 16:43:29 CST 2017
Pairing of R1 and R2 tags ...
/Users/lab2116/Desktop/analysis/HiC-Pro_2.8.1_devel/scripts/bowtie_pairing.sh -c /Users/lab2116/desktop/analysis/HiC-Pro_2.8.1_devel/data/S6/config_test_latest.txt >> hicpro.log
--------------------------------------------
Sat Feb 11 17:17:00 CST 2017
Assign alignments to restriction fragments ...
/Users/lab2116/Desktop/analysis/HiC-Pro_2.8.1_devel/scripts/mapped_2hic_fragments.sh -c /Users/lab2116/desktop/analysis/HiC-Pro_2.8.1_devel/data/S6/config_test_latest.txt >> hicpro.log
--------------------------------------------
Sat Feb 11 18:51:24 CST 2017
Merge multiple files from the same sample ...
/Users/lab2116/Desktop/analysis/HiC-Pro_2.8.1_devel/scripts/merge_valid_interactions.sh -c /Users/lab2116/desktop/analysis/HiC-Pro_2.8.1_devel/data/S6/config_test_latest.txt >> hicpro.log
gsort: cannot create temporary file in 'mp': No such file or directory
make: *** [merge_valid_interactions] Error 2
lab2116s-iMac:HiC-Pro_2.8.1_devel lab2116$

**Comment by nservant** [comment]
Hi
The error comes from the sort function ...
 gsort: cannot create temporary file in 'mp': No such file or directory
Could you check what you get in the configuration file for TMP_DIR ?
By default, this variable is fixed to 'tmp', and not 'mp' as in the error message ...
N

**Comment by skyingg** [comment]
I did not edit that part of configuration.
TMP_DIR = tmp
LOGS_DIR = logs
BOWTIE2_OUTPUT_DIR = bowtie_results
MAPC_OUTPUT = hic_results
RAW_DIR = rawdata

**Comment by nservant** [comment]
If I understand correctly, it runs until you get one .validPairs file per fastq file ?
But it seems that it crashes when it tries to combines all these files into one big file with all validPairs.
In practice, it should uses the following command ;

sort -k2,2V -k3,3n -k5,5V -k6,6n -T ${TMP_DIR} -m ${IN_DIR}/${RES_FILE_NAME}/*.validPairs | awk -F"\t" 'BEGIN{c1=0;c2=0;s1=0;s2=0}(c1!=$2 || c2!=$5 || s1!=$3 || s2!=$6){print;c1=$2;c2=$5;s1=$3;s2=$6}' > ${DATA_DIR}/${RES_FILE
_NAME}/${RES_FILE_NAME}_allValidPairs

Could you try to directly run it ?
If you go in the hic_results/data/ fodler, then try ;
sort -k2,2V -k3,3n -k5,5V -k6,6n -T ../../tmp  -m *.validPairs | awk -F"\t" 'BEGIN{c1=0;c2=0;s1=0;s2=0}(c1!=$2 || c2!=$5 || s1!=$3 || s2!=$6){print;c1=$2;c2=$5;s1=$3;s2=$6}' > test_allValidPairs

**Comment by skyingg** [comment]
I will try this soon. 
By the way, is there any link that I can download 2.7.9?

**Comment by nservant** [comment]
forget about this version. It was a devel version

**Comment by skyingg** [comment]
I run 
gsort -k2,2V -k3,3n -k5,5V -k6,6n -T ../../../tmp -m *.validPairs | awk -F"\t" 'BEGIN{c1=0;c2=0;s1=0;s2=0}(c1!=$2 || c2!=$5 || s1!=$3 || s2!=$6){print;c1=$2;c2=$5;s1=$3;s2=$6}' > test_allValidPairs
../../../tmp instead of ../../tmp
and get the test_allValidPairs in hic_results/data/ folder.
Now what should I do?

**Comment by skyingg** [comment]
So is the problem caused by hardware limitation? Is there anyway to clear something to release space?

**Comment by nservant** [comment]
Yes it seems so ...
I think that you will need to run HiC-Pro in stepwise mode.
Look at the -s options. It allows you to run each step of the analysis, one by one.
In these case, the -i options should point on the output of the previous step.
You have example here
http://nservant.github.io/HiC-Pro/USER_CASES.html
You can clean the mapping ... you should have three folders, bwt2_global, bwt2_local, bwt2. The bwt2_global and local can be removed. And in the bwt2 folder, only the bwt2pairs.bam files matter !

And another question, do you have a "sort" command on your environment and not "gsort" ? because HiC-Pro will use the "sort" ...

**Comment by skyingg** [comment]
Thanks very much. I will try it step wise.
I use ios instead of linux. The sort in ios does not support '2V'.

**Comment by skyingg** [comment]
Is 'combine both alignment' part of step 'mapping'? If that is the way, stepwise would not work either. Or is it in the second step 'proc_hic'?
If I start from the combined test_allValidPairs, which step I should continue to?

I use ios instead of linux. The sort in ios does not support '2

**Comment by nservant** [comment]
Hi,
Do you fix your issue ?
I have another user with the same error  
gsort: cannot create temporary file in 'mp': No such file or directory
Would remind me what was the cause of this error ? what is a sort issue ?
Thank you

**Comment by skyingg** [comment]
It is because of the tmp dir.



在 2017年3月10日，下午6:17，Nicolas Servant <notifications@github.com<mailto:notifications@github.com>> 写道：


Hi,
Do you fix your issue ?
I have another user with the same error
gsort: cannot create temporary file in 'mp': No such file or directory
Would remind me what was the cause of this error ? what is a sort issue ?
Thank you

**Comment by skyingg** [comment]
By the way, I never get hicpro plot working on my computer. R is fine, and all the required pachages have been installed. Is it because of the system or some other reason?

**Comment by nservant** [comment]
Do you have some error message in Rout files (in logs) ?
Thanks
