### ISSUE TITLE
Error in Run ICE Normalization

### ISSUE THREAD

**Issue by liencau** [nservant/HiC-Pro#74]
Hi
I am getting this error at the ICE normalization stage. Do you have any idea about this?

Thanks
Enli

Run ICE Normalization ...
/NAS1/lien/software/HiC-Pro_2.7.8/scripts/ice_norm.sh -c /NAS/software/HiC-Pro_2.7.1b/HiCPro_testdata/config_test_latest.txt >> hicpro.log 
Traceback (most recent call last):
  File "/NAS1/lien/software/HiC-Pro_2.7.8/scripts/ice", line 6, in <module>
    from scipy import sparse
  File "/NAS/wangshuaihu/mysoft/python2.7/lib/python2.7/site-packages/scipy/sparse/__init__.py", line 223, in <module>
    from .lil import *
  File "/NAS/wangshuaihu/mysoft/python2.7/lib/python2.7/site-packages/scipy/sparse/lil.py", line 16, in <module>
    from . import _csparsetools
ImportError: /NAS/wangshuaihu/mysoft/python2.7/lib/python2.7/site-packages/scipy/sparse/_csparsetools.so: undefined symbol: PyUnicodeUCS2_FromStringAndSize
make: *** [ice_norm] Error 1

I use HiC-Pro_2.7.8;
the version of python is 2.7.11;
The parameters I am using are
#######################################################################
MAX_ITER = 100
FILTER_LOW_COUNT_PERC = 0.02
FILTER_HIGH_COUNT_PERC = 0
EPS = 0.1

**Comment by nservant** [comment]
I think that there was something wrong in the python package.
Could you try to install iced manually ?
Thank you
