### ISSUE TITLE
Different iced matrix (HiC-Pro_2.7.2b vs HiC-Pro 2.8.0)

### ISSUE THREAD

**Issue by suhnrhie** [nservant/HiC-Pro#75]
Hi Nicolas,

I have run HiC-Pro 2.7.2b previously and got iced.matrices, now I am using HiC-Pro 2.8.0 to get iced matrices. 
The output matrices with same data and same settings give different results by version.
Is this something you expected?
For instance, old version outputs all genomic interactions 
[OLD]$ head rawdata_1000000_iced.matrix
1	1	70926.632090
1	2	9339.916707
1	3	820.848897
1	4	549.191153
1	5	269.700949
1	6	233.051106
1	7	431.452350
1	8	278.575667
1	9	360.915734
1	10	432.550035

However, new version outputs only signif interactions? I see nan for the 1 in the matrix biases too.

[new]$ head rawdata_1000000_iced.matrix
2       2       116018.646786
2       3       6059.055013
2       4       1777.083330
2       5       428.663392
2       6       363.574940
2       7       987.327166
2       8       513.471677
2       9       1127.886527
2       10      1268.523530
2       11      1200.891428
[new]$ head rawdata_1000000_iced.matrix.biases
nan
7.730027541852662054e-01
6.960359368214282805e-01
7.221423882210227241e-01
7.303279622036291663e-01
7.970270050451853105e-01
1.033796066333695363e+00
9.624226361099769145e-01
1.144679989989582980e+00
1.063664683643716247e+00

**Comment by nservant** [comment]
Hi,
Yes we expect changes between these two versions. In the 2.8.0, we updated the iced normalization package. In practice, there is almost no difference between the new and previous versions. 
However, we updated the way we filter out low row/cols counts before running the normalization. The new version gives much better results in term of convergence for very high resolution data.
If you have nan for first row it means that this row has been filtered out.
However, when I looked at your data it seems that there is a +1 differences in the i/j indexes.
Could I ask you to look at the maps, and to check if you see a +1 shift in the new ones ?
Thank you very much
Nicolas

**Comment by suhnrhie** [comment]
Hi Nicolas, 

Sorry for the late reply. I visualized in maps and they don't seem to have a +1 shift in the new ones. 
However, version 2.8.0 still gave the samtools sort error (https://github.com/nservant/HiC-Pro/issues/23). I used the HiC-Pro 2.7.2b to generate raw matrix and just run the iced normalization part using version 2.8.0.

Thanks,

**Comment by nservant** [comment]
Great thanks.
I'm surpise that you still have the issue with samtools.
Do you know at which step it crashed ?

**Comment by suhnrhie** [comment]
HiC-Pro_2.8.0/scripts/bowtie_combine.sh -c /HiC-Pro-2.8.0.hg19.cut/HiC.run/config-hicpro.hg19.cut.txt >> hicpro.log
sort: invalid option -- 'T'
sort: invalid option -- 'T'
[bam_sort_core] merging from 466 files...
[bam_sort_core] merging from 438 files...
mv: cannot stat 'bowtie_results/bwt2/rawdata/HiC_NoIndex_R2_hg19.bwt2merged.sorted.bam': No such file or directory
mv: cannot stat 'bowtie_results/bwt2/rawdata/HiC_NoIndex_R1_hg19.bwt2merged.sorted.bam': No such file or directory

I think the error is from the mergeSAM step 

python HiC-Pro_2.8.0/scripts/mergeSAM.py -q 0 -t -v -f bowtie_results/bwt2/rawdata/HiC_NoIndex_R1_hg19.bwt2merged.bam -r bowtie_results/bwt2/rawdata/HiC_NoIndex_R2_hg19.bwt2merged.bam -o bowtie_results/bwt2/rawdata/HiC_NoIndex_hg19.bwt2pairs.bam > logs/rawdata/mergeSAM.log

Instead of putting aligned reads to bwt2pairs.bam, it seemed to be outputed to hicpro.log
1.5K Feb 15 22:35 HiC_NoIndex_hg19.bwt2pairs.bam
176G Feb 24 23:41 hicpro.log
