### ISSUE TITLE
group order in plots

### ISSUE THREAD

**Issue by JoshTycko** [nservant/HiC-Pro#77]
The groups are not ordered in the bar graphs such that the color and text match up. I'm attaching a few examples. 
I am using ggplot2 version 2.2.1
I just installed HiCPro today.
My collaborator ran HiCPro on the same data on a different computer with an older installation and did not see the same problem.

Thanks for this great tool and any help you can offer!

[plotHiCContactRanges_JT_test.pdf](https://github.com/nservant/HiC-Pro/files/823438/plotHiCContactRanges_JT_test.pdf)
[plotMapping_JT_test.pdf](https://github.com/nservant/HiC-Pro/files/823439/plotMapping_JT_test.pdf)

**Comment by nservant** [comment]
Hi Josh !
Thanks for you feedbacks. I will try to reproduce this error.
Which R version are you using please ?
Thanks

**Comment by JoshTycko** [comment]
Thanks so much!

R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"

Platform: x86_64-pc-linux-gnu (64-bit)

**Comment by nservant** [comment]
fixed in devel
