### ISSUE TITLE
Error - pysam version 0.10

### ISSUE THREAD

**Issue by mintlover** [nservant/HiC-Pro#78]
I installed the newest version of pysam, but I got this error:
Error - pysam: AttributeError: 'module' object has no attribute 'AlignmentFile'

I have HiC-Pro 2.7.6. What version of pysam is compatible?

Thank you.

**Comment by nservant** [comment]
Hi,
This is strange ...
If you look at the pysam 0.10 manual, the object AlignmentFile is there
http://pysam.readthedocs.io/en/latest/api.html 
And if pysam remove the AlignmentFile object from v0.10, it would mean that there is no backward compatibility ... which looks very weird !

I rather think that HiC-Pro is not loading the good version.
To check, could you run the python which is set in the config_system.txt file.
Then
>> import pysam
>> pysam__version__
>> dir(pysam)

Thank you

**Comment by mintlover** [comment]
Fixed it. I installed pysam 0.10 locally, but the cluster has pysam 0.8.4, which used by HiC-Pro. I didn't realize it before. Thank you.
