### ISSUE TITLE
hicpro2juicebox.sh problem

### ISSUE THREAD

**Issue by labdevgen** [nservant/HiC-Pro#79]
I found that hicpro2juicebox creates wrong heatmaps, and after some test understand that it happens when contig (chromosome) names contain "_".
I'm sure this is due to the line
`awk '{$4=$4!="+"; $7=$7!="+"; split($9, frag1, "_"); split($10, frag2, "_"); } $2<=$5{print $1, $4, $2, $3, frag1[3], $7, $5, $6, frag2[3], $11, $12 }$5<$2{ print $1, $7, $5, $6, frag2[3], $4, $2, $3, frag1[3], $12, $11}' $VALIDPAIRS | sort -k3,3d  -k7,7d -S 90 > ${TEMP}/$$_allValidPairs.pre_juicebox_sorted
`
I suggest to fix it changing the line to
`awk '{$4=$4!="+"; $7=$7!="+"; n1=split($9, frag1, "_"); n2=split($10, frag2, "_"); } $2<=$5{print $1, $4, $2, $3, frag1[n1], $7, $5, $6, frag2[n2], $11, $12 }$5<$2{ print $1, $7, $5, $6, frag2[n2], $4, $2, $3, frag1[n1], $12, $11}' $VALIDPAIRS | sort -k3,3d  -k7,7d -S 90 > ${TEMP}/$$_allValidPairs.pre_juicebox_sorted`

Best regards,
Veniamin Fishman

**Comment by nservant** [comment]
Hi
Thank you very much for your comments.
It's now fixed in the master !
Nicolas
