### ISSUE TITLE
Problem creating the torque script when filename contains several PAIR1_EXT

### ISSUE THREAD

**Issue by NelleV** [nservant/HiC-Pro#8]
To reproduce the bug:
create datafiles of following format:
00_all_1.fastq  00_all_2.fastq  01_all_1.fastq  01_all_2.fastq  02_all_1.fastq  02_all_2.fastq  03_all_1.fastq  03_all_2.fastq  04_all_1.fastq  04_all_2.fastq  05_all_1.fastq  05_all_2.fastq

and set 
PAIR1_EXT = 1
PAIR2_EXT = 2

=> it fails.

**Comment by nservant** [comment]
There is the same issue when the extension is .R1.
It looks like the extension"_" is used during the mapping ....

**Comment by sameet** [comment]
I think, it should be trivial to make all the "Read1" end in `_R1.fastq` or `_R1.fastq.gz` using something as follows:

    ```
    $ for i in *_1_* ; do mv $i $(basename $i .fastq)_R1.fastq; done
    $ for i in *_2_*; do mv $i $(basename $i .fastq)_R2.fastq; done

    ```

That should make the file names for Read1 and Read2 consistent, and this problem should solve.
