### ISSUE TITLE
Error during Ice normalization

### ISSUE THREAD

**Issue by scrosenbe** [nservant/HiC-Pro#84]
Run ICE Normalization ...
/mnt/silencer2/home/srosenbe/software/HiC-Pro_2.8.1_devel/scripts/ice_norm.sh -c /mnt/silencer2/home/srosenbe/hictest_allelespecific/config-hicpro.txt >> hicpro.log 
Traceback (most recent call last):
  File "/mnt/silencer2/home/srosenbe/software/HiC-Pro_2.8.1_devel/scripts/ice", line 77, in <module>
    if min(i.min(), j.min()) == 0:
  File "/usr/lib64/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
make: *** [ice_norm] Error 1

I'm running this analysis on a very truncated data set of 2500 reads, and trying to use the allele specific mapping feature. Any idea why this error is occuring? Thanks.

**Comment by nservant** [comment]
Hi
Could you check that the input raw matrix files are created ? in matrix/raw
Then, two possibilities ; either the iced package is not correctly installed, or your data are too sparse to be normalized (which I think is the case with 2500 reads)
Could you try to run the test dataset available on https://zerkalo.curie.fr/partage/HiC-Pro/
Thanks

**Comment by scrosenbe** [comment]
Thank you very much for your response. So I attempted to rerun the analysis
with a truncated data set of 10 million reads this time. And I think I got
a similar failure when I look at this output file, is 10M reads enough?

*HiCpro_s2_SRC725.e8396405*

Thu May 11 16:24:42 PDT 2017
Run ICE Normalization ...
/home/srosenbe/software/HiC-Pro_2.8.1_devel/scripts/ice_norm.sh -c
/oasis/tscc/scratch/srosenbe/config-hicpro.txt >> hicpro.log
Traceback (most recent call last):
File "/home/srosenbe/software/HiC-Pro_2.8.1_devel/scripts/ice", line 77, in
<module>
if min(i.min(), j.min()) == 0:
File
"/home/srosenbe/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py",
line 29, in _amin
return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no
identity
make: *** [ice_norm] Error 1

It also seems like there may be something wrong with the way i'm setting up
the allele specific analysis or VCF file, as I'm seeing this:

*From hicpro.log*

## Loading VCF file '
/home/srosenbe/scratch/srosenbe/VCF/snps_C57BL6J_CASTEiJ.vcf '...
## Number of loaded SNPs = 0 over 0

*SRC725_10M_mm10_mask.bwt2pairs.RSstat*

## Hi-C processing
Valid_interaction_pairs 4682787
Valid_interaction_pairs_FF 1166459
Valid_interaction_pairs_RR 1162693
Valid_interaction_pairs_RF 1158907
Valid_interaction_pairs_FR 1194728
Dangling_end_pairs 105277
Religation_pairs 53756
Self_Cycle_pairs 3579
Single-end_pairs 0
Dumped_pairs 797419
## ======================================
## Allele specific information
Valid_pairs_from_ref_genome_(1-1) 0
Valid_pairs_from_ref_genome_with_one_unassigned_mate_(0-1/1-0) 0
Valid_pairs_from_alt_genome_(2-2) 0
Valid_pairs_from_alt_genome_with_one_unassigned_mate_(0-2/2-0) 0
Valid_pairs_from_alt_and_ref_genome_(1-2/2-1) 0
Valid_pairs_with_both_unassigned_mated_(0-0) 4682787
Valid_pairs_with_at_least_one_conflicting_mate_(3-) 0

Thank you very much for your support, any insight you might have is
appreciated.

Thanks,
Scott

**Comment by nservant** [comment]
Indeed ! Your VCF file is not interpretated. Therefore, you have no allele specific maps ... your matrix are empty, and the normlaization crashes.
Could you show me what your VCF file looks like please ?
Thanks

**Comment by scrosenbe** [comment]
Thanks for all your help Nicolas. I keep getting this odd error when I run
HiC-Pro and i'm not sure how this makes sense...

Option -i requires an argument.

/var/spool/torque/mom_priv/jobs/8504840.tscc-mgr.local.SC: line 16:
/home/srosenbe/scratch/srosenbe/raw_reads: is a directory

So this is referring to the folder my raw data is in. I'm confused because
I'm pretty sure I want to be giving it a directory, but the error is
unhappy about this. Any insight?


Thanks,

Scott

**Comment by nservant** [comment]
Could you please show me the content of your input folder, and the command line you used.
The -i option must be a folder, which contains again a folder per sample.
For instance ;
* mydata
-- sample1
++++ s1_R1.fastq
++++ s1_R2.fastq
-- sample2
...

Did you follow this organization ?
best

**Comment by scrosenbe** [comment]
Input folder:

-test_data

  --sample1

      --s1_R1

      --s1_R1


/home/srosenbe/software/HiC-Pro/bin/HiC-Pro -c config-hicpro.txt -i
/home/srosenbe/scratch/srosenbe/test_data/sample1
-o output -p


So I believe my organization is exactly as it should be. I have
successfully run the script using this same organization so I'm very
confused as to why this error is popping up... If it matters, I am running
this through a cluster and the files are not .fastq, althoguh when i try
submitting the job using a directory containing .fastq files i get the same
error.


A couple other questions: If I have multiple samples in the test_data
folder, how do I specify to the program that I only want sample 1 run? My
multiple samples are also corresponding to the different set of split_read
truncations I obtained using the pymol script. How would I go about merging
the reads once I've run all the different sets through HiC-Pro?


Thanks,

Scott

**Comment by nservant** [comment]
Hi
You folder organization is good but you need to use -i /home/srosenbe/scratch/srosenbe/test_data/
All samples within "test_data" will be run. If you want to run just one sample, I would recommand to create a new folder, with a symbolic link to the sample you want to analyse.
Regarding the reads splitting, if you put all chuncks in sample1, they will be analyzed in parallel and then merge to remove the duplicates and create the maps.
Hope it helps

**Comment by scrosenbe** [comment]
Adding the slash is still not working for me. It keeps returning the error
that -i needs an argument and I'm giving it a directory, which is
completely confusing because the input should be a directory...

**Comment by nservant** [comment]
In your last post, you told me that you are using 
-i /home/srosenbe/scratch/srosenbe/test_data/sample1
but it should be
/home/srosenbe/scratch/srosenbe/test_data/

**Comment by scrosenbe** [comment]
Okay shoot sorry, I totally messed that up. My data files are not actually
in the sample1 directory but another directory in sample1. So:

/home/srosenbe/scratch/srosenbe/test_data/sample1/raw

so my .fastq files would be in the raw folder and I'm specifying sample1 as
the directory containing that directory.

I really appreciate the support

Scott

**Comment by nservant** [comment]
hum ... ok.
So in the cluster mode, HiCpro first generate a raw data link and an inputXXX file with the list of R1 file to work on.
Then, it finds the file using rawdata/+the content of the input file list.
For instance ;

>>more inputfiles_test.txt 
sample_test/SRR4271982_1.fastq.gz
>>ls rawdata/sample_test/SRR4271982_1.fastq.gz
rawdata/sample_test/SRR4271982_1.fastq.gz

Is it the case ?

**Comment by scrosenbe** [comment]
This has been the case in the past for me. Somehow it is not even making it
far enough to generate the output folder or any of these output files. I
think it is crashing before it can run anything because somehow it's not
reading agreeing with the input argument I am submitting. I've been able to
run the pipeline successfully before in cluster mode so I'm quite confused
as to why this error is showing up.

**Comment by nservant** [comment]
It is difficult without seeing the data by myself.
Are you using a sym link ... which cannot be read ? does it work if you provide the full absolute path ?

**Comment by scrosenbe** [comment]
Hi Nicolas,

I've been trying to run Hi-C pro in sequential mode. I deleted blacklist
regions from my aligned bwt2 .bam files, and I am now trying to run -S
proc_hic like this:

/home/srosenbe/software/HiC-Pro/bin/HiC-Pro -c config-hicpro.txt -i
/oasis/tscc/scratch/srosenbe/hic_blacklist/SRC725 -o 5_blacklist -s
proc_hic -s quality_checks -p

I'm getting this error:


Run HiC-Pro 2.8.1_devel parallel mode

make: *** [make_cluster_script] Error 1


Any advice on what could be generating this? This is for one sample, which
I used split reads on to generate 7 sets of 50 million chunk reads.

Thanks,

Scott
