### ISSUE TITLE
Error in bowtie2 alignment step 1

### ISSUE THREAD

**Issue by awaisc** [nservant/HiC-Pro#87]
Hi, i am trying to run HiCPro 2.8.1, i have a couple friends who have successfully gotten our installation of HiC pro to work and i have gotten it to work on the testdata sample but, when i run the script on my experimental mouse datan i keep getting this error: 
I have checked my files and had a couple friends check and we cannot figure it out! any idea?
```
Bowtie2 alignment step1 ...
/apps/software/HiC-Pro/2.8.1_devel-foss-2016uofa/scripts/bowtie_wrap.sh -c /home/a1649239/fastdir/Test/mm9/config-hicpro.txt -u >> hicpro.log
/apps/software/HiC-Pro/2.8.1_devel-foss-2016uofa/scripts/hic.inc.sh: line 91: logs/brain/bowtie_SRR501772_2_global_/fast/users/a1649239/BowTieIndex/mm9.ucsc.fa.log: No such file or directory
/apps/software/HiC-Pro/2.8.1_devel-foss-2016uofa/scripts/hic.inc.sh: line 91: logs/brain/bowtie_SRR501772_1_global_/fast/users/a1649239/BowTieIndex/mm9.ucsc.fa.log: No such file or directory
/apps/software/HiC-Pro/2.8.1_devel-foss-2016uofa/scripts/hic.inc.sh: line 91: bowtie_results/bwt2_global/brain/SRR501772_2_/fast/users/a1649239/BowTieIndex/mm9.ucsc.fa.bwt2glob.bam: No such file or directory
/apps/software/HiC-Pro/2.8.1_devel-foss-2016uofa/scripts/hic.inc.sh: line 91: bowtie_results/bwt2_global/brain/SRR501772_1_/fast/users/a1649239/BowTieIndex/mm9.ucsc.fa.bwt2glob.bam: No such file or directory

```

I cannot figure out why HiC  pro cannot generate the log files

**Comment by nservant** [comment]
Hi,
There is something wrong in your input files.
What did you put in the REFERENCE_GENOME ?
It looks like you put the fasta file ? actually it requires the prefix of the bowtie indexes ... usually, 'mm9', 'hg19', etc.
N

**Comment by awaisc** [comment]
Thankyou Nservant! That appears to have stopped that issue but now i am getting
`Bowtie2 alignment step1 ...

/apps/software/HiC-Pro/2.8.1_devel-foss-2016uofa/scripts/bowtie_wrap.sh -c /home/a1649239/fastdir/Test/mm9/config-hicpro.txt -u >> hicpro.log
`
so i went to the hicpro.log file
`/apps/software/Bowtie2/2.2.9-GCC-5.3.0-binutils-2.25/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/brain/SRR501772_2_mm9.bwt2glob.unmap.fastq --rg-id BMG --rg SM:SRR501772_2 --phred33-quals -p 16 -x /fast/users/a1649239/BowTieIndex/bowtie/mm9 -U rawdata/brain/SRR501772_2.fastq 2> logs/brain/bowtie_SRR501772_2_global_mm9.log | /apps/software/SAMtools/1.3.1-GCC-5.3.0-binutils-2.25/bin/samtools view -F 4 -bS - > bowtie_results/bwt2_global/brain/SRR501772_2_mm9.bwt2glob.bam
/apps/software/Bowtie2/2.2.9-GCC-5.3.0-binutils-2.25/bin/bowtie2 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --un bowtie_results/bwt2_global/brain/SRR501772_1_mm9.bwt2glob.unmap.fastq --rg-id BMG --rg SM:SRR501772_1 --phred33-quals -p 16 -x /fast/users/a1649239/BowTieIndex/bowtie/mm9 -U rawdata/brain/SRR501772_1.fastq 2> logs/brain/bowtie_SRR501772_1_global_mm9.log | /apps/software/SAMtools/1.3.1-GCC-5.3.0-binutils-2.25/bin/samtools view -F 4 -bS - > bowtie_results/bwt2_global/brain/SRR501772_1_mm9.bwt2glob.bam
`

Sorry, if these are really basic problems! i am new to this

**Comment by nservant** [comment]
Sorry I did not get your point. So it fails again ?
Could you have a look into logs/brain/bowtie_SRR501772_2_global_mm9.log and logs/brain/bowtie_SRR501772_1_global_mm9.log ?
thanks

**Comment by awaisc** [comment]
hi it says,

```
Command: /apps/software/Bowtie2/2.2.9-GCC-5.3.0-binutils-2.25/bin/bowtie2-align-s --wrapper basic-0 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --rg-id BMG --rg SM:SRR501772_1 --phred33-quals -p 16 -x /fast/users/a1649239/BowTieIndex/bowtie/mm9 --passthrough -U rawdata/brain/SRR501772_1.fastq 
(ERR): bowtie2-align exited with value 1

```

**Comment by nservant** [comment]
That's it !!? you do not have an more explicit error in the log file ?
Could you try to run this command in a terminal to see if we can have a better log report ?
Thanks

**Comment by awaisc** [comment]
hey I ran that command, and got this

```
/apps/software/Bowtie2/2.2.9-GCC-5.3.0-binutils-2.25/bin/bowtie2-align-s --wrapper basic-0 --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder --rg-id BMG --rg SM:SRR5297626_1 --phred33-quals -p 16 -x /fast/users/a1649239/BowTieIndex/bowtie/mm9 --passthrough -U rawdata/brain2/SRR5297626_1.fastq 
Warning: Could not open read file "rawdata/brain2/SRR5297626_1.fastq" for reading; skipping...
Error: No input read files were valid
```
i tried changing my input files to a different mouse set and that didnt work either

**Comment by nservant** [comment]
In command line, you need to execute the command within the HiCPro output folder or to provide the complete path to the fastq file.
I never tested the 2.2.9 version, could you try to remove some options to see if some options are no longer maintain for instance ...

**Comment by awaisc** [comment]
Hi Nservant!

I really appreciate the help! I have it running ( i think, it was a miss named index files!)

mine are called mm9.ucsc whereas in the config I put mm9. 

:+1: 

This forum gave me the answer: http://seqanswers.com/forums/showthread.php?t=3977

**Comment by nservant** [comment]
ok. Great. I close the issue
