### ISSUE TITLE
Hic-pro sort issues

### ISSUE THREAD

**Issue by yuzhang0327** [nservant/HiC-Pro#88]
Dear professor,

I got the sort issue problem when running bowtie_combine.sh command, I have seen your issue answers about this question, however, I am not sure I am the case? I run our data with normal command, it works well, but when I tried to use the same data for spliting alleles, it came the sort problem, here is the wrong message:
## Merging forward and reverse tags ...
Forward and reverse reads not paired. Check that BAM files are sorted.

How can I solve or avoid this special problem?

Best,
Yu

**Comment by nservant** [comment]
Hi Yu,
The merge of R1/R2 does not change in allele specific process.
How do you know that this is a sort issue ? Could you check if you have a more explicit error somewhere ?
Thanks
