### ISSUE TITLE
some question about  normalization！

### ISSUE THREAD

**Issue by RuiqinZheng** [nservant/HiC-Pro#89]
Hi,
I just want to know is the normalization method normalized for the library size? that's to say does the .iced.matrix is not related to the library size.
wish you reply soon!
wating for your reply!
Best wishes!
Ruiqin Zheng

**Comment by RuiqinZheng** [comment]
library size or the sequencing depth

**Comment by nservant** [comment]
Hi
No there is no normalization based on sequencing depth.
The ICE normalization is an "intra" sample normalization
Best
