### ISSUE TITLE
Chimeric read trimming position

### ISSUE THREAD

**Issue by yezhengSTAT** [nservant/HiC-Pro#90]
Hello,
I am curious about your cutsite_trimming.cpp script to align chimeric read. It seems that the 3' end trimming occurs at the beginning of the ligation sequence, say --cutsite AAGCTAGCTT, instead of the center of it, namely AGCTT instead of AAGCTAGCTT. My understanding is that the first five base pairs (AAGCT) are still part of the original 5' read end and shouldn't be removed. Furthermore, if I set --cutsite AGCTT, it will not check whether whole ligation sequence exists in the chimeric read.
Thus, may I know your concern to choose to have the 3' end cut at the beginning of the ligation sequence instead of the center position?

Thanks,
Ye

**Comment by nservant** [comment]
move to the forum
https://groups.google.com/forum/#!topic/hic-pro/PCSEp3rmJrI
