### ISSUE TITLE
Bowtie Error1

### ISSUE THREAD

**Issue by roberto-saenz** [nservant/HiC-Pro#91]
Hello, 

I would greatly appreciate your input on the following issue. When I run HiC-Pro all goes well until this error appears, and the process is killed:

> lun jun 19 10:28:16 CDT 2017
Bowtie2 alignment step2 ...
/home/r/Documents/Hi-C_Pro_INSTALLLED/HiC-Pro_2.8.1_devel/scripts/bowtie_wrap.sh -c /home/r/Documents/Hi-C_Pro_INSTALLLED/HiC-Pro_2.8.1_devel/config-hicpro_ZT0_B.txt -l >> hicpro.log
Exit: Error in Bowtie alignment
/home/r/Documents/Hi-C_Pro_INSTALLLED/HiC-Pro_2.8.1_devel/bin/../scripts//Makefile:97: recipe for target 'bowtie_local' failed
make: *** [bowtie_local] Error 1

Upon checking the log files:
[bowtie_lane8_NoIndex_L008_R1_global_mm9.txt](https://github.com/nservant/HiC-Pro/files/1085632/bowtie_lane8_NoIndex_L008_R1_global_mm9.txt)
[bowtie_lane8_NoIndex_L008_R1_mm9.bwt2glob.unmap_local.txt](https://github.com/nservant/HiC-Pro/files/1085633/bowtie_lane8_NoIndex_L008_R1_mm9.bwt2glob.unmap_local.txt)
[readsTrimming.txt](https://github.com/nservant/HiC-Pro/files/1085635/readsTrimming.txt)

I cannot identify a clear mention of an Error.

I thank you in advance for your help.

**Comment by nservant** [comment]
Hi
Indeed, it looks strange
Could you show me how you organized your data and run HiC-Pro ?
Thanks

**Comment by roberto-saenz** [comment]
Hey
I ran HiC-Pro with this command in /HiC-Pro_2.8.1_devel/
> /home/r/Documents/Hi-C_Pro_INSTALLLED/HiC-Pro_2.8.1_devel/bin/./HiC-Pro -i /home/r/Documents/Hi-C_Pro_INSTALLLED/HiC-Pro_2.8.1_devel/fastqfiles/ZT0_R1/ -o /home/r/Documents/Hi-C_Pro_INSTALLLED/HiC-Pro_2.8.1_devel/results/mm9_ZT0_B/ -c config-hicpro_ZT0_B.txt

The bowtie indices are in 

> /home/r/Documents/fastqfiles/Mus_musculus/UCSC/mm9/Sequence/Bowtie2Index

the restriction fragment and chromosome files are in the /HiC-Pro_2.8.1_devel/annotation directory.

Thanks

**Comment by nservant** [comment]
What do you have in ; 
/home/r/Documents/Hi-C_Pro_INSTALLLED/HiC-Pro_2.8.1_devel/fastqfiles/ZT0_R1/
You should get one folder per sample ie.
/home/r/Documents/Hi-C_Pro_INSTALLLED/HiC-Pro_2.8.1_devel/fastqfiles/ZT0_R1/
/home/r/Documents/Hi-C_Pro_INSTALLLED/HiC-Pro_2.8.1_devel/fastqfiles/ZT0_R1/sample1
/home/r/Documents/Hi-C_Pro_INSTALLLED/HiC-Pro_2.8.1_devel/fastqfiles/ZT0_R1/sample/file1_R1.fastq
/home/r/Documents/Hi-C_Pro_INSTALLLED/HiC-Pro_2.8.1_devel/fastqfiles/ZT0_R1/sample/file1_R2.fastq
...

**Comment by roberto-saenz** [comment]
Hey
That's basically how I have it:

/home/r/Documents/Hi-C_Pro_INSTALLLED/HiC-Pro_2.8.1_devel/fastqfiles/ZT0_R1/lane8_NoIndex_L008_R1.fastq.gz

/home/r/Documents/Hi-C_Pro_INSTALLLED/HiC-Pro_2.8.1_devel/fastqfiles/ZT0_R1/lane8_NoIndex_L008_R2.fastq.gz

Do you suggest I make another folder in ZT0_R1 and put the .fastq s in there?

I did have trouble putting the .fastq's directly in /fastqfiles/ (some sort of heirarchy error), which is why I `mkdir ZT0_R1` and put them in there and that let me run HiC-Pro until I got the new error.

**Comment by nservant** [comment]
arrgs ! yes sorry.
It fails because you have "R1" in your sample name. Thus, when it greps "R1" to get the first reads, it also catch the R2 ...
You are not the first one who reports me this bug. I have to think about a way to fix this point
So change you sample name please, and tell me if it fixes the issue !
Best

**Comment by roberto-saenz** [comment]
Thanks a lot! Changing the sample folder name fixed it.

**Comment by nservant** [comment]
great ! I will try to improve this part.
N
