### ISSUE TITLE
Many Dangling end pairs

### ISSUE THREAD

**Issue by smarhon** [nservant/HiC-Pro#92]
Hi Nicolas

I am trying to process the Cortex HiC dataset which uses HindIII  restriction enzyme using the HiC-Pro, but I am getting many Dangling end pairs (about %50). Do you have suggestions for the parameters  MIN/MAX_INSERT_SIZE, MIN/MAX_FRAG_SIZE, MIN_CIS_DIST that could help decrease the number of Dangling end pairs?

Thanks
Sajid

**Comment by nservant** [comment]
Moved to the forum
https://groups.google.com/forum/#!topic/hic-pro/PbYxCQlelwU
