### ISSUE TITLE
missing cutsite_trimming in HiC-Pro_2.9.0/scripts

### ISSUE THREAD

**Issue by Tocci89** [nservant/HiC-Pro#99]
Hi, I was testing HiC-Pro 2.9.0 on my data running in parallel mode and the job crashed with the following error stored in logs/mydata/readsTrimming.log:

/my_path_to/HiC-Pro_2.9.0/scripts/bowtie_wrap.sh: line 109: /my_path_to/HiC-Pro_2.9.0/scripts/cutsite_trimming: No such file or directory

I've added the missing script from the HiC-Pro_2.7.8 release.

**Comment by nservant** [comment]
Hi
The cutsite_trimming script should be created when you compile HiC-pro.
Did you follow the intallation process, with 'make configure', 'make install' ?
Thanks

**Comment by Tocci89** [comment]
My fault,
I skipped the 'make install' step...
Now everything is working fine.
Thank you!
